#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  License:
#
#  Copyright (c) 2013 AlienVault
#  All rights reserved.
#
#  This package is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2 dated June, 1991.
#  You may not use, modify or distribute this program under any other version
#  of the GNU General Public License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this package; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
#  MA  02110-1301  USA
#
#
#  On Debian GNU/Linux systems, the complete text of the GNU General
#  Public License can be found in `/usr/share/common-licenses/GPL-2'.
#
#  Otherwise you can read it here: http://www.gnu.org/licenses/gpl-2.0.txt
#

from optparse import OptionParser

#from ansiblemethods.system.network import make_tunnel
from apimethods.system.system import make_tunnel_with_vpn

def parse_args():
    parser = OptionParser()
    parser.add_option("-s", "--system", dest="system", type="string", default=None,
                      help="select host for make tunnel")
    parser.add_option("-p", "--password", dest="password", type="string", default=None,
                      help="Remote system password")

    (options, args) = parser.parse_args()

    if not options.system:
        parser.print_help()
        exit(-1)

    if options.password == "" or options.password is None:
        print "Password requiered"
        parser.print_help()
        exit(-1)
    return (options, args)


if __name__ == "__main__":
    (options, args) = parse_args()

    success, data = make_tunnel_with_vpn(options.system,options.password)
    if not success:
        print "An error occurred while establishing the vpn tunnel: %s" % data
        exit(-1)
    print data
    exit(0)
