#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  License:
#
#  Copyright (c) 2013 AlienVault
#  All rights reserved.
#
#  This package is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2 dated June, 1991.
#  You may not use, modify or distribute this program under any other version
#  of the GNU General Public License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this package; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
#  MA  02110-1301  USA
#
#
#  On Debian GNU/Linux systems, the complete text of the GNU General
#  Public License can be found in `/usr/share/common-licenses/GPL-2'.
#
#  Otherwise you can read it here: http://www.gnu.org/licenses/gpl-2.0.txt
#

from optparse import OptionParser

from apimethods.system.av_license import register_appliance_trial, register_appliance_pro


def parse_args():
    parser = OptionParser()
    parser.add_option("-k", "--key", dest="key", type="string", default=None,
                      help="key for register the appliance")
    parser.add_option("-t", "--trial", dest="trial", action="store_true", default=False,
                      help="Trial version")

    (options, args) = parser.parse_args()

    if not options.key:
        print "key option needed"
        exit(-1)

    return (options, args)


if __name__ == "__main__":

    (options, args) = parse_args()
    if options.trial:
        (success, msg) = register_appliance_trial(email = options.key)
    else:
        (success, msg) = register_appliance_pro(key = options.key)

    print msg
    if not success:
        exit(-1)

    exit(0)
