#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  License:
#
#  Copyright (c) 2014 AlienVault
#  All rights reserved.
#
#  This package is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2 dated June, 1991.
#  You may not use, modify or distribute this program under any other version
#  of the GNU General Public License.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this package; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
#  MA  02110-1301  USA
#
#
#  On Debian GNU/Linux systems, the complete text of the GNU General
#  Public License can be found in `/usr/share/common-licenses/GPL-2'.
#
#  Otherwise you can read it here: http://www.gnu.org/licenses/gpl-2.0.txt

import sys
from apimethods.system.system import get_all_systems_with_ping_info


def main():
    print "Gathering systems data..."
    sys.stdout.flush()
    (success, systems) = get_all_systems_with_ping_info()
    if not success:
        print "Something wrong happened gathering systems data: %s" % systems
        exit(-1)

    for system_id, system_data in systems.iteritems():
        reachable = "Unreachable"
        if system_data['reachable']:
            reachable = "Reachable"
        system_ip = system_data['vpn_ip']
        if system_ip == '':
            system_ip = system_data['admin_ip']
        print "%s - '%s' - %s - %s" % (system_id, system_data['hostname'], system_ip, reachable)
    exit(0)


if __name__ == "__main__":
    main()
