SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

-- Upgrade to PIC DSS 2.0

DROP PROCEDURE IF EXISTS truncates;
DELIMITER '//'
CREATE PROCEDURE truncates() BEGIN
  IF NOT EXISTS
		(SELECT * FROM R04_Data_encryption WHERE x1='R' AND x2='4' AND x3='2' AND x4='')
  THEN
		TRUNCATE TABLE `R01_FW_Config`;
		TRUNCATE TABLE `R02_Vendor_default`;
		TRUNCATE TABLE `R03_Stored_cardholder`;
		TRUNCATE TABLE `R04_Data_encryption`;
		TRUNCATE TABLE `R05_Antivirus`;
		TRUNCATE TABLE `R06_System_app`;
		TRUNCATE TABLE `R07_Access_control`;
		TRUNCATE TABLE `R08_UniqueID`;
		TRUNCATE TABLE `R09_Physical_Access`;
		TRUNCATE TABLE `R10_Monitoring`; 
		TRUNCATE TABLE `R11_Security_test`; 
		TRUNCATE TABLE `R12_IS_Policy`;
  END IF;
END;
//
DELIMITER ';'
CALL truncates();
DROP PROCEDURE truncates;


--
-- Database: `PCI`
--

--
-- Dumping data for table `R01_FW_Config`
--

INSERT IGNORE INTO `R01_FW_Config` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '1', '1', '', 'Establish firewall configuration standards that include the following:', NULL, NULL, NULL, NULL, '<b>1.1</b> Obtain and inspect the firewall and router configuration standards and other documentation specified below to verify that standards are complete. Complete the following:'),
('R', '1', '1', '1', 'A formal process for approving and testing all external network connections and changes to the firewall and router configurations', '1', NULL, NULL, NULL, '<b>1.1.1</b> Verify that there is a formal process for testing and approval of all network connections and changes to firewall and router configurations.'),
('R', '1', '1', '2', 'A current network diagram with all connections to cardholder data, including any wireless networks', '1', NULL, NULL, NULL, '<b>1.1.2.a</b> Verify that a current network diagram (for example, one that shows cardholder data flows over the network) exists and that it documents all connections to cardholder data, including any wireless networks.<br><b>1.1.2.b</b> Verify that the diagram is kept current.'),
('R', '1', '1', '3', 'Requirements for a firewall at each Internet connection and between any demilitarizedzone (DMZ) and the internal network zone', '1', NULL, NULL, NULL, '<b>1.1.3.a</b> Verify that firewall configuration standards include requirements for a firewall at each Internet connection and between any DMZ and the internal network zone.<br><b>1.1.3.b</b> Verify that the current network diagram is consistent with the firewall configuration standards.'),
('R', '1', '1', '4', 'Description of groups, roles, and responsibilities for logical management of network components', '1', NULL, NULL, NULL, '<b>1.1.4</b> Verify that firewall and router configuration standards include a description of groups, roles, and responsibilities for logical management of network components.'),
('R', '1', '1', '5', 'Documentation and business justification for use of all services, protocols, and ports allowed, including documentation of security features implemented for those protocols considered to be insecure', NULL, '1', NULL, NULL, '<b>1.1.5.a</b> Verify that firewall and router configuration standards include a documented list of services, protocols and ports necessary for business—for example, hypertext transfer protocol (HTTP) and Secure Sockets Layer (SSL), Secure Shell (SSH), and Virtual Private Network (VPN) protocols.<br><b>1.1.5.b</b> Identify insecure services, protocols, and ports allowed; and verify they are necessary and that security features are documented and implemented by examining firewall and router configuration standards and settings for each service.'),
('R', '1', '1', '6', 'Requirement to review firewall and router rule sets at least every six months', '1', NULL, NULL, NULL, '<b>1.1.6.a</b> Verify that firewall and router configuration standards require review of firewall and router rule sets at least every six months. <br><b>1.1.6.b</b> Obtain and examine documentation to verify that the rule sets are reviewed at least every six months.'),

('R', '1', '2', '', 'Build a firewall configuration that denies all traffic from "untrusted" networks and hosts, except for protocols necessary for the cardholder data environment', '1', NULL, NULL, NULL, '<b>1.2</b> Examine firewall and router configurations to verify that connections are restricted between untrusted networks and system components in the cardholder data environment, as follows:'),
('R', '1', '2', '1', 'Restrict inbound and outbound traffic to that which is necessary for the cardholder data environment', '1', NULL, NULL, NULL, '<b>1.2.1.a</b> Verify that inbound and outbound traffic is limited to that which is necessary for the cardholder data environment, and that the restrictions are documented. <br><b>1.2.1.b</b> Verify that all other inbound and outbound traffic is specifically denied, for example by using an explicit "deny all" or an implicit deny after allow statement.'),
('R', '1', '2', '2', 'Secure and synchronize router configuration files', '1', NULL, NULL, NULL, '<b>1.2.2</b> Verify that router configuration files are secure and synchronized—for example, running configuration files (used for normal running of the routers) and start-up configuration files (used when machines are re-booted), have the same, secure configurations.'),
('R', '1', '2', '3', 'Install perimeter firewalls between any wireless networks and the cardholder data environment, and configure these firewalls to deny or control (if such traffic is necessary for business purposes) any traffic from the wireless environment into the cardholder data environment', '1', NULL, NULL, NULL, '<b>1.2.3</b> Verify that there are perimeter firewalls installed between any wireless networks and systems that store cardholder data, and that these firewalls deny or control (if such traffic is necessary for business purposes) any traffic from the wireless environment into the cardholder data environment.'),

('R', '1', '3', '', 'Prohibit direct public access between the Internet and any system component in the cardholder data environment.', '1', NULL, NULL, NULL,'<b>1.3</b> Examine firewall and router configurations—including but not limited to the choke router at the Internet, the DMZ router and firewall, the DMZ cardholder segment, the perimeter router, and the internal cardholder network segment—to determine that there is no direct access between the Internet and system components in the internal cardholder network segment, as detailed below.'),
('R', '1', '3', '1', 'Implement a DMZ to limit inbound traffic to only system components that provide authorized publicly accessible services, protocols, and ports', '1', NULL, NULL, NULL, '<b>1.3.1</b> Verify that a DMZ is implemented to limit inbound traffic to only system components that provide authorized publicly accessible services, protocols, and ports.'),
('R', '1', '3', '2', 'Limit inbound Internet traffic to IP addresses within the DMZ', '1', NULL, NULL, NULL ,'<b>1.3.2</b> Verify that inbound Internet traffic is limited to IP addresses within the DMZ.'),
('R', '1', '3', '3', 'Do not allow any direct connections inbound or outbound for traffic between the Internet and the cardholder data environment', '1', NULL, NULL, NULL, '<b>1.3.3</b> Verify direct connections inbound or outbound are not allowed for traffic between the Internet and the cardholder data environment.'),
('R', '1', '3', '4', 'Do not allow internal addresses to pass from the Internet into the DMZ', '1', NULL, NULL, NULL, '<b>1.3.4</b> Verify that internal addresses cannot pass from the Internet into the DMZ.'),
('R', '1', '3', '5', 'Do not allow unauthorized outbound traffic from the cardholder data environment to the Internet', '1', NULL, NULL, NULL, '<b>1.3.5</b> Verify that outbound traffic from the cardholder data environment to the Internet is explicitly authorized.'),
('R', '1', '3', '6', 'Implement stateful inspection, also known as dynamic packet filtering', NULL, '1', NULL, NULL, '<b>1.3.6</b> Verify that the firewall performs stateful inspection (dynamic packet filtering). (Only established connections should be allowed in, and only if they are associated with a previously established session.)'),
('R', '1', '3', '7', 'Place system components that store cardholder data (such as a database) in an internal network zone, segregated from the DMZ and other untrusted networks', '1', NULL, NULL, NULL, '<b>1.3.7</b> Verify that system components that store cardholder data are on an internal network zone, segregated from the DMZ and other untrusted networks'),
('R', '1', '3', '8', 'Do not disclose private IP addresses and routing information to unauthorized parties', '1', NULL, NULL, NULL, '<b>1.3.8.a</b> Verify that methods are in place to prevent the disclosure of private IP addresses and routing information from internal networks to the Internet. <br><b>1.3.8.b</b> Verify that any disclosure of private IP addresses and routing information to external entities is authorized. <br><b>Note:</b> Methods to obscure IP addressing may include, but are not limited to: <br>* Network Address Translation (NAT)<br>* Placing servers containing cardholder data behind proxy servers/firewalls or content caches, <br>* Removal or filtering of route advertisements for private networks that employ registered addressing, <br>* Internal use of RFC1918 address space instead of registered addresses.'),

('R', '1', '4', '', 'Install personal firewall software on any mobile and/or employee-owned computers with direct connectivity to the Internet (for example, laptops used by employees), which are used to access the organizationís network', '1', NULL, NULL, NULL, '<b>1.4.a</b> Verify that mobile and/or employee-owned computers with direct connectivity to the Internet (for example, laptops used by employees), and which are used to access the organization¥s network, have personal firewall software installed and active.<br><b>1.4.b</b> Verify that the personal firewall software is configured by the organization to specific standards and is not alterable by users of mobile and/or employee-owned computers.');

--
-- Dumping data for table `R02_Vendor_default`
--

INSERT IGNORE INTO `R02_Vendor_default` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '2', '1', '', 'Always change vendor-supplied defaults before installing a system on the network, including but not limited to passwords, simple network management protocol (SNMP) community strings, and elimination of unnecessary accounts', NULL, '1', NULL, NULL, '<b>2.1</b> Choose a sample of system components, and attempt to log on (with system administrator help) to the devices using default vendor-supplied accounts and passwords, to verify that default accounts and passwords have been changed. (Use vendor manuals and sources on the Internet to find vendor-supplied accounts/passwords.)'),
('R', '2', '1', '1', 'For wireless environments connected to the cardholder data environment or transmitting cardholder data, change wireless vendor defaults, including but not limited to default wireless encryption keys, passwords, and SNMP community strings.', '1', NULL, NULL, NULL, '<b>2.1.1</b> Verify the following regarding vendor default settings for wireless environments: <br><b>2.1.1.a</b> Verify encryption keys were changed from default at installation, and are changed anytime anyone with knowledge of the keys leaves the company or changes positions <br><b>2.1.1.b</b> Verify default SNMP community strings on wireless devices were changed. <br><b>2.1.1.c</b> Verify default passwords/passphrases on access points were changed. <br><b>2.1.1.d</b> Verify firmware on wireless devices is updated to support strong encryption for authentication and transmission over wireless networks. <br><b>2.1.1.e</b> Verify other security-related wireless vendor defaults were changed, if applicable.'),

('R', '2', '2', '', 'Develop configuration standards for all system components. Assure that these standards address all known security vulnerabilities and are consistent with industry-accepted system hardening standards', '1', NULL, NULL, NULL, 'Sources of industry-accepted system hardening standards may include, but are not limited to: <br>* Center for Internet Security (CIS) <br>* International Organization for Standardization (ISO) <br>* SysAdmin Audit Network Security (SANS) Institute <br>* National Institute of Standards Technology (NIST)<br> <br><b>2.2.a</b> Examine the organizationís system configuration standards for all types of system components and verify the system configuration standards are consistent with industry-accepted hardening standards. <br><b>2.2.b</b> Verify that system configuration standards are updated as new vulnerability issues are identified, as defined in Requirement 6.2. <br><b>2.2.c</b> Verify that system configuration standards are applied when new systems are configured. <br><b>2.2.d</b> Verify that system configuration standards include each item below (2.2.1 - 2.2.4).'),
('R', '2', '2', '1', 'Implement only one primary function per server to prevent functions that require different security levels from co-existing on the same server. (For example, web servers, database servers, and DNS should be implemented on separate servers.)', '1', NULL, NULL, NULL, '<b>2.2.1.a</b> For a sample of system components, verify that only one primary function is implemented per server. <br><b>2.2.1.b</b> If virtualization technologies are used, verify that only one primary function is implemented per virtual system component or device.'),
('R', '2', '2', '2', 'Enable only necessary and secure services, protocols, daemons, etc., as required for the function of the system. Implement security features for any required services, protocols or daemons that are considered to be insecureófor example, use secured technologies such as SSH, S-FTP, SSL, or IPSec VPN to protect insecure services such as NetBIOS, file-sharing, Telnet, FTP, etc.', '1', NULL, NULL, NULL, '<b>2.2.2.a</b> For a sample of system components, inspect enabled system services, daemons, and protocols. Verify that only necessary services or protocols are enabled. <br><b>2.2.2.b</b> Identify any enabled insecure services, daemons, or protocols. Verify they are justified and that security features are documented and implemented.'),
('R', '2', '2', '3', 'Configure system security parameters to prevent misuse', NULL, '1', NULL, NULL, '<b>2.2.3.a</b> Interview system administrators and/or security managers to verify that they have knowledge of common security parameter settings for system components. <br><b>2.2.3.b</b> Verify that common security parameter settings are included in the system configuration standards. <br><b>2.2.3.c</b> For a sample of system components, verify that common security parameters are set appropriately.'),
('R', '2', '2', '4', 'Remove all unnecessary functionality, such as scripts, drivers, features, subsystems, file systems, and unnecessary web servers.', NULL, '1', NULL, NULL, '<b>2.2.4.a</b> For a sample of system components, verify that all unnecessary functionality (for example, scripts, drivers, features, subsystems, file systems, etc.) is removed. <br><b>2.2.4.b.</b> Verify enabled functions are documented and support secure configuration. <br><b>2.2.4.c.</b> Verify that only documented functionality is present on the sampled system components.'),

('R', '2', '3', '', 'Encrypt all non-console administrative access using strong cryptography. Use technologies such as SSH, VPN, or SSL/TLS for webbased management and other nonconsole administrative access', NULL, '1', NULL, NULL, '<b>2.3</b> For a sample of system components, verify that non-console administrative access is encrypted by performing the following: <br><b>2.3.a</b> Observe an administrator log on to each system to verify that a strong encryption method is invoked before the administratorís password is requested.<br><b>2.3.b</b> Review services and parameter files on systems to determine that Telnet and other remote login commands are not available for use internally. <br><b>2.3.c</b> Verify that administrator access to the web-based management interfaces is encrypted with strong cryptography.'),

('R', '2', '4', '', 'Shared hosting providers must protect each entityís hosted environment and cardholder data. These providers must meet specific requirements as detailed in Appendix A: Additional PCI DSS Requirements for Shared Hosting Providers.', NULL, '1', NULL, NULL, '<b>2.4</b> Perform testing procedures A.1.1 through A.1.4 detailed in Appendix A: Additional PCI DSS Requirements for Shared Hosting Providers for PCI DSS assessments of shared hosting providers, to verify that shared hosting providers protect their entitiesí (merchants and service providers) hosted environment and data.');

--
-- Dumping data for table `R03_Stored_cardholder`
--

INSERT IGNORE INTO `R03_Stored_cardholder` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '3', '1', '', 'Keep cardholder data storage to a minimum by implementing data retention and disposal policies, procedures and processes, as follows.', '1', NULL, NULL, NULL, '<b>3.1</b> Obtain and examine the policies, procedures and processes for data retention and disposal, and perform the following:'),
('R', '3', '1', '1', 'Implement a data retention and disposal policy', '1', NULL, NULL, NULL, '<b>3.1.1.a</b> Verify that policies and procedures are implemented and include legal, regulatory, and business requirements for data retention, including specific requirements for retention of cardholder data (for example, cardholder data needs to be held for X period for Y business reasons). <br><b>3.1.1.b</b> Verify that policies and procedures include provisions for secure disposal of data when no longer needed for legal, regulatory, or business reasons, including disposal of cardholder data. <br><b>3.1.1.c</b> Verify that policies and procedures include coverage for all storage of cardholder data. <br><b>3.1.1.d</b> Verify that policies and procedures include at least one of the following:<br> A programmatic process (automatic or manual) to remove, at least quarterly, stored cardholder data that exceeds requirements defined in the data retention policy<br>Requirements for a review, conducted at least quarterly, to verify that stored cardholder data does not exceed requirements defined in the data retention policy.<br><b>3.1.1.e</b> For a sample of system components that store cardholder data, verify that the data stored does not exceed the requirements defined in the data retention policy.'),

('R', '3', '2', '', 'Do not store sensitive authentication data after authorization (even if encrypted). Sensitive authentication data includes the data as cited in the following Requirements 3.2.1 through 3.2.3', '1', NULL, NULL, NULL, '<b>3.2.a</b> For issuers and/or companies that support issuing services and store sensitive authentication data, verify there is a business justification for the storage of sensitive authentication data, and that the data is secured. <br><b>3.2.b</b> For all other entities, if sensitive authentication data is received and deleted, obtain and review the processes for securely deleting the data to verify that the data is unrecoverable. <br><b>3.2.c</b> For each item of sensitive authentication data below, perform the following steps'),
('R', '3', '2', '1', 'Do not store the full contents of any track (from the magnetic stripe located on the back of a card, equivalent data contained on a chip, or elsewhere). This data is alternatively called full track, track, track 1, track 2, and magnetic-stripe data', NULL, '1', NULL, NULL, '<b>3.2.1</b> For a sample of system components, examine data sources, including but not limited to the following, and verify that the full contents of any track from the magnetic stripe on the back of card or equivalent data on a chip are not stored under any circumstance:<br>* Incoming transaction data<br>* All logs (for example, transaction, history, debugging, error)<br>* History files <br>* Trace files<br>* Several database schemas<br>* Database contents'),
('R', '3', '2', '2', 'Do not store the card verification code or value (three-digit or four-digit number printed on the front or back of a payment card) used to verify card-notpresent transactions', '1', NULL, NULL, NULL, '<b>3.2.2</b> For a sample of system components, examine data sources, including but not limited to the following, and verify that the threedigit or four-digit card verification code or value printed on the front of the card or the signature panel (CVV2, CVC2, CID, CAV2 data) is not stored under any circumstance: <br>* Incoming transaction data <br>* All logs (for example, transaction, history, debugging, error) <br>* History files <br>* Trace files <br>* Several database schemas <br>* Database contents'),
('R', '3', '2', '3', 'Do not store the personal identification number (PIN) or the encrypted PIN block', '1', NULL, NULL, NULL, '<b>3.2.3</b> For a sample of system components, examine data sources, including but not limited to the following and verify that PINs and encrypted PIN blocks are not stored under any circumstance: <br>* Incoming transaction data <br>* All logs (for example, transaction, history, debugging, error) <br>* History files <br>* Trace files <br>* Several database schemas <br>* Database contents'),

('R', '3', '3', '', 'Mask PAN when displayed (the first six and last four digits are the maximum number of digits to be displayed)', '1', NULL, NULL, NULL, '<b>3.3</b> Obtain and examine written policies and examine displays of PAN (for example, on screen, on paper receipts) to verify that primary account numbers (PANs) are masked when displaying cardholder data, except for those with a legitimate business need to see full PAN.'),

('R', '3', '4', '', 'Render PAN unreadable anywhere it is stored (including on portable digital media, backup media, and in logs)', '1', NULL, NULL, NULL, '<b>3.4.a</b> Obtain and examine documentation about the system used to protect the PAN, including the vendor, type of system/process, and the encryption algorithms (if applicable). Verify that the PAN is rendered unreadable using any of the following methods: <br>* One-way hashes based on strong cryptography <br>* Truncation <br>* Index tokens and pads, with the pads being securely stored <br>* Strong cryptography, with associated key-management processes and procedures <br><b>3.4.b</b> Examine several tables or files from a sample of data repositories to verify the PAN is rendered unreadable (that is, not stored in plain-text). <br><b>3.4.c</b> Examine a sample of removable media (for example, back-up tapes) to confirm that the PAN is rendered unreadable. <br><b>3.4.d</b> Examine a sample of audit logs to confirm that the PAN is rendered unreadable or removed from the logs.'),
('R', '3', '4', '1', 'If disk encryption is used (rather than file- or column-level database encryption), logical access must be managed independently of native operating system access control mechanisms (for example, by not using local user account databases). Decryption keys must not be tied to user accounts', '1', NULL, NULL, NULL, '<b>3.4.1.a</b> If disk encryption is used, verify that logical access to encrypted file systems is implemented via a mechanism that is separate from the native operating systems mechanism (for example, not using local user account databases). <br><b>3.4.1.b</b> Verify that cryptographic keys are stored securely (for example, stored on removable media that is adequately protected with strong access controls). <br><b>3.4.1.c</b> Verify that cardholder data on removable media is encrypted wherever stored.'),

('R', '3', '5', '', 'Protect any keys used to secure cardholder data against disclosure and misuse', '1', NULL, NULL, NULL, '<b>3.5</b> Verify processes to protect keys used for encryption of cardholder data against disclosure and misuse by performing the following:'),
('R', '3', '5', '1', 'Restrict access to cryptographic keys to the fewest number of custodians necessary', NULL, '1', NULL, NULL, '<b>3.5.1</b> Examine user access lists to verify that access to keys is restricted to the fewest number of custodians necessary.'),
('R', '3', '5', '2', 'Store cryptographic keys securely in the fewest possible locations and forms', '1', NULL, NULL, NULL, '<b>3.5.2.a</b> Examine system configuration files to verify that keys are stored in encrypted format and that key-encrypting keys are stored separately from data-encrypting keys. <br><b>3.5.2.b</b> Identify key storage locations to verify that keys are stored in the fewest possible locations and forms.'),

('R', '3', '6', '', 'Fully document and implement all key-management processes and procedures for cryptographic keys used for encryption of cardholder data, including the following:', NULL, '1', NULL, NULL, '<br><b>3.6.a</b> Verify the existence of key-management procedures for keys used for encryption of cardholder data. <br><b>3.6.b</b> For service providers only: If the service provider shares keys with their customers for transmission or storage of cardholder data, verify that the service provider provides documentation to customers that includes guidance on how to securely transmit, store and update customerís keys, in accordance with Requirements 3.6.1 through 3.6.8 below. <br><b>3.6.c</b> Examine the key-management procedures and perform the following:'),
('R', '3', '6', '1', 'Generation of strong cryptographic keys', NULL, '1', NULL, NULL, '<b>3.6.1</b> Verify that key-management procedures are implemented to require the generation of strong keys.'),
('R', '3', '6', '2', 'Secure cryptographic key distribution', '1', NULL, NULL, NULL, '<b>3.6.2</b> Verify that key-management procedures are implemented to require secure key distribution.'),
('R', '3', '6', '3', 'Secure cryptographic key storage', '1', NULL, NULL, NULL, '<b>3.6.3</b> Verify that key-management procedures are implemented to require secure key storage.'),
('R', '3', '6', '4', 'Cryptographic key changes for keys that have reached the end of their cryptoperiod (for example, after a defined period of time has passed and/or after a certain amount of ciphertext has been produced by a given key), as defined by the associated application vendor or key owner, and based on industry best practices and guidelines (for example, NIST Special Publication 800-57).', '1', NULL, NULL, NULL, '<b>3.6.4</b> Verify that key-management procedures are implemented to require periodic key changes at the end of the defined cryptoperiod.'),
('R', '3', '6', '5', 'Retirement or replacement (for example, archiving, destruction, and/or revocation) of keys as deemed necessary when the integrity of the key has been weakened (for example, departure of an employee with knowledge of a clear-text key), or keys are suspected of being compromised', '1', NULL, NULL, NULL, '<b>3.6.5.a</b> Verify that key-management procedures are implemented to require the retirement of keys when the integrity of the key has been weakened. <br><b>3.6.5.b</b> Verify that the key-management procedures are implemented to require the replacement of known or suspected compromised keys. <br><b>3.6.5.c</b> If retired or replaced cryptographic keys are retained, verify that these keys are not used for encryption operations.'),
('R', '3', '6', '6', 'If manual clear-text cryptographic key management operations are used, these operations must be managed using split knowledge and dual control (for example, requiring two or three people, each knowing only their own key component, to reconstruct the whole key).', NULL, '1', NULL, NULL, '<b>3.6.6</b> Verify that manual clear-text key-management procedures require split knowledge and dual control of keys.'),
('R', '3', '6', '7', 'Prevention of unauthorized substitution of cryptographic keys', NULL, '1', NULL, NULL, '<b>3.6.7</b> Verify that key-management procedures are implemented to require the prevention of unauthorized substitution of keys.'),
('R', '3', '6', '8', 'Requirement for cryptographic key custodians to formally acknowledge that they understand and accept their key-custodian responsibilities', NULL, '1', NULL, NULL, '<b>3.6.8</b> Verify that key-management procedures are implemented to require key custodians to acknowledge (in writing or electronically) that they understand and accept their key-custodian responsibilities.');

--
-- Dumping data for table `R04_Data_encryption`
--

INSERT IGNORE INTO `R04_Data_encryption` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '4', '1', '', 'Use strong cryptography and security protocols (for example, SSL/TLS, IPSEC, SSH, etc.) to safeguard sensitive cardholder data during transmission over open, public networks.', '1', NULL, NULL, '32014,32022,32025,32029', '<b>4.1</b> Verify the use of security protocols wherever cardholder data is transmitted or received over open, public networks. Verify that strong cryptography is used during data transmission, as follows: <br><b>4.1.a</b> Select a sample of transactions as they are received and observe transactions as they occur to verify that cardholder data is encrypted during transit. <br><b>4.1.b</b> Verify that only trusted keys and/or certificates are accepted. <br><b>4.1.c</b> Verify that the protocol is implemented to use only secure configurations, and does not support insecure versions or configurations. <br><b>4.1.d</b> Verify that the proper encryption strength is implemented for the encryption methodology in use. (Check vendor recommendations/best practices.) <br><b>4.1.e</b> For SSL/TLS implementations: <br>* Verify that HTTPS appears as a part of the browser Universal Record Locator (URL). <br>* Verify that no cardholder data is required when HTTPS does not appear in the URL.'),
('R', '4', '1', '1', 'Ensure wireless networks transmitting cardholder data or connected to the cardholder data environment, use industry best practices (for example, IEEE 802.11i) to implement strong encryption for authentication and transmission', '1', NULL, NULL, NULL, '<b>4.1.1</b> For wireless networks transmitting cardholder data or connected to the cardholder data environment, verify that industry best practices (for example, IEEE 802.11i) are used to implement strong encryption for authentication and transmission.'),

('R', '4', '2', '', 'Never send unprotected PANs by end-user messaging technologies (for example, e-mail, instant messaging, chat, etc.)', '1', NULL, NULL, NULL, '<b>4.2.a</b> Verify that PAN is rendered unreadable or secured with strong cryptography whenever it is sent via end-user messaging technologies. <br><b>4.2.b</b> Verify the existence of a policy stating that unprotected PANs are not to be sent via end-user messaging technologies.');

--
-- Dumping data for table `R05_Antivirus`
--

INSERT IGNORE INTO `R05_Antivirus` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '5', '1', '', 'Deploy anti-virus software on all systems commonly affected by malicious software (particularly personal computers and servers)', '1', NULL, NULL, NULL, '<b>5.1</b> For a sample of system components including all operating system types commonly affected by malicious software, verify that anti-virus software is deployed if applicable anti-virus technology exists.'),
('R', '5', '1', '1', 'Ensure that all anti-virus programs are capable of detecting, removing, and protecting against all known types of malicious software', '1', NULL, NULL, NULL, '<b>5.1.1</b> For a sample of system components, verify that all anti-virus programs detect, remove, and protect against all known types of malicious software (for example, viruses, Trojans, worms, spyware, adware, and rootkits).'),
('R', '5', '2', '', 'Ensure that all anti-virus mechanisms are current, actively running, and generating audit logs', NULL, '1', NULL, NULL, '<b>5.2</b> Verify that all anti-virus software is current, actively running, and generating logs by performing the following: <br><b>5.2.a</b> Obtain and examine the policy and verify that it requires updating of anti-virus software and definitions. <br><b>5.2.b</b> Verify that the master installation of the software is enabled for automatic updates and periodic scans. <br><b>5.2.c</b> For a sample of system components including all operating system types commonly affected by malicious software, verify that automatic updates and periodic scans are enabled. <br><b>5.2.d</b> For a sample of system components, verify that anti-virus software log generation is enabled and that such logs are retained in accordance with PCI DSS Requirement 10.7.');

--
-- Dumping data for table `R06_System_app`
--

INSERT IGNORE INTO `R06_System_app` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '6', '1', '', 'Ensure that all system components and software are protected from known vulnerabilities by having the latest vendor-supplied security patches installed. Install critical security patches within one month of release.', NULL, '1', NULL, '45003,45004,45006,45008,45009,45010,45011,45012,45013,45014,45015,45016,45017,45018,45019,45020,45021,45022,45023,45026,45027,45', '<b>6.1.a</b> For a sample of system components and related software, compare the list of security patches installed on each system to the most recent vendor security patch list, to verify that current vendor patches are installed. <br><b>6.1.b</b> Examine policies related to security patch installation to verify they require installation of all critical new security patches within one month.'),

('R', '6', '2', '', 'Establish a process to identify and assign a risk ranking to newly discovered security vulnerabilities.', NULL, '1', NULL, NULL, ''),

('R', '6', '3', '', 'Develop software applications (internal and external, and including webbased administrative access to applications) in accordance with PCI DSS (for example, secure authentication and logging), and based on industry best practices. Incorporate information security throughout the software development life cycle.', NULL, '1', NULL, NULL, '<b>6.3.a</b> Obtain and examine written software development processes to verify that the processes are based on industry standards and/or best practices. <br><b>6.3.b</b> Examine written software development processes to verify that information security is included throughout the life cycle. <br><b>6.3.c</b> Examine written software development processes to verify that software applications are developed in accordance with PCI DSS.<br><b>6.3.d</b> From an examination of written software development processes, and interviews of software developers'),
('R', '6', '3', '1', 'Removal of custom application accounts, user IDs, and passwords before applications become active or are released to customers', NULL, '1', NULL, NULL, '<b>6.3.1</b> Custom application accounts, user IDs and/or passwords are removed before system goes into production or is released to customers.'),
('R', '6', '3', '2', 'Review of custom code prior to release to production or customers in order to identify any potential coding vulnerability', NULL, '1', NULL, NULL, '<b>6.3.2.a</b> Obtain and review policies to confirm that all custom application code changes must be reviewed (using either manual or automated processes) as follows: <br>* Code changes are reviewed by individuals other than the originating code author, and by individuals who are knowledgeable in code review techniques and secure coding practices. <br>* Code reviews ensure code is developed according to secure coding guidelines (see PCI DSS Requirement 6.5). <br>* Appropriate corrections are implemented prior to release.<br>* Code review results are reviewed and approved by management prior to release. <br><b>6.3.2.b</b> Select a sample of recent custom application changes and verify that custom'),

('R', '6', '4', '', 'Follow change control processes and procedures for all changes to system components. The processes must include the following:', '1', NULL, NULL, NULL, '<b>6.4</b> From an examination of change control processes, interviews with system and network administrators, and examination of relevant data (network configuration documentation, production and test data, etc.)'),
('R', '6', '4', '1', 'Separate development/test and production environments', '1', NULL, NULL, NULL ,'<b>6.4.1</b> The development/test environments are separate from the production environment, with access control in place to enforce the separation.'),
('R', '6', '4', '2', 'Separation of duties between development/test and production environments', '1', NULL, NULL, NULL, '<b>6.4.2</b> There is a separation of duties between personnel assigned to the development/test environments and those assigned to the production environment.'),
('R', '6', '4', '3', 'Production data (live PANs) are not used for testing or development', '1', NULL, NULL, NULL, '<b>6.4.3</b> Production data (live PANs) are not used for testing or development.'),
('R', '6', '4', '4', 'Removal of test data and accounts before production systems become active', NULL, '1', NULL, NULL, '<b>6.4.4</b> Test data and accounts are removed before a production system becomes active.'),
('R', '6', '4', '5', 'Change control procedures for the implementation of security patches and software modifications. Procedures must include the following: * Documentation of impact, * Documented change approval by authorized parties, * Functionality testing to verify that the change does not adversely impact the security of the system, * Back-out procedures.', NULL, '1', NULL, NULL, '<b>6.4.5.a</b> Verify that change-control procedures related to implementing security patches and software modifications are documented and require items 6.4.5.1 ñ 6.4.5.4 below. <br><b>6.4.5.b For a sample of system components and recent changes/security patches, trace those changes back to related change control documentation. For each change examined, perform the following: <br><b>6.4.5.1 Verify that documentation of impact is included in the change control documentation for each sampled change. <br><b>6.4.5.2 Verify that documented approval by authorized parties is present for each sampled change. <br><b>6.4.5.3.a For each sampled change, verify that functionality testing is performed to verify that the change does not adversely impact the security of the system. <br><b>6.4.5.3.b For custom code changes, verify that all updates are tested for compliance with PCI DSS Requirement 6.5 before being deployed into production. <br><b>6.4.5.4 Verify that back-out procedures are prepared for each sampled change.'),

('R', '6', '5', '', 'Develop applications based on secure coding guidelines. Prevent common coding vulnerabilities in software development processes, to include the following:', '1', NULL, NULL, NULL, '<b>6.5.a</b> Obtain and review software development processes. Verify that processes require training in secure coding techniques for developers, based on industry best practices and guidance. <br><b>6.5.b</b> Interview a sample of developers and obtain evidence that they are knowledgeable in secure coding techniques. <br><b>6.5.c.</b> Verify that processes are in place to ensure that applications are not vulnerable to, at a minimum, the following:'),
('R', '6', '5', '1', 'Injection flaws, particularly SQL injection. Also consider OS Command Injection, LDAP and XPath injection flaws as well as other injection flaws', '1', NULL, NULL, NULL, '<b>6.5.1</b> Injection flaws, particularly SQL injection. (Validate input to verify user data cannot modify meaning of commands and queries, utilize parameterized queries, etc.)'),
('R', '6', '5', '2', 'Buffer overflow', NULL, '1', NULL, NULL, '<b>6.5.2</b> Buffer overflow (Validate buffer boundaries and truncate input strings.)'),
('R', '6', '5', '3', 'Insecure cryptographic storage', NULL, '1', NULL, '32021,32026,32033,32038,32039', '<b>6.5.3</b> Insecure cryptographic storage (Prevent cryptographic flaws)'),
('R', '6', '5', '4', 'Insecure communications', NULL, '1', NULL, NULL, '<b>6.5.4</b> Insecure communications (Properly encrypt all authenticated and sensitive communications)'),
('R', '6', '5', '5', 'Improper error handling', NULL, '1', NULL, NULL, '<b>6.5.5</b> Improper error handling (Do not leak information via error messages)'),
('R', '6', '5', '6', 'All "High" vulnerabilities identified in the vulnerability identification process (as defined in PCI DSS Requirement 6.2)', NULL, '1', NULL, '45062,45063,45063,45064,45065,45066,45067,45068,45069,45070,45071,45072,45073,45074', '<b>6.5.6</b> All "High" vulnerabilities as identified in PCI DSS Requirement 6.2.'),
('R', '6', '5', '7', 'Cross-site scripting (XSS)', NULL, '1', NULL, NULL, '<b>6.5.7</b> Cross-site scripting (XSS) (Validate all parameters before inclusion, utilize context-sensitive escaping, etc.)'),
('R', '6', '5', '8', 'Improper Access Control (such as insecure direct object references, failure to restrict URL access, and directory traversal)', '1', NULL, NULL, NULL, '<b>6.5.8</b> Improper Access Control, such as insecure direct object references, failure to restrict URL access, and directory traversal (Properly authenticate users and sanitize input. Do not expose internal object references to users.)'),
('R', '6', '5', '9', 'Cross-site request forgery (CSRF)', '1', NULL, NULL, '34001,34002,34003,34004,34005,34006,34007,34008,34009,34010,34011,34012,34013,34014,34015,34016,34017,34018,34019,34020,34021,34', '<b>6.5.9</b> Cross-site request forgery (CSRF). (Do not reply on authorization credentials and tokens automatically submitted by browsers.)'),

('R', '6', '6', '', 'For public-facing web applications, address new threats and vulnerabilities on an ongoing basis and ensure these applications are protected against known attacks by either of the following methods: * Reviewing public-facing web applications via manual or automated application vulnerability security assessment tools or methods, at least annually and after any changes, * Installing a web-application firewall in front of public-facing web applications', NULL, '1', NULL, NULL, '<b>6.6</b> For public-facing web applications, ensure that either one of the following methods are in place as follows:<br>* Verify that public-facing web applications are reviewed (using either manual or automated vulnerability security assessment tools or methods), as follows: <br>- At least annually <br>- After any changes <br>- By an organization that specializes in application security <br>- That all vulnerabilities are corrected <br>- That the application is re-evaluated after the corrections  <br><br>* Verify that a web-application firewall is in place in front of public-facing web applications to detect and prevent web-based attacks.');

--
-- Dumping data for table `R07_Access_control`
--

INSERT IGNORE INTO `R07_Access_control` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '7', '1', '', 'Limit access to system components and cardholder data to only those individuals whose job requires such access. Access limitations must include the following:', '1', NULL, NULL, '32039,32038,32033', '<b>7.1</b> Obtain and examine written policy for data control, and verify that the policy incorporates the following:'),
('R', '7', '1', '1', 'Restriction of access rights to privileged user IDs to least privileges necessary to perform job responsibilities', '1', NULL, NULL, NULL, '<b>7.1.1</b> Confirm that access rights for privileged user IDs are restricted to least privileges necessary to perform job responsibilities.'),
('R', '7', '1', '2', 'Assignment of privileges is based on individual personnelís job classification and function', '1', NULL, NULL, NULL, '<b>7.1.2</b> Confirm that privileges are assigned to individuals based on job classification and function (also called "role-based access control" or RBAC).'),
('R', '7', '1', '3', 'Requirement for a documented approval by authorized parties specifying required privileges', '1', NULL, NULL, NULL, '<b>7.1.3</b> Confirm that documented approval by authorized parties is required (in writing or electronically) for all access, and that it must specify required privileges.'),
('R', '7', '1', '4', 'Implementation of an automated access control system', '1', NULL, NULL, NULL, '<b>7.1.4</b> Confirm that access controls are implemented via an automated access control system.'),

('R', '7', '2', '', 'Establish an access control system for systems components with multiple users that restricts access based on a userís need to know, and is set to "deny all" unless specifically allowed. This access control system must include the following:', '1', NULL, NULL, '50001,50002,50003,50004,50005,50006,50007,50008,50009,50010,50011,50012,50013,50014,50015,50016,50017,50018,50019,50020,50021,50', '<b>7.2</b> Examine system settings and vendor documentation to verify that an access control system is implemented as follows:'),
('R', '7', '2', '1', 'Coverage of all system components', '1', NULL, NULL, NULL, '<b>7.2.1</b> Confirm that access control systems are in place on all system components.'),
('R', '7', '2', '2', 'Assignment of privileges to individuals based on job classification and function', '1', NULL, NULL, NULL, '<b>7.2.2</b> Confirm that access control systems are configured to enforce privileges assigned to individuals based on job classification and function.'),
('R', '7', '2', '3', 'Default "deny-all" setting', '1', NULL, NULL, NULL, '<b>7.2.3</b> Confirm that the access control systems have a default "deny-all" setting.');

--
-- Dumping data for table `R08_UniqueID`
--

INSERT IGNORE INTO `R08_UniqueID` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '8', '1', '', 'Assign all users a unique ID before allowing them to access system components or cardholder data.', '1', NULL, NULL, NULL, '<b>8.1</b> Verify that all users are assigned a unique ID for access to system components or cardholder data.'),

('R', '8', '2', '', 'In addition to assigning a unique ID, employ at least one of the following methods to authenticate all users: * Something you know, such as a password or passphrase ,* Something you have, such as a token device or smart card,* Something you are, such as a biometric', '1', NULL, NULL, NULL, '<b>8.2</b> To verify that users are authenticated using unique ID and additional authentication (for example, a password) for access to the cardholder data environment, perform the following:<br>* Obtain and examine documentation describing the authentication method(s) used. <br>* For each type of authentication method used and for each type of system component, observe an authentication to verify authentication is functioning consistent with documented authentication method(s).'),

('R', '8', '3', '', 'Incorporate two-factor authentication for remote access (network-level access originating from outside the network) to the network by employees, administrators, and third parties. (For example, remote authentication and dialin service (RADIUS) with tokens; terminal access controller access control system (TACACS) with tokens; or other technologies that facilitate two-factor authentication.)', '1', NULL, NULL, NULL, '<b>8.3</b> To verify that two-factor authentication is implemented for all remote network access, observe an employee (for example, an administrator) connecting remotely to the network and verify that two of the three authentication methods are used.'),

('R', '8', '4', '', 'Render all passwords unreadable during transmission and storage on all system components using strong cryptography', '1', NULL, NULL, NULL, '<b>8.4.a</b> For a sample of system components, examine password files to verify that passwords are unreadable during transmission and storage. <br><b>8.4.b</b> For service providers only, observe password files to verify that customer passwords are encrypted.'),

('R', '8', '5', '', 'Ensure proper user identification and authentication management for nonconsumer users and administrators on all system components as follows:', '1', NULL, NULL, NULL, '<b>8.5</b> Review procedures and interview personnel to verify that procedures are implemented for user identification and authentication management, by performing the following:'),
('R', '8', '5', '1', 'Control addition, deletion, and modification of user IDs, credentials, and other identifier objects', NULL, '1', NULL, NULL, '<b>8.5.1</b> Select a sample of user IDs, including both administrators and general users. Verify that each user is authorized to use the system according to policy by performing the following: <br>* Obtain and examine an authorization form for each ID. <br>* Verify that the sampled user IDs are implemented in accordance with the authorization form (including with privileges as specified and all signatures obtained), by tracing information from the authorization form to the system.'),
('R', '8', '5', '2', 'Verify user identity before performing password resets', NULL, '1', NULL, NULL, '<b>8.5.2</b> Examine password/authentication procedures and observe security personnel to verify that, if a user requests a password reset by phone, e-mail, web, or other non-face-to-face method, the userís identity is verified before the password is reset.'),
('R', '8', '5', '3', 'Set passwords for first-time use and resets to a unique value for each user and change immediately after the first use.', NULL, '1', NULL, NULL, '<b>8.5.3</b> Examine password procedures and observe security personnel to verify that first-time passwords for new users, and reset passwords for existing users, are set to a unique value for each user and changed after first use.'),
('R', '8', '5', '4', 'Immediately revoke access for any terminated users', '1', NULL, NULL, NULL, '<b>8.5.4</b> Select a sample of users terminated in the past six months, and review current user access lists to verify that their IDs have been deactivated or removed.'),
('R', '8', '5', '5', 'Remove/disable inactive user accounts at least every 90 days', '1', NULL, NULL, NULL, '<b>8.5.5</b> Verify that inactive accounts over 90 days old are either removed or disabled.'),
('R', '8', '5', '6', 'Enable accounts used by vendors for remote access only during the time period needed. Monitor vendor remote access accounts when in use.', '1', NULL, NULL, NULL, '<b>8.5.6.a</b> Verify that any accounts used by vendors to access, support and maintain system components are disabled, and enabled only when needed by the vendor. <br><b>8.5.6.b</b> Verify that vendor remote access accounts are monitored while being used.'),
('R', '8', '5', '7', 'Communicate authentication procedures and policies to all users who have access to cardholder data', '1', NULL, NULL, NULL, '<b>8.5.7</b> Interview the users from a sample of user IDs, to verify that they are familiar with authentication procedures and policies.'),
('R', '8', '5', '8', 'Do not use group, shared, or generic accounts and passwords, or other authentication methods', '1', NULL, NULL, NULL, '<b>8.5.8.a</b> For a sample of system components, examine user ID lists to verify the following: <br>* Generic user IDs and accounts are disabled or removed <br>* Shared user IDs for system administration activities and other critical functions do not exist <br>* Shared and generic user IDs are not used to administer any system components <br><b>8.5.8.b</b> Examine authentication policies/procedures to verify that group and shared passwords or other authentication methods are explicitly prohibited. <br><b>8.5.8.c</b> Interview system administrators to verify that group and shared passwords or other authentication methods are not distributed, even if requested.'),
('R', '8', '5', '9', 'Change user passwords at least every 90 days', '1', NULL, NULL, NULL, '<b>8.5.9.a</b> For a sample of system components, obtain and inspect system configuration settings to verify that user password parameters are set to require users to change passwords at least every 90 days.<br><b>8.5.9.b</b> For service providers only, review internal processes and customer/user documentation to verify that non-consumer user passwords are required to change periodically and that nonconsumer users are given guidance as to when, and under what circumstances, passwords must change.'),
('R', '8', '5', '10', 'Require a minimum password length of at least seven characters', '1', NULL, NULL, NULL, '<b>8.5.10.a</b> For a sample of system components, obtain and inspect system configuration settings to verify that password parameters are set to require passwords to be at least seven characters long. <b>8.5.10.b</b> For service providers only, review internal processes and customer/user documentation to verify that that non-consumer user passwords are required to meet minimum length requirements.'),
('R', '8', '5', '11', 'Use passwords containing both numeric and alphabetic characters', '1', NULL, NULL, NULL, '<b>8.5.11.a</b> For a sample of system components, obtain and inspect system configuration settings to verify that password parameters are set to require passwords to contain both numeric and alphabetic characters. <br><b>8.5.11.b</b> For service providers only, review internal processes and customer/user documentation to verify that non-consumer user passwords are required to contain both numeric and alphabetic characters.'),
('R', '8', '5', '12', 'Do not allow an individual to submit a new password that is the same as any of the last four passwords he or she has used', '1', NULL, NULL, NULL, '<b>8.5.12.a</b> For a sample of system components, obtain and inspect system configuration settings to verify that password parameters are set to require that new passwords cannot be the same as the four previously used passwords. <br><b>8.5.12.b</b> For service providers only, review internal processes and customer/user documentation to verify that new non-consumer user passwords cannot be the same as the previous four passwords.'),
('R', '8', '5', '13', 'Limit repeated access attempts by locking out the user ID after not more than six attempts', NULL, '1', NULL, '50001,50002,50003,50004,50005,50006,50007,50008,50009,50010,50011,50012,50013,50014,50015,50016,50017,50018,50019,50020,50021,50','<b>8.5.13.a</b> For a sample of system components, obtain and inspect system configuration settings to verify that authentication parameters are set to require that a userís account be locked out after not more than six invalid logon attempts. <br><b>8.5.13.b</b> For service providers only, review internal processes and customer/user documentation to verify that non-consumer user accounts are temporarily locked-out after not more than six invalid access attempts.'),
('R', '8', '5', '14', 'Set the lockout duration to a minimum of 30 minutes or until administrator enables the user ID', NULL, '1', NULL, NULL, '<b>8.5.14</b> For a sample of system components, obtain and inspect system configuration settings to verify that password parameters are set to require that once a user account is locked out, it remains locked for a minimum of 30 minutes or until a system administrator resets the account.'),
('R', '8', '5', '15', 'If a session has been idle for more than 15 minutes, require the user to re-authenticate to re-activate the terminal or session', NULL, '1', NULL, NULL, '<b>8.5.15</b> For a sample of system components, obtain and inspect system configuration settings to verify that system/session idle time out features have been set to 15 minutes or less.'),
('R', '8', '5', '16', 'Authenticate all access to any database containing cardholder data. This includes access by applications, administrators, and all other users. Restrict user direct access or queries to databases to database administrators', '1', NULL, NULL, NULL, '<b>8.5.16.a</b> Review database and application configuration settings and verify that all users are authenticated prior to access. <br><b>8.5.16.b</b> Verify that database and application configuration settings ensure that all user access to, user queries of, and user actions on (for example, move, copy, delete), the database are through programmatic methods only (for example, through stored procedures). <br><b>8.5.16.c</b> Verify that database and application configuration settings restrict user direct access or queries to databases to database administrators. <br><b>8.5.16.d</b> Review database applications and the related application IDs to verify that application IDs can only be used by the applications (and not by individual users or other processes).');

--
-- Dumping data for table `R09_Physical_Access`
--

INSERT IGNORE INTO `R09_Physical_Access` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '9', '1', '', 'Use appropriate facility entry controls to limit and monitor physical access to systems in the cardholder data environment', '1', NULL, NULL, NULL, '<b>9.1</b> Verify the existence of physical security controls for each computer room, data center, and other physical areas with systems in the cardholder data environment. <br>* Verify that access is controlled with badge readers or other devices including authorized badges and lock and key. <br>* Observe a system administratorís attempt to log into consoles for randomly selected systems in the cardholder environment and verify that they are "locked" to prevent unauthorized use.'),
('R', '9', '1', '1', 'Use video cameras and/or access control mechanisms to monitor individual physical access to sensitive areas. Review collected data and correlate with other entries. Store for at least three months, unless otherwise restricted by law', NULL, '1', NULL, NULL, '<b>9.1.1.a</b> Verify that video cameras and/or access control mechanisms are in place to monitor the entry/exit points to sensitive areas. <br><b>9.1.1.b</b> Verify that video cameras and/or access control mechanisms are protected from tampering or disabling. <br><b>9.1.1.c</b> Verify that video cameras and/or access control mechanisms are monitored and that data from cameras or other mechanisms is stored for at least three months.'),
('R', '9', '1', '2', 'Restrict physical access to publicly accessible network jacks. For example, areas accessible to visitors should not have network ports enabled unless network access is explicitly authorized', NULL, '1', NULL, NULL, '<b>9.1.2</b> Verify by interviewing network administrators and by observation that network jacks are enabled only when needed by authorized onsite personnel. Alternatively, verify that visitors are escorted at all times in areas with active network jacks.'),
('R', '9', '1', '3', 'Restrict physical access to wireless access points, gateways, handheld devices, networking/communications hardware, and telecommunication lines.', NULL, '1', NULL, NULL, '<b>9.1.3</b> Verify that physical access to wireless access points, gateways, handheld devices, networking/communications hardware, and telecommunication lines is appropriately restricted.'),

('R', '9', '2', '', 'Develop procedures to easily distinguish between onsite personnel and visitors, especially in areas where cardholder data is accessible', NULL, '1', NULL, NULL, '<b>9.2.a</b> Review processes and procedures for assigning badges to onsite personnel and visitors, and verify these processes include the following: <br>* Granting new badges, <br>* Changing access requirements, and <br>* Revoking terminated onsite personnel and expired visitor badges <br><b>9.2.b</b> Verify that access to the badge system is limited to authorized personnel. <br><b>9.2.c</b> Examine badges in use to verify that they clearly identify visitors and it is easy to distinguish between onsite personnel and visitors.'),

('R', '9', '3', '', 'Make sure all visitors are handled as follows:', '1', NULL, NULL, NULL, '<b>9.3</b> Verify that visitor controls are in place as follows:'),
('R', '9', '3', '1', 'Authorized before entering areas where cardholder data is processed or maintained', NULL, '1', NULL, NULL, 'Observe the use of visitor ID badges to verify that a visitor ID badge does not permit unescorted access to physical areas that store cardholder data.'),
('R', '9', '3', '2', 'Given a physical token (for example, a badge or access device) that expires and that identifies the visitors as not onsite personnel.', NULL, '1', NULL, NULL, '<b>9.3.2.a</b> Observe people within the facility to verify the use of visitor ID badges, and that visitors are easily distinguishable from onsite personnel. <br><b>9.3.2.b</b> Verify that visitor badges expire.'),
('R', '9', '3', '3', 'Asked to surrender the physical token before leaving the facility or at the date of expiration', NULL, '1', NULL, NULL, '<b>9.3.3</b> Observe visitors leaving the facility to verify visitors are asked to surrender their ID badge upon departure or expiration.'),

('R', '9', '4', '', 'Use a visitor log to maintain a physical audit trail of visitor activity. Document the visitorís name, the firm represented, and the onsite personnel authorizing physical access on the log. Retain this log for a minimum of three months, unless otherwise restricted by law.', '1', NULL, NULL, NULL, '<b>9.4.a</b> Verify that a visitor log is in use to record physical access to the facility as well as for computer rooms and data centers where cardholder data is stored or transmitted. <br><b>9.4.b</b> Verify that the log contains the visitorís name, the firm represented, and the onsite personnel authorizing physical access, and is retained for at least three months.'),

('R', '9', '5', '', 'Store media back-ups in a secure location, preferably an off-site facility, such as an alternate or back-up site, or a commercial storage facility. Review the locationís security at least annually.', NULL, '1', NULL, NULL, '<b>9.5.a</b> Observe the storage locationís physical security to confirm that backup media storage is secure. <br><b>9.5.b</b> Verify that the storage location security is reviewed at least annually.'),

('R', '9', '6', '', 'Physically secure all media', NULL, '1', NULL, NULL, '<b>9.6</b> Verify that procedures for protecting cardholder data include controls for physically securing all media (including but not limited to computers, removable electronic media, paper receipts, paper reports, and faxes).'),

('R', '9', '7', '', 'Maintain strict control over the internal or external distribution of any kind of media, including the following', NULL, '1', NULL, NULL, '<b>9.7</b> Verify that a policy exists to control distribution of media, and that the policy covers all distributed media including that distributed to individuals.'),
('R', '9', '7', '1', 'Classify media so the sensitivity of the data can be determined', NULL, '1', NULL, NULL, '<b>9.7.1</b> Verify that all media is classified so the sensitivity of the data can be determined.'),
('R', '9', '7', '2', 'Send the media by secured courier or other delivery method that can be accurately tracked', NULL, '1', NULL, NULL, '<b>9.7.2</b> Verify that all media sent outside the facility is logged and authorized by management and sent via secured courier or other delivery method that can be tracked'),

('R', '9', '8', '', 'Ensure management approves any and all media that is moved from a secured area (especially when media is distributed to individuals)', NULL, '1', NULL, NULL, '<b>9.8</b> Select a recent sample of several days of offsite tracking logs for all media, and verify the presence in the logs of tracking details and proper management authorization.'),

('R', '9', '9', '', 'Maintain strict control over the storage and accessibility of media', '1', NULL, NULL, NULL, '<b>9.9</b> Obtain and examine the policy for controlling storage and maintenance of all media and verify that the policy requires periodic media inventories.'),
('R', '9', '9', '1', 'Properly maintain inventory logs of all media and conduct media inventories at least annually.', NULL, '1', NULL, NULL, '<b>9.9.1</b> Obtain and review the media inventory log to verify that periodic media inventories are performed at least annually.'),

('R', '9', '10', '', 'Destroy media when it is no longer needed for business or legal reasons as follows:', '1', NULL, NULL, NULL, '9.10 Obtain and examine the periodic media destruction policy and verify that it covers all media, and confirm the following:'),
('R', '9', '10', '1', 'Shred, incinerate, or pulp hardcopy materials so that cardholder data cannot be reconstructed', '1', NULL, NULL, NULL, '<b>9.10.1.a</b> Verify that hard-copy materials are crosscut shredded, incinerated, or pulped such that there is reasonable assurance the hard-copy materials cannot be reconstructed. <br><b>9.10.1.b</b> Examine storage containers used for information to be destroyed to verify that the containers are secured. For example, verify that a "to-be-shredded" container has a lock preventing access to its contents'),
('R', '9', '10', '2', 'Render cardholder data on electronic media unrecoverable so that cardholder data cannot be reconstructed', '1', NULL, NULL, NULL, '<b>9.10.2</b> Verify that cardholder data on electronic media is rendered unrecoverable via a secure wipe program in accordance with industry-accepted standards for secure deletion, or otherwise physically destroying the media (for example, degaussing).');

--
-- Dumping data for table `R10_Monitoring`
--

INSERT IGNORE INTO `R10_Monitoring` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '10', '1', '', 'Establish a process for linking all access to system components (especially access done with administrative privileges such as root) to each individual user.', '1', NULL, NULL, NULL, '10.1 Verify through observation and interviewing the system administrator, that audit trails are enabled and active for system components.'),

('R', '10', '2', '', 'Implement automated audit trails for all system components to reconstruct the following events:', '1', NULL, NULL, NULL, '<b>10.2</b> Through interviews, examination of audit logs, and examination of audit log settings, perform the following:'),
('R', '10', '2', '1', 'All individual accesses to cardholder data', '1', NULL, NULL, NULL, '<b>10.2.1</b> Verify all individual access to cardholder data is logged.'),
('R', '10', '2', '2', 'All actions taken by any individual with root or administrative privileges', NULL, '1', NULL, NULL, '<b>10.2.2</b> Verify actions taken by any individual with root or administrative privileges are logged.'),
('R', '10', '2', '3', 'Access to all audit trails', '1', NULL, NULL, NULL, '<b>10.2.3</b> Verify access to all audit trails is logged.'),
('R', '10', '2', '4', 'Invalid logical access attempts', '1', NULL, NULL, NULL, '<b>10.2.4</b> Verify invalid logical access attempts are logged.'),
('R', '10', '2', '5', 'Use of identification and authentication mechanisms', '1', NULL, NULL, NULL, '<b>10.2.5</b> Verify use of identification and authentication mechanisms is logged.'),
('R', '10', '2', '6', 'Initialization of the audit logs', '1', NULL, NULL, NULL, '<b>10.2.6</b> Verify initialization of audit logs is logged.'),
('R', '10', '2', '7', 'Creation and deletion of system-level objects', '1', NULL, NULL, NULL, '<b>10.2.7</b> Verify creation and deletion of system level objects are logged.'),

('R', '10', '3', '', 'Record at least the following audit trail entries for all system components for each event:', NULL, '1', NULL, NULL, '<b>10.3</b> Through interviews and observation, for each auditable event (from 10.2), perform the following:'),
('R', '10', '3', '1', 'User identification', '1', NULL, NULL, NULL, '<b>10.3.1</b> Verify user identification is included in log entries.'),
('R', '10', '3', '2', 'Type of event', '1', NULL, NULL, NULL, '<b>10.3.2</b> Verify type of event is included in log entries.'),
('R', '10', '3', '3', 'Date and time', '1', NULL, NULL, NULL, '<b>10.3.3</b> Verify date and time stamp is included in log entries.'),
('R', '10', '3', '4', 'Success or failure indication', NULL, '1', NULL, NULL, '<b>10.3.4</b> Verify success or failure indication is included in log entries.'),
('R', '10', '3', '5', 'Origination of event', NULL, '1', NULL, NULL, '<b>10.3.5</b> Verify origination of event is included in log entries.'),
('R', '10', '3', '6', 'Identity or name of affected data, system component, or resource.', '1', NULL, NULL, NULL, '<b>10.3.6</b> Verify identity or name of affected data, system component, or resources is included in log entries.'),

('R', '10', '4', '', 'Using time-synchronization technology, synchronize all critical system clocks and times and ensure that the following is implemented for acquiring, distributing, and storing time', '1', NULL, NULL, NULL, '<b>10.4.a</b> Verify that time-synchronization technology is implemented and kept current per PCI DSS Requirements 6.1 and 6.2.<br><b>10.4.b</b> Obtain and review the process for acquiring, distributing and storing the correct time within the organization, and review the time-related system-parameter settings for a sample of system components. Verify the following is included in the process and implemented:'),
('R', '10', '4', '1', 'Critical systems have the correct and consistent time', '1', NULL, NULL, NULL, '<b>10.4.1.a</b> Verify that only designated central time servers receive time signals from external sources, and time signals from external sources are based on International Atomic Time or UTC.<br><b>10.4.1.b</b> Verify that the designated central time servers peer with each other to keep accurate time, and other internal servers receive time only from the central time servers.'),
('R', '10', '4', '2', 'Time data is protected', '1', NULL, NULL, NULL, '<b>10.4.2.a</b> Review system configurations and time-synchronization settings to verify that access to time data is restricted to only personnel with a business need to access time data. <br><b>10.4.2.b</b> Review system configurations and time synchronization settings and processes to verify that any changes to time settings on critical systems are logged, monitored, and reviewed.'),
('R', '10', '4', '3', 'Time settings are received from industry-accepted time sources', '1', NULL, NULL, NULL, '<b>10.4.3</b> Verify that the time servers accept time updates from specific, industry-accepted external sources (to prevent a malicious individual from changing the clock). Optionally, those updates can be encrypted with a symmetric key, and access control lists can be created that specify the IP addresses of client machines that will be provided with the time updates (to prevent unauthorized use of internal time servers).'),

('R', '10', '5', '', 'Secure audit trails so they cannot be altered', '1', NULL, NULL, NULL, '10.5 Interview system administrator and examine permissions to verify that audit trails are secured so that they cannot be altered as follows:'),
('R', '10', '5', '1', 'Limit viewing of audit trails to those with a job-related need', NULL, '1', NULL, NULL, '<b>10.5.1</b> Verify that only individuals who have a job-related need can view audit trail files.'),
('R', '10', '5', '2', 'Protect audit trail files from unauthorized modifications', '1', NULL, NULL, NULL, '<b>10.5.2</b> Verify that current audit trail files are protected from unauthorized modifications via access control mechanisms, physical segregation, and/or network segregation.'),
('R', '10', '5', '3', 'Promptly back-up audit trail files to a centralized log server or media that is difficult to alter', '1', NULL, NULL, NULL, '<b>10.5.3</b> Verify that current audit trail files are promptly backed up to a centralized log server or media that is difficult to alter.'),
('R', '10', '5', '4', 'Copy logs for wireless networks onto a log server on the internal LAN', '1', NULL, NULL, NULL, '<b>10.5.4</b> Verify that logs for external-facing technologies (for example, wireless, firewalls, DNS, mail) are offloaded or copied onto a secure centralized internal log server or media.'),
('R', '10', '5', '5', 'Use file-integrity monitoring or change-detection software on logs to ensure that existing log data cannot be changed without generating alerts (although new data being added should not cause an alert)', NULL, '1', NULL, NULL, '<b>10.5.5</b> Verify the use of file-integrity monitoring or changedetection software for logs by examining system settings and monitored files and results from monitoring activities.'),

('R', '10', '6', '', 'Review logs for all system components at least daily. Log reviews must include those servers that perform security functions like intrusion-detection system (IDS) and authentication, authorization, and accounting protocol (AAA) servers (for example, RADIUS)', '1', NULL, NULL, NULL, '<b>10.6.a</b> Obtain and examine security policies and procedures to verify that they include procedures to review security logs at least daily and that follow-up to exceptions is required. <br><b>10.6.b</b> Through observation and interviews, verify that regular log reviews are performed for all system components.'),

('R', '10', '7', '', 'Retain audit trail history for at least one year, with a minimum of three months immediately available for analysis (for example, online, archived, or restorable from back-up)', '1', NULL, NULL, NULL, '<b>10.7.a</b> Obtain and examine security policies and procedures and verify that they include audit log retention policies and require audit log retention for at least one year.<br><b>10.7.b</b> Verify that audit logs are available for at least one year and processes are in place to immediately restore at least the last three monthsí logs for analysis.');

--
-- Dumping data for table `R11_Security_test`
--

INSERT IGNORE INTO `R11_Security_test` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '11', '1', '', 'Test for the presence of wireless access points and detect unauthorized wireless access points on a quarterly basis.', '1', NULL, NULL, NULL, '<b>11.1.a</b> Verify that the entity has a documented process to detect and identify wireless access points on a quarterly basis. <br><b>11.1.b</b> Verify that the methodology is adequate to detect and identify any unauthorized wireless access points, including at least the following: <br>* WLAN cards inserted into system components <br>* Portable wireless devices connected to system components (for example, by USB, etc.) <br>* Wireless devices attached to a network port or network device <br><b>11.1.c</b> Verify that the documented process to identify unauthorized wireless access points is performed at least quarterly for all system components and facilities. <br><b>11.1.d</b> If automated monitoring is utilized (for example, wireless IDS/IPS, NAC, etc.), verify the configuration will generate alerts to personnel. <br><b>11.1.e</b> Verify the organizationís incident response plan (Requirement 12.9) includes a response in the event unauthorized wireless devices are detected.'),

('R', '11', '2', '', 'Run internal and external network vulnerability scans at least quarterly and after any significant change in the network (such as new system component installations, changes in network topology, firewall rule modifications, product upgrades)', NULL, '1', NULL, NULL, '<b>11.2</b> Verify that internal and external vulnerability scans are performed as follows:'),
('R', '11', '2', '1', 'Perform quarterly internal vulnerability scans', NULL, '1', NULL, NULL, '<b>11.2.1.a</b> Review the scan reports and verify that four quarterly internal scans occurred in the most recent 12-month period. <br><b>11.2.1.b</b> Review the scan reports and verify that the scan process includes rescans until passing results are obtained, or all "High" vulnerabilities as defined in PCI DSS Requirement 6.2 are resolved. <br><b>11.2.1.c</b> Validate that the scan was performed by a qualified internal resource(s) or qualified external third party, and if applicable, organizational independence of the tester exists (not required to be a QSA or ASV).'),
('R', '11', '2', '2', 'Perform quarterly external vulnerability scans via an Approved Scanning Vendor (ASV), approved by the Payment Card Industry Security Standards Council (PCI SSC).', NULL, '1', NULL, NULL, '<b>11.2.2.a</b> Review output from the four most recent quarters of external vulnerability scans and verify that four quarterly scans occurred in the most recent 12-month period. <br><b>11.2.2.b</b> Review the results of each quarterly scan to ensure that they satisfy the ASV Program Guide requirements (for example, no vulnerabilities rated higher than a 4.0 by the CVSS and no automatic failures).<br><b>11.2.2.c</b> Review the scan reports to verify that the scans were completed by an Approved Scanning Vendor (ASV), approved by the PCI SSC.'),
('R', '11', '2', '3', 'Perform internal and external scans after any significant change', NULL, '1', NULL, NULL, '<b>11.2.3.a</b> Inspect change control documentation and scan reports to verify that system components subject to any significant change were scanned. <br><b>11.2.3.b</b> Review scan reports and verify that the scan process includes rescans until:<br> For external scans, no vulnerabilities exist that are scored greater than a 4.0 by the CVSS,  For internal scans, a passing result is obtained or all "High" vulnerabilities as defined in PCI DSS Requirement 6.2 are resolved. <br><b>11.2.3.c</b> Validate that the scan was performed by a qualified internal resource(s) or qualified external third party, and if applicable, organizational independence of the tester exists (not required to be a QSA or ASV).'),

('R', '11', '3', '', 'Perform external and internal penetration testing at least once a year and after any significant infrastructure or application upgrade or modification (such as an operating system upgrade, a subnetwork added to the environment, or a web server added to the environment). These penetration tests must include the following:', '1', NULL, NULL, NULL, '<b>11.3.a</b> Obtain and examine the results from the most recent penetration test to verify that penetration testing is performed at least annually and after any significant changes to the environment. <br><b>11.3.b</b> Verify that noted exploitable vulnerabilities were corrected and testing repeated. <br><b>11.3.c</b> Verify that the test was performed by a qualified internal resource or qualified external third party, and if applicable, organizational independence of the tester exists (not required to be a QSA or ASV).'),
('R', '11', '3', '1', 'Network-layer penetration tests', '1', NULL, NULL, NULL, '<b>11.3.1</b> Verify that the penetration test includes network-layer penetration tests. These tests should include components that support network functions as well as operating systems.'),
('R', '11', '3', '2', 'Application-layer penetration tests.', '1', NULL, NULL, NULL, '<b>11.3.2</b> Verify that the penetration test includes application-layer penetration tests. The tests should include, at a minimum, the vulnerabilities listed in Requirement 6.5.'),

('R', '11', '4', '', 'Use intrusion-detection systems, and/or intrusion-prevention systems to monitor all traffic at the perimeter of the cardholder data environment as well as at critical points inside of the cardholder data environment, and alert personnel to suspected compromises. Keep all intrusion-detection and prevention engines, baselines, and signatures up-to-date.', '1', NULL, NULL, NULL, '<b>11.4.a</b> Verify the use of intrusion-detection systems and/or intrusion-prevention systems and that all traffic at the perimeter of the cardholder data environment as well as at critical points in the cardholder data environment is monitored.<br><b>11.4.b</b> Confirm IDS and/or IPS are configured to alert personnel of suspected compromises. <br><b>11.4.c</b> Examine IDS/IPS configurations and confirm IDS/IPS devices are configured, maintained, and updated per vendor instructions to ensure optimal protection.'),

('R', '11', '5', '', 'Deploy file-integrity monitoring tools to alert personnel to unauthorized modification of critical system files, configuration files, or content files; and configure the software to perform critical file comparisons at least weekly.', '1', NULL, NULL, NULL, '<b>11.5.a</b> Verify the use of file-integrity monitoring tools within the cardholder data environment by observing system settings and monitored files, as well as reviewing results from monitoring activities. Examples of files that should be monitored:<br>* System executables <br>* Application executables <br>* Configuration and parameter files <br>* Centrally stored, historical or archived, log and audit files <br><b>11.5.b</b> Verify the tools are configured to alert personnel to unauthorized modification of critical files, and to perform critical file comparisons at least weekly.');

--
-- Dumping data for table `R12_IS_Policy`
--

INSERT IGNORE INTO `R12_IS_Policy` (`x1`, `x2`, `x3`, `x4`, `Security_control`, `operational`, `not_operational`, `comments`, `SIDSS_ref`,`testing_procedures`) VALUES
('R', '12', '1', '', 'Establish, publish, maintain, and disseminate a security policy that accomplishes the following:', '1', NULL, NULL, NULL, '<b>12.1</b> Examine the information security policy and verify that the policy is published and disseminated to all relevant personnel (including vendors and business partners).'),
('R', '12', '1', '1', 'Addresses all PCI DSS requirements', '1', NULL, NULL, NULL, '<b>12.1.1</b> Verify that the policy addresses all PCI DSS requirements.'),
('R', '12', '1', '2', 'Includes an annual process that identifies threats, and vulnerabilities, and results in a formal risk assessment. (Examples of risk assessment methodologies include but are not limited to OCTAVE, ISO 27005 and NIST SP 800-30.)', NULL, '1', NULL, NULL, '<b>12.1.2.a</b> Verify that an annual risk assessment process is documented that identifies threats, vulnerabilities, and results in a formal risk assessment. <br><b>12.1.2.b</b> Review risk assessment documentation to verify that the risk assessment process is performed at least annually.'),
('R', '12', '1', '3', 'Includes a review at least annually and updates when the environment changes', NULL, '1', NULL, NULL, '<b>12.1.3</b> Verify that the information security policy is reviewed at least annually and updated as needed to reflect changes to business objectives or the risk environment.'),

('R', '12', '2', '', 'Develop daily operational security procedures that are consistent with requirements in this specification (for example, user account maintenance procedures, and log review procedures)', '1', NULL, NULL, NULL, '<b>12.2</b> Examine the daily operational security procedures. Verify that they are consistent with this specification, and include administrative and technical procedures for each of the requirements.'),

('R', '12', '3', '', 'Develop usage policies for critical technologies (for example, remoteaccess technologies, wireless technologies, removable electronic media, laptops, tablets, personal data/digital assistants (PDAs), e-mail usage and Internet usage) and define proper use of these technologies. Ensure these usage policies require the following:', '1', NULL, NULL, NULL, '<b>12.3</b> Obtain and examine the usage policies for critical technologies and perform the following:'),
('R', '12', '3', '1', 'Explicit approval by authorized parties', '1', NULL, NULL, NULL, '<b>12.3.1</b> Verify that the usage policies require explicit approval from authorized parties to use the technologies.'),
('R', '12', '3', '2', 'Authentication for use of the technology', NULL, '1', NULL, NULL, '<b>12.3.2</b> Verify that the usage policies require that all technology use be authenticated with user ID and password or other authentication item (for example, token).'),
('R', '12', '3', '3', 'A list of all such devices and personnel with access', '1', NULL, NULL, NULL, '<b>12.3.3</b> Verify that the usage policies require a list of all devices and personnel authorized to use the devices.'),
('R', '12', '3', '4', 'Labeling of devices to determine owner, contact information and purpose', '1', NULL, NULL, NULL, '<b>12.3.4</b> Verify that the usage policies require labeling of devices with information that can be correlated to owner, contact information and purpose.'),
('R', '12', '3', '5', 'Acceptable uses of the technology', '1', NULL, NULL, NULL, '<b>12.3.5</b> Verify that the usage policies require acceptable uses for the technology.'),
('R', '12', '3', '6', 'Acceptable network locations for the technologies', '1', NULL, NULL, NULL, '<b>12.3.6</b> Verify that the usage policies require acceptable network locations for the technology.'),
('R', '12', '3', '7', 'List of company-approved products', '1', NULL, NULL, NULL, '<b>12.3.7</b> Verify that the usage policies require a list of companyapproved products.'),
('R', '12', '3', '8', 'Automatic disconnect of sessions for remote-access technologies after a specific period of inactivity', NULL, '1', NULL, NULL, '<b>12.3.8</b> Verify that the usage policies require automatic disconnect of sessions for remote-access technologies after a specific period of inactivity.'),
('R', '12', '3', '9', 'Activation of remote-access technologies for vendors and business partners only when needed by vendors and business partners, with immediate deactivation after use', NULL, '1', NULL, NULL, '<b>12.3.9</b> Verify that the usage policies require activation of remoteaccess technologies used by vendors and business partners only when needed by vendors and business partners, with immediate deactivation after use.'),
('R', '12', '3', '10', 'For personnel accessing cardholder data via remote-access technologies, prohibit copy, move, and storage of cardholder data onto local hard drives and removable electronic media, unless explicitly authorized for a defined business need.', '1', NULL, NULL, NULL, '<b>12.3.10.a</b> Verify that the usage policies prohibit copying, moving, or storing of cardholder data onto local hard drives and removable electronic media when accessing such data via remote-access technologies. <br><b>12.3.10.b</b> For personnel with proper authorization, verify that usage policies require the protection of cardholder data in accordance with PCI DSS Requirements.'),

('R', '12', '4', '', 'Ensure that the security policy and procedures clearly define information security responsibilities for all personnel', '1', NULL, NULL, NULL, '<b>12.4</b> Verify that information security policies clearly define information security responsibilities for all personnel.'),

('R', '12', '5', '', 'Assign to an individual or team the following information security management responsibilities:', NULL, '1', NULL, NULL, '<b>12.5</b> Verify the formal assignment of information security to a Chief Security Officer or other security-knowledgeable member of management.<br>Obtain and examine information security policies and procedures to verify that the following information security responsibilities are specifically and formally assigned:'),
('R', '12', '5', '1', 'Establish, document, and distribute security policies and procedures', '1', NULL, NULL, NULL, '<b>12.5.1</b> Verify that responsibility for creating and distributing security policies and procedures is formally assigned.'),
('R', '12', '5', '2', 'Monitor and analyze security alerts and information, and distribute to appropriate personnel', '1', NULL, NULL, NULL, '<b>12.5.2</b> Verify that responsibility for monitoring and analyzing security alerts and distributing information to appropriate information security and business unit management personnel is formally assigned.'),
('R', '12', '5', '3', 'Establish, document, and distribute security incident response and escalation procedures to ensure timely and effective handling of all situations', '1', NULL, NULL, NULL, '<b>12.5.3</b> Verify that responsibility for creating and distributing security incident response and escalation procedures is formally assigned.'),
('R', '12', '5', '4', 'Administer user accounts, including additions, deletions, and modifications', '1', NULL, NULL, NULL, '12.5.4 Verify that responsibility for administering user account and authentication management is formally assigned.'),
('R', '12', '5', '5', 'Monitor and control all access to data', '1', NULL, NULL, NULL, '<b>12.5.5</b> Verify that responsibility for monitoring and controlling all access to data is formally assigned.'),

('R', '12', '6', '', 'Implement a formal security awareness program to make all personnel aware of the importance of cardholder data security.', NULL, '1', NULL, NULL, '<b>12.6.a</b> Verify the existence of a formal security awareness program for all personnel. <br><b>12.6.b</b> Obtain and examine security awareness program procedures and documentation and perform the following:'),
('R', '12', '6', '1', 'Educate personnel upon hire and at least annually', NULL, '1', NULL, NULL, '<b>12.6.1.a</b> Verify that the security awareness program provides multiple methods of communicating awareness and educating personnel (for example, posters, letters, memos, web based training, meetings, and promotions). <br><b>12.6.1.b</b> Verify that personnel attend awareness training upon hire and at least annually.'),
('R', '12', '6', '2', 'Require personnel to acknowledge at least annually that they have read and understood the security policy and procedures', NULL, '1', NULL, NULL, '<b>12.6.2</b> Verify that the security awareness program requires personnel to acknowledge, in writing or electronically, at least annually that they have read and understand the information security policy.'),

('R', '12', '7', '', 'Screen potential personnel prior to hire to minimize the risk of attacks from internal sources. (Examples of background checks include previous employment history, criminal record, credit history, and reference checks.)', NULL, '1', NULL, NULL, '<b>12.7</b> Inquire with Human Resource department management and verify that background checks are conducted (within the constraints of local laws) on potential personnel prior to hire who will have access to cardholder data or the cardholder data environment.'),

('R', '12', '8', '', 'If cardholder data is shared with service providers, maintain and implement policies and procedures to manage service providers, to include the following:', '1', NULL, NULL, NULL, '<b>12.8</b> If the entity shares cardholder data with service providers (for example, back-up tape storage facilities, managed service providers such as Web hosting companies or security service providers, or those that receive data for fraud modeling purposes), through observation, review of policies and procedures, and review of supporting documentation, perform the following:'),
('R', '12', '8', '1', 'Maintain a list of service providers', '1', NULL, NULL, NULL, '<b>12.8.1</b> Verify that a list of service providers is maintained.'),
('R', '12', '8', '2', 'Maintain a written agreement that includes an acknowledgement that the service providers are responsible for the security of cardholder data the service providers possess', '1', NULL, NULL, NULL, '<b>12.8.2</b> Verify that the written agreement includes an acknowledgement by the service providers of their responsibility for securing cardholder data.'),
('R', '12', '8', '3', 'Ensure there is an established process for engaging service providers including proper due diligence prior to engagement', '1', NULL, NULL, NULL, '<b>12.8.3</b> Verify that policies and procedures are documented and were followed including proper due diligence prior to engaging any service provider.'),
('R', '12', '8', '4', 'Maintain a program to monitor service providersí PCI DSS compliance status at least annually', '1', NULL, NULL, NULL, '<b>12.8.4</b> Verify that the entity maintains a program to monitor its service providersí PCI DSS compliance status at least annually'),

('R', '12', '9', '', 'Implement an incident response plan. Be prepared to respond immediately to a system breach', '1', NULL, NULL, NULL, '<b>12.9</b> Obtain and examine the Incident Response Plan and related procedures and perform the following:'),
('R', '12', '9', '1', 'Create the incident response plan to be implemented in the event of system breach', '1', NULL, NULL, NULL, '<b>12.9.1.a</b> Verify that the incident response plan includes: <br>* Roles, responsibilities, and communication strategies in the event of a compromise including notification of the payment brands, at a minimum: <br>* Specific incident response procedures <br>* Business recovery and continuity procedures <br>* Data back-up processes <br>* Analysis of legal requirements for reporting compromises (for example, California Bill 1386 which requires notification of affected consumers in the event of an actual or suspected compromise for any business with California residents in their database) <br>* Coverage and responses for all critical system components <br>* Reference or inclusion of incident response procedures from the payment brands <br><b>12.9.1.b</b> Review documentation from a previously reported incident or alert to verify that the documented incident response plan and procedures were followed.'),
('R', '12', '9', '2', 'Test the plan at least annually', '1', NULL, NULL, NULL, '<b>12.9.2</b> Verify that the plan is tested at least annually.'),
('R', '12', '9', '3', 'Designate specific personnel to be available on a 24/7 basis to respond to alerts', NULL, '1', NULL, NULL, '<b>12.9.3</b> Verify through observation and review of policies, that designated personnel are available for 24/7 incident response and monitoring coverage for any evidence of unauthorized activity, detection of unauthorized wireless access points, critical IDS alerts, and/or reports of unauthorized critical system or content file changes.'),
('R', '12', '9', '4', 'Provide appropriate training to staff with security breach response responsibilities', NULL, '1', NULL, NULL, '<b>12.9.4</b> Verify through observation and review of policies that staff with responsibilities for security breach response are periodically trained.'),
('R', '12', '9', '5', 'Include alerts from intrusion detection, intrusion prevention, and file integrity monitoring', '1', NULL, NULL, NULL, '<b>12.9.5</b> Verify through observation and review of processes that monitoring and responding to alerts from security systems including detection of unauthorized wireless access points are covered in the Incident Response Plan'),
('R', '12', '9', '6', 'Develop a process to modify and evolve the incident response plan according to lessons learned and to incorporate industry developments', NULL, '1', NULL, NULL, '<b>12.9.6</b> Verify through observation and review of policies that there is a process to modify and evolve the incident response plan according to lessons learned and to incorporate industry developments.');
