#!/bin/bash
exit 0

# obsolete: 
#if [ -x /usr/bin/ossim-db ] && [ -x /usr/bin/mysql ]; then
#SCHEMA_VERSION=`echo 'select vseq from \`schema\`;' | ossim-db snort | tail -n 1`
#  if [ $SCHEMA_VERSION -lt 200 ]; then
#    #########
#    # Drop ossim_event, alter some indexes, speed increase
#    #########
#		echo Migrating from pre 200 to 200 snort schema version
#    if [ -d /usr/share/ossim-database-migration/files/ ]; then
#      cat /usr/share/ossim-database-migration/files/snort_106_to_200.sql | ossim-db snort
#    fi
#  fi
#fi
#
#exit 0
