#!/bin/bash

base_dir=`grep base_dir /etc/ossim/framework/ossim.conf | cut -d= -f2`
mrtg_path=`grep mrtg_path /etc/ossim/framework/ossim.conf | cut -d= -f2`

cd $base_dir/mrtg/hosts
./create_cfg.pl

cd $base_dir/mrtg/nets
./create_cfg.pl

cd $base_dir/mrtg/global
./create_cfg.pl

$mrtg_path/mrtg /etc/ossim/framework/mrtg.cfg
$mrtg_path/mrtg /etc/ossim/framework/mrtg-rrd.cfg

