#!/usr/bin/python -OOt

import sys
sys.path.append('/usr/share/ossim-framework/')

from ossimframework.Framework import Framework


if __name__ == '__main__':

    f = Framework()
    #f.startup()
    f.main()
    #f.waitforever()

# vim:ts=4 sts=4 tw=79 expandtab:
