# Maintenance Playbook
# Input params:
# target: Host where it should remove the files
# Sample of usage:
# ansible-playbook -b --become-method=sudo  -v --extra-vars="tar_file=192.168.5.119.tar.gz target=192.168.5.119" /etc/ansible/playbooks/untar_vpn_and_start.yml

- name: unpack vpn configuracion and start openvpn service
  hosts: "{{ target }}"

  # Define the backup folder
  vars:
    target_path: /etc/openvpn/
    file: /tmp/"{{ tar_file }}"

  #Task list
  tasks:

#    - name: move tar.gz from tmp
#      action: shell mv /tmp/$tar_file /home/avapi/

    - name: unpack vpn configuration tar file.
      action: shell /bin/tar zxf {{ file }} -C /tmp/

    - name: move configuration files to dest
      action: shell cp -arf /tmp/etc/openvpn/nodes/* /etc/openvpn/

    - name: move the configuration to its folder
      action: shell mv /etc/openvpn/"{{ target }}"/*.conf /etc/openvpn/

    - name: move the keysize file to its folder
      action: shell mv /etc/openvpn/"{{ target }}"/*.keysize /etc/openvpn/

    - name: fire triggers
      action: shell dpkg-trigger --no-await alienvault-network-vpn-net-client

    - name: configure triggers
      action: shell dpkg --pending --configure

    - name: clean directories
      action: shell rm -rf /tmp/etc

    - name: clean tar file
      action: shell rm -rf {{ file }}

    - name: start/restart openvpn service
      action: shell /etc/init.d/openvpn restart

