/*
  License:

  Copyright (c) 2003-2006 ossim.net
  Copyright (c) 2007-2013 AlienVault
  All rights reserved.

  This package is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; version 2 dated June, 1991.
  You may not use, modify or distribute this program under any other version
  of the GNU General Public License.

  This package is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this package; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
  MA  02110-1301  USA


  On Debian GNU/Linux systems, the complete text of the GNU General
  Public License can be found in `/usr/share/common-licenses/GPL-2'.

  Otherwise you can read it here: http://www.gnu.org/licenses/gpl-2.0.txt
*/

#ifndef __SIM_SCANNER_TOKENS_H__
#define __SIM_SCANNER_TOKENS_H__
typedef enum {
  SIM_COMMAND_SCOPE_COMMAND,
  SIM_COMMAND_SCOPE_CONNECT,
  SIM_COMMAND_SCOPE_SESSION_APPEND_PLUGIN,
  SIM_COMMAND_SCOPE_SESSION_REMOVE_PLUGIN,
  SIM_COMMAND_SCOPE_SERVER_GET_SENSORS,
  SIM_COMMAND_SCOPE_SENSOR,						//command from children server	
  SIM_COMMAND_SCOPE_SERVER_GET_SERVERS,
  SIM_COMMAND_SCOPE_SERVER,						//command from children server	
  SIM_COMMAND_SCOPE_SERVER_GET_SENSOR_PLUGINS,
  SIM_COMMAND_SCOPE_SERVER_SET_DATA_ROLE,
  SIM_COMMAND_SCOPE_SENSOR_PLUGIN,							
  SIM_COMMAND_SCOPE_SENSOR_PLUGIN_START,
  SIM_COMMAND_SCOPE_SENSOR_PLUGIN_STOP,
  SIM_COMMAND_SCOPE_SENSOR_PLUGIN_ENABLE,
  SIM_COMMAND_SCOPE_SENSOR_PLUGIN_DISABLE,
  SIM_COMMAND_SCOPE_SENSOR_GET_EVENTS,
  SIM_COMMAND_SCOPE_PLUGIN_STATE_STARTED,
  SIM_COMMAND_SCOPE_PLUGIN_STATE_UNKNOWN,
  SIM_COMMAND_SCOPE_PLUGIN_STATE_STOPPED,
  SIM_COMMAND_SCOPE_PLUGIN_ENABLED,
  SIM_COMMAND_SCOPE_PLUGIN_DISABLED,
  SIM_COMMAND_SCOPE_EVENT,
  SIM_COMMAND_SCOPE_RELOAD_PLUGINS,
  SIM_COMMAND_SCOPE_RELOAD_SENSORS,
  SIM_COMMAND_SCOPE_RELOAD_HOSTS,
  SIM_COMMAND_SCOPE_RELOAD_NETS,
  SIM_COMMAND_SCOPE_RELOAD_POLICIES,
  SIM_COMMAND_SCOPE_RELOAD_DIRECTIVES,
  SIM_COMMAND_SCOPE_RELOAD_SERVERS,
  SIM_COMMAND_SCOPE_RELOAD_ALL,
  SIM_COMMAND_SCOPE_RELOAD_POST_CORRELATION_SIDS,
  SIM_COMMAND_SCOPE_HOST_OS_EVENT,
  SIM_COMMAND_SCOPE_HOST_MAC_EVENT,
  SIM_COMMAND_SCOPE_HOST_SERVICE_EVENT,
  SIM_COMMAND_SCOPE_OK,
  SIM_COMMAND_SCOPE_ERROR,
  SIM_COMMAND_SCOPE_DATABASE_QUERY,
  SIM_COMMAND_SCOPE_DATABASE_ANSWER,
  SIM_COMMAND_SCOPE_SNORT_EVENT,
  SIM_COMMAND_SCOPE_SNORT_EVENT_DATA,
  SIM_COMMAND_SCOPE_SNORT_EVENT_PACKET_RAW,
  SIM_COMMAND_SCOPE_SNORT_EVENT_IP,
  SIM_COMMAND_SCOPE_SNORT_EVENT_UDP,
  SIM_COMMAND_SCOPE_SNORT_EVENT_TCP,
  SIM_COMMAND_SCOPE_SNORT_EVENT_ICMP,
  SIM_COMMAND_SCOPE_AGENT_DATE,
	SIM_COMMAND_SCOPE_BACKLOG,
  SIM_COMMAND_SCOPE_IDM_EVENT,
  SIM_COMMAND_SCOPE_IDM_RELOAD_CONTEXT
} SimCommandScopeType;

typedef enum {
  SIM_COMMAND_SYMBOL_INVALID = G_TOKEN_LAST,
  SIM_COMMAND_SYMBOL_CONNECT,
  SIM_COMMAND_SYMBOL_SESSION_APPEND_PLUGIN,
  SIM_COMMAND_SYMBOL_SESSION_REMOVE_PLUGIN,
  SIM_COMMAND_SYMBOL_SERVER_GET_SENSORS,
  SIM_COMMAND_SYMBOL_SERVER_GET_SERVERS,
  SIM_COMMAND_SYMBOL_SERVER_GET_SENSOR_PLUGINS,
  SIM_COMMAND_SYMBOL_SERVER_SET_DATA_ROLE,
  SIM_COMMAND_SYMBOL_SENSOR_PLUGIN,
  SIM_COMMAND_SYMBOL_SENSOR_PLUGIN_START,
  SIM_COMMAND_SYMBOL_SENSOR_PLUGIN_STOP,
  SIM_COMMAND_SYMBOL_SENSOR_PLUGIN_ENABLE,
  SIM_COMMAND_SYMBOL_SENSOR_PLUGIN_DISABLE,
  SIM_COMMAND_SYMBOL_SENSOR_GET_EVENTS,
  SIM_COMMAND_SYMBOL_PLUGIN_STATE_STARTED,
  SIM_COMMAND_SYMBOL_PLUGIN_STATE_UNKNOWN,
  SIM_COMMAND_SYMBOL_PLUGIN_STATE_STOPPED,
  SIM_COMMAND_SYMBOL_PLUGIN_ENABLED,
  SIM_COMMAND_SYMBOL_PLUGIN_DISABLED,
  SIM_COMMAND_SYMBOL_EVENT,
  SIM_COMMAND_SYMBOL_RELOAD_PLUGINS,
  SIM_COMMAND_SYMBOL_RELOAD_SENSORS,
  SIM_COMMAND_SYMBOL_RELOAD_HOSTS,
  SIM_COMMAND_SYMBOL_RELOAD_NETS,
  SIM_COMMAND_SYMBOL_RELOAD_POLICIES,
  SIM_COMMAND_SYMBOL_RELOAD_DIRECTIVES,
  SIM_COMMAND_SYMBOL_RELOAD_SERVERS,
  SIM_COMMAND_SYMBOL_RELOAD_ALL,
  SIM_COMMAND_SYMBOL_RELOAD_POST_CORRELATION_SIDS,
  SIM_COMMAND_SYMBOL_POST_CORRELATION_SIDS,
  SIM_COMMAND_SYMBOL_OK,
  SIM_COMMAND_SYMBOL_PONG,
  SIM_COMMAND_SYMBOL_HOST_OS_EVENT,
  SIM_COMMAND_SYMBOL_HOST_MAC_EVENT,
  SIM_COMMAND_SYMBOL_HOST_SERVICE_EVENT,
  SIM_COMMAND_SYMBOL_AGENT_DATE,  //this is for the message
  SIM_COMMAND_SYMBOL_AGENT__DATE, //this is for the variable
  SIM_COMMAND_SYMBOL_AGENT_TZONE, 
  SIM_COMMAND_SYMBOL_ERROR,
  SIM_COMMAND_SYMBOL_ID,
  SIM_COMMAND_SYMBOL_CTX,
  SIM_COMMAND_SYMBOL_SENSOR,
  SIM_COMMAND_SYMBOL_DEVICE,
  SIM_COMMAND_SYMBOL_DEVICE_ID,
  SIM_COMMAND_SYMBOL_SERVER, //used for multiple things, like to know the server where a aspecific event has been generated
  SIM_COMMAND_SYMBOL_STATE,
  SIM_COMMAND_SYMBOL_ENABLED,
  SIM_COMMAND_SYMBOL_INTERFACE,
  SIM_COMMAND_SYMBOL_TYPE,
  SIM_COMMAND_SYMBOL_AGENT_VERSION,
  SIM_COMMAND_SYMBOL_NAME,
  SIM_COMMAND_SYMBOL_DATE,
  SIM_COMMAND_SYMBOL_DATE_STRING,
  SIM_COMMAND_SYMBOL_DATE_TZONE,
  SIM_COMMAND_SYMBOL_PLUGIN_TYPE,
  SIM_COMMAND_SYMBOL_PLUGIN_ID,
  SIM_COMMAND_SYMBOL_PLUGIN_SID,
  SIM_COMMAND_SYMBOL_PRIORITY,
  SIM_COMMAND_SYMBOL_PROTOCOL,
  SIM_COMMAND_SYMBOL_IP,
  SIM_COMMAND_SYMBOL_SRC_IP,
  SIM_COMMAND_SYMBOL_SRC_PORT,
  SIM_COMMAND_SYMBOL_DST_IP,
  SIM_COMMAND_SYMBOL_DST_PORT,
  SIM_COMMAND_SYMBOL_SRC_NET,
  SIM_COMMAND_SYMBOL_DST_NET,
  SIM_COMMAND_SYMBOL_CONDITION,
  SIM_COMMAND_SYMBOL_VALUE,
  SIM_COMMAND_SYMBOL_INTERVAL,
  SIM_COMMAND_SYMBOL_HOST,
  SIM_COMMAND_SYMBOL_HOSTNAME,
  SIM_COMMAND_SYMBOL_DOMAIN,
  SIM_COMMAND_SYMBOL_LOGIN,
  SIM_COMMAND_SYMBOL_SERVERNAME,
  SIM_COMMAND_SYMBOL_SENSORNAME, //used only to get Policy from sensors
  SIM_COMMAND_SYMBOL_OS,
  SIM_COMMAND_SYMBOL_CPU,
  SIM_COMMAND_SYMBOL_MEMORY,
  SIM_COMMAND_SYMBOL_VIDEO,
  SIM_COMMAND_SYMBOL_MAC,
  SIM_COMMAND_SYMBOL_SERVICE,
  SIM_COMMAND_SYMBOL_SOFTWARE,
  SIM_COMMAND_SYMBOL_VENDOR,
  SIM_COMMAND_SYMBOL_PORT,
  SIM_COMMAND_SYMBOL_APPLICATION,
  SIM_COMMAND_SYMBOL_DATA,
  SIM_COMMAND_SYMBOL_EVENT_TYPE,
  SIM_COMMAND_SYMBOL_HIDS_EVENT_TYPE, //FIXME: Used only for backwards compatibility. Remove when using the agent-1.0
  SIM_COMMAND_SYMBOL_TARGET,
  SIM_COMMAND_SYMBOL_WHAT,
  SIM_COMMAND_SYMBOL_EXTRA_DATA,
  SIM_COMMAND_SYMBOL_LOG,
  SIM_COMMAND_SYMBOL_SNORT_SID,
  SIM_COMMAND_SYMBOL_SNORT_CID,
  SIM_COMMAND_SYMBOL_ASSET_SRC,
  SIM_COMMAND_SYMBOL_ASSET_DST,
  SIM_COMMAND_SYMBOL_RISK_A,
  SIM_COMMAND_SYMBOL_RISK_C,
  SIM_COMMAND_SYMBOL_ALARM,
  SIM_COMMAND_SYMBOL_BELONGS_TO_ALARM,
  SIM_COMMAND_SYMBOL_IS_REMOTE,
  SIM_COMMAND_SYMBOL_UUID,
  SIM_COMMAND_SYMBOL_UUID_BACKLOG,
  SIM_COMMAND_SYMBOL_BACKLOG_ID,
  SIM_COMMAND_SYMBOL_LEVEL,
  SIM_COMMAND_SYMBOL_RELIABILITY,
  SIM_COMMAND_SYMBOL_FILENAME,	//this and the following words, are used in events, and in HIDS events (not MAC, OS, or service events)
  SIM_COMMAND_SYMBOL_USERNAME,
  SIM_COMMAND_SYMBOL_PASSWORD,
  SIM_COMMAND_SYMBOL_SENSOR_ID,
  SIM_COMMAND_SYMBOL_USERDATA1,
  SIM_COMMAND_SYMBOL_USERDATA2,
  SIM_COMMAND_SYMBOL_USERDATA3,
  SIM_COMMAND_SYMBOL_USERDATA4,
  SIM_COMMAND_SYMBOL_USERDATA5,
  SIM_COMMAND_SYMBOL_USERDATA6,
  SIM_COMMAND_SYMBOL_USERDATA7,
  SIM_COMMAND_SYMBOL_USERDATA8,
  SIM_COMMAND_SYMBOL_USERDATA9,
  SIM_COMMAND_SYMBOL_SRC_ID,
  SIM_COMMAND_SYMBOL_DST_ID,
  SIM_COMMAND_SYMBOL_SRC_USERNAME,
  SIM_COMMAND_SYMBOL_DST_USERNAME,
  SIM_COMMAND_SYMBOL_SRC_HOSTNAME,
  SIM_COMMAND_SYMBOL_DST_HOSTNAME,
  SIM_COMMAND_SYMBOL_SRC_MAC,
  SIM_COMMAND_SYMBOL_DST_MAC,
  SIM_COMMAND_SYMBOL_REP_IP_SRC,
  SIM_COMMAND_SYMBOL_REP_IP_DST,
  SIM_COMMAND_SYMBOL_REP_PRIO_SRC,
  SIM_COMMAND_SYMBOL_REP_PRIO_DST,
  SIM_COMMAND_SYMBOL_REP_REL_SRC,
  SIM_COMMAND_SYMBOL_REP_REL_DST,
  SIM_COMMAND_SYMBOL_REP_ACT_SRC,
  SIM_COMMAND_SYMBOL_REP_ACT_DST,
  SIM_COMMAND_SYMBOL_ROLE_CORRELATE, //different kinds of servers, each one with its own role.
  SIM_COMMAND_SYMBOL_ROLE_CROSS_CORRELATE,
  SIM_COMMAND_SYMBOL_ROLE_REPUTATION,
	SIM_COMMAND_SYMBOL_ROLE_LOGGER_IF_PRIORITY,
  SIM_COMMAND_SYMBOL_ROLE_STORE,
  SIM_COMMAND_SYMBOL_ROLE_QUALIFY,
  SIM_COMMAND_SYMBOL_DATABASE_QUERY,
  SIM_COMMAND_SYMBOL_DATABASE_ANSWER,
  SIM_COMMAND_SYMBOL_ANSWER,
//  SIM_COMMAND_SYMBOL_QUERY,
	SIM_COMMAND_SYMBOL_DATABASE_ELEMENT_TYPE, //What kind of element is the answer/query talking about? host, network, directives...
  SIM_COMMAND_SYMBOL_IS_PRIORITIZED,
	SIM_COMMAND_SYMBOL_SNORT_EVENT,
	// Commpress command data.
	SIM_COMMAND_SYMBOL_GZIPDATA,
	SIM_COMMAND_SYMBOL_UNZIPLEN,
  SIM_COMMAND_SYMBOL_IPV6,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TYPE,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_SENSOR,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IF,
	// Snort data info
	SIM_COMMAND_SYMBOL_SNORT_EVENT_DATA_TYPE,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_DATE,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_DATE_STRING,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_GID,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_SID,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_REV,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_CLASSIFICATION,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_PRIORITY,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_PACKET_TYPE,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_PACKET_RAW,
  SIM_COMMAND_SYMBOL_SNORT_SENSOR_ID,            // IPV6
  SIM_COMMAND_SYMBOL_SNORT_EVENT_ID,             // IPV6
  SIM_COMMAND_SYMBOL_SNORT_EVENT_SECOND,         // IPV6
  SIM_COMMAND_SYMBOL_SNORT_EVENT_MICROSECOND,    // IPV6
  SIM_COMMAND_SYMBOL_SNORT_SIGNATURE_ID,         // IPV6
  SIM_COMMAND_SYMBOL_SNORT_GENERATOR_ID,         // IPV6
  SIM_COMMAND_SYMBOL_SNORT_SIGNATURE_REVISION,   // IPV6
  SIM_COMMAND_SYMBOL_SNORT_CLASSIFICATION_ID,    // IPV6
  SIM_COMMAND_SYMBOL_SNORT_PRIORITY_ID,          // IPV6
  SIM_COMMAND_SYMBOL_SNORT_SOURCE_IP,            // IPV6
  SIM_COMMAND_SYMBOL_SNORT_DESTINATION_IP,       // IPV6
  SIM_COMMAND_SYMBOL_SNORT_SOURCE_PORT_ITYPE,    // IPV6
  SIM_COMMAND_SYMBOL_SNORT_DEST_PORT_ITYPE,      // IPV6
  SIM_COMMAND_SYMBOL_SNORT_PROTOCOL,             // IPV6
  SIM_COMMAND_SYMBOL_SNORT_IMPACT_FLAG,          // IPV6
  SIM_COMMAND_SYMBOL_SNORT_IMPACT,               // IPV6
  SIM_COMMAND_SYMBOL_SNORT_BLOCKED,              // IPV6
	// Packet INFO
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_VER,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_TOS,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_ID,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_OFFSET,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_HDRLEN,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_LEN,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_FLAGS,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_TTL,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_PROTO,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_CSUM,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_SRC,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_DST,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_PAYLOAD,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_OPTNUM,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_OPTCODE,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_OPTLEN,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_OPTPAYLOAD,
  SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_TRAFFIC,     // IPV6
  SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_FLOWLABEL,   // IPV6
  SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_PAYLOAD_LEN, // IPV6
  SIM_COMMAND_SYMBOL_SNORT_EVENT_IP_HOPLIMIT,    // IPV6
	// The next one, for UDP Packets
	SIM_COMMAND_SYMBOL_SNORT_EVENT_UDP_SPORT,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_UDP_DPORT,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_UDP_LEN,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_UDP_CSUM,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_UDP_PAYLOAD,
	// The next one, for ICMP
	SIM_COMMAND_SYMBOL_SNORT_EVENT_ICMP_TYPE,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_ICMP_CODE,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_ICMP_CSUM,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_ICMP_ID,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_ICMP_SEQ,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_ICMP_PAYLOAD,
	// The next one, for TCP
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_SPORT,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_DPORT,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_SEQ,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_ACK,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_OFFSET,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_FLAGS,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_WINDOW,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_CSUM,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_URGPTR,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_OPTNUM,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_OPTCODE,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_OPTLEN,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_OPTPAYLOAD,
	SIM_COMMAND_SYMBOL_SNORT_EVENT_TCP_PAYLOAD,
	SIM_COMMAND_SYMBOL_BACKLOG,
	SIM_COMMAND_SYMBOL_BACKLOG_DIRECTIVE_ID,
	SIM_COMMAND_SYMBOL_BACKLOG_CTX,
	SIM_COMMAND_SYMBOL_BACKLOG_UUID,
	SIM_COMMAND_SYMBOL_BACKLOG_UUID_EVENT,
	SIM_COMMAND_SYMBOL_BACKLOG_LEVEL,
	SIM_COMMAND_SYMBOL_BACKLOG_MATCHED,
	SIM_COMMAND_SYMBOL_BACKLOG_OCCURRENCE,
	SIM_COMMAND_SYMBOL_BACKLOG_EVENT_TYPE,
	SIM_COMMAND_SYMBOL_FRMK_GETDB,//for server_get_db
	SIM_COMMAND_SYMBOL_SENSOR_GET_FRAMEWORK,
  SIM_COMMAND_SYMBOL_SENSOR_PING,
  SIM_COMMAND_SYMBOL_IDM_EVENT,
  SIM_COMMAND_SYMBOL_IDM_RELOAD_CONTEXT,
  SIM_COMMAND_SYMBOL_EVENT_ID,
  SIM_COMMAND_SYMBOL_BINARY_DATA,
  SIM_COMMAND_SYMBOL_BINARY_DATA_LEN,
  SIM_COMMAND_SYMBOL_INVENTORY_SOURCE
} SimCommandSymbolType;


#endif 


