#!/bin/bash
### BEGIN INIT INFO
# Provides:          alienvault-center
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: alienvault-center
# Description:
#
### END INIT INFO

