#!/bin/bash
#
# /etc/init.d/openvas-scanner
#
### BEGIN INIT INFO
# Provides:          openvas-scanner
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the OpenVAS daemon
# Description:       Controls the main OpenVAS daemon "openvassd".
### END INIT INFO
