#!/bin/bash
### BEGIN INIT INFO
# Provides:          ossec
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ossec
# Description:
#
### END INIT INFO

