#!/bin/bash
### BEGIN INIT INFO
# Provides:          ossim-firewall 
# Required-Start:    $time $network $local_fs $syslog
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OSSIM Firewall
# Description:       OSSIM automanaged Firewall ruleset init script
### END INIT INFO

