#! /bin/bash
### BEGIN INIT INFO
# Provides:          ossim-framework
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop alienvault framework daemon
### END INIT INFO

