#!/bin/bash
### BEGIN INIT INFO
# Provides:          ossim-ha
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     
# Should-Start:      $syslog
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OSSIM High Availability script
# Description:       OSSIM Heartbeat Resource.
#                    Intended for start/stop services
#                    and related tasks
#                    in active/passive node
### END INIT INFO

