Document: alienvault-dummy-database
Title: Debian alienvault-dummy-database Manual
Author: <insert document author here>
Abstract: This manual describes what alienvault-dummy-database is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alienvault-dummy-database/alienvault-dummy-database.sgml.gz

Format: postscript
Files: /usr/share/doc/alienvault-dummy-database/alienvault-dummy-database.ps.gz

Format: text
Files: /usr/share/doc/alienvault-dummy-database/alienvault-dummy-database.text.gz

Format: HTML
Index: /usr/share/doc/alienvault-dummy-database/html/index.html
Files: /usr/share/doc/alienvault-dummy-database/html/*.html
