Document: ossim-mysql
Title: Debian ossim-mysql Manual
Author: <insert document author here>
Abstract: This manual describes what ossim-mysql is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ossim-mysql/ossim-mysql.sgml.gz

Format: postscript
Files: /usr/share/doc/ossim-mysql/ossim-mysql.ps.gz

Format: text
Files: /usr/share/doc/ossim-mysql/ossim-mysql.text.gz

Format: HTML
Index: /usr/share/doc/ossim-mysql/html/index.html
Files: /usr/share/doc/ossim-mysql/html/*.html
