Document: alienvault-dummy-sensor
Title: Debian alienvault-dummy-sensor Manual
Author: <insert document author here>
Abstract: This manual describes what alienvault-dummy-sensor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alienvault-dummy-sensor/alienvault-dummy-sensor.sgml.gz

Format: postscript
Files: /usr/share/doc/alienvault-dummy-sensor/alienvault-dummy-sensor.ps.gz

Format: text
Files: /usr/share/doc/alienvault-dummy-sensor/alienvault-dummy-sensor.text.gz

Format: HTML
Index: /usr/share/doc/alienvault-dummy-sensor/html/index.html
Files: /usr/share/doc/alienvault-dummy-sensor/html/*.html
