Document: alienvault-framework-documentation
Title: Debian alienvault-framework-documentation Manual
Author: <insert document author here>
Abstract: This manual describes what alienvault-framework-documentation is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alienvault-framework-documentation/alienvault-framework-documentation.sgml.gz

Format: postscript
Files: /usr/share/doc/alienvault-framework-documentation/alienvault-framework-documentation.ps.gz

Format: text
Files: /usr/share/doc/alienvault-framework-documentation/alienvault-framework-documentation.text.gz

Format: HTML
Index: /usr/share/doc/alienvault-framework-documentation/html/index.html
Files: /usr/share/doc/alienvault-framework-documentation/html/*.html
