#!/bin/bash

array=(alienvault-attacks alienvault-misc alienvault-scada alienvault-network alienvault-dos alienvault-scan alienvault-policy alienvault-malware alienvault-bruteforce)
filename=/etc/ossim/server/directives.xml
SUCCESS=0

if [ -d /usr/share/alienvault-directives-free/d_clean/ ]; then
        echo -n "Updating directives ... "
        cp -f /usr/share/alienvault-directives-free/d_clean/*.xml /etc/ossim/server/
        echo "Done"
fi

for item in ${array[*]}
do  
  printf "   %s\n" $item
  grep -q "$item" "$filename"
  if [ $? -eq $SUCCESS ]
  then
    echo "Reference Found"
  else
    sed -i "s/]>/  <!ENTITY $item SYSTEM \'\/etc\/ossim\/server\/$item.xml\'>\n]>/g" "$filename"
    sed -i "s/<directives>/<directives>\n  \&$item;\n/g" "$filename"
  fi
  SUCCESS=0
done

# "user.xml" cannot be included in the debian package because
# it will overwrite user configuration on update.
test -f /etc/ossim/server/user.xml || echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > /etc/ossim/server/user.xml

echo "show databases" | ossim-db mysql | grep datawarehouse &> /dev/null
if [ $? -eq 0 ]; then
    if [ -f /usr/share/doc/alienvault-directives-pro/contrib/datawarehouse_category.sql.gz ]; then
        zcat /usr/share/doc/alienvault-directives-pro/contrib/datawarehouse_category.sql.gz | ossim-db datawarehouse 2> /dev/null
    fi
fi

echo "show databases" | ossim-db mysql | grep PCI | grep -v PCI3 &> /dev/null
if [ $? -eq 0 ]; then
    if [ -f /usr/share/doc/alienvault-directives-pro/contrib/PCI.sql.gz ]; then
        zcat /usr/share/doc/alienvault-directives-pro/contrib/PCI.sql.gz | ossim-db PCI 2> /dev/null
    fi
fi

echo "show databases" | ossim-db mysql | grep ISO27001An &> /dev/null
if [ $? -eq 0 ]; then
    if [ -f /usr/share/doc/alienvault-directives-pro/contrib/ISO27001An.sql.gz ]; then
        zcat /usr/share/doc/alienvault-directives-pro/contrib/ISO27001An.sql.gz | ossim-db ISO27001An 2> /dev/null
    fi
fi

echo "show databases" | ossim-db mysql | grep alienvault | grep -v "_" &> /dev/null
if [ $? -eq 0 ]; then pref1x="alienvault"; else pref1x="ossim"; fi

echo "show tables" | ossim-db $pref1x | grep repository &> /dev/null
if [ $? -eq 0 ]; then
    if [ -f /usr/share/doc/alienvault-directives-pro/contrib/$pref1x-kb.sql.gz ]; then
        zcat /usr/share/doc/alienvault-directives-pro/contrib/$pref1x-kb.sql.gz | ossim-db $pref1x 2> /dev/null
    fi
fi


exit 0


