#!/usr/bin/env bash
 
# Generate a UUID
uuid()
{
    local N B C='89ab'

    for (( N=0; N < 16; ++N ))
    do
        B=$(( $RANDOM%256 ))

        case $N in
            6)
                printf '4%x' $(( B%16 ))
                ;;
            8)
                printf '%c%x' ${C:$RANDOM%${#C}:1} $(( B%16 ))
                ;;
            3 | 5 | 7 | 9)
                printf '%02x-' $B
                ;;
            *)
                printf '%02x' $B
                ;;
        esac
    done

    echo
}

FILE='/etc/alienvault/system-id'
CENTERFILE='/etc/alienvault-center/alienvault-center-uuid'

if [ ! -f $FILE ];
then
    if [ -f $CENTERFILE ] && egrep --quiet "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$" $CENTERFILE;
    then
        # CASE 1: Copy System UUID from AV center file
        cp $CENTERFILE $FILE
    else
        dmi_uuid=$(/usr/sbin/dmidecode -s system-uuid | perl -ne 'print lc')
        if [[ $dmi_uuid =~ ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$ ]];
        then
            # CASE 2: Get System UUID from dmidecode
            echo $dmi_uuid > $FILE
        else
            # CASE 3: Create a new System UUID
            new_uuid=$(uuid)
            echo $new_uuid > $FILE
        fi
    fi
    chgrp alienvault $FILE
    chmod g+w $FILE
fi

output=$(cat $FILE)
printf $output
