#!/usr/bin/php
<?php
/**
*
* License:
*
* Copyright (c) 2003-2006 ossim.net
* Copyright (c) 2007-2013 AlienVault
* All rights reserved.
*
* This package is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2 dated June, 1991.
* You may not use, modify or distribute this program under any other version
* of the GNU General Public License.
*
* This package is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this package; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
* MA  02110-1301  USA
*
*
* On Debian GNU/Linux systems, the complete text of the GNU General
* Public License can be found in `/usr/share/common-licenses/GPL-2'.
*
* Otherwise you can read it here: http://www.gnu.org/licenses/gpl-2.0.txt
*
*/

$auth = FALSE;

if ( preg_match("/\/tmp\/headers\//",$_SERVER["URI"]) && !preg_match("/\.\./",$_SERVER["URI"]) )
{
    exit(0);
}

//if (preg_match("/ntop_\d+\.\d+\.\d+\.\d+/",$_SERVER["URI"])) exit(0);

set_time_limit(0);
ob_implicit_flush();
ini_set('include_path', '/usr/share/ossim/include');

require_once 'av_init.php';

$db            = new ossim_db();
$dbconn        = $db->connect();

$allowed_users = Session_activity::get_list($dbconn, " ORDER BY activity desc");

preg_match("/PHPSESSID=([a-zA-Z0-9\,\-]+)/", getenv("COOKIE"), $matches);

$nagios = preg_match("/nagios3/",$_SERVER["URI"]) ? TRUE : FALSE;

foreach ($allowed_users as $au) 
{
    if ( trim($au->get_id()) == trim($matches[1]) )
    {
        $auth = TRUE;

        if ($nagios && !Template::menu_perms($dbconn, $au->get_login(), 'environment-menu', 'MonitorsAvailability'))
        {
            $auth = FALSE;
        }
    }
}

$db->close($dbconn);

if ($auth)
{
    exit(0);
}
else
{
    exit(1);
}
?>