-- BIND (DNS)
-- plugin_id: 1577

delete from plugin where id=1577;
delete from plugin_sid where plugin_id=1577;

INSERT IGNORE INTO plugin (id, type, name, description) values (1577, 1, 'bind', 'BIND');	
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1, NULL, NULL, 1, 3, 'DNS (Bind) - Succesful Zone Transfer (AFXR)');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 2, NULL, NULL, 1, 3, 'DNS (Bind) - Bad Referal');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 3, NULL, NULL, 1, 3, 'DNS (Bind) - Bad Response to SOA Query');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 4, NULL, NULL, 1, 3, 'DNS (Bind) - Interface Deleted due to listenig error');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 5, NULL, NULL, 1, 3, 'DNS (Bind) - Denied AXFR - equivalent to unapprouved');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 6, NULL, NULL, 1, 3, 'DNS (Bind) - Denied Update Command - equivalent to unapprouved');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 7, NULL, NULL, 1, 3, 'DNS (Bind) - Drop source port zero packet');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 8, NULL, NULL, 1, 3, 'DNS (Bind) - Update error due to existing record');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 9, NULL, NULL, 1, 3, 'DNS (Bind) - TCP based query or zone transfer');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 10, NULL, NULL, 1, 3, 'DNS (Bind) - Lame server: remote name server not authoritative for domain');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 11, NULL, NULL, 1, 3, 'DNS (Bind) - Malformed Response');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 12, NULL, NULL, 1, 3, 'DNS (Bind) - Query for unknown class');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 13, NULL, NULL, 1, 3, 'DNS (Bind) - NOTIFY(SOA): propably domain name is not the good one for the specified zone');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 14, NULL, NULL, 1, 3, 'DNS (Bind) - NOTIFY(SOA): local name server not slave for specified zone: unexpected message');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 15, NULL, NULL, 1, 3, 'DNS (Bind) - NOTIFY(SOA): remote IP is not master server for the specified zone: unexpected message');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 16, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: Network Unreachable');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 17, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: Operation not permitted');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 18, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: Resource temporarily unavailable');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 19, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: Connection refused');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 20, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: No buffer space available');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 21, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: All possible Records are Lame');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 22, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: Remote server already cached as unexisting');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 23, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: Bogus Loopback');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 24, NULL, NULL, 1, 3, 'DNS (Bind) - NS Operation: no possible A record');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 25, NULL, NULL, 1, 3, 'DNS (Bind) - Remote Name server known by multiple domains');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 26, NULL, NULL, 1, 3, 'DNS (Bind) - TCP packet truncated');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 27, NULL, NULL, 1, 3, 'DNS (Bind) - Remote Name server restricting zone transfer');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 28, NULL, NULL, 1, 3, 'DNS (Bind) - Query received on non-query socket');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 29, NULL, NULL, 1, 3, 'DNS (Bind) - Response received from a Name Server not queried');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 30, NULL, NULL, 1, 3, 'DNS (Bind) - Response from remote server out of time (more than 10 min');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 31, NULL, NULL, 1, 3, 'DNS (Bind) - Zone transfer denied due to local ACL');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 32, NULL, NULL, 1, 3, 'DNS (Bind) - Zone transfer denied because local server is not authoritative for the specified zone');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 33, NULL, NULL, 1, 3, 'DNS (Bind) - Zone transfer denied because remote domain is not top of the zone');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 34, NULL, NULL, 1, 3, 'DNS (Bind) - Zone transfer denied because of a syntax error or an illegal domain name');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 35, NULL, NULL, 1, 3, 'DNS (Bind) - Unapproved Recursive Query');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 36, NULL, NULL, 1, 3, 'DNS (Bind) - Unapproved Update Query');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 37, NULL, NULL, 1, 3, 'DNS (Bind) - Unrelated additional info for domain in response');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 38, NULL, NULL, 1, 3, 'DNS (Bind) - Zone Transfer Successful');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 39, NULL, NULL, 1, 3, 'DNS (Bind) - Zone Transfer Timeout');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 40, NULL, NULL, 1, 3, 'DNS (Bind) - Zone Transfer - Master server unreachable');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 41, NULL, NULL, 1, 3, 'DNS (Bind) - Secondary zone expired - unable to refresh zone data');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 42, 13, NULL, 'DNS (Bind) - Zone transfer Started');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 43, 13, NULL, 'DNS (Bind) - Zone transfer Ended');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 44, 13, NULL, 'DNS (Bind) - Zone transfer REFUSED');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 45, 13, NULL, 'DNS (Bind) - Sending notifies');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 46, 13, NULL, 'DNS (Bind) - Updating Zone - Adding an RR');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 47, 13, NULL, 'DNS (Bind) - Updating Zone - Deleting an RR');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 48, 13, NULL, 'DNS (Bind) - Updating Zone - Deleting rrset');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 49, 13, NULL, 'DNS (Bind) - Error Updating Zone - name not in use');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES (1577, 50, 13, NULL, 'DNS (Bind) - Error Updating Zone - RRset exists');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 51, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN A');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 52, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN A6');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 53, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN AAAA');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 54, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN ANY');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 55, NULL, NULL, 1, 2, 'DNS (Bind) - Query Type: IN AXFR');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 56, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN CNAME');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 57, NULL, NULL, 1, 3, 'DNS (Bind) - Query Type: IN DNSKEY');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 58, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN DS');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 59, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN HINFO');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 61, NULL, NULL, 1, 2, 'DNS (Bind) - Query Type: IN IXFR');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 62, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN MAILB');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 63, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN MX');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 64, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN NAPTR');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 65, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN NS');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 66, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN PTR');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 67, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN RRSIG');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 68, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN SOA');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 69, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN SRV');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 70, NULL, NULL, 1, 1, 'DNS (Bind) - Query Type: IN TXT');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 71, NULL, NULL, 2, 2, 'DNS (Bind) - Query Type: CH TXT');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 72, NULL, NULL, 1, 1, 'DNS (Bind) - Security');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 73, NULL, NULL, 1, 1, 'DNS (Bind) - Network');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 74, NULL, NULL, 1, 1, 'DNS (Bind) - xfer-out Started');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 75, NULL, NULL, 1, 1, 'DNS (Bind) - xfer-out ended');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 76, NULL, NULL, 1, 1, 'DNS (Bind) - Notify - sending notifies');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 77, NULL, NULL, 1, 1, 'DNS (Bind) - Notify - notify question');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 79, NULL, NULL, 1, 1, 'DNS (Bind) - Notify - received notify');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 80, NULL, NULL, 2, 3, 'DNS (Bind) - xfer-out: Bad zone transfer');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 81, NULL, NULL, 2, 2, 'DNS (Bind) - Query Type: IN SPF');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1000, NULL, NULL, 1, 3, 'DNS (Bind) - Too many timeouts');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1001, NULL, NULL, 1, 3, 'DNS (Bind) - Query cache denied');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1002, NULL, NULL, 1, 3, 'DNS (Bind) - FORMERR resolving');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1003, NULL, NULL, 1, 3, 'DNS (Bind) - RFC1918 response');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1004, NULL, NULL, 1, 3, 'DNS (Bind) - Checkhints');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1005, NULL, NULL, 1, 3, 'DNS (Bind) - Bind unexpected RCODE');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1006, NULL, NULL, 1, 3, 'DNS (Bind) - Lame Server resolving');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1007, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type queries');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1008, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type client');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1009, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type config');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1010, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type database');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1011, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type default');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1012, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type delegation-only');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1013, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type dispatch');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1014, NULL, NULL, 2, 2, 'DNS (Bind) - General: Type dnssec');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 78, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type general');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1016, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type lame-servers');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1017, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type network');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1018, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type notify');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1019, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type resolver');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1020, NULL, NULL, 2, 3, 'DNS (Bind) - General: Type security');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1021, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type unmatched');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1022, NULL, NULL, 2, 2, 'DNS (Bind) - General: Type update');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1023, NULL, NULL, 2, 3, 'DNS (Bind) - General: Type update-security');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1024, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type xfer-in');
INSERT IGNORE INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `reliability`, `priority`, `name`) VALUES (1577, 1025, NULL, NULL, 2, 1, 'DNS (Bind) - General: Type xfer-out');

