-- bit9
-- plugin_id: 1630

DELETE FROM plugin WHERE id = '1630';
DELETE FROM plugin_sid where plugin_id = '1630';

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1630, 1, 'bit9', 'Bit9, Advanced Threat Protection');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 1, NULL, NULL, 'bit9: Server Shutdown', 5, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 2, NULL, NULL, 'bit9: Server restart', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 3, NULL, NULL, 'bit9: Server config modified', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 4, NULL, NULL, 'bit9: Server backup started', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 5, NULL, NULL, 'bit9: Server backup failed', 5, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 6, NULL, NULL, 'bit9: Server backup stopped', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 7, NULL, NULL, 'bit9: Server backup missed', 5, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 8, NULL, NULL, 'bit9: Old events were deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 9, NULL, NULL, 'bit9: Database verification error', 5, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 10, NULL, NULL, 'bit9: File tracking disabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 11, NULL, NULL, 'bit9: Server upgrade succeeded', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 12, NULL, NULL, 'bit9: Server upgrade failed', 5, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 13, NULL, NULL, 'bit9: Server config list error', 5, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 14, NULL, NULL, 'bit9: AD lookups are slow', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 15, NULL, NULL, 'bit9: License Warning', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 16, NULL, NULL, 'bit9: Console user login', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 17, NULL, NULL, 'bit9: Console user logout', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 18, NULL, NULL, 'bit9: Console user created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 19, NULL, NULL, 'bit9: Console user modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 20, NULL, NULL, 'bit9: Console user deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 21, NULL, NULL, 'bit9: Alert created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 22, NULL, NULL, 'bit9: Alert deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 23, NULL, NULL, 'bit9: Alert modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 24, NULL, NULL, 'bit9: Alert triggered', 5, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 25, NULL, NULL, 'bit9: Alert reset', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 26, NULL, NULL, 'bit9: Metered execution', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 27, NULL, NULL, 'bit9: Meter created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 28, NULL, NULL, 'bit9: Meter modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 29, NULL, NULL, 'bit9: Meter deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 30, NULL, NULL, 'bit9: File ban created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 31, NULL, NULL, 'bit9: File ban modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 32, NULL, NULL, 'bit9: File ban deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 33, NULL, NULL, 'bit9: File approval (trusted directory)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 34, NULL, NULL, 'bit9: File approval (trusted user)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 35, NULL, NULL, 'bit9: File approval (trusted updated)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 36, NULL, NULL, 'bit9: File approval (trusted publisher)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 37, NULL, NULL, 'bit9: File approval failed', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 38, NULL, NULL, 'bit9: File approval (admin)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 39, NULL, NULL, 'bit9: File approval (local approval)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 40, NULL, NULL, 'bit9: File approval (block and ask)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 41, NULL, NULL, 'bit9: File approval (time)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 42, NULL, NULL, 'bit9: Trusted directory created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 43, NULL, NULL, 'bit9: Trusted directory modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 44, NULL, NULL, 'bit9: Trusted directory deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 45, NULL, NULL, 'bit9: Trusted user added', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 46, NULL, NULL, 'bit9: Trusted user deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 47, NULL, NULL, 'bit9: Trusted publisher enabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 48, NULL, NULL, 'bit9: Trusted publisher disabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 49, NULL, NULL, 'bit9: Trusted updater enabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 50, NULL, NULL, 'bit9: Trusted updater disabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 51, NULL, NULL, 'bit9: Group local approval (admin)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 52, NULL, NULL, 'bit9: Group local approval revoked (admin)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 53, NULL, NULL, 'bit9: Trusted package imported', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 54, NULL, NULL, 'bit9: Agent shutdown', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 55, NULL, NULL, 'bit9: Agent restart', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 56, NULL, NULL, 'bit9: Agent settings changed', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 57, NULL, NULL, 'bit9: Agent SecCon changed', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 58, NULL, NULL, 'bit9: Agent policy changed', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 59, NULL, NULL, 'bit9: CLI password reset', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 60, NULL, NULL, 'bit9: Computer added', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 61, NULL, NULL, 'bit9: Computer deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 62, NULL, NULL, 'bit9: Computer modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 63, NULL, NULL, 'bit9: Policy created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 64, NULL, NULL, 'bit9: Policy deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 65, NULL, NULL, 'bit9: Policy modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 66, NULL, NULL, 'bit9: Install package created', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 67, NULL, NULL, 'bit9: AD mapping changed', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 68, NULL, NULL, 'bit9: AD rules loaded', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 69, NULL, NULL, 'bit9: Policy file tracking disabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 70, NULL, NULL, 'bit9: Policy file tracking enabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 71, NULL, NULL, 'bit9: Agent bulk state change requested', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 72, NULL, NULL, 'bit9: Agent bulk state change finished', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 73, NULL, NULL, 'bit9: Agent deleted events', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 74, NULL, NULL, 'bit9: Agent requires upgrade', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 75, NULL, NULL, 'bit9: Cache check complete', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 76, NULL, NULL, 'bit9: Agent synchronization requested', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 77, NULL, NULL, 'bit9: Agent synchronization started', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 78, NULL, NULL, 'bit9: Agent synchronization finished', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 79, NULL, NULL, 'bit9: New publisher found', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 80, NULL, NULL, 'bit9: New pending file to computer', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 81, NULL, NULL, 'bit9: Installation group created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 82, NULL, NULL, 'bit9: Banned file written to computer', 5, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 83, NULL, NULL, 'bit9: New file on network', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 84, NULL, NULL, 'bit9: Process Demoted', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 85, NULL, NULL, 'bit9: First execution on network', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 86, NULL, NULL, 'bit9: Execution block (pending file)', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 87, NULL, NULL, 'bit9: Execution block (banned file)', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 88, NULL, NULL, 'bit9: Execution block (network file)', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 89, NULL, NULL, 'bit9: Test execution block', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 90, NULL, NULL, 'bit9: Execution block (still analyzing)', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 91, NULL, NULL, 'bit9: Execution block (exclusion policy)', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 92, NULL, NULL, 'bit9: Write block (exclusion policy)', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 93, NULL, NULL, 'bit9: Report execution (exclusion policy)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 94, NULL, NULL, 'bit9: Report write (exclusion policy)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 95, NULL, NULL, 'bit9: Exclusion policy created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 96, NULL, NULL, 'bit9: Exclusion policy modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 97, NULL, NULL, 'bit9: Exclusion policy deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 98, NULL, NULL, 'bit9: Report execution (removable media)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 99, NULL, NULL, 'bit9: Report read (removable media)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 100, NULL, NULL, 'bit9: Report write (removable media)', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 101, NULL, NULL, 'bit9: Execution block (removable media)', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 102, NULL, NULL, 'bit9: Write block (removable media)', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 103, NULL, NULL, 'bit9: Approved device enabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 104, NULL, NULL, 'bit9: Approved device disabled', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 105, NULL, NULL, 'bit9: Device attached', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 106, NULL, NULL, 'bit9: Device detached', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 107, NULL, NULL, 'bit9: New device found', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 108, NULL, NULL, 'bit9: Multiple failed logins', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 109, NULL, NULL, 'bit9: Unauthorized computer registration', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 110, NULL, NULL, 'bit9: CLI executed', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 111, NULL, NULL, 'bit9: Self protection block', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 112, NULL, NULL, 'bit9: Access error', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 113, NULL, NULL, 'bit9: Potential risk file detected', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 114, NULL, NULL, 'bit9: Malicious file detected', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 115, NULL, NULL, 'bit9: Connection lost', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 116, NULL, NULL, 'bit9: Connection restored', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 117, NULL, NULL, 'bit9: Using proxy', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 118, NULL, NULL, 'bit9: Not using proxy', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 119, NULL, NULL, 'bit9: Baseline drift report created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 120, NULL, NULL, 'bit9: Baseline drift report modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 121, NULL, NULL, 'bit9: Baseline drift report deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 122, NULL, NULL, 'bit9: Baseline drift report generated', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 123, NULL, NULL, 'bit9: Snapshot created', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 124, NULL, NULL, 'bit9: Snapshot modified', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 125, NULL, NULL, 'bit9: Snapshot deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 126, NULL, NULL, 'bit9: Baseline drift report generation is slow', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1630, 9999, NULL, NULL, 'bit9: Unknown event', 5, 2);
