-- cisco-ids
-- plugin_id: 1515

DELETE FROM plugin WHERE id = "1515";
DELETE FROM plugin_sid where plugin_id = "1515";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1515, 1, 'cisco-ids', 'Cisco Secure IDS');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1000, NULL, NULL, 'cisco-ids: IP options-Bad Option List');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 10000, NULL, NULL, 'cisco-ids: IP-Spoof Interface 1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1001, NULL, NULL, 'cisco-ids: IP options-Record Packet Route');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1002, NULL, NULL, 'cisco-ids: IP options-Timestamp');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1003, NULL, NULL, 'cisco-ids: IP options-Provide s,c,h,tcc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1004, NULL, NULL, 'cisco-ids: IP options-Loose Source Route');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1005, NULL, NULL, 'cisco-ids: IP options-SATNET ID');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1006, NULL, NULL, 'cisco-ids: IP options-Strict Source Route');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1100, NULL, NULL, 'cisco-ids: IP Fragment Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11000, NULL, NULL, 'cisco-ids: KaZaA v2 UDP Client Probe');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11001, NULL, NULL, 'cisco-ids: Gnutella Client Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11002, NULL, NULL, 'cisco-ids: Gnutella Server Reply');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11003, NULL, NULL, 'cisco-ids: Qtella File Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11004, NULL, NULL, 'cisco-ids: Bearshare file request ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11005, NULL, NULL, 'cisco-ids: KaZaA GET Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11006, NULL, NULL, 'cisco-ids: Gnucleus file request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11007, NULL, NULL, 'cisco-ids: Limewire File Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11008, NULL, NULL, 'cisco-ids: Morpheus File Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11009, NULL, NULL, 'cisco-ids: Phex File Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1101, NULL, NULL, 'cisco-ids: Unknown IP Protocol');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11010, NULL, NULL, 'cisco-ids: Swapper File Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11011, NULL, NULL, 'cisco-ids: XoloX File Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11012, NULL, NULL, 'cisco-ids: GTK-Gnutella File Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11013, NULL, NULL, 'cisco-ids: Mutella File Request ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11014, NULL, NULL, 'cisco-ids: Hotline Client Login');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11015, NULL, NULL, 'cisco-ids: Hotline File Transfer');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11016, NULL, NULL, 'cisco-ids: Hotline Tracker Login');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1102, NULL, NULL, 'cisco-ids: Impossible IP Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1103, NULL, NULL, 'cisco-ids: IP Fragments Overlap');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1104, NULL, NULL, 'cisco-ids: IP Localhost Source Spoof');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1107, NULL, NULL, 'cisco-ids: RFC 1918 Addresses Seen');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1108, NULL, NULL, 'cisco-ids: IP Packet with Proto 11');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11200, NULL, NULL, 'cisco-ids: Yahoo Messenger Activity');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11201, NULL, NULL, 'cisco-ids: MSN Messenger Activity');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11202, NULL, NULL, 'cisco-ids: AOL / ICQ Activity');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11203, NULL, NULL, 'cisco-ids: IRC Channel Join');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 11204, NULL, NULL, 'cisco-ids: Jabber Activity [new.gif]');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1200, NULL, NULL, 'cisco-ids: IP Fragmentation Buffer Full');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1201, NULL, NULL, 'cisco-ids: IP Fragment Overlap');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1202, NULL, NULL, 'cisco-ids: IP Fragment Overrun - Datagram Too Long');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1203, NULL, NULL, 'cisco-ids: IP Fragment Overwrite - Data is Overwritten');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1204, NULL, NULL, 'cisco-ids: IP Fragment Missing Initial Fragment ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1205, NULL, NULL, 'cisco-ids: IP Fragment Too Many Datagrams');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1206, NULL, NULL, 'cisco-ids: IP Fragment Too Small');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1207, NULL, NULL, 'cisco-ids: IP Fragment Too Many Frags');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1208, NULL, NULL, 'cisco-ids: IP Fragment Incomplete Datagram');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1220, NULL, NULL, 'cisco-ids: Jolt2 Fragment Reassembly DoS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 1300, NULL, NULL, 'cisco-ids: TCP Segment Overwrite');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2000, NULL, NULL, 'cisco-ids: ICMP Echo Reply');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2001, NULL, NULL, 'cisco-ids: ICMP Host Unreachable');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2002, NULL, NULL, 'cisco-ids: ICMP Source Quench');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2003, NULL, NULL, 'cisco-ids: ICMP Redirect');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2004, NULL, NULL, 'cisco-ids: ICMP Echo Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2005, NULL, NULL, 'cisco-ids: ICMP Time Exceeded for a Datagram');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2006, NULL, NULL, 'cisco-ids: ICMP Parameter Problem on Datagram');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2007, NULL, NULL, 'cisco-ids: ICMP Timestamp Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2008, NULL, NULL, 'cisco-ids: ICMP Timestamp Reply');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2009, NULL, NULL, 'cisco-ids: ICMP Information Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2010, NULL, NULL, 'cisco-ids: ICMP Information Reply');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2011, NULL, NULL, 'cisco-ids: ICMP Address Mask Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2012, NULL, NULL, 'cisco-ids: ICMP Address Mask Reply');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2100, NULL, NULL, 'cisco-ids: ICMP Network Sweep w/Echo');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2101, NULL, NULL, 'cisco-ids: ICMP Network Sweep w/Timestamp');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2102, NULL, NULL, 'cisco-ids: ICMP Network Sweep w/Address Mask');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2150, NULL, NULL, 'cisco-ids: Fragmented ICMP Traffic');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2151, NULL, NULL, 'cisco-ids: Large ICMP Traffic');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2152, NULL, NULL, 'cisco-ids: ICMP Flood');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2153, NULL, NULL, 'cisco-ids: Smurf');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2154, NULL, NULL, 'cisco-ids: Ping of Death Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 2155, NULL, NULL, 'cisco-ids: Modem DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3000, NULL, NULL, 'cisco-ids: TCP Ports');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3001, NULL, NULL, 'cisco-ids: TCP Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3002, NULL, NULL, 'cisco-ids: TCP SYN Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3003, NULL, NULL, 'cisco-ids: TCP Frag SYN Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3005, NULL, NULL, 'cisco-ids: TCP FIN Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3006, NULL, NULL, 'cisco-ids: TCP Frag FIN Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3010, NULL, NULL, 'cisco-ids: TCP High Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3011, NULL, NULL, 'cisco-ids: TCP FIN High Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3012, NULL, NULL, 'cisco-ids: TCP Frag FIN High Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3015, NULL, NULL, 'cisco-ids: TCP Null Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3016, NULL, NULL, 'cisco-ids: TCP Frag Null Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3020, NULL, NULL, 'cisco-ids: TCP SYN FIN Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3021, NULL, NULL, 'cisco-ids: TCP Frag SYN FIN Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3030, NULL, NULL, 'cisco-ids: TCP SYN Host Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3031, NULL, NULL, 'cisco-ids: TCP FRAG SYN Host Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3032, NULL, NULL, 'cisco-ids: TCP FIN Host Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3033, NULL, NULL, 'cisco-ids: TCP FRAG FIN Host Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3034, NULL, NULL, 'cisco-ids: TCP NULL Host Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3035, NULL, NULL, 'cisco-ids: TCP FRAG NULL Host Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3036, NULL, NULL, 'cisco-ids: TCP SYN FIN Host Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3037, NULL, NULL, 'cisco-ids: TCP FRAG SYN FIN Host Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3038, NULL, NULL, 'cisco-ids: Fragmented NULL TCP Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3039, NULL, NULL, 'cisco-ids: Fragmented Orphaned FIN packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3040, NULL, NULL, 'cisco-ids: NULL TCP Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3041, NULL, NULL, 'cisco-ids: SYN/FIN Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3042, NULL, NULL, 'cisco-ids: Orphaned Fin Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3043, NULL, NULL, 'cisco-ids: Fragmented SYN/FIN Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3045, NULL, NULL, 'cisco-ids: Queso Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3046, NULL, NULL, 'cisco-ids: NMAP OS Fingerprint');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3050, NULL, NULL, 'cisco-ids: Half-open SYN Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3100, NULL, NULL, 'cisco-ids: Smail Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3101, NULL, NULL, 'cisco-ids: Sendmail Invalid Recipient');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3102, NULL, NULL, 'cisco-ids: Sendmail Invalid Sender');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3103, NULL, NULL, 'cisco-ids: Sendmail Reconnaissance');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3104, NULL, NULL, 'cisco-ids: Archaic Sendmail Attacks');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3105, NULL, NULL, 'cisco-ids: Sendmail Decode Alias');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3106, NULL, NULL, 'cisco-ids: Mail Spam');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3107, NULL, NULL, 'cisco-ids: Majordomo Execute Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3108, NULL, NULL, 'cisco-ids: MIME Overflow Bug');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3109, NULL, NULL, 'cisco-ids: Long SMTP Command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3110, NULL, NULL, 'cisco-ids: Suspicious Mail Attachment');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3111, NULL, NULL, 'cisco-ids: W32 Sircam Malicious Code');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3112, NULL, NULL, 'cisco-ids: Lotus Domino Mail Loop DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3114, NULL, NULL, 'cisco-ids: FetchMail Arbitrary Code Execution');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3115, NULL, NULL, 'cisco-ids: Sendmail Data Header Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3116, NULL, NULL, 'cisco-ids: Netbus');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3117, NULL, NULL, 'cisco-ids: KLEZ worm ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3118, NULL, NULL, 'cisco-ids: rwhoisd format string');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3119, NULL, NULL, 'cisco-ids: WS_FTP STAT overflow ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3120, NULL, NULL, 'cisco-ids: ANTS virus');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3121, NULL, NULL, 'cisco-ids: Vintra MailServer EXPN DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3122, NULL, NULL, 'cisco-ids: SMTP EXPN root Recon');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3123, NULL, NULL, 'cisco-ids: NetBus Pro Traffic');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3124, NULL, NULL, 'cisco-ids: Sendmail prescan Memory Corruption');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3150, NULL, NULL, 'cisco-ids: FTP Remote Command Execution');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3151, NULL, NULL, 'cisco-ids: FTP SYST Command Attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3152, NULL, NULL, 'cisco-ids: FTP CWD ~root');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3153, NULL, NULL, 'cisco-ids: FTP Improper Address Specified');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3154, NULL, NULL, 'cisco-ids: FTP Improper Port Specified');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3155, NULL, NULL, 'cisco-ids: FTP RETR Pipe Filename Command Execution');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3156, NULL, NULL, 'cisco-ids: FTP STOR Pipe Filename Command Execution');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3157, NULL, NULL, 'cisco-ids: FTP PASV Port Spoof');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3158, NULL, NULL, 'cisco-ids: FTP SITE EXEC Format String');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3159, NULL, NULL, 'cisco-ids: FTP PASS Suspicious Length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3160, NULL, NULL, 'cisco-ids: Cesar FTP Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3161, NULL, NULL, 'cisco-ids: FTP realpath Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3162, NULL, NULL, 'cisco-ids: glFtpD LIST DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3163, NULL, NULL, 'cisco-ids: wu-ftpd heap corruption vulnerability');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3164, NULL, NULL, 'cisco-ids: Instant Server Mini Portal Directory Traversal ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3165, NULL, NULL, 'cisco-ids: FTP SITE EXEC');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3166, NULL, NULL, 'cisco-ids: FTP USER Suspicious Length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3167, NULL, NULL, 'cisco-ids: Format String in FTP username');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3168, NULL, NULL, 'cisco-ids: FTP SITE EXEC Directory Traversal');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3169, NULL, NULL, 'cisco-ids: FTP SITE EXEC tar');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3170, NULL, NULL, 'cisco-ids: WS_FTP SITE CPWD Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3171, NULL, NULL, 'cisco-ids: Ftp Priviledged Login');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3172, NULL, NULL, 'cisco-ids: Ftp Cwd Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3173, NULL, NULL, 'cisco-ids: Long FTP Command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3175, NULL, NULL, 'cisco-ids: ProFTPD STAT DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3200, NULL, NULL, 'cisco-ids: WWW Phf Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3201, NULL, NULL, 'cisco-ids: Unix Password File Access Attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3202, NULL, NULL, 'cisco-ids: WWW .url File Requested');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3203, NULL, NULL, 'cisco-ids: WWW .lnk File Requested');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3204, NULL, NULL, 'cisco-ids: WWW .bat File Requested');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3205, NULL, NULL, 'cisco-ids: HTML File Has .url Link');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3206, NULL, NULL, 'cisco-ids: HTML File Has .lnk Link');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3207, NULL, NULL, 'cisco-ids: HTML File Has .bat Link');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3208, NULL, NULL, 'cisco-ids: WWW campas Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3209, NULL, NULL, 'cisco-ids: WWW Glimpse Server Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3210, NULL, NULL, 'cisco-ids: WWW IIS View Source Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3211, NULL, NULL, 'cisco-ids: WWW IIS Hex View Source Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3212, NULL, NULL, 'cisco-ids: WWW NPH-TEST-CGI Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3213, NULL, NULL, 'cisco-ids: WWW TEST-CGI Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3214, NULL, NULL, 'cisco-ids: IIS DOT DOT VIEW Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3215, NULL, NULL, 'cisco-ids: IIS DOT DOT EXECUTE Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3216, NULL, NULL, 'cisco-ids: WWW Directory Traversal ../..');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3217, NULL, NULL, 'cisco-ids: WWW php View File Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3218, NULL, NULL, 'cisco-ids: WWW SGI Wrap Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3219, NULL, NULL, 'cisco-ids: WWW PHP Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3220, NULL, NULL, 'cisco-ids: IIS Long URL Crash Bug');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3221, NULL, NULL, 'cisco-ids: WWW cgi-viewsource Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3222, NULL, NULL, 'cisco-ids: WWW PHP Log Scripts Read Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3223, NULL, NULL, 'cisco-ids: WWW IRIX cgi-handler Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3224, NULL, NULL, 'cisco-ids: HTTP WebGais');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3225, NULL, NULL, 'cisco-ids: WWW websendmail File Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3226, NULL, NULL, 'cisco-ids: WWW Webdist Bug');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3227, NULL, NULL, 'cisco-ids: WWW Htmlscript Bug');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3228, NULL, NULL, 'cisco-ids: WWW Performer Bug');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3229, NULL, NULL, 'cisco-ids: Website Win-C-Sample Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3230, NULL, NULL, 'cisco-ids: Website Uploader');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3231, NULL, NULL, 'cisco-ids: Novell convert');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3232, NULL, NULL, 'cisco-ids: WWW finger attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3233, NULL, NULL, 'cisco-ids: WWW count-cgi Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3250, NULL, NULL, 'cisco-ids: TCP Hijack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3251, NULL, NULL, 'cisco-ids: TCP Hijacking Simplex Mode');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3300, NULL, NULL, 'cisco-ids: NetBIOS OOB Data');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3301, NULL, NULL, 'cisco-ids: NETBIOS Stat');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3302, NULL, NULL, 'cisco-ids: NETBIOS Session Setup Failure');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3303, NULL, NULL, 'cisco-ids: Windows Guest Login');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3304, NULL, NULL, 'cisco-ids: Windows Null Account Name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3305, NULL, NULL, 'cisco-ids: Windows Password File Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3306, NULL, NULL, 'cisco-ids: Windows Registry Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3307, NULL, NULL, 'cisco-ids: Windows Redbutton Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3308, NULL, NULL, 'cisco-ids: Windows LSARPC Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3309, NULL, NULL, 'cisco-ids: Windows SRVSVC Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3310, NULL, NULL, 'cisco-ids: Netbios Enum Share DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3311, NULL, NULL, 'cisco-ids: SMB: remote SAM service access attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3312, NULL, NULL, 'cisco-ids: SMB .eml email file remote access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3313, NULL, NULL, 'cisco-ids: SMB suspicous password usage');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3314, NULL, NULL, 'cisco-ids: Windows Locator Service Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3320, NULL, NULL, 'cisco-ids: SMB: ADMIN$ hidden share access attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3321, NULL, NULL, 'cisco-ids: SMB: User Enumeration');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3322, NULL, NULL, 'cisco-ids: SMB: Windows Share Enumeration');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3323, NULL, NULL, 'cisco-ids: SMB: RFPoison Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3324, NULL, NULL, 'cisco-ids: SMB NIMDA infected file transfer');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3325, NULL, NULL, 'cisco-ids: Samba call_trans2open Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3326, NULL, NULL, 'cisco-ids: Windows Startup Folder Remote Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3400, NULL, NULL, 'cisco-ids: Sunkill');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3401, NULL, NULL, 'cisco-ids: Telnet-IFS Match');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3402, NULL, NULL, 'cisco-ids: BSD Telnet Daemon Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3403, NULL, NULL, 'cisco-ids: Telnet Excessive Environment Options');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3404, NULL, NULL, 'cisco-ids: SysV /bin/login Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3405, NULL, NULL, 'cisco-ids: Avirt Gateway proxy Buffer Overflow ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3406, NULL, NULL, 'cisco-ids: Solaris TTYPROMPT /bin/login Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3450, NULL, NULL, 'cisco-ids: Finger Bomb');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3451, NULL, NULL, 'cisco-ids: BearShare Directory Traversal');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3452, NULL, NULL, 'cisco-ids: gopherd halidate overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3453, NULL, NULL, 'cisco-ids: MS NetMeeting RDS DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3454, NULL, NULL, 'cisco-ids: Check Point Firewall Information Leak');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3455, NULL, NULL, 'cisco-ids: Java Web Server Cmd Exec');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3456, NULL, NULL, 'cisco-ids: Solaris in.fingerd Information Leak');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3457, NULL, NULL, 'cisco-ids: Finger root shell');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3458, NULL, NULL, 'cisco-ids: AIM game invite overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3459, NULL, NULL, 'cisco-ids: ValiCert forms.exe overflow ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3461, NULL, NULL, 'cisco-ids: Finger probe');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3462, NULL, NULL, 'cisco-ids: Finger Redirect');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3463, NULL, NULL, 'cisco-ids: Finger root');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3464, NULL, NULL, 'cisco-ids: File access in finger');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3465, NULL, NULL, 'cisco-ids: Finger Activity');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3500, NULL, NULL, 'cisco-ids: Rlogin -froot Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3501, NULL, NULL, 'cisco-ids: Rlogin Long TERM Variable');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3502, NULL, NULL, 'cisco-ids: rlogin Activity');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3525, NULL, NULL, 'cisco-ids: IMAP Authenticate Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3526, NULL, NULL, 'cisco-ids: Imap Login Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3530, NULL, NULL, 'cisco-ids: Cisco Secure ACS Oversized TACACS+ Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3540, NULL, NULL, 'cisco-ids: Cisco Secure ACS CSAdmin Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3550, NULL, NULL, 'cisco-ids: POP Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3551, NULL, NULL, 'cisco-ids: POP User Root');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3575, NULL, NULL, 'cisco-ids: INN Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3576, NULL, NULL, 'cisco-ids: INN Control Message Exploit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3600, NULL, NULL, 'cisco-ids: IOS Telnet Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3601, NULL, NULL, 'cisco-ids: IOS Command History Exploit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3602, NULL, NULL, 'cisco-ids: Cisco IOS Identity');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3603, NULL, NULL, 'cisco-ids: IOS Enable Bypass');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3604, NULL, NULL, 'cisco-ids: Cisco Catalyst CR DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3650, NULL, NULL, 'cisco-ids: SSH RSAREF2 Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3651, NULL, NULL, 'cisco-ids: SSH CRC32 Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3652, NULL, NULL, 'cisco-ids: SSH Gobbles');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3700, NULL, NULL, 'cisco-ids: CDE dtspcd overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3701, NULL, NULL, 'cisco-ids: Oracle 9iAS Web Cache Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3702, NULL, NULL, 'cisco-ids: Default sa account access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3703, NULL, NULL, 'cisco-ids: Squid FTP URL Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3704, NULL, NULL, 'cisco-ids: IIS FTP STAT Denial of Service');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3705, NULL, NULL, 'cisco-ids: Tivoli Storage Manager Client Acceptor Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3706, NULL, NULL, 'cisco-ids: MIT PGP Public Key Server Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3707, NULL, NULL, 'cisco-ids: Perl fingerd Command Exec');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3708, NULL, NULL, 'cisco-ids: AnalogX Proxy Socks4a DNS Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3709, NULL, NULL, 'cisco-ids: AnalogX Proxy Web Proxy Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3710, NULL, NULL, 'cisco-ids: Cisco Secure ACS Directory Traversal');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3711, NULL, NULL, 'cisco-ids: Informer FW1 auth replay DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3714, NULL, NULL, 'cisco-ids: Oracle TNS \'Service_Name\' Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3728, NULL, NULL, 'cisco-ids: Long pop username');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3729, NULL, NULL, 'cisco-ids: Long pop password');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3730, NULL, NULL, 'cisco-ids: Trinoo (TCP)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3731, NULL, NULL, 'cisco-ids: IMail HTTP Get Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3732, NULL, NULL, 'cisco-ids: MSSQL xp_cmdshell Usage');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3990, NULL, NULL, 'cisco-ids: BackOrifice BO2K TCP Non Stealth');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3991, NULL, NULL, 'cisco-ids: BackOrifice BO2K TCP Stealth 1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 3992, NULL, NULL, 'cisco-ids: BackOrifice BO2K TCP Stealth 2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4000, NULL, NULL, 'cisco-ids: UDP Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4001, NULL, NULL, 'cisco-ids: UDP Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4002, NULL, NULL, 'cisco-ids: UDP Flood');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4003, NULL, NULL, 'cisco-ids: Nmap UDP Port Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4050, NULL, NULL, 'cisco-ids: UDP Bomb');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4051, NULL, NULL, 'cisco-ids: Snork');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4052, NULL, NULL, 'cisco-ids: Chargen DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4053, NULL, NULL, 'cisco-ids: Back Orifice');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4054, NULL, NULL, 'cisco-ids: RIP Trace');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4055, NULL, NULL, 'cisco-ids: BackOrifice BO2K UDP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4056, NULL, NULL, 'cisco-ids: NTPd readvar overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4058, NULL, NULL, 'cisco-ids: UPnP LOCATION Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4060, NULL, NULL, 'cisco-ids: Back Orifice Ping');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4061, NULL, NULL, 'cisco-ids: Chargen Echo DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4100, NULL, NULL, 'cisco-ids: Tftp Passwd File');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4101, NULL, NULL, 'cisco-ids: Cisco TFTPD Directory Traversal');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4150, NULL, NULL, 'cisco-ids: Ascend Denial of Service');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4500, NULL, NULL, 'cisco-ids: Cisco IOS Embedded SNMP Community Names');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4501, NULL, NULL, 'cisco-ids: Cisco CVCO/4K Remote Username/Password return');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4502, NULL, NULL, 'cisco-ids: SNMP Password Brute Force Attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4503, NULL, NULL, 'cisco-ids: SNMP NT Info Retrieve');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4504, NULL, NULL, 'cisco-ids: SNMP IOS Configuration Retrieval');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4505, NULL, NULL, 'cisco-ids: SNMP VACM MIB Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4506, NULL, NULL, 'cisco-ids: D-Link Wireless SNMP Plain Text Password ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4507, NULL, NULL, 'cisco-ids: SNMP Protocol Violation');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4508, NULL, NULL, 'cisco-ids: Non SNMP Traffic');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4509, NULL, NULL, 'cisco-ids: HP Openview SNMP Hidden Community Name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4510, NULL, NULL, 'cisco-ids: Solaris SNMP Hidden Community Name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4511, NULL, NULL, 'cisco-ids: Avaya SNMP Hidden Community Name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4600, NULL, NULL, 'cisco-ids: IOS UDP Bomb');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4601, NULL, NULL, 'cisco-ids: CheckPoint Firewall RDP Bypass');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4603, NULL, NULL, 'cisco-ids: DHCP Discover');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4604, NULL, NULL, 'cisco-ids: DHCP Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4605, NULL, NULL, 'cisco-ids: DHCP Offer');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4606, NULL, NULL, 'cisco-ids: Cisco TFTP Long Filename Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4607, NULL, NULL, 'cisco-ids: Deep Throat Response');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4608, NULL, NULL, 'cisco-ids: Trinoo (UDP)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4609, NULL, NULL, 'cisco-ids: Orinoco SNMP Info Leak ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4610, NULL, NULL, 'cisco-ids: Kerberos 4 User Recon');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4611, NULL, NULL, 'cisco-ids: D-Link DWL-900AP+ TFTP Config Retrieve');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4612, NULL, NULL, 'cisco-ids: Cisco IP Phone TFTP Config Retrieve');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4613, NULL, NULL, 'cisco-ids: TFTP Filename Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 4701, NULL, NULL, 'cisco-ids: MS-SQL Control Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5034, NULL, NULL, 'cisco-ids: WWW IIS newdsn attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5035, NULL, NULL, 'cisco-ids: HTTP cgi HylaFAX Faxsurvey');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5036, NULL, NULL, 'cisco-ids: WWW Windows Password File Access Attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5037, NULL, NULL, 'cisco-ids: WWW SGI MachineInfo Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5038, NULL, NULL, 'cisco-ids: WWW wwwsql file read Bug');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5039, NULL, NULL, 'cisco-ids: WWW finger attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5040, NULL, NULL, 'cisco-ids: WWW Perl Interpreter Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5041, NULL, NULL, 'cisco-ids: WWW anyform attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5042, NULL, NULL, 'cisco-ids: WWW CGI Valid Shell Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5043, NULL, NULL, 'cisco-ids: WWW Cold Fusion Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5044, NULL, NULL, 'cisco-ids: WWW Webcom.se Guestbook attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5045, NULL, NULL, 'cisco-ids: WWW xterm display attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5046, NULL, NULL, 'cisco-ids: WWW dumpenv.pl recon');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5047, NULL, NULL, 'cisco-ids: WWW Server Side Include POST attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5048, NULL, NULL, 'cisco-ids: WWW IIS BAT EXE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5049, NULL, NULL, 'cisco-ids: WWW IIS showcode.asp access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5050, NULL, NULL, 'cisco-ids: WWW IIS .htr Overflow Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5051, NULL, NULL, 'cisco-ids: IIS Double Byte Code Page');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5052, NULL, NULL, 'cisco-ids: FrontPage Extensions PWD Open Attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5053, NULL, NULL, 'cisco-ids: FrontPage _vti_bin Directory List Attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5054, NULL, NULL, 'cisco-ids: WWWBoard Password');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5055, NULL, NULL, 'cisco-ids: HTTP Basic Authentication Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5056, NULL, NULL, 'cisco-ids: WWW Cisco IOS %% DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5057, NULL, NULL, 'cisco-ids: WWW Sambar Samples');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5058, NULL, NULL, 'cisco-ids: WWW info2www Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5059, NULL, NULL, 'cisco-ids: WWW Alibaba Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5060, NULL, NULL, 'cisco-ids: WWW Excite AT-generate.cgi Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5061, NULL, NULL, 'cisco-ids: WWW catalog_type.asp Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5062, NULL, NULL, 'cisco-ids: WWW classifieds.cgi Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5063, NULL, NULL, 'cisco-ids: WWW dmblparser.exe Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5064, NULL, NULL, 'cisco-ids: WWW imagemap.cgi Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5065, NULL, NULL, 'cisco-ids: WWW IRIX infosrch.cgi Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5066, NULL, NULL, 'cisco-ids: WWW man.sh Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5067, NULL, NULL, 'cisco-ids: WWW plusmail Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5068, NULL, NULL, 'cisco-ids: WWW formmail.pl Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5069, NULL, NULL, 'cisco-ids: WWW whois_raw.cgi Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5070, NULL, NULL, 'cisco-ids: WWW msadcs.dll Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5071, NULL, NULL, 'cisco-ids: WWW msacds.dll Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5072, NULL, NULL, 'cisco-ids: WWW bizdb1-search.cgi Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5073, NULL, NULL, 'cisco-ids: WWW EZshopper loadpage.cgi Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5074, NULL, NULL, 'cisco-ids: WWW EZshopper search.cgi Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5075, NULL, NULL, 'cisco-ids: WWW IIS Virtualized UNC Bug');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5076, NULL, NULL, 'cisco-ids: WWW webplus bug');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5077, NULL, NULL, 'cisco-ids: WWW Excite AT-admin.cgi Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5078, NULL, NULL, 'cisco-ids: WWW Piranha passwd attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5079, NULL, NULL, 'cisco-ids: WWW PCCS MySQL Admin Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5080, NULL, NULL, 'cisco-ids: WWW IBM WebSphere Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5081, NULL, NULL, 'cisco-ids: WWW WinNT cmd.exe Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5083, NULL, NULL, 'cisco-ids: WWW Virtual Vision FTP Browser Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5084, NULL, NULL, 'cisco-ids: WWW Alibaba Attack 2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5085, NULL, NULL, 'cisco-ids: WWW IIS Source Fragment Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5086, NULL, NULL, 'cisco-ids: WWW WEBactive Logfile Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5087, NULL, NULL, 'cisco-ids: WWW Sun Java Server Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5088, NULL, NULL, 'cisco-ids: WWW Akopia MiniVend Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5089, NULL, NULL, 'cisco-ids: WWW Big Brother Directory Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5090, NULL, NULL, 'cisco-ids: WWW FrontPage htimage.exe Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5091, NULL, NULL, 'cisco-ids: WWW Cart32 Remote Admin Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5092, NULL, NULL, 'cisco-ids: WWW CGI-World Poll It Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5093, NULL, NULL, 'cisco-ids: WWW PHP-Nuke admin.php3 Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5095, NULL, NULL, 'cisco-ids: WWW CGI Script Center Account Manager Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5096, NULL, NULL, 'cisco-ids: WWW CGI Script Center Subscribe Me Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5097, NULL, NULL, 'cisco-ids: WWW FrontPage MS-DOS Device Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5099, NULL, NULL, 'cisco-ids: WWW GWScripts News Publisher Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5100, NULL, NULL, 'cisco-ids: WWW CGI Center Auction Weaver File Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5101, NULL, NULL, 'cisco-ids: WWW CGI Center Auction Weaver Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5102, NULL, NULL, 'cisco-ids: WWW phpPhotoAlbum explorer.php Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5103, NULL, NULL, 'cisco-ids: WWW SuSE Apache CGI Source Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5104, NULL, NULL, 'cisco-ids: WWW YaBB File Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5105, NULL, NULL, 'cisco-ids: WWW Ranson Johnson mailto.cgi Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5106, NULL, NULL, 'cisco-ids: WWW Ranson Johnson mailform.pl Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5107, NULL, NULL, 'cisco-ids: WWW Mandrake Linux /perl Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5108, NULL, NULL, 'cisco-ids: WWW Netegrity Site Minder Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5109, NULL, NULL, 'cisco-ids: WWW Sambar Beta search.dll Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5110, NULL, NULL, 'cisco-ids: WWW SuSE Installed Packages Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5111, NULL, NULL, 'cisco-ids: WWW Solaris Answerbook 2 Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5112, NULL, NULL, 'cisco-ids: WWW Solaris Answerbook 2 Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5113, NULL, NULL, 'cisco-ids: WWW CommuniGate Pro Access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5114, NULL, NULL, 'cisco-ids: WWW IIS Unicode Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5115, NULL, NULL, 'cisco-ids: Netscape Enterprise Server with ?wp Tags');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5116, NULL, NULL, 'cisco-ids: Endymion MailMan Remote Command Execution');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5117, NULL, NULL, 'cisco-ids: phpGroupWare Remote Command Exec');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5118, NULL, NULL, 'cisco-ids: eWave ServletExec 3.0C File Upload');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5119, NULL, NULL, 'cisco-ids: CGI Script Center News Update Admin Passwd Change');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5120, NULL, NULL, 'cisco-ids: Netscape Server Suite Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5121, NULL, NULL, 'cisco-ids: iPlanet .shtml Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5122, NULL, NULL, 'cisco-ids: Nokia IP440 Denial of Service');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5123, NULL, NULL, 'cisco-ids: WWW IIS Internet Printing Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5124, NULL, NULL, 'cisco-ids: IIS CGI Double Decode');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5125, NULL, NULL, 'cisco-ids: PerlCal Directory Traversal');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5126, NULL, NULL, 'cisco-ids: WWW IIS .ida Indexing Service Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5127, NULL, NULL, 'cisco-ids: WWW viewsrc.cgi Directory Traversal');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5128, NULL, NULL, 'cisco-ids: WWW nph-maillist.pl Cmd Exec');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5129, NULL, NULL, 'cisco-ids: IOS HTTP Unauth Command Execution');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5130, NULL, NULL, 'cisco-ids: Bugzilla globals.pl');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5131, NULL, NULL, 'cisco-ids: talkback.cgi Directory Traversal');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5132, NULL, NULL, 'cisco-ids: VirusScan catinfo Buffer Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5133, NULL, NULL, 'cisco-ids: Net.Commerce Macro Path Disclosure');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5134, NULL, NULL, 'cisco-ids: MacOS PWS DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5138, NULL, NULL, 'cisco-ids: Oracle Application Server Shared Library Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5140, NULL, NULL, 'cisco-ids: Net.Commerce Macro Denial of Service');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5141, NULL, NULL, 'cisco-ids: NCM content.pl SQL Query Vulnerability');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5142, NULL, NULL, 'cisco-ids: DCShop File Disclosure');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5146, NULL, NULL, 'cisco-ids: MS-DOS Device Name DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5147, NULL, NULL, 'cisco-ids: Arcadia Internet Store Directory Traversal Attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1515, 5148, NULL, NULL, 'cisco-ids: Perception LiteServe Web Server CGI Script Source Code');


