DELETE FROM plugin WHERE id = "1653";
DELETE FROM plugin_sid where plugin_id = "1653";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1653, 1, 'cisco-ace', 'Cisco ACE');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 106021, NULL, NULL, 'cisco-ace: Deny protocol reverse path check from source_address to dest_address on interface interface_name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 106023, NULL, NULL, 'cisco-ace: Deny protocol number | name src incoming-interface:src-ip dst outgoing-interface:dst-ip by access-group "acl-name"');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 106028, NULL, NULL, 'cisco-ace: WARNING: Access rule memory exhausted while processing Access-group. Incomplete rules are currently applied on interface interface-name.  Manual roll back to a previous access rule configuration on this interface is needed. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 111008, NULL, NULL, 'cisco-ace: User root executed the string command ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 111009, NULL, NULL, 'cisco-ace: User user executed cmd:string');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 199006, NULL, NULL, 'cisco-ace: Orderly reload started at when by whom. Reload reason: reason ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 212007, NULL, NULL, 'cisco-ace: SNMPD initialization failed while Variable1 ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 212008, NULL, NULL, 'cisco-ace: Failed while allocating memory in snmpd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251001, NULL, NULL, 'cisco-ace: Probe configuration error, memory allocation failure.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251002, NULL, NULL, 'cisco-ace: The configured health probe script script-name for server A.B.C.D on port P is empty');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251003, NULL, NULL, 'cisco-ace: Could not load script script-name - File not found');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251004, NULL, NULL, 'cisco-ace: Could not load script script-name - memory allocation failure');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251005, NULL, NULL, 'cisco-ace: Could not unload script script-name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251006, NULL, NULL, 'cisco-ace: Health probe failed for server A.B.C.D on port P, internal error: error message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251007, NULL, NULL, 'cisco-ace: ICMP health probe failed for server A.B.C.D, internal error: error message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251008, NULL, NULL, 'cisco-ace: Health probe failed for server A.B.C.D on port P, connectivity error: server open timeout (no SYN ACK)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251009, NULL, NULL, 'cisco-ace: ICMP health probe failed for server A.B.C.D, connectivity error: error message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251010, NULL, NULL, 'cisco-ace: Health probe failed for server A.B.C.D on port P, error message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251011, NULL, NULL, 'cisco-ace: ICMP health probe failed for server A.B.C.D, error message.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251012, NULL, NULL, 'cisco-ace: Could not load script script-name - Error reading script-file');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 251013, NULL, NULL, 'cisco-ace: Could not load script script-name - Error getting file size');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253001, NULL, NULL, 'cisco-ace: Certificate certificate_information expired');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253002, NULL, NULL, 'cisco-ace: Certificate certificate_information not yet valid');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253003, NULL, NULL, 'cisco-ace: Unknown CA certificate_information');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253004, NULL, NULL, 'cisco-ace: Certificate certificate_information revoked');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253005, NULL, NULL, 'cisco-ace: Signature for certificate_information is invalid');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253006, NULL, NULL, 'cisco-ace: Error peer sent invalid or nonexistent certificate ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253007, NULL, NULL, 'cisco-ace: Certificate in file file_name is expired ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253008, NULL, NULL, 'cisco-ace: CRL crl_name could not be retrieved ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253009, NULL, NULL, 'cisco-ace: ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 253010, NULL, NULL, 'cisco-ace: Configuration failure: Certificate in file ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 254001, NULL, NULL, 'cisco-ace: ACL resource usage beyond maximum limit for context ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 254002, NULL, NULL, 'cisco-ace: Minimum ACL resources could not be guaranteed for ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302022, NULL, NULL, 'cisco-ace: Built TCP connection id for interface:real-address/real-port (mapped-address/mapped-port) to interface:real-address/real-port (mapped-address/mapped-port)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302023, NULL, NULL, 'cisco-ace: Teardown TCP connection id for interface:real-address/real-port to interface:real-address/real-port duration hh:mm:ss bytes bytes [reason]');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302024, NULL, NULL, 'cisco-ace: Built UDP connection id for interface:real-address/real-port (mapped-address/mapped-port) to interface:real-address/real-port (mapped-address/mapped-port)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302025, NULL, NULL, 'cisco-ace: Teardown UDP connection id for interface:real-address/real-port to interface:real-address/real-port duration hh:mm:ss bytes bytes');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302026, NULL, NULL, 'cisco-ace: Built ICMP connection for faddr/NATed_ID gaddr/icmp_type laddr/icmpID ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302027, NULL, NULL, 'cisco-ace: Teardown ICMP connection for faddr/NATed ID gaddr/icmp_type laddr/icmpID ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302028, NULL, NULL, 'cisco-ace: Built TCP connection id for interface: real-address/real-port  (mapped-address/mapped-port) to interface: real-address/real-port (mapped-address/mapped-port)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302029, NULL, NULL, 'cisco-ace: Teardown TCP connection id for interface: real-address/real-port to interface: real-address/real-port duration hh:mm:ss bytes bytes [reason]');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302030, NULL, NULL, 'cisco-ace: Built UDP connection id for interface:       real-address/real-port (mapped-address/mapped-port) to interface: real-address/real-port (mapped-address/mapped-port)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 302031, NULL, NULL, 'cisco-ace: Teardown UDP connection id for interface: real-address/real-port to interface: real-address/real-port duration hh:mm:ss bytes bytes');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 303003, NULL, NULL, 'cisco-ace: FTP cmd_name command denied - failed strict inspection, ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 303004, NULL, NULL, 'cisco-ace: FTP cmd_string command unsupported - failed strict inspection, terminating connection from ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 304001, NULL, NULL, 'cisco-ace: user source_address Accessed {URL} dest_address: url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 305009, NULL, NULL, 'cisco-ace: Built {dynamic|static} translation from interface_name ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 305010, NULL, NULL, 'cisco-ace: Teardown {dynamic|static} translation from ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 313004, NULL, NULL, 'cisco-ace: Denied ICMP type=icmp_type, from source_address on interface interface_name to dest_address:no matching session');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 313006, NULL, NULL, 'cisco-ace: ICMP Manager Initialization Failed. Reason : Variable1 ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 313007, NULL, NULL, 'cisco-ace: ICMP Manager Memory Problem. Reason: Variable1 ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 314001, NULL, NULL, 'cisco-ace: Pre-allocate RTSP UDP backconnection for foreign_address outside_address/outside_port to local_address ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 322001, NULL, NULL, 'cisco-ace: Deny MAC address MAC_address, possible spoof attempt on interface interface');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 322002, NULL, NULL, 'cisco-ace: ARP inspection check failed for arp {request|response} received from host MAC_address on interface interface. This host is advertising MAC Address MAC_address_1 for IP Address IP_address, which is {statically|dynamically} bound to MAC Address MAC_address_2.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 322003, NULL, NULL, 'cisco-ace: ARP inspection check failed for arp {request|response} ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 322005, NULL, NULL, 'cisco-ace: Source MAC address validation check failed for ARP ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 327001, NULL, NULL, 'cisco-ace: Detected Encap table Full when allocating encap entry for IP interface interface_name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 400000, NULL, NULL, 'cisco-ace: IDS:1000 IP Option Bad Option List from IP_address to ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 405001, NULL, NULL, 'cisco-ace: Received ARP {request | response} collision from IP_address/mac_address on interface interface_name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 405201, NULL, NULL, 'cisco-ace: ILS ctxid from vlan x:src_ip/src_prt to vlan ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 406001, NULL, NULL, 'cisco-ace: FTP port command low port: IP_address/port to ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 406002, NULL, NULL, 'cisco-ace: FTP port command different address: ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 410001, NULL, NULL, 'cisco-ace: Dropped UDP DNS packet_type from source_interface:source_address/source_port to dest_interface:dest_address/dest_port; error_length_type length length bytes exceeds max_length_type limit of maximum_length bytes. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 411001, NULL, NULL, 'cisco-ace: Line protocol on interface interface_name changed state to up');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 411002, NULL, NULL, 'cisco-ace: Line protocol on interface interface_name changed state to down');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 411003, NULL, NULL, 'cisco-ace:  Interface interface_name changed state to administratively up');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 411004, NULL, NULL, 'cisco-ace:  Interface interface_name changed state to administratively down');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 412001, NULL, NULL, 'cisco-ace: MAC MAC_address moved from interface_1 to interface_2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415006, NULL, NULL, 'cisco-ace: HTTP - matched class_map_name in policy_map_name, URI ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415007, NULL, NULL, 'cisco-ace: HTTP - matched class_map_name in policy-map ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415008, NULL, NULL, 'cisco-ace: HTTP - matched class_map_name in policy-map ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415009, NULL, NULL, 'cisco-ace: HTTP - matched class_map_name in policy-map ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415010, NULL, NULL, 'cisco-ace: HTTP - matched class_map_name in policy-map ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415011, NULL, NULL, 'cisco-ace: HTTP - policy-map policy_map_name:Protocol violation ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415021, NULL, NULL, 'cisco-ace: HTTP - matched class_map_name in policy-map ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415022, NULL, NULL, 'cisco-ace: HTTP - matched class_map_name in policy_map_name, ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415023, NULL, NULL, 'cisco-ace: HTTP - matched class_map_name in policy-map ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415025, NULL, NULL, 'cisco-ace: HTTP policy_map_name - Tunnel detected - ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415026, NULL, NULL, 'cisco-ace: HTTP  policy_map_name: Instant Messenger detected ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 415027, NULL, NULL, 'cisco-ace: HTTP policy_map_name:  Peer-to-Peer detected ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 440002, NULL, NULL, 'cisco-ace: Addition failed for variable 1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 440003, NULL, NULL, 'cisco-ace: Deletion failed for variable 2 ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 441001, NULL, NULL, 'cisco-ace: Serverfarm name failed over to backup. Number of ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 441002, NULL, NULL, 'cisco-ace: Serverfarm name is back in service. Number of failovers ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 442001, NULL, NULL, 'cisco-ace:  Health probe probe name detected real_server_name (interface interface_name) in serverfarm sfarm_name changed state to UP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 442002, NULL, NULL, 'cisco-ace:  Health probe probe name detected real_server_name (interface interface_name) in serverfarm sfarm_name changed state to DOWN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 442003, NULL, NULL, 'cisco-ace:  Real Server real_server_name in serverfarm sfarm_name changed state to new state');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 442004, NULL, NULL, 'cisco-ace:  Health probe probe name detected real_server_name ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 442005, NULL, NULL, 'cisco-ace:  Health probe probe name detected real_server_name ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 442006, NULL, NULL, 'cisco-ace: Real Server Real Server name changed state to ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 443001, NULL, NULL, 'cisco-ace: System experienced fatal failure. Char, reloading ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 443002, NULL, NULL, 'cisco-ace: dataplane_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 444001, NULL, NULL, 'cisco-ace: License checkout failure for feature feature_name reason ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 444002, NULL, NULL, 'cisco-ace: Installed license file license_file_name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 444003, NULL, NULL, 'cisco-ace: Uninstalled license file license_file_name ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 444004, NULL, NULL, 'cisco-ace: Evaluation license expired for feature feature_name');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 444005, NULL, NULL, 'cisco-ace: Evaluation license for feature feature_name will expire in num_days days num_hours hours');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 444006, NULL, NULL, 'cisco-ace: License manager exiting: reason ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 444007, NULL, NULL, 'cisco-ace: Installed feature_name license on Revision 6 or older ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456001, NULL, NULL, 'cisco-ace: Unable to allocate memory or buffer space. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456002, NULL, NULL, 'cisco-ace: debug_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456008, NULL, NULL, 'cisco-ace: New connection can not be accommodated within the existing connection pool.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456009, NULL, NULL, 'cisco-ace: Network IO error. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456010, NULL, NULL, 'cisco-ace: reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456012, NULL, NULL, 'cisco-ace: Unknown/Unsupported protocol');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456013, NULL, NULL, 'cisco-ace: Unable to access file filename.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456014, NULL, NULL, 'cisco-ace: Invalid stream. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456015, NULL, NULL, 'cisco-ace: Process creation failed pid.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456016, NULL, NULL, 'cisco-ace: message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456017, NULL, NULL, 'cisco-ace: Unable to create cache key for url. Reason is reason.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456018, NULL, NULL, 'cisco-ace: Application class policy is empty for url url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456019, NULL, NULL, 'cisco-ace: Invalid regular expression pattern for url. Pattern is pattern. Application class is appl_classname.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456021, NULL, NULL, 'cisco-ace: CacheDynamic is not on while CacheDelta is on in application class appl_classname.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456023, NULL, NULL, 'cisco-ace: Parser detected invalid HTML content content.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456024, NULL, NULL, 'cisco-ace: Content not accelerated due to presence of UTF characters');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456025, NULL, NULL, 'cisco-ace: Unrecognized special marker marker_code found in delta stream.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456026, NULL, NULL, 'cisco-ace: debug_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456027, NULL, NULL, 'cisco-ace: Unable to access cache directory path');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456028, NULL, NULL, 'cisco-ace: No content type found for filename');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456029, NULL, NULL, 'cisco-ace: Error creating ACC core process. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456030, NULL, NULL, 'cisco-ace: Unable to parse url url reason.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456031, NULL, NULL, 'cisco-ace: Error reading post data. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456032, NULL, NULL, 'cisco-ace: debug_messages');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456033, NULL, NULL, 'cisco-ace: debug_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456034, NULL, NULL, 'cisco-ace: Unable to lock to access shared memory log. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456035, NULL, NULL, 'cisco-ace: debug_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456038, NULL, NULL, 'cisco-ace: Unable to apply caching policy. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456040, NULL, NULL, 'cisco-ace: Container object cache is already stale, TTL is time_to_live.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456042, NULL, NULL, 'cisco-ace: Disk cache subsystem error. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456043, NULL, NULL, 'cisco-ace: Cannot read disk cache file filename, sending a normal GET to origin server instead.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456044, NULL, NULL, 'cisco-ace: Invalid cache file filename deleted, reason is reason, url is url');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456046, NULL, NULL, 'cisco-ace: Unable to merge 304 headers, reason: reason, url, filename');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456047, NULL, NULL, 'cisco-ace: Unable to calculate moving average because reason, url is url');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456048, NULL, NULL, 'cisco-ace: debug_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456049, NULL, NULL, 'cisco-ace: Unexpected http null response for url url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456050, NULL, NULL, 'cisco-ace: Unable to get the whole http response for url url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456051, NULL, NULL, 'cisco-ace: Null host header for url url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456052, NULL, NULL, 'cisco-ace: No request header found for url url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456053, NULL, NULL, 'cisco-ace: Invalid POST content length for url url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456054, NULL, NULL, 'cisco-ace: Sending of request failed for url url');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456055, NULL, NULL, 'cisco-ace: Response header read from cache is null for url url, file name filename.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456056, NULL, NULL, 'cisco-ace: Unable to create path path, error reason.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456058, NULL, NULL, 'cisco-ace: Invalid meta data. Version mismatch for file filename, url url. Deleting cached file.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456060, NULL, NULL, 'cisco-ace:  Reset of base file meta data failed.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456061, NULL, NULL, 'cisco-ace: Refresh of cached base file meta data failed');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456062, NULL, NULL, 'cisco-ace: warning_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456067, NULL, NULL, 'cisco-ace: Compilation of regular expression failed for regex.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456068, NULL, NULL, 'cisco-ace: Unable to send base page because cookie not found for request url');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456069, NULL, NULL, 'cisco-ace: Base file Creation time has changed. Using Alternate File');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456070, NULL, NULL, 'cisco-ace: Empty container cache hit for request url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456071, NULL, NULL, 'cisco-ace: Delta engine can not handle unknown response mode send_mode for container cache hit url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456073, NULL, NULL, 'cisco-ace: Can not save delta in cache, container_cache pointer is NULL for url url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456076, NULL, NULL, 'cisco-ace: Unknown user agent/browser name accessing url url.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456077, NULL, NULL, 'cisco-ace: Locking/unlocking error. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456078, NULL, NULL, 'cisco-ace: Critical shared memory setup failure. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456079, NULL, NULL, 'cisco-ace: Shared memory error. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456080, NULL, NULL, 'cisco-ace: Critical Semaphore related errors. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456081, NULL, NULL, 'cisco-ace: message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456083, NULL, NULL, 'cisco-ace: Unable to get performance monitoring page pg_num_type for url url reason.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456085, NULL, NULL, 'cisco-ace: Message.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456086, NULL, NULL, 'cisco-ace: Error initializing the ACE. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456087, NULL, NULL, 'cisco-ace: Connect method declined. Visible https proxy is not supported.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456088, NULL, NULL, 'cisco-ace: Error parsing HTTP header header_string for reason reason.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456090, NULL, NULL, 'cisco-ace: Critical error parsing ACC module configuration config_directive reason.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456091, NULL, NULL, 'cisco-ace: httpheader_warning');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456092, NULL, NULL, 'cisco-ace: Buffer write error. reason');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456093, NULL, NULL, 'cisco-ace: appscope_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456094, NULL, NULL, 'cisco-ace: coreserver_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 456095, NULL, NULL, 'cisco-ace: debug_message');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 504001, NULL, NULL, 'cisco-ace: Security context context-name was added to the system');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 504002, NULL, NULL, 'cisco-ace: Security context context-name was removed from the system');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 607001, NULL, NULL, 'cisco-ace: Pre-allocate SIP media secondary channel for ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 607003, NULL, NULL, 'cisco-ace: SIP Classification: Action_type and log SIP message_id ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 608001, NULL, NULL, 'cisco-ace: Pre-allocate Skinny connection_type secondary channel ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 608002, NULL, NULL, 'cisco-ace: Dropping Skinny message for ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 608003, NULL, NULL, 'cisco-ace: Dropping Skinny message for ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 608004, NULL, NULL, 'cisco-ace: Dropping Skinny message for ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 608005, NULL, NULL, 'cisco-ace: Dropping Skinny message for ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 615003, NULL, NULL, 'cisco-ace: VLAN VLAN-number not available for configuring an interface');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 615004, NULL, NULL, 'cisco-ace: VLAN VLAN-number available for configuring an interface');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727001, NULL, NULL, 'cisco-ace: hostname: HA: Peer IP address is not reachable. Error: error str.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727002, NULL, NULL, 'cisco-ace: hostname: HA: FT interface interface name to reach  peer IP address is down. Error: error str');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727003, NULL, NULL, 'cisco-ace: hostname: HA: Mismatch in context names detected for FT group FTgroupID. Cannot be redundant.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727004, NULL, NULL, 'cisco-ace: hostname: HA: Two actives have been detected for FT group FTgroupID. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727005, NULL, NULL, 'cisco-ace: hostname: HA: Config replication failed for context ctx name. Error : error str');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727006, NULL, NULL, 'cisco-ace: hostname: HA: Peer is incompatible due to error str. Cannot be Redundant. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727007, NULL, NULL, 'cisco-ace: hostname: HA: Module Initialization failure - Error Error str. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727008, NULL, NULL, 'cisco-ace: hostname: HA: Failed to send heartbeats to peer.  Internal error: Error str');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727009, NULL, NULL, 'cisco-ace: hostname: HA: Communication failure for Peer Peer id Event: error str');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727010, NULL, NULL, 'cisco-ace: hostname: HA: Data replication failed for context ctx name. Error code error str');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727011, NULL, NULL, 'cisco-ace: HA: Configuration replication for context ctx name will not happen. Error: Error str');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727012, NULL, NULL, 'cisco-ace: hostname: HA: FT Group group ID changed state to NewState. Reason: reason str.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727013, NULL, NULL, 'cisco-ace: hostname: HA: Peer Peer # is UP and reachable.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727014, NULL, NULL, 'cisco-ace: hostname: HA: Heartbeats from Peer Peer id have become unidirectional.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727015, NULL, NULL, 'cisco-ace: hostname: HA: Detected mismatch in heartbeat interval from Peer peer id. Modified interval to interval. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727016, NULL, NULL, 'cisco-ace: hostname: HA: Replication for context ctx name has started. Status - status.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727017, NULL, NULL, 'cisco-ace: hostname: HA: FT Track track type track name is UP.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727018, NULL, NULL, 'cisco-ace: hostname: HA: FT Track track type track name is DOWN. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727019, NULL, NULL, 'cisco-ace: hostname: HA: Started alternate ping to IP address ip addr ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727020, NULL, NULL, 'cisco-ace: hostname: HA: Stopped alternate ping to IP address ip addr. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727021, NULL, NULL, 'cisco-ace: hostname: HA: Peer is compatible.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727022, NULL, NULL, 'cisco-ace: hostname: HA: Started sending heartbeats to peer Peer id interval value and count cnt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 727023, NULL, NULL, 'cisco-ace: hostname: HA: Stopped sending heartbeats to peer Peer id. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728001, NULL, NULL, 'cisco-ace: Initialization failure (general) type variable1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728002, NULL, NULL, 'cisco-ace: Initialization failure (sticky) type variable1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728003, NULL, NULL, 'cisco-ace: Initialization failure (sticky hash) variable1 entries, variable2 min, variable3 max type variable4');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728004, NULL, NULL, 'cisco-ace: Internal communications notice (general) type variable1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728005, NULL, NULL, 'cisco-ace: Failed to transmit variable1 decision for connection from client variable2 type variable3');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728006, NULL, NULL, 'cisco-ace: Internal communications error (messaging) msg subType variable1 -- type variable2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728007, NULL, NULL, 'cisco-ace: Internal configuration communications error (sticky) type variable1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728008, NULL, NULL, 'cisco-ace: Internal communications error (sticky) /source processor variable1 destination processor variable2 -- type variable3');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728009, NULL, NULL, 'cisco-ace: Context ID variable1 requested variable2 of variable3 sticky entries. No action taken. -- type variable4');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728011, NULL, NULL, 'cisco-ace: Context ID variable1 being variable2 should not have variable3 associated sticky groups -- type variable4');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728012, NULL, NULL, 'cisco-ace: Context ID variable1 failed to receive return data -- type variable2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728013, NULL, NULL, 'cisco-ace: A cache alignment error variable1 was detected during initialization -- type variable2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728014, NULL, NULL, 'cisco-ace: Internal cross-processor communications error (sticky) type variable1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728015, NULL, NULL, 'cisco-ace: Internal channel communications error (sticky) type variable1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728016, NULL, NULL, 'cisco-ace: HA data receive failure (type variable1)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728017, NULL, NULL, 'cisco-ace: Internal communications error (ha) -- type variable1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728018, NULL, NULL, 'cisco-ace: Proxy connection variable1 rebalanced to server variable2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728019, NULL, NULL, 'cisco-ace: Sticky resources were not variable1 for this context -- type variable2 ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728020, NULL, NULL, 'cisco-ace: LB is configured to consume variable1 bytes of  memory.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728021, NULL, NULL, 'cisco-ace: Found inconsistent sticky entry.  Terminating variable1.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728022, NULL, NULL, 'cisco-ace: Invalid hash table index (variable1) used for variable2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728023, NULL, NULL, 'cisco-ace: variable1 variable2 sticky entries from ContextId variable3.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728024, NULL, NULL, 'cisco-ace: Received an unknown variable1 type message (variable2) for Sticky from remote IXP variable3!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728025, NULL, NULL, 'cisco-ace: Dropped variable1 variable2 messages (variable3 total) from IXP variable4 to IXP variable5!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728026, NULL, NULL, 'cisco-ace: Attempting to use invalid lookup key for variable1 processing.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728027, NULL, NULL, 'cisco-ace: Received unhandled message of type variable1 from CP SrcSAP variable2.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728028, NULL, NULL, 'cisco-ace: Sticky mapping failed: variable1 variable2');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728029, NULL, NULL, 'cisco-ace: HA state for FtGroup variable1 changed from variable2 to variable3 State variable4.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728030, NULL, NULL, 'cisco-ace: Silently discarding HA data: variable1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 728031, NULL, NULL, 'cisco-ace: Memory mapping for debug logging failed. ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 729001, NULL, NULL, 'cisco-ace: Regular expression config download failed due to out of ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 729002, NULL, NULL, 'cisco-ace: Regex resource usage beyond maximum limit for context ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 729003, NULL, NULL, 'cisco-ace: Minimum regex resources could not be guaranteed for ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 750001, NULL, NULL, 'cisco-ace: Sticky resource usage beyond maximum limit for context ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES ('1653', 750002, NULL, NULL, 'cisco-ace: Minimum sticky resources could not be guaranteed for ');
