DELETE FROM plugin WHERE id = "1673";
DELETE FROM plugin_sid where plugin_id = "1673";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1673, 1, 'extreme-wireless', 'Extreme Wireless');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 10, 1, NULL, NULL, 'Extreme Wireless - Registration Success');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 11, 1, NULL, NULL, 'Extreme Wireless - Registration Failure');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 12, 1, NULL, NULL, 'Extreme Wireless - Wireless Roam');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 20, 1, NULL, NULL, 'Extreme Wireless - De-Registration Success');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 21, 1, NULL, NULL, 'Extreme Wireless - De-Registration Failure');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 22, 1, NULL, NULL, 'Extreme Wireless - Client State Change');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 30, 1, NULL, NULL, 'Extreme Wireless - DHCPACK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 31, 1, NULL, NULL, 'Extreme Wireless - DHCPNAK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 32, 1, NULL, NULL, 'Extreme Wireless - DHCPOFFER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 33, 1, NULL, NULL, 'Extreme Wireless - DHCPREQUEST');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 34, 1, NULL, NULL, 'Extreme Wireless - DHCPDISCOVER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 35, 1, NULL, NULL, 'Extreme Wireless - DHCP Leases Written');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 36, 1, NULL, NULL, 'Extreme Wireless - DHCPREQUEST Error');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 37, 1, NULL, NULL, 'Extreme Wireless - WAP Disconnct');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 38, 1, NULL, NULL, 'Extreme Wireless - Backup Event');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 39, 1, NULL, NULL, 'Extreme Wireless - DHCPINFORM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, reliability, category_id, class_id, name) VALUES (1673, 2000000000, 1, NULL, NULL, 'Extreme Wireless - Generic Event');
