DELETE FROM plugin WHERE id = "1588";
DELETE FROM plugin_sid where plugin_id = "1588";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1588, 1, 'lucent-brick', 'Lucent Brick');

-- For manual plugin additions start at 10001 and work forward. 9999 means "unknown sid"
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 9999, NULL, NULL, 'lucent-brick: Unknown event (Please report at plugins.com)',1,1);
-- Missing plugins
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 53, NULL, NULL, 'lucent-brick: Promon event',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 177, NULL, NULL, 'lucent-brick: Ruleset event',1,1);

-- Session ids
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 10001, NULL, NULL, 'lucent-brick: Pass',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 10002, NULL, NULL, 'lucent-brick: Drop',2,5);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 10003, NULL, NULL, 'lucent-brick: Proxy',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 10004, NULL, NULL, 'lucent-brick: VPN',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 10005, NULL, NULL, 'lucent-brick: VpnProxy',1,1);

-- Conf changes
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 10006, NULL, NULL, 'lucent-brick: Ruleset-init',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 10007, NULL, NULL, 'lucent-brick: Ruleset-modify',1,1);

-- VPN Stuff
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19205, NULL, NULL, 'lucent-brick: Packet requires policy, none configured',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19206, NULL, NULL, 'lucent-brick: Tunnel is up',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19207, NULL, NULL, 'lucent-brick: Tunnel is down',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19208, NULL, NULL, 'lucent-brick: IKE Error',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19209, NULL, NULL, 'lucent-brick: Packet Received on Disabled Tunnel',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19211, NULL, NULL, 'lucent-brick: IKE Error',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19212, NULL, NULL, 'lucent-brick: Rekey complete',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19213, NULL, NULL, 'lucent-brick: Rekey failed',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19214, NULL, NULL, 'lucent-brick: Tunnel initiate failed',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19221, NULL, NULL, 'lucent-brick: IP address added to user group',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19222, NULL, NULL, 'lucent-brick: IP address deleted from user group',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19241, NULL, NULL, 'lucent-brick: Init Phase 1',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19242, NULL, NULL, 'lucent-brick: Init Phase 2',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19243, NULL, NULL, 'lucent-brick: IKE pkt rcvd',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19244, NULL, NULL, 'lucent-brick: IKE pkt sent',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19245, NULL, NULL, 'lucent-brick: IKE pkt rcvd(2)',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19247, NULL, NULL, 'lucent-brick: Notify pkt rcvd',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19248, NULL, NULL, 'lucent-brick: Notify pkt sent',1,1);

-- INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 0, NULL, NULL, 'lucent-brick: Session Start',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 1, NULL, NULL, 'lucent-brick: Session End',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 2, NULL, NULL, 'lucent-brick: Packet Audit',1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 3, NULL, NULL, 'lucent-brick: Session Start Mapped',1,1);

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 4, NULL, NULL, 'lucent-brick: General Brick Event' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 5, NULL, NULL, 'lucent-brick: Errors - Brick and LSMS - See [35]Error Explanations' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 7, NULL, NULL, 'lucent-brick: Failed Admin Host Authentication' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 10, NULL, NULL, 'lucent-brick: Admin Login' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 11, NULL, NULL, 'lucent-brick: Admin Logout' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 12, NULL, NULL, 'lucent-brick: Add Admin Account' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 13, NULL, NULL, 'lucent-brick: Modify Admin Account' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 14, NULL, NULL, 'lucent-brick: Delete Admin Account' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 15, NULL, NULL, 'lucent-brick: Add Zone Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 16, NULL, NULL, 'lucent-brick: Modify Zone Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 17, NULL, NULL, 'lucent-brick: Delete Zone Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 18, NULL, NULL, 'lucent-brick: Add Brick Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 19, NULL, NULL, 'lucent-brick: Modify Brick Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 20, NULL, NULL, 'lucent-brick: Delete Brick Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 21, NULL, NULL, 'lucent-brick: Brick Alarm' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 22, NULL, NULL, 'lucent-brick: LSMS Alarm' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 24, NULL, NULL, 'lucent-brick: Brick Status (LSMS message)' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 25, NULL, NULL, 'lucent-brick: LSMS Subsystem Information Message' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 26, NULL, NULL, 'lucent-brick: Add Zone to LSMS' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 27, NULL, NULL, 'lucent-brick: Delete Zone from LSMS' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 28, NULL, NULL, 'lucent-brick: Modify Zone in the LSMS' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 29, NULL, NULL, 'lucent-brick: Add Brick' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 30, NULL, NULL, 'lucent-brick: Delete Brick' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 31, NULL, NULL, 'lucent-brick: Modify Brick' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 32, NULL, NULL, 'lucent-brick: Audit GUI Request' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 33, NULL, NULL, 'lucent-brick: Audit GUI Request for File Modification' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 34, NULL, NULL, 'lucent-brick: Admin Login Failed' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 35, NULL, NULL, 'lucent-brick: Alarm Alert Status' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 36, NULL, NULL, 'lucent-brick: LSMS Data Object Imported' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 37, NULL, NULL, 'lucent-brick: LSMS Data Object Published' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 38, NULL, NULL, 'lucent-brick: Add Brick Route' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 39, NULL, NULL, 'lucent-brick: Delete Brick Route' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 40, NULL, NULL, 'lucent-brick: Modify Brick Route' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 41, NULL, NULL, 'lucent-brick: Start Brick Upgrade' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 42, NULL, NULL, 'lucent-brick: End Brick Upgrade' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 43, NULL, NULL, 'lucent-brick: ISS RealSecure Event' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 44, NULL, NULL, 'lucent-brick: Add Dynamic SA' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 45, NULL, NULL, 'lucent-brick: Delete Dynamic SA' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 46, NULL, NULL, 'lucent-brick: FTP Log File' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 47, NULL, NULL, 'lucent-brick: Add RS Engine' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 48, NULL, NULL, 'lucent-brick: Delete RS Engine' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 49, NULL, NULL, 'lucent-brick: Modify RS Engine' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 50, NULL, NULL, 'lucent-brick: Duplicate Zone' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 51, NULL, NULL, 'lucent-brick: Start Loading Brick Config' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 52, NULL, NULL, 'lucent-brick: End Loading Brick Config' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 61, NULL, NULL, 'lucent-brick: Add Proxy Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 62, NULL, NULL, 'lucent-brick: Modify Proxy Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 63, NULL, NULL, 'lucent-brick: Delete Proxy Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 64, NULL, NULL, 'lucent-brick: Add User Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 65, NULL, NULL, 'lucent-brick: Modify User Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 66, NULL, NULL, 'lucent-brick: Delete User Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 67, NULL, NULL, 'lucent-brick: Add UserGrp Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 68, NULL, NULL, 'lucent-brick: Modify UserGrp Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 69, NULL, NULL, 'lucent-brick: Delete UserGrp Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 70, NULL, NULL, 'lucent-brick: Add AuthSvc Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 71, NULL, NULL, 'lucent-brick: Modify AuthSvc Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 72, NULL, NULL, 'lucent-brick: Delete AuthSvc Table Entry' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 73, NULL, NULL, 'lucent-brick: Brick SA Info: General' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 74, NULL, NULL, 'lucent-brick: Kill Session' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 75, NULL, NULL, 'lucent-brick: Kill All Sessions' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 76, NULL, NULL, 'lucent-brick: Add VPN Routing Info from Pool' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 79, NULL, NULL, 'lucent-brick: Dynamic Rule' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 80, NULL, NULL, 'lucent-brick: Add Host Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 81, NULL, NULL, 'lucent-brick: Modify Host Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 83, NULL, NULL, 'lucent-brick: Add Service Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 84, NULL, NULL, 'lucent-brick: Modify Service Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 85, NULL, NULL, 'lucent-brick: Delete Service Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 86, NULL, NULL, 'lucent-brick: Add Dependency Mask' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 87, NULL, NULL, 'lucent-brick: Modify Dependency Mask' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 88, NULL, NULL, 'lucent-brick: Delete Dependency Mask' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 89, NULL, NULL, 'lucent-brick: Add Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 90, NULL, NULL, 'lucent-brick: Modify Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 91, NULL, NULL, 'lucent-brick: Delete Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 92, NULL, NULL, 'lucent-brick: VPN Status' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 93, NULL, NULL, 'lucent-brick: Add Router' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 94, NULL, NULL, 'lucent-brick: Modify Router' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 95, NULL, NULL, 'lucent-brick: Delete Router' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 96, NULL, NULL, 'lucent-brick: Add Router Rule Set' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 97, NULL, NULL, 'lucent-brick: Modify Router Rule Set' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 98, NULL, NULL, 'lucent-brick: Delete Router Rule Set' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 99, NULL, NULL, 'lucent-brick: Add Authentication Service' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 100, NULL, NULL, 'lucent-brick: Modify Authentication Service' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 101, NULL, NULL, 'lucent-brick: Delete Authentication Service' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 102, NULL, NULL, 'lucent-brick: Add User Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 103, NULL, NULL, 'lucent-brick: Modify User Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 104, NULL, NULL, 'lucent-brick: Delete User Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 105, NULL, NULL, 'lucent-brick: Add User' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 106, NULL, NULL, 'lucent-brick: Modify User' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 107, NULL, NULL, 'lucent-brick: Delete User' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 111, NULL, NULL, 'lucent-brick: Add LAN-to-LAN Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 112, NULL, NULL, 'lucent-brick: Modify LAN-to-LAN Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 113, NULL, NULL, 'lucent-brick: Modify LAN-to-LAN Tunnel Defaults' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 115, NULL, NULL, 'lucent-brick: Enable LAN-to-LAN Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 116, NULL, NULL, 'lucent-brick: Disable LAN-to-LAN Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 117, NULL, NULL, 'lucent-brick: Delete LAN-to-LAN Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 118, NULL, NULL, 'lucent-brick: Intelligent Cache Management' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 119, NULL, NULL, 'lucent-brick: Add Client Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 120, NULL, NULL, 'lucent-brick: Modify Client Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 121, NULL, NULL, 'lucent-brick: Modify Client Tunnel Defaults' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 122, NULL, NULL, 'lucent-brick: Enable Client Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 123, NULL, NULL, 'lucent-brick: Disable Client Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 124, NULL, NULL, 'lucent-brick: Delete Client Tunnel' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 125, NULL, NULL, 'lucent-brick: LSMS Status' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 126, NULL, NULL, 'lucent-brick: LSMS Refresh' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 128, NULL, NULL, 'lucent-brick: Tunnel Heartbeat Received' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 129, NULL, NULL, 'lucent-brick: Tunnel Heartbeat Missing' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 130, NULL, NULL, 'lucent-brick: List Up Tunnels' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 131, NULL, NULL, 'lucent-brick: LSMS Clock Synchronization' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 132, NULL, NULL, 'lucent-brick: Control Brick' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 133, NULL, NULL, 'lucent-brick: Encapsulation Info' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 134, NULL, NULL, 'lucent-brick: Scan FTP Content Result' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 135, NULL, NULL, 'lucent-brick: Address Translation Tables' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 136, NULL, NULL, 'lucent-brick: Archive Details' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 137, NULL, NULL, 'lucent-brick: QOS Alarm' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 138, NULL, NULL, 'lucent-brick: Add Application Filter' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 139, NULL, NULL, 'lucent-brick: Mod Application Filter' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 140, NULL, NULL, 'lucent-brick: Del Application Filter' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 141, NULL, NULL, 'lucent-brick: List Application Filter' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 142, NULL, NULL, 'lucent-brick: Audit Application Filter Result' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 143, NULL, NULL, 'lucent-brick: Audit Application Filter Exception' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 144, NULL, NULL, 'lucent-brick: TCP Exception' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 145, NULL, NULL, 'lucent-brick: VPN Error' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 146, NULL, NULL, 'lucent-brick: Add Dynamic SA Brick' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 147, NULL, NULL, 'lucent-brick: Del Dynamic SA Brick' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 148, NULL, NULL, 'lucent-brick: Add Domain Name Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 149, NULL, NULL, 'lucent-brick: Mod Domain Name Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 150, NULL, NULL, 'lucent-brick: Del Domain Name Group' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 151, NULL, NULL, 'lucent-brick: Failed TL1 Host Auth' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 152, NULL, NULL, 'lucent-brick: TL1 Login' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 153, NULL, NULL, 'lucent-brick: TL1 Logout' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 154, NULL, NULL, 'lucent-brick: VPN Debug' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 155, NULL, NULL, 'lucent-brick: VPN Tunnel Down' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 156, NULL, NULL, 'lucent-brick: VPN Tunnel Up' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 175, NULL, NULL, 'lucent-brick: Cache Statistics' ,1,1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1588, 176, NULL, NULL, 'lucent-brick: Heartbeats' ,1,1);
