-- plugin_id: 4008
--
-- Plugin sids from McAfee ePO
--
-- Update plugin sid values with the following documentation:
-- https://kc.mcafee.com/corporate/index?page=content&id=KB54677

DELETE FROM plugin WHERE id = "4008";
DELETE FROM plugin_sid where plugin_id = "4008";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (4008, 1, 'mcafee-epo', 'McAfee ePolicy Orchestrator (ePO)');

INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1000, 'McAfee ePO: NetShield service started successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1001, 'McAfee ePO: NetShield service ended successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1002, 'McAfee ePO: Task started successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1003, 'McAfee ePO: Error starting Task', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1004, 'McAfee ePO: Task has completed successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1005, 'McAfee ePO: Error while stopping task', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1024, 'McAfee ePO: Infected file found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1025, 'McAfee ePO: Infected file successfully Cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1026, 'McAfee ePO: Unable to clean infected file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1027, 'McAfee ePO: Infected file deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1028, 'McAfee ePO: Unable to delete infected file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1029, 'McAfee ePO: File to be excluded from scans', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1030, 'McAfee ePO: Unable to exclude item from scans', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1031, 'McAfee ePO: Infected file access denied', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1032, 'McAfee ePO: Infected file was moved to quarantine area', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1033, 'McAfee ePO: Unable to move infected file to quarantine', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1034, 'McAfee ePO: Scan completed. No viruses found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1035, 'McAfee ePO: Scan was cancelled', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1036, 'McAfee ePO: Memory infected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1037, 'McAfee ePO: Infected boot record found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1038, 'McAfee ePO: Scan found infected files', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1039, 'McAfee ePO: Scan found and cleaned infected files', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1040, 'McAfee ePO: Activity Log error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1041, 'McAfee ePO: Scan reports memory allocation error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1042, 'McAfee ePO: Path too long', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1043, 'McAfee ePO: Media is write protected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1044, 'McAfee ePO: Specified media not found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1045, 'McAfee ePO: Specified scan item is invalid', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1046, 'McAfee ePO: File I/O errors', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1047, 'McAfee ePO: Disk I/O errors', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1048, 'McAfee ePO: Scan reports general system error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1049, 'McAfee ePO: Scan reported an internal application error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1050, 'McAfee ePO: Unable to repair password protected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1051, 'McAfee ePO: Unable to scan password protected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1052, 'McAfee ePO: Infected Binder Object', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1053, 'McAfee ePO: Infected file found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1054, 'McAfee ePO: Infected file deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1055, 'McAfee ePO: Unable to delete infected file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1056, 'McAfee ePO: File moved to quarantine', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1057, 'McAfee ePO: Unable to move infected file to quarantine', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1059, 'McAfee ePO: Scan Timed Out', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1060, 'McAfee ePO: Boot sector virus was cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1061, 'McAfee ePO: Error while cleaning boot sector virus', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1062, 'McAfee ePO: Error sending alert', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1063, 'McAfee ePO: Invalid options specified', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1064, 'McAfee ePO: Service was started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1065, 'McAfee ePO: Service ended', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1066, 'McAfee ePO: Task started ok', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1067, 'McAfee ePO: Unable to start scheduled task', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1068, 'McAfee ePO: Scheduled task was stopped', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1069, 'McAfee ePO: Error stopping scheduled task', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1070, 'McAfee ePO: Task was successful', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1071, 'McAfee ePO: Task was cancelled', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1076, 'McAfee ePO: Error logging information', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1077, 'McAfee ePO: Memory allocation error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1086, 'McAfee ePO: Scan Process Error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1087, 'McAfee ePO: On-access Scan started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1088, 'McAfee ePO: On-access scan stopped', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1089, 'McAfee ePO: Scan Settings', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1090, 'McAfee ePO: OAS stopped', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1091, 'McAfee ePO: JavaScript security violation detected and blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1092, 'McAfee ePO: Access Protection rule violation detected and blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1093, 'McAfee ePO: Buffer Overflow detected; Blocked successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1094, 'McAfee ePO: Port blocking rule violation detected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1095, 'McAfee ePO: Access Protection rule violation detected and NOT blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1096, 'McAfee ePO: Antivirus Standard Protection', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1099, 'McAfee ePO: Buffer Overflow detected and NOT blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1100, 'McAfee ePO: Macro Detected in file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1101, 'McAfee ePO: Macro Deleted from file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1118, 'McAfee ePO: The update was successful', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1119, 'McAfee ePO: The update failed; see event log', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1120, 'McAfee ePO: The update is running', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1121, 'McAfee ePO: The update was cancelled', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1122, 'McAfee ePO: The upgrade is running', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1123, 'McAfee ePO: The upgrade failed; see event log', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1124, 'McAfee ePO: The upgrade was cancelled', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1125, 'McAfee ePO: The DAT version was not new enough', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1126, 'McAfee ePO: Scan was cancelled by AutoUpdate of DAT files', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1127, 'McAfee ePO: OAS Scanning Engine Disabled', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1128, 'McAfee ePO: Scan time exceeded', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1129, 'McAfee ePO: Scan shut down by Windows', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1200, 'McAfee ePO: Process started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1201, 'McAfee ePO: Process Ended', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1202, 'McAfee ePO: On-demand scan started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1203, 'McAfee ePO: On Demand scan complete', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1204, 'McAfee ePO: Report OS & Serial', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1270, 'McAfee ePO: file infected. No cleaner available, quarantined successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1271, 'McAfee ePO: file infected. No cleaner available, heuristic detection, quarantined successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1272, 'McAfee ePO: file infected. Undetermined clean error, quarantined successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1273, 'McAfee ePO: file infected. Clean error, Encrypted file, quarantined successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1274, 'McAfee ePO: file infected. No cleaner available, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1275, 'McAfee ePO: file infected. No cleaner available, heuristic detection, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1276, 'McAfee ePO: file infected. Undetermined clean error, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1277, 'McAfee ePO: file infected. Clean error, Encrypted file, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1278, 'McAfee ePO: file infected. No cleaner available, file deleted successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1279, 'McAfee ePO: file infected. No cleaner available, heuristic detection, deleted successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1280, 'McAfee ePO: file infected. Undetermined clean error, deleted successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1281, 'McAfee ePO: file infected. Clean error, Encrypted file, deleted successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1282, 'McAfee ePO: file infected. No cleaner available, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1283, 'McAfee ePO: file infected. Clean error, heuristic detection, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1284, 'McAfee ePO: file infected. Undetermined clean error, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1285, 'McAfee ePO: file infected. Clean error, Encrypted file, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1286, 'McAfee ePO: file infected. No cleaner available, continued scanning (ODS)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1287, 'McAfee ePO: file infected. Clean error, heuristic detection, continued scanning (ODS)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1288, 'McAfee ePO: file infected. Undetermined clean error, continued scanning (ODS)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1289, 'McAfee ePO: file infected. Clean error, Encrypted file, continued scanning (ODS)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1290, 'McAfee ePO: file infected. No cleaner available, OAS denied access and continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1291, 'McAfee ePO: file infected. Clean error, heuristic detection, OAS denied access and continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1292, 'McAfee ePO: file infected. Undetermined clean error, OAS denied access and continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1293, 'McAfee ePO: file infected. Quarantine failed, deleted successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1294, 'McAfee ePO: file infected. Quarantine failed, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1295, 'McAfee ePO: file infected. Move failed, continued scanning (ODS)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1296, 'McAfee ePO: file infected. Move failed, denied access and continued (OAS)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1297, 'McAfee ePO: file infected. Delete failed, quarantined', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1298, 'McAfee ePO: file infected. Delete failed, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1299, 'McAfee ePO: file infected. Delete failed, continued scanning (ODS)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1300, 'McAfee ePO: file infected. Delete failed, denied access and continued (OAS)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1500, 'McAfee ePO: Infected email cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1501, 'McAfee ePO: Infected email quarantined', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1502, 'McAfee ePO: Unable to clean infected mail', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1503, 'McAfee ePO: Infected email detected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1504, 'McAfee ePO: Infected mail item deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1505, 'McAfee ePO: Email content filtered', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1506, 'McAfee ePO: Email content blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1507, 'McAfee ePO: Inbound email suspend for low disk', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1508, 'McAfee ePO: Inbound Mail Resumed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1509, 'McAfee ePO: Startup request successfully processed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1510, 'McAfee ePO: Shutdown request successfully processed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1511, 'McAfee ePO: Warning - abnormal termination!', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1512, 'McAfee ePO: A maximum load condition is occurring!', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1513, 'McAfee ePO: Mail virus quarantined and cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1514, 'McAfee ePO: Mail virus quarantined (not cleaned)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1515, 'McAfee ePO: Infected email has had virus replaced', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1700, 'McAfee ePO: GroupShield Exchange - service started successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1701, 'McAfee ePO: GroupShield Exchange - service ended successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1702, 'McAfee ePO: GroupShield Exchange - File copy has been blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1703, 'McAfee ePO: GroupShield Exchange - Message is infected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1704, 'McAfee ePO: GroupShield Exchange - Message blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1705, 'McAfee ePO: GroupShield Exchange - Infected file found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1706, 'McAfee ePO: GroupShield Exchange - Infected file successfully cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1707, 'McAfee ePO: GroupShield Exchange - Infected file was moved to quarantine area', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1708, 'McAfee ePO: GroupShield Exchange - Scheduled Once Scan Started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1709, 'McAfee ePO: GroupShield Exchange - Scheduled Repeat Event Scan Started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1710, 'McAfee ePO: GroupShield Exchange - Scheduled Scan Finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1711, 'McAfee ePO: GroupShield Exchange - Scheduled Scan Failed To Start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1712, 'McAfee ePO: GroupShield Exchange - Internal Error occurred', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1713, 'McAfee ePO: GroupShield Exchange - On-Demand Scan Started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1714, 'McAfee ePO: GroupShield Exchange - On-Demand Scan Finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1715, 'McAfee ePO: GroupShield Exchange - AV Engine has been stopped', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1716, 'McAfee ePO: GroupShield Exchange - AV Engine has been started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1717, 'McAfee ePO: GroupShield Exchange - An update Failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1718, 'McAfee ePO: GroupShield Exchange - An update has started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1719, 'McAfee ePO: GroupShield Exchange - No update is available', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1720, 'McAfee ePO: GroupShield Exchange - An update was successful', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1721, 'McAfee ePO: GroupShield Exchange - Disk space is low', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1722, 'McAfee ePO: GroupShield Exchange - Infected file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1725, 'McAfee ePO: GroupShield Exchange - Nearly end of designed life', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1726, 'McAfee ePO: GroupShield Exchange - End of designed life reached', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1751, 'McAfee ePO: GroupShield Exchange - Phish detection', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1752, 'McAfee ePO: GroupShield Exchange - Scanner control filtering', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1753, 'McAfee ePO: GroupShield Exchange - Signed mail (digital signature)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1754, 'McAfee ePO: GroupShield Exchange - Encrypted content is found in the mail', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1755, 'McAfee ePO: GroupShield Exchange - Content is found to be corrupted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1756, 'McAfee ePO: GroupShield Exchange - DOS attack such as multiple level of nesting', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1757, 'McAfee ePO: GroupShield Exchange - A password set on an attachment', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1758, 'McAfee ePO: GroupShield Exchange - The attachment is an archive or zip file that is password protected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1759, 'McAfee ePO: GroupShield Exchange - There is partial mime content or some external content', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1760, 'McAfee ePO: GroupShield Exchange - Statistical event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1800, 'McAfee ePO: GroupShield Domino: Task started successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1801, 'McAfee ePO: GroupShield Domino: Error starting task', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1802, 'McAfee ePO: GroupShield Domino: Task has completed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1803, 'McAfee ePO: GroupShield Domino: Error while stopping task', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1804, 'McAfee ePO: GroupShield Domino: File virus found and cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1805, 'McAfee ePO: GroupShield Domino: Infected file successfully quarantined', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1806, 'McAfee ePO: GroupShield Domino: Infected file deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1807, 'McAfee ePO: GroupShield Domino Infected file ignored', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1808, 'McAfee ePO: GroupShield Domino Quarantined a Lotus Script Exception', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1809, 'McAfee ePO: GroupShield Domino Lotus Script Exception found and ignored', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1810, 'McAfee ePO: GroupShield Domino Quarantined a Formula Exception', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1811, 'McAfee ePO: GroupShield Domino Formula Exception found and ignored', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1812, 'McAfee ePO: GroupShield Domino Quarantined a Content Exception', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1813, 'McAfee ePO: GroupShield Domino Content Exception found and ignored', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1814, 'McAfee ePO: GroupShield Domino Unable to read configuration database', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1815, 'McAfee ePO: GroupShield Domino Unable to write to configuration database', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1816, 'McAfee ePO: GroupShield Domino AutoGO update unable to restart task', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1817, 'McAfee ePO: GroupShield Domino AutoGO update failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1818, 'McAfee ePO: GroupShield for Lotus Domino: Attachments Blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1851, 'McAfee ePO: GroupShield Domino - Phish detection', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1852, 'McAfee ePO: GroupShield Domino - Scanner control filtering', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1853, 'McAfee ePO: GroupShield Domino - Signed mail (digital signature)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1854, 'McAfee ePO: GroupShield Domino - Encrypted content is found in the mail', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1855, 'McAfee ePO: GroupShield Domino - Content is found to be corrupted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1856, 'McAfee ePO: GroupShield Domino - DOS attack such as multiple level of nesting', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1857, 'McAfee ePO: GroupShield Domino - A password set on an attachment', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1858, 'McAfee ePO: GroupShield Domino - The attachment is an archive or zip file that is password protected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1859, 'McAfee ePO: GroupShield Domino - There is partial mime content or some external content', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1860, 'McAfee ePO: GroupShield Domino - Statistical event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 1900, 'McAfee ePO: New MIB File Available', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2000, 'McAfee ePO: Infected file found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2001, 'McAfee ePO: Infected file successfully cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2002, 'McAfee ePO: Unable to clean infected file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2003, 'McAfee ePO: Infected file deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2004, 'McAfee ePO: Unable to delete infected file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2005, 'McAfee ePO: File to be excluded from scans', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2006, 'McAfee ePO: Unable to exclude item from scans', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2007, 'McAfee ePO: Infected file access denied', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2008, 'McAfee ePO: Infected file was moved to quarantine area', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2009, 'McAfee ePO: Unable to move infected file to quarantine', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2010, 'McAfee ePO: Centralized Alerting - Infected file found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2011, 'McAfee ePO: Centralized Alerting - Infected file successfully cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2012, 'McAfee ePO: Centralized Alerting - Unable to clean infected file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2013, 'McAfee ePO: Centralized Alerting - Infected file deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2014, 'McAfee ePO: Centralized Alerting - Unable to delete infected file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2015, 'McAfee ePO: Centralized Alerting - File to be excluded from scans', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2016, 'McAfee ePO: Centralized Alerting - Unable to exclude item from scans', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2017, 'McAfee ePO: Centralized Alerting -', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2018, 'McAfee ePO: Centralized Alerting - Infected file was moved to quarantine area', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2019, 'McAfee ePO: Centralized Alerting - Unable to move infected file to quarantine', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2020, 'McAfee ePO: Boot record infection found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2021, 'McAfee ePO: Boot record infection cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2022, 'McAfee ePO: Boot record infection clean error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2023, 'McAfee ePO: New File Virus Found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2024, 'McAfee ePO: New File Virus Found And Deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2025, 'McAfee ePO: New File Virus Found But Move Failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2026, 'McAfee ePO: New File Virus Found And Moved', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2027, 'McAfee ePO: New File Virus Found But Move Failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2028, 'McAfee ePO: MBR Virus Found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2100, 'McAfee ePO: Outbreak Rule Name', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2201, 'McAfee ePO: ePolicy Orchestrator Agent: Failed to install software package', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2202, 'McAfee ePO: ePolicy Orchestrator Agent: Install retry limit reached for software package', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2204, 'McAfee ePO: ePolicy Orchestrator Agent: Insufficient disk space to install software', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2208, 'McAfee ePO: ePolicy Orchestrator Agent: Insufficient disk space to download software', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2216, 'McAfee ePO: ePolicy Orchestrator Agent: Cannot install software due to OS version mismatch', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2232, 'McAfee ePO: ePolicy Orchestrator Agent: Enforce Policy Failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2264, 'McAfee ePO: ePolicy Orchestrator Agent: Property Collection Failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2328, 'McAfee ePO: ePolicy Orchestrator Agent: Enforce Task Failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2401, 'McAfee ePO: Update Successful', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2402, 'McAfee ePO: Update Failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2411, 'McAfee ePO: Deployment Successful', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2412, 'McAfee ePO: Deployment Failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 2413, 'McAfee ePO: Attempt to uninstall ePolicy Orchestrator Agent', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3000, 'McAfee ePO: Scan task completed. No viruses found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3001, 'McAfee ePO: Task was cancelled', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3002, 'McAfee ePO: Virus found in Memory', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3003, 'McAfee ePO: Infected boot record found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3004, 'McAfee ePO: Task found infected files', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3005, 'McAfee ePO: Task found and cleaned infected files', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3006, 'McAfee ePO: Task error while accessing activity log file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3007, 'McAfee ePO: Task reports memory allocation error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3008, 'McAfee ePO: Directory length access error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3009, 'McAfee ePO: Media is write protected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3010, 'McAfee ePO: Specified media not found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3011, 'McAfee ePO: Specified scan item is invalid', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3012, 'McAfee ePO: File I/O errors', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3013, 'McAfee ePO: Disk I/O errors', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3014, 'McAfee ePO: Task reports general system error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3015, 'McAfee ePO: Task reported an internal application error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3016, 'McAfee ePO: Error opening Service Manager', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3017, 'McAfee ePO: Error starting drivers', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3018, 'McAfee ePO: Error occurred starting log subsystem', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3019, 'McAfee ePO: Error obtaining device driver versions', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3020, 'McAfee ePO: Invalid virus signature files', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3021, 'McAfee ePO: Scan engine error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3022, 'McAfee ePO: Initialization error with scan buffer', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3023, 'McAfee ePO: Memory allocation error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3024, 'McAfee ePO: Unknown error reported', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3025, 'McAfee ePO: Error sending new options to device driver', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3026, 'McAfee ePO: Error sending exclude information to the driver', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3027, 'McAfee ePO: Error sending move to folder to the driver', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3028, 'McAfee ePO: Error obtaining log data from device driver', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3029, 'McAfee ePO: Error occurred while enabling driver', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3030, 'McAfee ePO: Error occurred while disabling driver', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3031, 'McAfee ePO: Error while obtaining statistical data from driver', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3032, 'McAfee ePO: Error while trying to open/create activity log file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3033, 'McAfee ePO: Activity log file maximum size reached', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3034, 'McAfee ePO: Unable to write the activity log file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3035, 'McAfee ePO: Error launching a program upon virus infection', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3036, 'McAfee ePO: Error during initialization of the activity log file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3037, 'McAfee ePO: Memory grant unavailable', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3038, 'McAfee ePO: Error writing to log', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3039, 'McAfee ePO: Centralized Alerting - Scan completed. No viruses found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3040, 'McAfee ePO: Centralized Alerting - Scan was cancelled', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3041, 'McAfee ePO: Centralized Alerting - Virus found in Memory', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3042, 'McAfee ePO: Centralized Alerting - Infected boot record found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3043, 'McAfee ePO: Centralized Alerting - Scan found infected files', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3044, 'McAfee ePO: Centralized Alerting - Scan found and cleaned infected files', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3045, 'McAfee ePO: Centralized Alerting - Error while accessing activity log file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3046, 'McAfee ePO: Centralized Alerting - Scan reports memory allocation error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3047, 'McAfee ePO: Centralized Alerting - Directory length access error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3048, 'McAfee ePO: Centralized Alerting - Media is write protected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3049, 'McAfee ePO: Centralized Alerting - Specified media not found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3050, 'McAfee ePO: Centralized Alerting - Specified scan item is invalid', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3051, 'McAfee ePO: Centralized Alerting - File I/O errors', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3052, 'McAfee ePO: Centralized Alerting - Disk I/O errors', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3053, 'McAfee ePO: Centralized Alerting - Scan reports general system error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3054, 'McAfee ePO: Centralized Alerting - Scan reported an internal application error', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 3055, 'McAfee ePO: Error stopping drivers', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 4600, 'McAfee ePO: WebShield - URL Blocked', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 4650, 'McAfee ePO: Detected Spam Email', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 4651, 'McAfee ePO: Spam Email Scanning Statistics', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 4700, 'McAfee ePO: Failed to connect to CMA updater', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 4701, 'McAfee ePO: Failed to connect to CMA scheduler', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 4702, 'McAfee ePO: Failed to save schedule data into CMA', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 8000, 'McAfee ePO: Infected item found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 8500, 'McAfee ePO: Banned item found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 8501, 'McAfee ePO: Encrypted/Corrupted item found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 8502, 'McAfee ePO: Item matched filtering criteria', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 8503, 'McAfee ePO: Item matched spam criteria', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10016, 'McAfee ePO: scan started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10017, 'McAfee ePO: scan finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10018, 'McAfee ePO: Informational Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10029, 'McAfee ePO: scan host started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10030, 'McAfee ePO: scan host finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10031, 'McAfee ePO: module results', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10032, 'McAfee ePO: probe start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10033, 'McAfee ePO: probe stop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10034, 'McAfee ePO: Informational Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10046, 'McAfee ePO: probe results header', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10047, 'McAfee ePO: probe hop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10048, 'McAfee ePO: update start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10049, 'McAfee ePO: update stop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10050, 'McAfee ePO: Informational Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10061, 'McAfee ePO: update results header', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10062, 'McAfee ePO: update download file', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10063, 'McAfee ePO: update installfile', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10064, 'McAfee ePO: crack started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10065, 'McAfee ePO: crack finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10066, 'McAfee ePO: Informational Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10080, 'McAfee ePO: grind start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10081, 'McAfee ePO: grind stop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10082, 'McAfee ePO: Informational Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10094, 'McAfee ePO: smb grind status', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10095, 'McAfee ePO: smb grind result', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10096, 'McAfee ePO: sentry started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10097, 'McAfee ePO: sentry finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10098, 'McAfee ePO: Informational Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10110, 'McAfee ePO: sentry results verbose', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10111, 'McAfee ePO: sentry results non-verbose', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10112, 'McAfee ePO: IDS start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10113, 'McAfee ePO: IDS stop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10114, 'McAfee ePO: Informational Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10127, 'McAfee ePO: IDS testing text', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10128, 'McAfee ePO: Upgrade start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10129, 'McAfee ePO: Upgrade stop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10130, 'McAfee ePO: Informational Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10143, 'McAfee ePO: upgrade results', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10144, 'McAfee ePO: AutoDiscovery start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10145, 'McAfee ePO: AutoDiscovery stop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10157, 'McAfee ePO: AutoDiscovery host started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10158, 'McAfee ePO: AutoDiscovery host finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10159, 'McAfee ePO: AutoDiscovery results', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10160, 'McAfee ePO: ThreatScan start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10161, 'McAfee ePO: ThreatScan stop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10173, 'McAfee ePO: ThreatScan host started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10174, 'McAfee ePO: ThreatScan host finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10175, 'McAfee ePO: ThreatScan results', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10176, 'McAfee ePO: Audit start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10177, 'McAfee ePO: Audit stop', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10189, 'McAfee ePO: Audit host started', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10190, 'McAfee ePO: Audit host finished', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 10191, 'McAfee ePO: Audit results', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 11001, 'McAfee ePO: Intrusion detected (DTFW 7.5.x) or application blocked (DTFW 8.x)', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 11002, 'McAfee ePO: Failed Quarantine check', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 12000, 'McAfee ePO: Rogue System Sensor started successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 12001, 'McAfee ePO: Rogue System Sensor failed to start', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 12002, 'McAfee ePO: Rogue System Sensor stopped', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 13001, 'McAfee ePO: The machine is compliant or non-compliant with rules', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 13002, 'McAfee ePO: System Compliance Profiler rule violation', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 14000, 'McAfee ePO: Entercept IPS Security Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 14500, 'McAfee ePO: Entercept Firewall Event', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16000, 'McAfee ePO: Computers are non-compliant', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16001, 'McAfee ePO: Reserved for future use', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16002, 'McAfee ePO: Master Repository Update succeeded', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16003, 'McAfee ePO: Master Repository Update failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16004, 'McAfee ePO: Distributed Repository Replication succeeded', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16005, 'McAfee ePO: Distributed Repository Replication failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16006, 'McAfee ePO: New Rogue System detected', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16007, 'McAfee ePO: Subnet has become unmonitored by Rogue System Sensor', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16008, 'McAfee ePO: Active Directory Discovery task ran successfully', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16009, 'McAfee ePO: Active Directory Discovery task failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16012, 'McAfee ePO: Active Directory Discovery task added computers', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 16013, 'McAfee ePO: Active Directory Discovery task removed computers', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21024, 'McAfee ePO: Unwanted program found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21025, 'McAfee ePO: Unwanted program successfully cleaned', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21026, 'McAfee ePO: Unable to clean unwanted program', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21027, 'McAfee ePO: Unwanted program deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21028, 'McAfee ePO: Unable to delete unwanted program', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21031, 'McAfee ePO: Unwanted program access denied', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21032, 'McAfee ePO: Unwanted program was moved to quarantine area', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21033, 'McAfee ePO: Unable to move unwanted program to quarantine', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21036, 'McAfee ePO: Unwanted program found in memory', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21054, 'McAfee ePO: Unwanted program deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21055, 'McAfee ePO: Unable to delete unwanted program', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21056, 'McAfee ePO: Unwanted program moved to quarantine', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21057, 'McAfee ePO: Unable to move unwanted program to quarantine', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21270, 'McAfee ePO: Unwanted program quarantined-no cleaner', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21271, 'McAfee ePO: Unwanted program quarantined, Heuristics', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21272, 'McAfee ePO: Unwanted program quarantined, can\'t clean', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21273, 'McAfee ePO: Unwanted program quarantined, encrypted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21274, 'McAfee ePO: Unwanted program not cleaned or quarantined', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21275, 'McAfee ePO: Unwanted program, heuristics, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21276, 'McAfee ePO: Unwanted program, clean error, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21277, 'McAfee ePO: Unwanted program, encrypted, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21278, 'McAfee ePO: Unwanted program, no cleaner, deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21279, 'McAfee ePO: Unwanted program, heuristics, no cleaner, deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21280, 'McAfee ePO: Unwanted program, clean error, deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21281, 'McAfee ePO: Unwanted program, encrypted, deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21282, 'McAfee ePO: Unwanted program, no cleaner, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21283, 'McAfee ePO: Unwanted program, heuristics, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21284, 'McAfee ePO: Unwanted program, clean error, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21285, 'McAfee ePO: Unwanted program, encrypted, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21286, 'McAfee ePO: Unwanted program, no cleaner, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21287, 'McAfee ePO: Unwanted program, heuristics, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21288, 'McAfee ePO: Unwanted program, clean error, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21289, 'McAfee ePO: Unwanted program, encrypted, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21290, 'McAfee ePO: Unwanted program, no cleaner, denied access', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21291, 'McAfee ePO: Unwanted program, heuristics, denied access', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21292, 'McAfee ePO: Unwanted program, clean error, denied access', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21293, 'McAfee ePO: Unwanted program, quarantine failed, deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21294, 'McAfee ePO: Unwanted program, quarantine failed, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21295, 'McAfee ePO: Unwanted program, quarantine failed, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21296, 'McAfee ePO: Unwanted program, quarantine failed, denied access', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21297, 'McAfee ePO: Unwanted program, delete failed, quarantined', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21298, 'McAfee ePO: Unwanted program, delete failed, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21299, 'McAfee ePO: Unwanted program, delete failed, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21300, 'McAfee ePO: Unwanted program, delete failed, denied access', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21400, 'McAfee ePO: User-specified unwanted program found', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21401, 'McAfee ePO: User-specified unwanted program, clean error, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21402, 'McAfee ePO: User-specified unwanted program, clean error, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21403, 'McAfee ePO: User-specified unwanted program, clean error, quarantined', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21404, 'McAfee ePO: User-specified unwanted program, clean error, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21405, 'McAfee ePO: User-specified unwanted program, clean error, deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21406, 'McAfee ePO: User-specified unwanted program was moved to quarantine area', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21407, 'McAfee ePO: User-specified unwanted program, quarantine failed, delete failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21408, 'McAfee ePO: User-specified unwanted program, quarantine failed, deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21409, 'McAfee ePO: User-specified unwanted program, quarantine failed, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21410, 'McAfee ePO: User-specified unwanted program deleted', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21411, 'McAfee ePO: User-specified unwanted program, delete failed, quarantine failed', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21412, 'McAfee ePO: User-specified unwanted program, delete failed, quarantined', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 21413, 'McAfee ePO: User-specified unwanted program, delete failed, continued', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, name, reliability, priority) values (4008, 30000, 'McAfee ePO: Intrusion detected (firewall rule)', 2, 1);

