-- netscreen-firewall
-- plugin_id: 1522

DELETE FROM plugin WHERE id = 1522;
DELETE FROM plugin_sid where plugin_id = 1522;

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1522, 1, 'juniper-netscreen-firewall', 'Juniper Netscreen Firewall');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 1, 'juniper-netscreen-fw: Permit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 2, 'juniper-netscreen-fw: Deny or Reject');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 3, 'juniper-netscreen-fw: SYN flood');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 4, 'juniper-netscreen-fw: Teardrop attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 5, 'juniper-netscreen-fw: Ping of Death');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 6, 'juniper-netscreen-fw: WinNuke attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 7, 'juniper-netscreen-fw: IP spoofing');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 8, 'juniper-netscreen-fw: Source Route IP option');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 9, 'juniper-netscreen-fw: Land attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 10, 'juniper-netscreen-fw: ICMP flood');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 11, 'juniper-netscreen-fw: UDP flood');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 12, 'juniper-netscreen-fw: Port scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 13, 'juniper-netscreen-fw: Address sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 14, 'juniper-netscreen-fw: Malicious URL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 15, 'juniper-netscreen-fw: Src IP session limit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 16, 'juniper-netscreen-fw: SYN fragment');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 17, 'juniper-netscreen-fw: No TCP flag');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 18, 'juniper-netscreen-fw: Unknown protocol');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 19, 'juniper-netscreen-fw: Bad IP option');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 20, 'juniper-netscreen-fw: Dst IP session limit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 21, 'juniper-netscreen-fw: ZIP file blocked');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 22, 'juniper-netscreen-fw: Java applet blocked');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 23, 'juniper-netscreen-fw: EXE file blocked');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 24, 'juniper-netscreen-fw: ActiveX control blocked');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 25, 'juniper-netscreen-fw: ICMP fragment');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 26, 'juniper-netscreen-fw: Large ICMP packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 27, 'juniper-netscreen-fw: SYN and FIN bits');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 28, 'juniper-netscreen-fw: FIN but no ACK bit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 29, 'juniper-netscreen-fw: SYN-ACK-ACK Proxy DoS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 30, 'juniper-netscreen-fw: Fragmented traffic');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 31, 'juniper-netscreen-fw: DNS:EXPLOIT:CLASS-UNKNOWN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 32, 'juniper-netscreen-fw: DNS:EXPLOIT:EMPTY-UDP-MSG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 33, 'juniper-netscreen-fw: DNS:EXPLOIT:EXPLOIT-BIND9-RT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 34, 'juniper-netscreen-fw: DNS:EXPLOIT:POINTER-LOOP attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 35, 'juniper-netscreen-fw: DNS:EXPLOIT:REQUEST-SHORT-MSG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 36, 'juniper-netscreen-fw: DNS:EXPLOIT:TYPE-AXFR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 37, 'juniper-netscreen-fw: DNS:EXPLOIT:TYPE-UNKNOWN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 38, 'juniper-netscreen-fw: DNS:HEADERERROR:INVALID-OPCODE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 39, 'juniper-netscreen-fw: DNS:OVERFLOW:BIN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 40, 'juniper-netscreen-fw: DNS:OVERFLOW:INVALID-LABEL-LEN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 41, 'juniper-netscreen-fw: DNS:OVERFLOW:INVALID-POINTER attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 42, 'juniper-netscreen-fw: DNS:OVERFLOW:NAME-TOO-LONG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 43, 'juniper-netscreen-fw: DNS:OVERFLOW:OVERSIZED-UDP-MSG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 44, 'juniper-netscreen-fw: DNS:OVERFLOW:TOO-LONG-TCP-MSG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 45, 'juniper-netscreen-fw: DNS:REPERR:QCLASS-UNEXP attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 46, 'juniper-netscreen-fw: DNS:REPERR:REP-MISMATCHING-AN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 47, 'juniper-netscreen-fw: DNS:REPERR:REP-MISMATCHING-QD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 48, 'juniper-netscreen-fw: DNS:REPERR:REP-QTYPE-UNEXPECTED attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 49, 'juniper-netscreen-fw: DNS:REPERR:REP-S2C-QUERY attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 50, 'juniper-netscreen-fw: DNS:REPERR:REQ-INVALID-HDR-RD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 51, 'juniper-netscreen-fw: DNS:REQERR:REQ-ANSWERS-IN-QUERY attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 52, 'juniper-netscreen-fw: DNS:REQERR:REQ-C2S-RESPONSE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 53, 'juniper-netscreen-fw: DOS:NETDEV:IOS-HTTPD-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 54, 'juniper-netscreen-fw: DOS:NETDEV:NETWORK-3COM-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 55, 'juniper-netscreen-fw: FTP:COMMAND:PLATFTP-CD-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 56, 'juniper-netscreen-fw: FTP:COMMAND:SITE-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 57, 'juniper-netscreen-fw: FTP:DIRECTORY:DOT-DOT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 58, 'juniper-netscreen-fw: FTP:DIRECTORY:DOT-PCT-20-DOT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 59, 'juniper-netscreen-fw: FTP:EXPLOIT:BOUNCE-ATTACK attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 60, 'juniper-netscreen-fw: FTP:EXPLOIT:ILLEGAL-PORT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 61, 'juniper-netscreen-fw: FTP:EXPLOIT:SYNTAX-ERROR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 62, 'juniper-netscreen-fw: FTP:MS-FTP:ASTERISK attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 63, 'juniper-netscreen-fw: FTP:MS-FTP:STAT-GLOB attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 64, 'juniper-netscreen-fw: FTP:OVERFLOW:BSD-FTPD-MKD-OF attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 65, 'juniper-netscreen-fw: FTP:OVERFLOW:FREEBSD-FTPD-GLOB attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 66, 'juniper-netscreen-fw: FTP:OVERFLOW:LINE_TOO_LONG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 67, 'juniper-netscreen-fw: FTP:OVERFLOW:OPENBSD-X86 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 68, 'juniper-netscreen-fw: FTP:OVERFLOW:PASS_TOO_LONG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 69, 'juniper-netscreen-fw: FTP:OVERFLOW:PATH-LINUX-X86-1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 70, 'juniper-netscreen-fw: FTP:OVERFLOW:PATH-LINUX-X86-2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 71, 'juniper-netscreen-fw: FTP:OVERFLOW:PATH-LINUX-X86-3 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 72, 'juniper-netscreen-fw: FTP:OVERFLOW:PATH-TOO-LONG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 73, 'juniper-netscreen-fw: FTP:OVERFLOW:SITESTRING-2-LONG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 74, 'juniper-netscreen-fw: FTP:OVERFLOW:USERNAME-2-LONG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 75, 'juniper-netscreen-fw: FTP:OVERFLOW:WFTPD-MKD-OVERFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 76, 'juniper-netscreen-fw: FTP:OVERFLOW:WUBSD-SE-RACE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 77, 'juniper-netscreen-fw: FTP:PABLO-FTP:FORMAT-STRING attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 78, 'juniper-netscreen-fw: FTP:PASSWORD:4DGIFTS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 79, 'juniper-netscreen-fw: FTP:PASSWORD:H0TB0X attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 80, 'juniper-netscreen-fw: FTP:PASSWORD:LRKR0X attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 81, 'juniper-netscreen-fw: FTP:PASSWORD:SATORI attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 82, 'juniper-netscreen-fw: FTP:PASSWORD:WH00T attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 83, 'juniper-netscreen-fw: FTP:PROFTP:LOGXFR-OF1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 84, 'juniper-netscreen-fw: FTP:PROFTP:MKD-OVERFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 85, 'juniper-netscreen-fw: FTP:PROFTP:OVERFLOW1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 86, 'juniper-netscreen-fw: FTP:PROFTP:PPC-FS1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 87, 'juniper-netscreen-fw: FTP:PROFTP:PPC-FS2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 88, 'juniper-netscreen-fw: FTP:PROFTP:SIZE-DOS2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 89, 'juniper-netscreen-fw: FTP:PROFTP:USER-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 90, 'juniper-netscreen-fw: FTP:REQERR:LOGIN-FAILED attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 91, 'juniper-netscreen-fw: FTP:REQERR:REQ-INVALID-CMD-SEQ attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 92, 'juniper-netscreen-fw: FTP:REQERR:REQ-MISSING-ARGS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 93, 'juniper-netscreen-fw: FTP:REQERR:REQ-NESTED-REQUEST attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 94, 'juniper-netscreen-fw: FTP:REQERR:REQ-UNKNOWN-CMD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 95, 'juniper-netscreen-fw: FTP:RPLERR:REP-NESTED-REPLY attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 96, 'juniper-netscreen-fw: FTP:WS-FTP:CPWD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 97, 'juniper-netscreen-fw: FTP:WU-FTP:DELE-OF attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 98, 'juniper-netscreen-fw: FTP:WU-FTP:FTPD-BSD-X86 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 99, 'juniper-netscreen-fw: FTP:WU-FTP:GLOBARG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 100, 'juniper-netscreen-fw: FTP:WU-FTP:IREPLY-FS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 101, 'juniper-netscreen-fw: FTP:WU-FTP:LINUX-OF attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 102, 'juniper-netscreen-fw: FTP:WU-FTP:REALPATH-OF attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 103, 'juniper-netscreen-fw: FTP:WU-FTP:REALPATH-OF2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 104, 'juniper-netscreen-fw: HTTP:APACHE:NOSEJOB attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 105, 'juniper-netscreen-fw: HTTP:APACHE:PHP-INVALID-HDR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 106, 'juniper-netscreen-fw: HTTP:APACHE:SCALP attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 107, 'juniper-netscreen-fw: HTTP:BIGBROTHER:DIR-TRAVERSAL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 108, 'juniper-netscreen-fw: HTTP:CGI:ALTAVISTA-TRAVERSAL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 109, 'juniper-netscreen-fw: HTTP:CGI:APPLE-QT-FILEDISC1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 110, 'juniper-netscreen-fw: HTTP:CGI:BNB-SURVEY-REMOTE-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 111, 'juniper-netscreen-fw: HTTP:CGI:BUGZILLA-SEMICOLON attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 112, 'juniper-netscreen-fw: HTTP:CGI:DCFORUM-AZ-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 113, 'juniper-netscreen-fw: HTTP:CGI:FORMMAIL-ENV-VAR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 114, 'juniper-netscreen-fw: HTTP:CGI:HASSAN-DIR-TRAVERSAL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 115, 'juniper-netscreen-fw: HTTP:CGI:HTDIG-INCLUSION attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 116, 'juniper-netscreen-fw: HTTP:CGI:HYPERSEEK-DIR-TRAVERSL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 117, 'juniper-netscreen-fw: HTTP:CGI:INFOSRCH-REMOTE-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 118, 'juniper-netscreen-fw: HTTP:CGI:MOREOVER-CACHE-FEED attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 119, 'juniper-netscreen-fw: HTTP:CGI:TECHNOTE-PRINT-DSCLSR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 120, 'juniper-netscreen-fw: HTTP:CGI:W3-MSQL-CGI attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 121, 'juniper-netscreen-fw: HTTP:CGI:WEBPALS-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 122, 'juniper-netscreen-fw: HTTP:CGI:WEBSPEED-WSMADMIN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 123, 'juniper-netscreen-fw: HTTP:CGI:WEBSPIRS-FILE-DISCLSR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 124, 'juniper-netscreen-fw: HTTP:CGI:YABB-DIR-TRAVERSAL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 125, 'juniper-netscreen-fw: HTTP:CHKP-FW1-PROXY attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 126, 'juniper-netscreen-fw: HTTP:CISCO:IOS-ADMIN-ACCESS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 127, 'juniper-netscreen-fw: HTTP:CISCO:VOIP:PORT-INFO-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 128, 'juniper-netscreen-fw: HTTP:CISCO:VOIP:STREAM-ID-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 129, 'juniper-netscreen-fw: HTTP:COLDFUSION:EXPRCALC-OPNFIL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 130, 'juniper-netscreen-fw: HTTP:DIR:TRAVERSE-DIRECTORY attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 131, 'juniper-netscreen-fw: HTTP:EXPLOIT:AMBIG-CONTENT-LEN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 132, 'juniper-netscreen-fw: HTTP:EXPLOIT:BLAZIX-JSPVIEW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 133, 'juniper-netscreen-fw: HTTP:FRONTPAGE:ADMIN.PWD-REQ attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 134, 'juniper-netscreen-fw: HTTP:FRONTPAGE:FOURDOTS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 135, 'juniper-netscreen-fw: HTTP:FRONTPAGE:SERVICE.PWD-REQ attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 136, 'juniper-netscreen-fw: HTTP:HOSTCTRL:BROWSE-ASP attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 137, 'juniper-netscreen-fw: HTTP:IIS:AD-SERVER-CONFIG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 138, 'juniper-netscreen-fw: HTTP:IIS:ASP-CODEBROWSER-EXAIR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 139, 'juniper-netscreen-fw: HTTP:IIS:BAT-& attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 140, 'juniper-netscreen-fw: HTTP:IIS:COMMAND-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 141, 'juniper-netscreen-fw: HTTP:IIS:COMMAND-EXEC-2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 142, 'juniper-netscreen-fw: HTTP:IIS:DATA-DISCLOSURE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 143, 'juniper-netscreen-fw: HTTP:IIS:DOUBLE-ENCODE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 144, 'juniper-netscreen-fw: HTTP:IIS:FACTO-CMS-SQL-INJ attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 145, 'juniper-netscreen-fw: HTTP:IIS:HEADER-HOST-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 146, 'juniper-netscreen-fw: HTTP:IIS:ISAPI-IDQ-OVERFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 147, 'juniper-netscreen-fw: HTTP:IIS:ISAPI-PRINTER-OVERFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 148, 'juniper-netscreen-fw: HTTP:IIS:MDAC-RDS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 149, 'juniper-netscreen-fw: HTTP:IIS:MDAC-RDS-2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 150, 'juniper-netscreen-fw: HTTP:IIS:NEWDSN-FILE-CREATION attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 151, 'juniper-netscreen-fw: HTTP:IIS:OUTLOOK-WEB-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 152, 'juniper-netscreen-fw: HTTP:IIS:WEBDAV:MALFORMED-REQ1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 153, 'juniper-netscreen-fw: HTTP:IIS:WEBDAV:MALFORMED-REQ2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 154, 'juniper-netscreen-fw: HTTP:INFO-LEAK:VIGNETTE-LEAK attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 155, 'juniper-netscreen-fw: HTTP:INFO-LEAK:WEB-INF-DOT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 156, 'juniper-netscreen-fw: HTTP:IRIX:CGI-BIN-WRAP attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 157, 'juniper-netscreen-fw: HTTP:MISC:HP-PROCURVE-RESET attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 158, 'juniper-netscreen-fw: HTTP:MISC:HTACCESS-ATTEMPT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 159, 'juniper-netscreen-fw: HTTP:NOVELL:NETWARE-CONVERT.BAS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 160, 'juniper-netscreen-fw: HTTP:OREILLY:WIN-C-SMPLE-OVFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 161, 'juniper-netscreen-fw: HTTP:OVERFLOW:CHUNK-LEN-OFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 162, 'juniper-netscreen-fw: HTTP:OVERFLOW:CHUNK-OVERFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 163, 'juniper-netscreen-fw: HTTP:OVERFLOW:CONTENT-OVERFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 164, 'juniper-netscreen-fw: HTTP:OVERFLOW:HEADER attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 165, 'juniper-netscreen-fw: HTTP:OVERFLOW:INV-CHUNK-LEN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 166, 'juniper-netscreen-fw: HTTP:OVERFLOW:PI3WEB-SLASH-OF attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 167, 'juniper-netscreen-fw: HTTP:OVERFLOW:URL-OVERFLOW attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 168, 'juniper-netscreen-fw: HTTP:PHP:ACHIEVO-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 169, 'juniper-netscreen-fw: HTTP:PHP:DFORUM-PHP-INC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 170, 'juniper-netscreen-fw: HTTP:PHP:DOTPROJECT-USERCOOKIE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 171, 'juniper-netscreen-fw: HTTP:PHP:FI-DIR-TRAVERSAL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 172, 'juniper-netscreen-fw: HTTP:PHP:GALLERY-MAL-INCLUDE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 173, 'juniper-netscreen-fw: HTTP:PHP:MANTIS-ARB-EXEC1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 174, 'juniper-netscreen-fw: HTTP:PHP:MANTIS-ARB-EXEC2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 175, 'juniper-netscreen-fw: HTTP:PHP:MLOG-SCREEN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 176, 'juniper-netscreen-fw: HTTP:PHP:PHORUM:ADMIN-PW-CHG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 177, 'juniper-netscreen-fw: HTTP:PHP:PHORUM:READ-ACCESS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 178, 'juniper-netscreen-fw: HTTP:PHP:PHORUM:REMOTE-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 179, 'juniper-netscreen-fw: HTTP:PHP:PHPLIB-REMOTE-EXE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 180, 'juniper-netscreen-fw: HTTP:PHP:PHPNUKE:MODULES-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 181, 'juniper-netscreen-fw: HTTP:PHP:PHPWEB-REMOTE-FILE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 182, 'juniper-netscreen-fw: HTTP:PHP:PMACHINE-INCLUDE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 183, 'juniper-netscreen-fw: HTTP:PHP:POSTNUKE-SQL-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 184, 'juniper-netscreen-fw: HTTP:PHP:REDHAT-PIRANHA-PASSWD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 185, 'juniper-netscreen-fw: HTTP:PHP:VBULL-CAL-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 186, 'juniper-netscreen-fw: HTTP:PHP:WOLTAB-SQL-INJ attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 187, 'juniper-netscreen-fw: HTTP:PHP:YABBSE-PKG-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 188, 'juniper-netscreen-fw: HTTP:PHP:YABBSE-SSI-INCLUDE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 189, 'juniper-netscreen-fw: HTTP:PHP:ZENTRACK-CMD-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 190, 'juniper-netscreen-fw: HTTP:PKG:ALLAIRE-JRUN-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 191, 'juniper-netscreen-fw: HTTP:PKG:DB4WEB-FILE-ACCESS-LIN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 192, 'juniper-netscreen-fw: HTTP:PKG:EWAVE-SERVLET-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 193, 'juniper-netscreen-fw: HTTP:PKG:MOUNTAIN-ORDR-DSCLSR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 194, 'juniper-netscreen-fw: HTTP:PKG:WEBGAIS-REMOTE-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 195, 'juniper-netscreen-fw: HTTP:REQERR:REQ-INVALID-FORMAT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 196, 'juniper-netscreen-fw: HTTP:REQERR:REQ-LONG-UTF8CODE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 197, 'juniper-netscreen-fw: HTTP:REQERR:REQ-MALFORMED-URL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 198, 'juniper-netscreen-fw: HTTP:TOMCAT:JSP-AS-HTML attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 199, 'juniper-netscreen-fw: HTTP:TOMCAT:SERVLET-DEVICE-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 200, 'juniper-netscreen-fw: HTTP:WASD:CONF-ACCESS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 201, 'juniper-netscreen-fw: HTTP:WASD:DIR-TRAV attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 202, 'juniper-netscreen-fw: HTTP:WEBLOGIC:URL-REVEAL-SRC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 203, 'juniper-netscreen-fw: HTTP:WEBLOGIC:WEBROOT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 204, 'juniper-netscreen-fw: HTTP:WEBPLUS:DIR-TRAVERSAL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 205, 'juniper-netscreen-fw: HTTP:WIN-CMD:WIN-RGUEST attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 206, 'juniper-netscreen-fw: HTTP:WIN-CMD:WIN-WGUEST attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 207, 'juniper-netscreen-fw: IMAP:OVERFLOW:COMMAND attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 208, 'juniper-netscreen-fw: IMAP:OVERFLOW:FLAG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 209, 'juniper-netscreen-fw: IMAP:OVERFLOW:IMAP4-LSUB-OF attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 210, 'juniper-netscreen-fw: IMAP:OVERFLOW:LINE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 211, 'juniper-netscreen-fw: IMAP:OVERFLOW:MAILBOX attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 212, 'juniper-netscreen-fw: IMAP:OVERFLOW:PASS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 213, 'juniper-netscreen-fw: IMAP:OVERFLOW:REFERENCE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 214, 'juniper-netscreen-fw: IMAP:OVERFLOW:TAG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 215, 'juniper-netscreen-fw: IMAP:OVERFLOW:USER attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 216, 'juniper-netscreen-fw: IMAP:REQERR:LOGIN-FAILED attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 217, 'juniper-netscreen-fw: IMAP:REQERR:REQ-INVALID-STATE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 218, 'juniper-netscreen-fw: IMAP:REQERR:REQ-INVALID-TAG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 219, 'juniper-netscreen-fw: IMAP:REQERR:REQ-UNEXPECTED-ARG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 220, 'juniper-netscreen-fw: POP3:DOS:MDAEMON-POP-DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 221, 'juniper-netscreen-fw: POP3:OVERFLOW:APOP attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 222, 'juniper-netscreen-fw: POP3:OVERFLOW:COMMAND attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 223, 'juniper-netscreen-fw: POP3:OVERFLOW:LINE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 224, 'juniper-netscreen-fw: POP3:OVERFLOW:PASS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 225, 'juniper-netscreen-fw: POP3:OVERFLOW:QPOP-OF1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 226, 'juniper-netscreen-fw: POP3:OVERFLOW:QPOP-OF2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 227, 'juniper-netscreen-fw: POP3:OVERFLOW:QPOP-OF3 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 228, 'juniper-netscreen-fw: POP3:OVERFLOW:QPOP-OF4 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 229, 'juniper-netscreen-fw: POP3:OVERFLOW:USER attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 230, 'juniper-netscreen-fw: POP3:REQERR:LOGIN-FAILED attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 231, 'juniper-netscreen-fw: POP3:REQERR:REQ-INVALID-STATE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 232, 'juniper-netscreen-fw: POP3:REQERR:REQ-MESSAGE-NUMBER attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 233, 'juniper-netscreen-fw: POP3:REQERR:REQ-NESTED-REQUEST attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 234, 'juniper-netscreen-fw: POP3:REQERR:REQ-SYNTAX-ERROR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 235, 'juniper-netscreen-fw: POP3:REQERR:REQ-UNKNOWN-CMD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 236, 'juniper-netscreen-fw: SHELLCODE:AIX:NOOP-PKT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 237, 'juniper-netscreen-fw: SHELLCODE:BSDX86:GEN-1-PKT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 238, 'juniper-netscreen-fw: SHELLCODE:BSDX86:GEN-2-PKT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 239, 'juniper-netscreen-fw: SHELLCODE:DIGITAL:NOOP-PKT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 240, 'juniper-netscreen-fw: SHELLCODE:HP-UX:HP-NOOP-1-PKT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 241, 'juniper-netscreen-fw: SHELLCODE:HP-UX:HP-NOOP-2-PKT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 242, 'juniper-netscreen-fw: SMTP:COMMAND:DEBUG attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 243, 'juniper-netscreen-fw: SMTP:COMMAND:ETRN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 244, 'juniper-netscreen-fw: SMTP:COMMAND:EXPN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 245, 'juniper-netscreen-fw: SMTP:COMMAND:SMTP-VRFY-CMD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 246, 'juniper-netscreen-fw: SMTP:COMMAND:TURN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 247, 'juniper-netscreen-fw: SMTP:COMMAND:VRFY attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 248, 'juniper-netscreen-fw: SMTP:COMMAND:WIZ attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 249, 'juniper-netscreen-fw: SMTP:EMAIL:HEADER-FROM-PIPE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 250, 'juniper-netscreen-fw: SMTP:EMAIL:HEADER-TO-PIPE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 251, 'juniper-netscreen-fw: SMTP:EMAIL:MAIL-FROM-PIPE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 252, 'juniper-netscreen-fw: SMTP:EMAIL:RCPT-TO-DECODE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 253, 'juniper-netscreen-fw: SMTP:EMAIL:RCPT-TO-PIPE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 254, 'juniper-netscreen-fw: SMTP:EMAIL:REPLY-TO-PIPE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 255, 'juniper-netscreen-fw: SMTP:EXCHANGE:DOS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 256, 'juniper-netscreen-fw: SMTP:MAJORDOMO:COMMAND-EXEC attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 257, 'juniper-netscreen-fw: SMTP:MSSQL-WORM-EMAIL attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 258, 'juniper-netscreen-fw: SMTP:OVERFLOW:COMMAND-LINE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 259, 'juniper-netscreen-fw: SMTP:OVERFLOW:EMAIL-ADDRESS attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 260, 'juniper-netscreen-fw: SMTP:OVERFLOW:EMAIL-DOMAIN attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 261, 'juniper-netscreen-fw: SMTP:OVERFLOW:EMAIL-USERNAME attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 262, 'juniper-netscreen-fw: SMTP:OVERFLOW:OUTLOOK-CERT-OF attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 263, 'juniper-netscreen-fw: SMTP:OVERFLOW:REPLY-LINE attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 264, 'juniper-netscreen-fw: SMTP:OVERFLOW:SENDMAIL-CMT-OF1 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 265, 'juniper-netscreen-fw: SMTP:OVERFLOW:SENDMAIL-CMT-OF2 attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 266, 'juniper-netscreen-fw: SMTP:OVERFLOW:TOO-MANY-RCPT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 267, 'juniper-netscreen-fw: SMTP:REPERR:REP-INVALID-REPLY attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 268, 'juniper-netscreen-fw: SMTP:REPERR:REP-NESTED-REPLY attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 269, 'juniper-netscreen-fw: SMTP:REQERR:REQ-INVALID-CMD-SEQ attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 270, 'juniper-netscreen-fw: SMTP:REQERR:REQ-NESTED-REQUEST attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 271, 'juniper-netscreen-fw: SMTP:REQERR:REQ-SYNTAX-ERROR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 272, 'juniper-netscreen-fw: SMTP:REQERR:REQ-UNKNOWN-CMD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 273, 'juniper-netscreen-fw: SMTP:RESPONSE:PIPE-FAILED attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 274, 'juniper-netscreen-fw: SMTP:SENDMAIL:ADDR-PRESCAN-ATK attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 275, 'juniper-netscreen-fw: SMTP:SENDMAIL:SENDMAIL-FF-OF attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 276, 'juniper-netscreen-fw: TROJAN:QAZ:TCP25-CALLING-HOME attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 277, 'juniper-netscreen-fw: WORM:CODERED-2:CMD-BACKDOOR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 278, 'juniper-netscreen-fw: WORM:CODERED-2:INFECT-ATTEMPT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 279, 'juniper-netscreen-fw: WORM:CODERED-2:ROOT-BACKDOOR attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 280, 'juniper-netscreen-fw: WORM:NIMDA:BIN-255-CMD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 281, 'juniper-netscreen-fw: WORM:NIMDA:MSADC-ROOT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 282, 'juniper-netscreen-fw: WORM:NIMDA:SCRIPTS-C11C-CMD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 283, 'juniper-netscreen-fw: WORM:NIMDA:SCRIPTS-CMD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 284, 'juniper-netscreen-fw: WORM:NIMDA:SCRIPTS-ROOT attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 285, 'juniper-netscreen-fw: unknown');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 286, 'juniper-netscreen-fw: Remote admin user logged on');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 287, 'juniper-netscreen-fw: Remote admin user logged out');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 288, 'juniper-netscreen-fw: Remote admin logging attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 289, 'juniper-netscreen-fw: Multiple login failures');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 290, 'juniper-netscreen-fw: Detected an IP conflict');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 291, 'juniper-netscreen-fw: Tunnel Connection');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 1000, 'juniper-netscreen-fw: Permit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 1001, 'juniper-netscreen-fw: Deny or Reject');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 2000, 'juniper-netscreen-fw: Admin user logged on');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 2001, 'juniper-netscreen-fw: Admin user logged out');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 2002, 'juniper-netscreen-fw: Admin user login failed');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 2003, 'juniper-netscreen-fw: Multiple login failures');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 3000, 'juniper-netscreen-fw: AV: VIRUS FOUND');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 3001, 'juniper-netscreen-fw: System clock was changed');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 3002, 'juniper-netscreen-fw: System clock was Update');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 4000, 'juniper-netscreen-fw: BGP Peer changed to Idle');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 4001, 'juniper-netscreen-fw: Routing event');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 5000, 'juniper-netscreen-fw: SNMP reply');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 5001, 'juniper-netscreen-fw: SNMP request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 6000, 'juniper-netscreen-fw: System clock updated');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 6001, 'juniper-netscreen-fw: System clock changed');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 6002, 'juniper-netscreen-fw: System event');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 7000, 'juniper-netscreen-fw: Invalid route');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 8000, 'juniper-netscreen-fw: Exploit detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 9000, 'juniper-netscreen-fw: IP conflict detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 10000, 'juniper-netscreen-fw: Syslog enabled');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 10001, 'juniper-netscreen-fw: Syslog disabled');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 10002, 'juniper-netscreen-fw: Syslog removed');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 10003, 'juniper-netscreen-fw: Syslog added');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 10004, 'juniper-netscreen-fw: Syslog changed');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 10005, 'juniper-netscreen-fw: Syslog message levels cleared');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1522, 11000, 'juniper-netscreen-fw: System configuration saved');
