-- ntop
-- plugin_id: 2005

DELETE FROM plugin WHERE id = "2005";
DELETE FROM plugin_sid where plugin_id = "2005";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (2005, 2, 'ntop', 'NTop');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 1, NULL, NULL, 'ntop-monitor: firstSeen');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 2, NULL, NULL, 'ntop-monitor: lastSeen');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 3, NULL, NULL, 'ntop-monitor: minTTL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 4, NULL, NULL, 'ntop-monitor: maxTTL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 5, NULL, NULL, 'ntop-monitor: pktSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 6, NULL, NULL, 'ntop-monitor: pktRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 7, NULL, NULL, 'ntop-monitor: bytesSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 8, NULL, NULL, 'ntop-monitor: bytesRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 9, NULL, NULL, 'ntop-monitor: pktDuplicatedAckSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 10, NULL, NULL, 'ntop-monitor: pktDuplicatedAckRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 11, NULL, NULL, 'ntop-monitor: pktBroadcastSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 12, NULL, NULL, 'ntop-monitor: bytesMulticastSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 13, NULL, NULL, 'ntop-monitor: pktMulticastSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 14, NULL, NULL, 'ntop-monitor: bytesMulticastRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 15, NULL, NULL, 'ntop-monitor: pktMulticastRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 16, NULL, NULL, 'ntop-monitor: bytesSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 17, NULL, NULL, 'ntop-monitor: bytesSentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 18, NULL, NULL, 'ntop-monitor: bytesSentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 19, NULL, NULL, 'ntop-monitor: bytesRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 20, NULL, NULL, 'ntop-monitor: bytesRcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 21, NULL, NULL, 'ntop-monitor: bytesRcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 22, NULL, NULL, 'ntop-monitor: actualRcvdThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 23, NULL, NULL, 'ntop-monitor: lastHourRcvdThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 24, NULL, NULL, 'ntop-monitor: averageRcvdThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 25, NULL, NULL, 'ntop-monitor: peakRcvdThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 26, NULL, NULL, 'ntop-monitor: actualSentThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 27, NULL, NULL, 'ntop-monitor: lastHourSentThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 28, NULL, NULL, 'ntop-monitor: averageSentThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 29, NULL, NULL, 'ntop-monitor: peakSentThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 30, NULL, NULL, 'ntop-monitor: actualTThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 31, NULL, NULL, 'ntop-monitor: averageTThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 32, NULL, NULL, 'ntop-monitor: peakTThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 33, NULL, NULL, 'ntop-monitor: actualRcvdPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 34, NULL, NULL, 'ntop-monitor: averageRcvdPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 35, NULL, NULL, 'ntop-monitor: peakRcvdPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 36, NULL, NULL, 'ntop-monitor: actualSentPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 37, NULL, NULL, 'ntop-monitor: averageSentPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 38, NULL, NULL, 'ntop-monitor: peakSentPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 39, NULL, NULL, 'ntop-monitor: actualTPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 40, NULL, NULL, 'ntop-monitor: averageTPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 41, NULL, NULL, 'ntop-monitor: peakTPktThpt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 42, NULL, NULL, 'ntop-monitor: ipBytesSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 43, NULL, NULL, 'ntop-monitor: ipBytesRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 44, NULL, NULL, 'ntop-monitor: tcpBytesSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 45, NULL, NULL, 'ntop-monitor: tcpBytesRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 46, NULL, NULL, 'ntop-monitor: udpBytesSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 47, NULL, NULL, 'ntop-monitor: udpBytesRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 48, NULL, NULL, 'ntop-monitor: icmpSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 49, NULL, NULL, 'ntop-monitor: icmpRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 50, NULL, NULL, 'ntop-monitor: tcpSentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 51, NULL, NULL, 'ntop-monitor: udpSentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 52, NULL, NULL, 'ntop-monitor: udpSentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 53, NULL, NULL, 'ntop-monitor: ospfSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 54, NULL, NULL, 'ntop-monitor: igmpSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 55, NULL, NULL, 'ntop-monitor: tcpRcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 56, NULL, NULL, 'ntop-monitor: tcpRcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 57, NULL, NULL, 'ntop-monitor: udpRcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 58, NULL, NULL, 'ntop-monitor: udpRcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 59, NULL, NULL, 'ntop-monitor: ospfRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 60, NULL, NULL, 'ntop-monitor: igmpRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 61, NULL, NULL, 'ntop-monitor: tcpFragmentsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 62, NULL, NULL, 'ntop-monitor: tcpFragmentsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 63, NULL, NULL, 'ntop-monitor: udpFragmentsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 64, NULL, NULL, 'ntop-monitor: udpFragmentsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 65, NULL, NULL, 'ntop-monitor: icmpFragmentsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 66, NULL, NULL, 'ntop-monitor: icmpFragmentsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 67, NULL, NULL, 'ntop-monitor: stpSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 68, NULL, NULL, 'ntop-monitor: stpRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 69, NULL, NULL, 'ntop-monitor: ipxSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 70, NULL, NULL, 'ntop-monitor: ipxRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 71, NULL, NULL, 'ntop-monitor: osiSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 72, NULL, NULL, 'ntop-monitor: osiRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 73, NULL, NULL, 'ntop-monitor: dlcSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 74, NULL, NULL, 'ntop-monitor: dlcRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 75, NULL, NULL, 'ntop-monitor: arp_rarpSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 76, NULL, NULL, 'ntop-monitor: arp_rarpRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 77, NULL, NULL, 'ntop-monitor: arpReqPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 78, NULL, NULL, 'ntop-monitor: arpReplyPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 79, NULL, NULL, 'ntop-monitor: arpReplyPktsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 80, NULL, NULL, 'ntop-monitor: decnetSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 81, NULL, NULL, 'ntop-monitor: decnetRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 82, NULL, NULL, 'ntop-monitor: appletalkSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 83, NULL, NULL, 'ntop-monitor: appletalkRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 84, NULL, NULL, 'ntop-monitor: netbiosSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 85, NULL, NULL, 'ntop-monitor: netbiosRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 86, NULL, NULL, 'ntop-monitor: ipv6Sent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 87, NULL, NULL, 'ntop-monitor: ipv6Rcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 88, NULL, NULL, 'ntop-monitor: otherSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 89, NULL, NULL, 'ntop-monitor: otherRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 90, NULL, NULL, 'ntop-monitor: securityPkts synPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 91, NULL, NULL, 'ntop-monitor: securityPkts synPktsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 92, NULL, NULL, 'ntop-monitor: securityPkts rstPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 93, NULL, NULL, 'ntop-monitor: securityPkts rstPktsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 94, NULL, NULL, 'ntop-monitor: securityPkts rstAckPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 95, NULL, NULL, 'ntop-monitor: securityPkts rstAckPktsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 96, NULL, NULL, 'ntop-monitor: securityPkts synFinPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 97, NULL, NULL, 'ntop-monitor: securityPkts synFinPktsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 98, NULL, NULL, 'ntop-monitor: securityPkts finPushUrgPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 99, NULL, NULL, 'ntop-monitor: securityPkts finPushUrgPktsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 100, NULL, NULL, 'ntop-monitor: securityPkts nullPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 101, NULL, NULL, 'ntop-monitor: securityPkts nullPktsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 102, NULL, NULL, 'ntop-monitor: securityPkts ackScanSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 103, NULL, NULL, 'ntop-monitor: securityPkts ackScanRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 104, NULL, NULL, 'ntop-monitor: securityPkts xmasScanSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 105, NULL, NULL, 'ntop-monitor: securityPkts xmasScanRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 106, NULL, NULL, 'ntop-monitor: securityPkts finScanSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 107, NULL, NULL, 'ntop-monitor: securityPkts finScanRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 108, NULL, NULL, 'ntop-monitor: securityPkts nullScanSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 109, NULL, NULL, 'ntop-monitor: securityPkts nullScanRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 110, NULL, NULL, 'ntop-monitor: securityPkts rejectedTCPConnSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 111, NULL, NULL, 'ntop-monitor: securityPkts rejectedTCPConnRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 112, NULL, NULL, 'ntop-monitor: securityPkts establishedTCPConnSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 113, NULL, NULL, 'ntop-monitor: securityPkts establishedTCPConnRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 114, NULL, NULL, 'ntop-monitor: securityPkts terminatedTCPConnServer');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 115, NULL, NULL, 'ntop-monitor: securityPkts terminatedTCPConnClient');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 116, NULL, NULL, 'ntop-monitor: securityPkts udpToClosedPortSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 117, NULL, NULL, 'ntop-monitor: securityPkts udpToClosedPortRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 118, NULL, NULL, 'ntop-monitor: securityPkts udpToDiagnosticPortSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 119, NULL, NULL, 'ntop-monitor: securityPkts udpToDiagnosticPortRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 120, NULL, NULL, 'ntop-monitor: securityPkts tcpToDiagnosticPortSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 121, NULL, NULL, 'ntop-monitor: securityPkts tcpToDiagnosticPortRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 122, NULL, NULL, 'ntop-monitor: securityPkts tinyFragmentSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 123, NULL, NULL, 'ntop-monitor: securityPkts tinyFragmentRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 124, NULL, NULL, 'ntop-monitor: securityPkts icmpFragmentSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 125, NULL, NULL, 'ntop-monitor: securityPkts icmpFragmentRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 126, NULL, NULL, 'ntop-monitor: securityPkts overlappingFragmentSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 127, NULL, NULL, 'ntop-monitor: securityPkts overlappingFragmentRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 128, NULL, NULL, 'ntop-monitor: securityPkts closedEmptyTCPConnSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 129, NULL, NULL, 'ntop-monitor: securityPkts closedEmptyTCPConnRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 130, NULL, NULL, 'ntop-monitor: securityPkts icmpPortUnreachSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 131, NULL, NULL, 'ntop-monitor: securityPkts icmpPortUnreachRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 132, NULL, NULL, 'ntop-monitor: securityPkts icmpHostNetUnreachSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 133, NULL, NULL, 'ntop-monitor: securityPkts icmpProtocolUnreachSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 134, NULL, NULL, 'ntop-monitor: securityPkts icmpProtocolUnreachRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 135, NULL, NULL, 'ntop-monitor: securityPkts icmpHostNetUnreachRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 136, NULL, NULL, 'ntop-monitor: securityPkts icmpAdminProhibitedSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 137, NULL, NULL, 'ntop-monitor: securityPkts icmpAdminProhibitedRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 138, NULL, NULL, 'ntop-monitor: securityPkts malformedPktsSent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 139, NULL, NULL, 'ntop-monitor: securityPkts malformedPktsRcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 140, NULL, NULL, 'ntop-monitor: IP FTP sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 141, NULL, NULL, 'ntop-monitor: IP FTP sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 142, NULL, NULL, 'ntop-monitor: IP FTP rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 143, NULL, NULL, 'ntop-monitor: IP FTP rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 144, NULL, NULL, 'ntop-monitor: IP HTTP sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 145, NULL, NULL, 'ntop-monitor: IP HTTP sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 146, NULL, NULL, 'ntop-monitor: IP HTTP rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 147, NULL, NULL, 'ntop-monitor: IP HTTP rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 148, NULL, NULL, 'ntop-monitor: IP DNS sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 149, NULL, NULL, 'ntop-monitor: IP DNS sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 150, NULL, NULL, 'ntop-monitor: IP DNS rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 151, NULL, NULL, 'ntop-monitor: IP DNS rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 152, NULL, NULL, 'ntop-monitor: IP Telnet sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 153, NULL, NULL, 'ntop-monitor: IP Telnet sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 154, NULL, NULL, 'ntop-monitor: IP Telnet rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 155, NULL, NULL, 'ntop-monitor: IP Telnet rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 156, NULL, NULL, 'ntop-monitor: IP NBios-IP sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 157, NULL, NULL, 'ntop-monitor: IP NBios-IP sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 158, NULL, NULL, 'ntop-monitor: IP NBios-IP rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 159, NULL, NULL, 'ntop-monitor: IP NBios-IP rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 160, NULL, NULL, 'ntop-monitor: IP Mail sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 161, NULL, NULL, 'ntop-monitor: IP Mail sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 162, NULL, NULL, 'ntop-monitor: IP Mail rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 163, NULL, NULL, 'ntop-monitor: IP Mail rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 164, NULL, NULL, 'ntop-monitor: IP DHCP-BOOTP sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 165, NULL, NULL, 'ntop-monitor: IP DHCP-BOOTP sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 166, NULL, NULL, 'ntop-monitor: IP DHCP-BOOTP rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 167, NULL, NULL, 'ntop-monitor: IP DHCP-BOOTP rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 168, NULL, NULL, 'ntop-monitor: IP SNMP sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 169, NULL, NULL, 'ntop-monitor: IP SNMP sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 170, NULL, NULL, 'ntop-monitor: IP SNMP rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 171, NULL, NULL, 'ntop-monitor: IP SNMP rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 172, NULL, NULL, 'ntop-monitor: IP NNTP sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 173, NULL, NULL, 'ntop-monitor: IP NNTP sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 174, NULL, NULL, 'ntop-monitor: IP NNTP rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 175, NULL, NULL, 'ntop-monitor: IP NNTP rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 176, NULL, NULL, 'ntop-monitor: IP NFS sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 177, NULL, NULL, 'ntop-monitor: IP NFS sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 178, NULL, NULL, 'ntop-monitor: IP NFS rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 179, NULL, NULL, 'ntop-monitor: IP NFS rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 180, NULL, NULL, 'ntop-monitor: IP X11 sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 181, NULL, NULL, 'ntop-monitor: IP X11 sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 182, NULL, NULL, 'ntop-monitor: IP X11 rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 183, NULL, NULL, 'ntop-monitor: IP X11 rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 184, NULL, NULL, 'ntop-monitor: IP SSH sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 185, NULL, NULL, 'ntop-monitor: IP SSH sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 186, NULL, NULL, 'ntop-monitor: IP SSH rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 187, NULL, NULL, 'ntop-monitor: IP SSH rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 188, NULL, NULL, 'ntop-monitor: IP Gnutella sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 189, NULL, NULL, 'ntop-monitor: IP Gnutella sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 190, NULL, NULL, 'ntop-monitor: IP Gnutella rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 191, NULL, NULL, 'ntop-monitor: IP Gnutella rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 192, NULL, NULL, 'ntop-monitor: IP Kazaa sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 193, NULL, NULL, 'ntop-monitor: IP Kazaa sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 194, NULL, NULL, 'ntop-monitor: IP Kazaa rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 195, NULL, NULL, 'ntop-monitor: IP Kazaa rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 196, NULL, NULL, 'ntop-monitor: IP WinMX sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 197, NULL, NULL, 'ntop-monitor: IP WinMX sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 198, NULL, NULL, 'ntop-monitor: IP WinMX rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 199, NULL, NULL, 'ntop-monitor: IP WinMX rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 200, NULL, NULL, 'ntop-monitor: IP DirectConnect sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 201, NULL, NULL, 'ntop-monitor: IP DirectConnect sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 202, NULL, NULL, 'ntop-monitor: IP DirectConnect rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 203, NULL, NULL, 'ntop-monitor: IP DirectConnect rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 204, NULL, NULL, 'ntop-monitor: IP eDonkey sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 205, NULL, NULL, 'ntop-monitor: IP eDonkey sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 206, NULL, NULL, 'ntop-monitor: IP eDonkey rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 207, NULL, NULL, 'ntop-monitor: IP eDonkey rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 208, NULL, NULL, 'ntop-monitor: IP Messenger sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 209, NULL, NULL, 'ntop-monitor: IP Messenger sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 210, NULL, NULL, 'ntop-monitor: IP Messenger rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 211, NULL, NULL, 'ntop-monitor: IP Messenger rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 212, NULL, NULL, 'ntop-monitor: IP PROXY sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 213, NULL, NULL, 'ntop-monitor: IP PROXY sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 214, NULL, NULL, 'ntop-monitor: IP PROXY rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 215, NULL, NULL, 'ntop-monitor: IP PROXY rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 216, NULL, NULL, 'ntop-monitor: IP NEWS sentLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 217, NULL, NULL, 'ntop-monitor: IP NEWS sentRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 218, NULL, NULL, 'ntop-monitor: IP NEWS rcvdLoc');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 219, NULL, NULL, 'ntop-monitor: IP NEWS rcvdFromRem');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 220, NULL, NULL, 'ntop-monitor: ICMP SENT_ECHO');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 221, NULL, NULL, 'ntop-monitor: ICMP SENT_ECHOREPLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 222, NULL, NULL, 'ntop-monitor: ICMP SENT_UNREACH');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 223, NULL, NULL, 'ntop-monitor: ICMP SENT_ROUTERADVERT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 224, NULL, NULL, 'ntop-monitor: ICMP SENT_TMXCEED');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 225, NULL, NULL, 'ntop-monitor: ICMP SENT_PARAMPROB');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 226, NULL, NULL, 'ntop-monitor: ICMP SENT_MASKREPLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 227, NULL, NULL, 'ntop-monitor: ICMP SENT_MASKREQ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 228, NULL, NULL, 'ntop-monitor: ICMP SENT_INFO_REQUEST');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 229, NULL, NULL, 'ntop-monitor: ICMP SENT_INFO_REPLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 230, NULL, NULL, 'ntop-monitor: ICMP SENT_TIMESTAMP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 231, NULL, NULL, 'ntop-monitor: ICMP SENT_TIMESTAMPREPLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 232, NULL, NULL, 'ntop-monitor: ICMP SENT_SOURCE_QUENCH');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 233, NULL, NULL, 'ntop-monitor: ICMP RCVD_ECHO');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 234, NULL, NULL, 'ntop-monitor: ICMP RCVD_ECHOREPLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 235, NULL, NULL, 'ntop-monitor: ICMP RCVD_UNREACH');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 236, NULL, NULL, 'ntop-monitor: ICMP RCVD_ROUTERADVERT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 237, NULL, NULL, 'ntop-monitor: ICMP RCVD_TMXCEED');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 238, NULL, NULL, 'ntop-monitor: ICMP RCVD_PARAMPROB');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 239, NULL, NULL, 'ntop-monitor: ICMP RCVD_MASKREPLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 240, NULL, NULL, 'ntop-monitor: ICMP RCVD_MASKREQ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 241, NULL, NULL, 'ntop-monitor: ICMP RCVD_INFO_REQUEST');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 242, NULL, NULL, 'ntop-monitor: ICMP RCVD_INFO_REPLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 243, NULL, NULL, 'ntop-monitor: ICMP RCVD_TIMESTAMP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 244, NULL, NULL, 'ntop-monitor: ICMP RCVD_TIMESTAMPREPLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 245, NULL, NULL, 'ntop-monitor: ICMP RCVD_SOURCE_QUENCH');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 246, NULL, NULL, 'ntop-monitor: Session Data Sent');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 247, NULL, NULL, 'ntop-monitor: Session Data Rcvd');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 248, NULL, NULL, 'ntop-monitor: Session Duration');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (2005, 249, NULL, NULL, 'ntop-monitor: Num Sessions');
