-- oracle-syslog
-- plugin_id: 1651

DELETE FROM plugin WHERE id = 1651;
DELETE FROM plugin_sid where plugin_id = 1651;

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1651, 1, 'oracle-syslog','ORACLE Syslog');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1, 'oracle: UNKNOWN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  10000, 'oracle: ALTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  10001, 'oracle: CREATE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  10002, 'oracle: DROP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1000, 'oracle: FACTOR EVALUATION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1001, 'oracle: FACTOR ASSIGNMENT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1002, 'oracle: FACTOR EXPRESSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1003, 'oracle: REALM VIOLATION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1004, 'oracle: REALM AUTHORIZATION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1005, 'oracle: COMMAND AUTHORIZATION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1006, 'oracle: SECURE ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1007, 'oracle: LBL SEC SESSION INIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1008, 'oracle: ACCESS CTRL COMMAND AUTH');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1009, 'oracle: ACCESS CTRL SESSION INIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  100, 'oracle: LOGON');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1010, 'oracle: LBL SEC ATTEMPT TO UPGRADE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  101, 'oracle: LOGOFF');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  102, 'oracle: LOGOFF BY CLEANUP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  103, 'oracle: SESSION REC');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  104, 'oracle: SYSTEM AUDIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  105, 'oracle: SYSTEM NOAUDIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  106, 'oracle: AUDIT DEFAULT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  107, 'oracle: NOAUDIT DEFAULT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  108, 'oracle: SYSTEM GRANT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  109, 'oracle: SYSTEM REVOKE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  10, 'oracle: DROP INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  110, 'oracle: CREATE PUBLIC SYNONYM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  111, 'oracle: DROP PUBLIC SYNONYM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  112, 'oracle: CREATE PUBLIC DATABASE LINK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  113, 'oracle: DROP PUBLIC DATABASE LINK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  114, 'oracle: GRANT ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  115, 'oracle: REVOKE ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  116, 'oracle: EXECUTE PROCEDURE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  117, 'oracle: USER COMMENT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  118, 'oracle: ENABLE TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  119, 'oracle: DISABLE TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  11, 'oracle: ALTER INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  120, 'oracle: ENABLE ALL TRIGGERS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  121, 'oracle: DISABLE ALL TRIGGERS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  122, 'oracle: NETWORK ERROR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  123, 'oracle: EXECUTE TYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  128, 'oracle: FLASHBACK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  129, 'oracle: CREATE SESSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  12, 'oracle: DROP TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  13, 'oracle: CREATE SEQUENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  14, 'oracle: ALTER SEQUENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  157, 'oracle: CREATE DIRECTORY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  158, 'oracle: DROP DIRECTORY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  159, 'oracle: CREATE LIBRARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  15, 'oracle: ALTER TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  160, 'oracle: CREATE JAVA');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  161, 'oracle: ALTER JAVA');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  162, 'oracle: DROP JAVA');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  163, 'oracle: CREATE OPERATOR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  164, 'oracle: CREATE INDEXTYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  165, 'oracle: DROP INDEXTYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  167, 'oracle: DROP OPERATOR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  168, 'oracle: ASSOCIATE STATISTICS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  169, 'oracle: DISASSOCIATE STATISTICS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  16, 'oracle: DROP SEQUENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  170, 'oracle: CALL METHOD');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  171, 'oracle: CREATE SUMMARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  172, 'oracle: ALTER SUMMARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  173, 'oracle: DROP SUMMARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  174, 'oracle: CREATE DIMENSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  175, 'oracle: ALTER DIMENSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  176, 'oracle: DROP DIMENSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  177, 'oracle: CREATE CONTEXT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  178, 'oracle: DROP CONTEXT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  179, 'oracle: ALTER OUTLINE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  17, 'oracle: GRANT OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  180, 'oracle: CREATE OUTLINE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  181, 'oracle: DROP OUTLINE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  182, 'oracle: UPDATE INDEXES');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  183, 'oracle: ALTER OPERATOR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  18, 'oracle: REVOKE OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  197, 'oracle: PURGE USER_RECYCLEBIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  198, 'oracle: PURGE DBA_RECYCLEBIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  199, 'oracle: PURGE TABLESPACE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  19, 'oracle: CREATE SYNONYM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  1, 'oracle: CREATE TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  2000000000, 'oracle-syslog: Generic event');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  20000000, 'Demo event (limit reached)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  200, 'oracle: PURGE TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  201, 'oracle: PURGE INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  202, 'oracle: UNDROP OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  204, 'oracle: FLASHBACK DATABASE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  205, 'oracle: FLASHBACK TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  206, 'oracle: CREATE RESTORE POINT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  207, 'oracle: DROP RESTORE POINT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  208, 'oracle: PROXY AUTHENTICATION ONLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  209, 'oracle: DECLARE REWRITE EQUIVALENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  20, 'oracle: DROP SYNONYM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  210, 'oracle: ALTER REWRITE EQUIVALENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  211, 'oracle: DROP REWRITE EQUIVALENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  212, 'oracle: SUPER USER LOGON');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  213, 'oracle: SUPER USER DDL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  214, 'oracle: SUPER USER DML');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  215, 'oracle: STARTUP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  216, 'oracle: SHUTDOWN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  217, 'oracle: SUPER USER UNKNOWN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  21, 'oracle: CREATE VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  22, 'oracle: DROP VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  23, 'oracle: VALIDATE INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  24, 'oracle: CREATE PROCEDURE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  25, 'oracle: ALTER PROCEDURE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  26, 'oracle: LOCK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  27, 'oracle: NO-OP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  28, 'oracle: RENAME');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  29, 'oracle: COMMENT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  2, 'oracle: INSERT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  30000, 'oracle: INVALID RECORD');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  30, 'oracle: AUDIT OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  31, 'oracle: NOAUDIT OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  32, 'oracle: CREATE DATABASE LINK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  33, 'oracle: DROP DATABASE LINK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  34, 'oracle: CREATE DATABASE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  35, 'oracle: ALTER DATABASE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  36, 'oracle: CREATE ROLLBACK SEG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  37, 'oracle: ALTER ROLLBACK SEG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  38, 'oracle: DROP ROLLBACK SEG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  39, 'oracle: CREATE TABLESPACE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  3, 'oracle: SELECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  40, 'oracle: ALTER TABLESPACE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  41, 'oracle: DROP TABLESPACE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  42, 'oracle: ALTER SESSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  43, 'oracle: ALTER USER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  44, 'oracle: COMMIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  45, 'oracle: ROLLBACK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  46, 'oracle: SAVEPOINT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  47, 'oracle: PL/SQL EXECUTE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  48, 'oracle: SET TRANSACTION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  49, 'oracle: ALTER SYSTEM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  4, 'oracle: CREATE CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  50, 'oracle: EXPLAIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  51, 'oracle: CREATE USER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  52, 'oracle: CREATE ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  53, 'oracle: DROP USER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  54, 'oracle: DROP ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  55, 'oracle: SET ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  56, 'oracle: CREATE SCHEMA');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  57, 'oracle: CREATE CONTROL FILE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  59, 'oracle: CREATE TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  5, 'oracle: ALTER CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  60, 'oracle: ALTER TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  61, 'oracle: DROP TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  62, 'oracle: ANALYZE TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  63, 'oracle: ANALYZE INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  64, 'oracle: ANALYZE CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  65, 'oracle: CREATE PROFILE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  66, 'oracle: DROP PROFILE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  67, 'oracle: ALTER PROFILE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  68, 'oracle: DROP PROCEDURE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  6, 'oracle: UPDATE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  70, 'oracle: ALTER RESOURCE COST');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  71, 'oracle: CREATE MATERIALIZED VIEW LOG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  72, 'oracle: ALTER MATERIALIZED VIEW LOG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  73, 'oracle: DROP MATERIALIZED VIEW LOG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  74, 'oracle: CREATE MATERIALIZED VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  75, 'oracle: ALTER MATERIALIZED VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  76, 'oracle: DROP MATERIALIZED VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  77, 'oracle: CREATE TYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  78, 'oracle: DROP TYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  79, 'oracle: ALTER ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  7, 'oracle: DELETE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  80, 'oracle: ALTER TYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  81, 'oracle: CREATE TYPE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  82, 'oracle: ALTER TYPE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  83, 'oracle: DROP TYPE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  84, 'oracle: DROP LIBRARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  85, 'oracle: TRUNCATE TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  86, 'oracle: TRUNCATE CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  8, 'oracle: DROP CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  9000, 'oracle: CONNECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  91, 'oracle: CREATE FUNCTION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  92, 'oracle: ALTER FUNCTION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  93, 'oracle: DROP FUNCTION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  94, 'oracle: CREATE PACKAGE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  95, 'oracle: ALTER PACKAGE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  96, 'oracle: DROP PACKAGE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  97, 'oracle: CREATE PACKAGE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  98, 'oracle: ALTER PACKAGE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  99, 'oracle: DROP PACKAGE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name) VALUES (1651,  9, 'oracle: CREATE INDEX');
