-- Palo Alto Firewall
-- plugin_id: 1615

DELETE FROM plugin WHERE id = "1615";
DELETE FROM plugin_sid where plugin_id = "1615";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1615, 1, 'paloalto', 'PaloAlto Firewall');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 1, 'PaloAlto: TRAFFIC start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 2, 'PaloAlto: TRAFFIC end', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 3, 'PaloAlto: TRAFFIC drop', 2, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 4, 'PaloAlto: TRAFFIC deny', 2, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 5, 'PaloAlto: URL Blocked', 1, 4,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 6, 'PaloAlto: Vulnerability', 1, 4,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 11, 'PaloAlto: CONFIG event', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 21, 'PaloAlto: SYSTEM general', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 22, 'PaloAlto: SYSTEM Authentication Fail', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 23, 'PaloAlto: SYSTEM Authentication Success', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 24, 'PaloAlto: SYSTEM Cache Cleared', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 25, 'PaloAlto: SYSTEM Connect Agent', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 26, 'PaloAlto: SYSTEM Connect Change', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 27, 'PaloAlto: SYSTEM Connection Failure', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 28, 'PaloAlto: SYSTEM Connect LDAP Server', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 29, 'PaloAlto: SYSTEM Connect LDAP Server Failure', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 30, 'PaloAlto: SYSTEM Disconect Agent', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 31, 'PaloAlto: SYSTEM Get LDAP Data Failure', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 32, 'PaloAlto: SYSTEM Get HA1 Link Change', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 33, 'PaloAlto: SYSTEM Get HA2 Link Change', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 34, 'PaloAlto: SYSTEM Get HA3 Link Change', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 35, 'PaloAlto: SYSTEM ike config p1 success', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 36, 'PaloAlto: SYSTEM ike config p2 success', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 37, 'PaloAlto: SYSTEM ike daemon exit', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 38, 'PaloAlto: SYSTEM ike daemon init', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 39, 'PaloAlto: SYSTEM ike config start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 40, 'PaloAlto: SYSTEM keymngr daemon exit', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 41, 'PaloAlto: SYSTEM keymngr daemon init', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 42, 'PaloAlto: SYSTEM keymngr daemon start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 43, 'PaloAlto: SYSTEM keymngr flow full sync abort', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 44, 'PaloAlto: SYSTEM keymngr flow full sync done', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 45, 'PaloAlto: SYSTEM keymngr flow full sync start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 46, 'PaloAlto: SYSTEM keymngr ha full sync abort', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 47, 'PaloAlto: SYSTEM keymngr ha full sync done', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 48, 'PaloAlto: SYSTEM keymngr ha full sync start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 49, 'PaloAlto: SYSTEM keymngr ike full sync abort', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 50, 'PaloAlto: SYSTEM keymngr ike full sync done', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 51, 'PaloAlto: SYSTEM keymngr ike full sync start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 52, 'PaloAlto: SYSTEM link change', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 53, 'PaloAlto: SYSTEM link monitor down', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 54, 'PaloAlto: SYSTEM link monitor up', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 55, 'PaloAlto: SYSTEM Object Enable', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 56, 'PaloAlto: SYSTEM Peer Version Match', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 57, 'PaloAlto: SYSTEM Rasmgr config p1 success', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 58, 'PaloAlto: SYSTEM Rasmgr config p2 success', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 59, 'PaloAlto: SYSTEM Rasmgr daemon exit', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 60, 'PaloAlto: SYSTEM Rasmgr daemon init', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 61, 'PaloAlto: SYSTEM Rasmgr daemon start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 62, 'PaloAlto: SYSTEM Rasmgr ha full sync abort', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 63, 'PaloAlto: SYSTEM Rasmgr ha full sync start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 64, 'PaloAlto: SYSTEM Restart', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 65, 'PaloAlto: SYSTEM Routed Config P1 success', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 66, 'PaloAlto: SYSTEM Routed Config P2 success', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 67, 'PaloAlto: SYSTEM Routed daemon exit', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 68, 'PaloAlto: SYSTEM Routed daemon init', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 69, 'PaloAlto: SYSTEM Routed daemon start', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 70, 'PaloAlto: SYSTEM Routed fib sync peer backup', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 71, 'PaloAlto: SYSTEM Routed fib sync self master', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 72, 'PaloAlto: SYSTEM Routed OSPF neighbor down', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 73, 'PaloAlto: SYSTEM Routed OSPF neighbor full', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 74, 'PaloAlto: SYSTEM Split Brain', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 75, 'PaloAlto: SYSTEM State Change', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 76, 'PaloAlto: SYSTEM Upgrade url database success', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 77, 'PaloAlto: SYSTEM Url database is lastest', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 78, 'PaloAlto: SYSTEM Url engine starts', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 79, 'PaloAlto: SYSTEM Url engine stopped', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 80, 'PaloAlto: THREAT Vulnerability', 1, 4,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 80, 'PaloAlto: THREAT Virus', 1, 4,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 81, 'PaloAlto: THREAT Scan', 1, 4,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 82, 'PaloAlto: THREAT Spyware', 1, 4,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 84, 'PaloAlto: THREAT Flood', 1, 4,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 85, 'PaloAlto: SYSTEM userid', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 86, 'PaloAlto: THREAT url', 1, 4,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 87, 'PaloAlto: SYSTEM dns proxy', 1, 2,171,15);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 88, 'PaloAlto: SYSTEM url-filtering', 1, 2,171,15);

-- failsave event
INSERT IGNORE INTO plugin_sid (plugin_id, sid, name, priority, reliability,subcategory_id, category_id) VALUES (1615, 99, 'PaloAlto: Unknown event', 1, 2,171,15);
