-- rsa-secureid
-- plugin_id: 1593

DELETE FROM plugin WHERE id = "1593";
DELETE FROM plugin_sid where plugin_id = "1593";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1593, 0, 'RSA-Secureid', 'RSA plugin captures from RSA logs using ntsyslog');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 106, NULL, NULL, 'RSA-Secureid: Disabled token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 107, NULL, NULL, 'RSA-Secureid: Enabled token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 108, NULL, NULL, 'RSA-Secureid: Assigned token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 109, NULL, NULL, 'RSA-Secureid: Unassigned token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 110, NULL, NULL, 'RSA-Secureid: Synchronized token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 115, NULL, NULL, 'RSA-Secureid: New PIN set to next tokencode' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 117, NULL, NULL, 'RSA-Secureid: PIN cleared' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 131, NULL, NULL, 'RSA-Secureid: User not on agent host' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 143, NULL, NULL, 'RSA-Secureid: Token disabled, suspect stolen' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 144, NULL, NULL, 'RSA-Secureid: Next tokencode On' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 145, NULL, NULL, 'RSA-Secureid: Token disabled, too many failures' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 146, NULL, NULL, 'RSA-Secureid: ACCESS DENIED, syntax error' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 149, NULL, NULL, 'RSA-Secureid: PASSCODE REUSE ATTACK detected' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 151, NULL, NULL, 'RSA-Secureid: PIN set by admin' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 153, NULL, NULL, 'RSA-Secureid: Assigned replacement token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 155, NULL, NULL, 'RSA-Secureid: Assigned as replacement token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 157, NULL, NULL, 'RSA-Secureid: Unassigned replaced token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 159, NULL, NULL, 'RSA-Secureid: Replacement token authenticated' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1000, NULL, NULL, 'RSA-Secureid: ACCESS DENIED, next tokencode bad' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1002, NULL, NULL, 'RSA-Secureid: Next tokencode requested' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1004, NULL, NULL, 'RSA-Secureid: ACCESS DENIED, token disabled' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1008, NULL, NULL, 'RSA-Secureid: ACCESS DENIED, passcode incorrect' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1010, NULL, NULL, 'RSA-Secureid: Good tokencode/bad PIN detected' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1011, NULL, NULL, 'RSA-Secureid: Passcode accepted' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1022, NULL, NULL, 'RSA-Secureid: ACE/Server started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1025, NULL, NULL, 'RSA-Secureid: ACE/Server is authenticating' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1057, NULL, NULL, 'RSA-Secureid: Next tokencode accepted' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1093, NULL, NULL, 'RSA-Secureid: Admin server started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1103, NULL, NULL, 'RSA-Secureid: Administrator sign on' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1104, NULL, NULL, 'RSA-Secureid: Administrator sign off' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1105, NULL, NULL, 'RSA-Secureid: Administrator sign on failed' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1121, NULL, NULL, 'RSA-Secureid: User not in database' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1141, NULL, NULL, 'RSA-Secureid: ACCESS DENIED, multiple auths' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 1144, NULL, NULL, 'RSA-Secureid: Prev tokencode/bad PIN detected' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 2004, NULL, NULL, 'RSA-Secureid: Acesyncd started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 2121, NULL, NULL, 'RSA-Secureid: Primary cannot connect to replica' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 8000, NULL, NULL, 'RSA-Secureid: Sdadmin started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 8001, NULL, NULL, 'RSA-Secureid: Sdadmin session terminated' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 4014, NULL, NULL, 'RSA-Secureid: Added user' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 4015, NULL, NULL, 'RSA-Secureid: Edited user' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 4017, NULL, NULL, 'RSA-Secureid: Deleted user' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 4021, NULL, NULL, 'RSA-Secureid: Listed users in a group' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 4514, NULL, NULL, 'RSA-Secureid: Edited token' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 4526, NULL, NULL, 'RSA-Secureid: Listed assigned disabled tokens' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 4537, NULL, NULL, 'RSA-Secureid: Entered edit token extension data' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 4538, NULL, NULL, 'RSA-Secureid: Exited edit token extension data' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 5016, NULL, NULL, 'RSA-Secureid: Added member to group' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 5017, NULL, NULL, 'RSA-Secureid: Deleted member from group' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 5018, NULL, NULL, 'RSA-Secureid: Edited group member' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 5527, NULL, NULL, 'RSA-Secureid: Edited enabled user' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 6507, NULL, NULL, 'RSA-Secureid: ALM thread started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 6511, NULL, NULL, 'RSA-Secureid: ALM deleted logs' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 6515, NULL, NULL, 'RSA-Secureid: ALM archived logs' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 7004, NULL, NULL, 'RSA-Secureid: Printed activity report' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 7005, NULL, NULL, 'RSA-Secureid: Printed exception report' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15001, NULL, NULL, 'RSA-Secureid ACE/Server will handle authentication requests' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15032, NULL, NULL, 'RSA-Secureid: Broker service started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15033, NULL, NULL, 'RSA-Secureid: Broker for sdserv started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15034, NULL, NULL, 'RSA-Secureid: Broker for sdlog started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15044, NULL, NULL, 'RSA-Secureid: RSA ACE/Server acesrvc service started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15088, NULL, NULL, 'RSA-Secureid: The storage control block address is invalid ...' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15091, NULL, NULL, 'RSA-Secureid: The storage control block address is invalid ...' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15093, NULL, NULL, 'RSA-Secureid: The storage control block address is invalid ...' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15110, NULL, NULL, 'RSA-Secureid: Acesyncd Primary Started ...' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15119, NULL, NULL, 'RSA-Secureid: Primary unable to connect to Replica Port 5506' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15112, NULL, NULL, 'RSA-Secureid: Replica successfully bound to port 5505' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 15825, NULL, NULL, 'RSA-Secureid: RSA ACE/Server syncsrvc service started' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 16221, NULL, NULL, 'RSA-Secureid: Fewer BEs Wanted ...' , 1, 3);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1593, 20000, NULL, NULL, 'RSA-Secureid: The data is invalid. Offline authentication service started' , 1, 3);
