-- Snare for Windows
-- plugin_id: 1518

DELETE FROM plugin WHERE id = "1518";
DELETE FROM plugin_sid where plugin_id = "1518";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1518, 1, 'snarewindows', 'Snare Agent for Windows');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES
(1518, 512, NULL, NULL, 'Snare: Windows NT is starting up'),
(1518, 513, NULL, NULL, 'Snare: Windows is shutting down'),
(1518, 514, NULL, NULL, 'Snare: An authentication package has been loaded by the Local Security Authority'),
(1518, 515, NULL, NULL, 'Snare: A trusted logon process has registered with the Local Security Authority'),
(1518, 516, NULL, NULL, 'Snare: Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits'),
(1518, 517, NULL, NULL, 'Snare: The audit log was cleared'),
(1518, 518, NULL, NULL, 'Snare: A notification package has been loaded by the Security Account Manager'),
(1518, 519, NULL, NULL, 'Snare: A process is using an invalid local procedure call (LPC) port'),
(1518, 520, NULL, NULL, 'Snare: The system time was changed'),
(1518, 521, NULL, NULL, 'Snare: Unable to log events to security log'),
(1518, 528, NULL, NULL, 'Snare: Successful Logon'),
(1518, 529, NULL, NULL, 'Snare: Logon Failure - Unknown user name or bad password'),
(1518, 530, NULL, NULL, 'Snare: Logon Failure - Account logon time restriction violation'),
(1518, 531, NULL, NULL, 'Snare: Logon Failure - Account currently disabled'),
(1518, 532, NULL, NULL, 'Snare: Logon Failure - The specified user account has expired'),
(1518, 533, NULL, NULL, 'Snare: Logon Failure - User not allowed to logon at this computer'),
(1518, 534, NULL, NULL, 'Snare: Logon Failure - The user has not been granted the requested logon type at this machine'),
(1518, 535, NULL, NULL, 'Snare: Logon Failure - The specified accounts password has expired'),
(1518, 536, NULL, NULL, 'Snare: Logon Failure - The NetLogon component is not active'),
(1518, 537, NULL, NULL, 'Snare: Logon failure - The logon attempt failed for other reasons.'),
(1518, 538, NULL, NULL, 'Snare: User Logoff'),
(1518, 539, NULL, NULL, 'Snare: Logon Failure - Account locked out'),
(1518, 540, NULL, NULL, 'Snare: Successful Network Logon'),
(1518, 541, NULL, NULL, 'Snare: IKE security association established'),
(1518, 542, NULL, NULL, 'Snare: IKE security association ended.'),
(1518, 545, NULL, NULL, 'Snare: IKE peer authentication failed.'),
(1518, 546, NULL, NULL, 'Snare: IKE security association establishment failed because peer sent invalid proposal.'),
(1518, 547, NULL, NULL, 'Snare: IKE security association negotiation failed.'),
(1518, 548, NULL, NULL, 'Snare: Logon Failure.'),
(1518, 551, NULL, NULL, 'Snare: User initiated logoff'),
(1518, 552, NULL, NULL, 'Snare: Logon attempt using explicit credentials'),
(1518, 560, NULL, NULL, 'Snare: Object Open'),
(1518, 561, NULL, NULL, 'Snare: Handle Allocated'),
(1518, 562, NULL, NULL, 'Snare: Handle Closed'),
(1518, 563, NULL, NULL, 'Snare: Object Open for Delete'),
(1518, 564, NULL, NULL, 'Snare: Object Deleted'),
(1518, 565, NULL, NULL, 'Snare: Object Open (Active Directory)'),
(1518, 566, NULL, NULL, 'Snare: Object Operation (W3 Active Directory)'),
(1518, 567, NULL, NULL, 'Snare: Object Access Attempt'),
(1518, 568, NULL, NULL, 'Snare: Hard link creation attempt'),
(1518, 570, NULL, NULL, 'Snare: Application operation attempt'),
(1518, 576, NULL, NULL, 'Snare: Special privileges assigned to new logon'),
(1518, 577, NULL, NULL, 'Snare: Privileged Service Called'),
(1518, 578, NULL, NULL, 'Snare: Privileged object operation'),
(1518, 592, NULL, NULL, 'Snare: A new process has been created'),
(1518, 593, NULL, NULL, 'Snare: A process has exited'),
(1518, 594, NULL, NULL, 'Snare: A handle to an object has been duplicated'),
(1518, 595, NULL, NULL, 'Snare: Indirect access to an object has been obtained'),
(1518, 596, NULL, NULL, 'Snare: Backup of data protection master key. '),
(1518, 597, NULL, NULL, 'Snare: Recovery of data protection master key.'),
(1518, 598, NULL, NULL, 'Snare: Protection of auditable protected data. '),
(1518, 599, NULL, NULL, 'Snare: Unprotection of auditable protected data'),
(1518, 600, NULL, NULL, 'Snare: A process was assigned a primary token'),
(1518, 601, NULL, NULL, 'Snare: Attempt to install service'),
(1518, 602, NULL, NULL, 'Snare: Scheduled Task created'),
(1518, 608, NULL, NULL, 'Snare: User Right Assigned'),
(1518, 609, NULL, NULL, 'Snare: User Right Removed'),
(1518, 610, NULL, NULL, 'Snare: New Trusted Domain'),
(1518, 611, NULL, NULL, 'Snare: Removing Trusted Domain'),
(1518, 612, NULL, NULL, 'Snare: Audit Policy Change'),
(1518, 613, NULL, NULL, 'Snare: IPSec policy agent started'),
(1518, 614, NULL, NULL, 'Snare: IPSec policy agent disabled'),
(1518, 615, NULL, NULL, 'Snare: IPSEC PolicyAgent Service'),
(1518, 616, NULL, NULL, 'Snare: IPSec policy agent encountered a potentially serious failure.'),
(1518, 617, NULL, NULL, 'Snare: Kerberos Policy Changed'),
(1518, 618, NULL, NULL, 'Snare: Encrypted Data Recovery Policy Changed'),
(1518, 619, NULL, NULL, 'Snare: Quality of Service Policy Changed'),
(1518, 620, NULL, NULL, 'Snare: Trusted Domain Information Modified'),
(1518, 621, NULL, NULL, 'Snare: System Security Access Granted'),
(1518, 622, NULL, NULL, 'Snare: System Security Access Removed'),
(1518, 623, NULL, NULL, 'Snare: Per User Audit Policy was refreshed'),
(1518, 624, NULL, NULL, 'Snare: User Account Created'),
(1518, 625, NULL, NULL, 'Snare: User Account Type Changed'),
(1518, 626, NULL, NULL, 'Snare: User Account Enabled'),
(1518, 627, NULL, NULL, 'Snare: Change Password Attempt'),
(1518, 628, NULL, NULL, 'Snare: User Account password set'),
(1518, 629, NULL, NULL, 'Snare: User Account Disabled'),
(1518, 630, NULL, NULL, 'Snare: User Account Deleted'),
(1518, 631, NULL, NULL, 'Snare: Security Enabled Global Group Created'),
(1518, 632, NULL, NULL, 'Snare: Security Enabled Global Group Member Added'),
(1518, 633, NULL, NULL, 'Snare: Security Enabled Global Group Member Removed'),
(1518, 634, NULL, NULL, 'Snare: Security Enabled Global Group Deleted'),
(1518, 635, NULL, NULL, 'Snare: Security Enabled Local Group Created'),
(1518, 636, NULL, NULL, 'Snare: Security Enabled Local Group Member Added'),
(1518, 637, NULL, NULL, 'Snare: Security Enabled Local Group Member Removed'),
(1518, 638, NULL, NULL, 'Snare: Security Enabled Local Group Deleted'),
(1518, 639, NULL, NULL, 'Snare: Security Enabled Local Group Changed'),
(1518, 640, NULL, NULL, 'Snare: General Account Database Change'),
(1518, 641, NULL, NULL, 'Snare: Security Enabled Global Group Changed'),
(1518, 642, NULL, NULL, 'Snare: User Account Changed'),
(1518, 643, NULL, NULL, 'Snare: Domain Policy Changed'),
(1518, 644, NULL, NULL, 'Snare: User Account Locked Out'),
(1518, 645, NULL, NULL, 'Snare: Computer Account Created'),
(1518, 646, NULL, NULL, 'Snare: Computer Account Changed'),
(1518, 647, NULL, NULL, 'Snare: Computer Account Deleted'),
(1518, 648, NULL, NULL, 'Snare: Security Disabled Local Group Created'),
(1518, 649, NULL, NULL, 'Snare: Security Disabled Local Group Changed'),
(1518, 650, NULL, NULL, 'Snare: Security Disabled Local Group Member Added'),
(1518, 651, NULL, NULL, 'Snare: Security Disabled Local Group Member Removed'),
(1518, 652, NULL, NULL, 'Snare: Security Disabled Local Group Deleted'),
(1518, 653, NULL, NULL, 'Snare: Security Disabled Global Group Created'),
(1518, 654, NULL, NULL, 'Snare: Security Disabled Global Group Changed'),
(1518, 655, NULL, NULL, 'Snare: Security Disabled Global Group Member Added'),
(1518, 656, NULL, NULL, 'Snare: Security Disabled Global Group Member Removed'),
(1518, 657, NULL, NULL, 'Snare: Security Disabled Global Group Deleted'),
(1518, 658, NULL, NULL, 'Snare: Security Enabled Universal Group Created'),
(1518, 659, NULL, NULL, 'Snare: Security Enabled Universal Group Changed'),
(1518, 660, NULL, NULL, 'Snare: Security Enabled Universal Group Member Added'),
(1518, 661, NULL, NULL, 'Snare: Security Enabled Universal Group Member Removed'),
(1518, 662, NULL, NULL, 'Snare: Security Enabled Universal Group Deleted'),
(1518, 663, NULL, NULL, 'Snare: Security Disabled Universal Group Created'),
(1518, 664, NULL, NULL, 'Snare: Security Disabled Universal Group Changed'),
(1518, 665, NULL, NULL, 'Snare: Security Disabled Universal Group Member Added'),
(1518, 666, NULL, NULL, 'Snare: Security Disabled Universal Group Member Removed'),
(1518, 667, NULL, NULL, 'Snare: Security Disabled Universal Group Deleted'),
(1518, 668, NULL, NULL, 'Snare: Group Type Changed'),
(1518, 669, NULL, NULL, 'Snare: Add SID History'),
(1518, 670, NULL, NULL, 'Snare: Add SID History'),
(1518, 671, NULL, NULL, 'Snare: User Account Unlocked'),
(1518, 672, NULL, NULL, 'Snare: Authentication Ticket Granted'),
(1518, 673, NULL, NULL, 'Snare: Service Ticket Granted'),
(1518, 674, NULL, NULL, 'Snare: Ticket Granted Renewed'),
(1518, 675, NULL, NULL, 'Snare: Pre-authentication failed'),
(1518, 676, NULL, NULL, 'Snare: Authentication Ticket Request Failed'),
(1518, 677, NULL, NULL, 'Snare: Service Ticket Request Failed'),
(1518, 678, NULL, NULL, 'Snare: Account Mapped for Logon by'),
(1518, 679, NULL, NULL, 'Snare: The name: %2 could not be mapped for logon by: %1'),
(1518, 680, NULL, NULL, 'Snare: Account Used for Logon by'),
(1518, 681, NULL, NULL, 'Snare: The logon to account: %2 by: %1 from workstation: %3 failed.'),
(1518, 682, NULL, NULL, 'Snare: Session reconnected to winstation'),
(1518, 683, NULL, NULL, 'Snare: Session disconnected from winstation'),
(1518, 684, NULL, NULL, 'Snare: Set ACLs of members in administrators groups'),
(1518, 685, NULL, NULL, 'Snare: Account Name Changed'),
(1518, 686, NULL, NULL, 'Snare: Password of the following user accessed'),
(1518, 687, NULL, NULL, 'Snare: Basic Application Group Created'),
(1518, 688, NULL, NULL, 'Snare: Basic Application Group Changed'),
(1518, 689, NULL, NULL, 'Snare: Basic Application Group Member Added'),
(1518, 690, NULL, NULL, 'Snare: Basic Application Group Member Removed'),
(1518, 691, NULL, NULL, 'Snare: Basic Application Group Non-Member Added'),
(1518, 692, NULL, NULL, 'Snare: Basic Application Group Non-Member Removed'),
(1518, 693, NULL, NULL, 'Snare: Basic Application Group Deleted'),
(1518, 694, NULL, NULL, 'Snare: LDAP Query Group Created'),
(1518, 695, NULL, NULL, 'Snare: LDAP Query Group Changed'),
(1518, 696, NULL, NULL, 'Snare: LDAP Query Group Deleted'),
(1518, 697, NULL, NULL, 'Snare: Password Policy Checking API is called'),
(1518, 698, NULL, NULL, 'Snare: An attempt to set the Directory Services Restore Mode administrator password has been made.'),
(1518, 792, NULL, NULL, 'Snare: Certificate Services denied a certificate request.'),
(1518, 806, NULL, NULL, 'Snare: Per User Audit Policy was refreshed'),
(1518, 807, NULL, NULL, 'Snare: Per user auditing policy set for user'),
(1518, 808, NULL, NULL, 'Snare: A security event source has attempted to register.'),
(1518, 835, NULL, NULL, 'Snare: Destination DRA'),
(1518, 836, NULL, NULL, 'Snare: Destination DRA'),
(1518, 837, NULL, NULL, 'Snare: Destination DRA'),
(1518, 848, NULL, NULL, 'Snare: The following policy was active when the Windows Firewall started. '),
(1518, 849, NULL, NULL, 'Snare: An application was listed as an exception when the Windows Firewall started. '),
(1518, 850, NULL, NULL, 'Snare: A port was listed as an exception when the Windows Firewall started. '),
(1518, 852, NULL, NULL, 'Snare: A change has been made to the Windows Firewall port exception list.'),
(1518, 853, NULL, NULL, 'Snare: The Windows Firewall operational mode has changed.'),
(1518, 854, NULL, NULL, 'Snare: The Windows Firewall logging settings have changed.'),
(1518, 860, NULL, NULL, 'Snare: The Windows Firewall has switched the active policy profile.'),
(1518, 861, NULL, NULL, 'Snare: The Windows Firewall has detected an application listening for incoming traffic.'),
(1518, 1100, NULL, NULL, 'Snare: The event logging service has shut down'),
(1518, 1101, NULL, NULL, 'Snare: Audit events have been dropped by the transport.'),
(1518, 1102, NULL, NULL, 'Snare: The audit log was cleared'),
(1518, 1104, NULL, NULL, 'Snare: The security Log is now full'),
(1518, 1105, NULL, NULL, 'Snare: Event log automatic backup'),
(1518, 1108, NULL, NULL, 'Snare: The event logging service encountered an error'),
(1518, 4608, NULL, NULL, 'Snare: Windows is starting up'),
(1518, 4609, NULL, NULL, 'Snare: Windows is shutting down'),
(1518, 4610, NULL, NULL, 'Snare: An authentication package has been loaded by the Local Security Authority'),
(1518, 4611, NULL, NULL, 'Snare: A trusted logon process has been registered with the Local Security Authority'),
(1518, 4612, NULL, NULL, 'Snare: Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits.'),
(1518, 4614, NULL, NULL, 'Snare: A notification package has been loaded by the Security Account Manager.'),
(1518, 4615, NULL, NULL, 'Snare: Invalid use of LPC port'),
(1518, 4616, NULL, NULL, 'Snare: The system time was changed.'),
(1518, 4618, NULL, NULL, 'Snare: A monitored security event pattern has occurred'),
(1518, 4621, NULL, NULL, 'Snare: Administrator recovered system from CrashOnAuditFail'),
(1518, 4622, NULL, NULL, 'Snare: A security package has been loaded by the Local Security Authority.'),
(1518, 4624, NULL, NULL, 'Snare: An account was successfully logged on'),
(1518, 4625, NULL, NULL, 'Snare: An account failed to log on'),
(1518, 4634, NULL, NULL, 'Snare: An account was logged off'),
(1518, 4646, NULL, NULL, 'Snare: 1.00%'),
(1518, 4647, NULL, NULL, 'Snare: User initiated logoff'),
(1518, 4648, NULL, NULL, 'Snare: A logon was attempted using explicit credentials'),
(1518, 4649, NULL, NULL, 'Snare: A replay attack was detected'),
(1518, 4650, NULL, NULL, 'Snare: An IPsec Main Mode security association was established'),
(1518, 4651, NULL, NULL, 'Snare: An IPsec Main Mode security association was established'),
(1518, 4652, NULL, NULL, 'Snare: An IPsec Main Mode negotiation failed'),
(1518, 4653, NULL, NULL, 'Snare: An IPsec Main Mode negotiation failed'),
(1518, 4654, NULL, NULL, 'Snare: An IPsec Quick Mode negotiation failed'),
(1518, 4655, NULL, NULL, 'Snare: An IPsec Main Mode security association ended'),
(1518, 4656, NULL, NULL, 'Snare: A handle to an object was requested'),
(1518, 4657, NULL, NULL, 'Snare: A registry value was modified'),
(1518, 4658, NULL, NULL, 'Snare: The handle to an object was closed'),
(1518, 4659, NULL, NULL, 'Snare: A handle to an object was requested with intent to delete'),
(1518, 4660, NULL, NULL, 'Snare: An object was deleted'),
(1518, 4661, NULL, NULL, 'Snare: A handle to an object was requested'),
(1518, 4662, NULL, NULL, 'Snare: An operation was performed on an object'),
(1518, 4663, NULL, NULL, 'Snare: An attempt was made to access an object'),
(1518, 4664, NULL, NULL, 'Snare: An attempt was made to create a hard link'),
(1518, 4665, NULL, NULL, 'Snare: An attempt was made to create an application client context.'),
(1518, 4666, NULL, NULL, 'Snare: An application attempted an operation'),
(1518, 4667, NULL, NULL, 'Snare: An application client context was deleted'),
(1518, 4668, NULL, NULL, 'Snare: An application was initialized'),
(1518, 4670, NULL, NULL, 'Snare: Permissions on an object were changed'),
(1518, 4671, NULL, NULL, 'Snare: An application attempted to access a blocked ordinal through the TBS'),
(1518, 4672, NULL, NULL, 'Snare: Special privileges assigned to new logon'),
(1518, 4673, NULL, NULL, 'Snare: A privileged service was called'),
(1518, 4674, NULL, NULL, 'Snare: An operation was attempted on a privileged object'),
(1518, 4675, NULL, NULL, 'Snare: SIDs were filtered'),
(1518, 4685, NULL, NULL, 'Snare: The state of a transaction has changed'),
(1518, 4688, NULL, NULL, 'Snare: A new process has been created'),
(1518, 4689, NULL, NULL, 'Snare: A process has exited'),
(1518, 4690, NULL, NULL, 'Snare: An attempt was made to duplicate a handle to an object'),
(1518, 4691, NULL, NULL, 'Snare: Indirect access to an object was requested'),
(1518, 4692, NULL, NULL, 'Snare: Backup of data protection master key was attempted'),
(1518, 4693, NULL, NULL, 'Snare: Recovery of data protection master key was attempted'),
(1518, 4694, NULL, NULL, 'Snare: Protection of auditable protected data was attempted'),
(1518, 4695, NULL, NULL, 'Snare: Unprotection of auditable protected data was attempted'),
(1518, 4696, NULL, NULL, 'Snare: A primary token was assigned to process'),
(1518, 4697, NULL, NULL, 'Snare: A service was installed in the system'),
(1518, 4698, NULL, NULL, 'Snare: A scheduled task was created'),
(1518, 4699, NULL, NULL, 'Snare: A scheduled task was deleted'),
(1518, 4700, NULL, NULL, 'Snare: A scheduled task was enabled'),
(1518, 4701, NULL, NULL, 'Snare: A scheduled task was disabled'),
(1518, 4702, NULL, NULL, 'Snare: A scheduled task was updated'),
(1518, 4704, NULL, NULL, 'Snare: A user right was assigned'),
(1518, 4705, NULL, NULL, 'Snare: A user right was removed'),
(1518, 4706, NULL, NULL, 'Snare: A new trust was created to a domain'),
(1518, 4707, NULL, NULL, 'Snare: A trust to a domain was removed'),
(1518, 4709, NULL, NULL, 'Snare: IPsec Services was started'),
(1518, 4710, NULL, NULL, 'Snare: IPsec Services was disabled'),
(1518, 4711, NULL, NULL, 'Snare: PAStore Engine (1%)'),
(1518, 4712, NULL, NULL, 'Snare: IPsec Services encountered a potentially serious failure'),
(1518, 4713, NULL, NULL, 'Snare: Kerberos policy was changed'),
(1518, 4714, NULL, NULL, 'Snare: Encrypted data recovery policy was changed'),
(1518, 4715, NULL, NULL, 'Snare: The audit policy (SACL) on an object was changed'),
(1518, 4716, NULL, NULL, 'Snare: Trusted domain information was modified'),
(1518, 4717, NULL, NULL, 'Snare: System security access was granted to an account'),
(1518, 4718, NULL, NULL, 'Snare: System security access was removed from an account'),
(1518, 4719, NULL, NULL, 'Snare: System audit policy was changed'),
(1518, 4720, NULL, NULL, 'Snare: A user account was created'),
(1518, 4722, NULL, NULL, 'Snare: A user account was enabled'),
(1518, 4723, NULL, NULL, 'Snare: An attempt was made to change an accounts password'),
(1518, 4724, NULL, NULL, 'Snare: An attempt was made to reset an accounts password'),
(1518, 4725, NULL, NULL, 'Snare: A user account was disabled'),
(1518, 4726, NULL, NULL, 'Snare: A user account was deleted'),
(1518, 4727, NULL, NULL, 'Snare: A security-enabled global group was created'),
(1518, 4728, NULL, NULL, 'Snare: A member was added to a security-enabled global group'),
(1518, 4729, NULL, NULL, 'Snare: A member was removed from a security-enabled global group'),
(1518, 4730, NULL, NULL, 'Snare: A security-enabled global group was deleted'),
(1518, 4731, NULL, NULL, 'Snare: A security-enabled local group was created'),
(1518, 4732, NULL, NULL, 'Snare: A member was added to a security-enabled local group'),
(1518, 4733, NULL, NULL, 'Snare: A member was removed from a security-enabled local group'),
(1518, 4734, NULL, NULL, 'Snare: A security-enabled local group was deleted'),
(1518, 4735, NULL, NULL, 'Snare: A security-enabled local group was changed'),
(1518, 4737, NULL, NULL, 'Snare: A security-enabled global group was changed'),
(1518, 4738, NULL, NULL, 'Snare: A user account was changed'),
(1518, 4739, NULL, NULL, 'Snare: Domain Policy was changed'),
(1518, 4740, NULL, NULL, 'Snare: A user account was locked out'),
(1518, 4741, NULL, NULL, 'Snare: A computer account was created'),
(1518, 4742, NULL, NULL, 'Snare: A computer account was changed'),
(1518, 4743, NULL, NULL, 'Snare: A computer account was deleted'),
(1518, 4744, NULL, NULL, 'Snare: A security-disabled local group was created'),
(1518, 4745, NULL, NULL, 'Snare: A security-disabled local group was changed'),
(1518, 4746, NULL, NULL, 'Snare: A member was added to a security-disabled local group'),
(1518, 4747, NULL, NULL, 'Snare: A member was removed from a security-disabled local group'),
(1518, 4748, NULL, NULL, 'Snare: A security-disabled local group was deleted'),
(1518, 4749, NULL, NULL, 'Snare: A security-disabled global group was created'),
(1518, 4750, NULL, NULL, 'Snare: A security-disabled global group was changed'),
(1518, 4751, NULL, NULL, 'Snare: A member was added to a security-disabled global group'),
(1518, 4752, NULL, NULL, 'Snare: A member was removed from a security-disabled global group'),
(1518, 4753, NULL, NULL, 'Snare: A security-disabled global group was deleted'),
(1518, 4754, NULL, NULL, 'Snare: A security-enabled universal group was created'),
(1518, 4755, NULL, NULL, 'Snare: A security-enabled universal group was changed'),
(1518, 4756, NULL, NULL, 'Snare: A member was added to a security-enabled universal group'),
(1518, 4757, NULL, NULL, 'Snare: A member was removed from a security-enabled universal group'),
(1518, 4758, NULL, NULL, 'Snare: A security-enabled universal group was deleted'),
(1518, 4759, NULL, NULL, 'Snare: A security-disabled universal group was created'),
(1518, 4760, NULL, NULL, 'Snare: A security-disabled universal group was changed'),
(1518, 4761, NULL, NULL, 'Snare: A member was added to a security-disabled universal group'),
(1518, 4762, NULL, NULL, 'Snare: A member was removed from a security-disabled universal group'),
(1518, 4763, NULL, NULL, 'Snare: A security-disabled universal group was deleted'),
(1518, 4764, NULL, NULL, 'Snare: A groups type was changed'),
(1518, 4765, NULL, NULL, 'Snare: SID History was added to an account'),
(1518, 4766, NULL, NULL, 'Snare: An attempt to add SID History to an account failed'),
(1518, 4767, NULL, NULL, 'Snare: A user account was unlocked'),
(1518, 4768, NULL, NULL, 'Snare: A Kerberos authentication ticket (TGT) was requested'),
(1518, 4769, NULL, NULL, 'Snare: A Kerberos service ticket was requested'),
(1518, 4770, NULL, NULL, 'Snare: A Kerberos service ticket was renewed'),
(1518, 4771, NULL, NULL, 'Snare: Kerberos pre-authentication failed'),
(1518, 4772, NULL, NULL, 'Snare: A Kerberos authentication ticket request failed'),
(1518, 4773, NULL, NULL, 'Snare: A Kerberos service ticket request failed'),
(1518, 4774, NULL, NULL, 'Snare: An account was mapped for logon'),
(1518, 4775, NULL, NULL, 'Snare: An account could not be mapped for logon'),
(1518, 4776, NULL, NULL, 'Snare: The domain controller attempted to validate the credentials for an account'),
(1518, 4777, NULL, NULL, 'Snare: The domain controller failed to validate the credentials for an account'),
(1518, 4778, NULL, NULL, 'Snare: A session was reconnected to a Window Station'),
(1518, 4779, NULL, NULL, 'Snare: A session was disconnected from a Window Station'),
(1518, 4780, NULL, NULL, 'Snare: The ACL was set on accounts which are members of administrators groups'),
(1518, 4781, NULL, NULL, 'Snare: The name of an account was changed'),
(1518, 4782, NULL, NULL, 'Snare: The password hash an account was accessed'),
(1518, 4783, NULL, NULL, 'Snare: A basic application group was created'),
(1518, 4784, NULL, NULL, 'Snare: A basic application group was changed'),
(1518, 4785, NULL, NULL, 'Snare: A member was added to a basic application group'),
(1518, 4786, NULL, NULL, 'Snare: A member was removed from a basic application group'),
(1518, 4787, NULL, NULL, 'Snare: A non-member was added to a basic application group'),
(1518, 4788, NULL, NULL, 'Snare: A non-member was removed from a basic application group..'),
(1518, 4789, NULL, NULL, 'Snare: A basic application group was deleted'),
(1518, 4790, NULL, NULL, 'Snare: An LDAP query group was created'),
(1518, 4791, NULL, NULL, 'Snare: A basic application group was changed'),
(1518, 4792, NULL, NULL, 'Snare: An LDAP query group was deleted'),
(1518, 4793, NULL, NULL, 'Snare: The Password Policy Checking API was called'),
(1518, 4794, NULL, NULL, 'Snare: An attempt was made to set the Directory Services Restore Mode administrator password'),
(1518, 4800, NULL, NULL, 'Snare: The workstation was locked'),
(1518, 4801, NULL, NULL, 'Snare: The workstation was unlocked'),
(1518, 4802, NULL, NULL, 'Snare: The screen saver was invoked'),
(1518, 4803, NULL, NULL, 'Snare: The screen saver was dismissed'),
(1518, 4816, NULL, NULL, 'Snare: RPC detected an integrity violation while decrypting an incoming message'),
(1518, 4864, NULL, NULL, 'Snare: A namespace collision was detected'),
(1518, 4865, NULL, NULL, 'Snare: A trusted forest information entry was added'),
(1518, 4866, NULL, NULL, 'Snare: A trusted forest information entry was removed'),
(1518, 4867, NULL, NULL, 'Snare: A trusted forest information entry was modified'),
(1518, 4868, NULL, NULL, 'Snare: The certificate manager denied a pending certificate request'),
(1518, 4869, NULL, NULL, 'Snare: Certificate Services received a resubmitted certificate request'),
(1518, 4870, NULL, NULL, 'Snare: Certificate Services revoked a certificate'),
(1518, 4871, NULL, NULL, 'Snare: Certificate Services received a request to publish the certificate revocation list (CRL)'),
(1518, 4872, NULL, NULL, 'Snare: Certificate Services published the certificate revocation list (CRL)'),
(1518, 4873, NULL, NULL, 'Snare: A certificate request extension changed'),
(1518, 4875, NULL, NULL, 'Snare: Certificate Services received a request to shut down'),
(1518, 4876, NULL, NULL, 'Snare: Certificate Services backup started'),
(1518, 4877, NULL, NULL, 'Snare: Certificate Services backup completed'),
(1518, 4878, NULL, NULL, 'Snare: Certificate Services restore started'),
(1518, 4879, NULL, NULL, 'Snare: Certificate Services restore completed'),
(1518, 4880, NULL, NULL, 'Snare: Certificate Services started'),
(1518, 4881, NULL, NULL, 'Snare: Certificate Services stopped'),
(1518, 4882, NULL, NULL, 'Snare: The security permissions for Certificate Services changed'),
(1518, 4883, NULL, NULL, 'Snare: Certificate Services retrieved an archived key'),
(1518, 4884, NULL, NULL, 'Snare: Certificate Services imported a certificate into its database'),
(1518, 4885, NULL, NULL, 'Snare: The audit filter for Certificate Services changed'),
(1518, 4886, NULL, NULL, 'Snare: Certificate Services received a certificate request'),
(1518, 4887, NULL, NULL, 'Snare: Certificate Services approved a certificate request and issued a certificate'),
(1518, 4888, NULL, NULL, 'Snare: Certificate Services denied a certificate request'),
(1518, 4889, NULL, NULL, 'Snare: Certificate Services set the status of a certificate request to pending'),
(1518, 4890, NULL, NULL, 'Snare: The certificate manager settings for Certificate Services changed.'),
(1518, 4891, NULL, NULL, 'Snare: A configuration entry changed in Certificate Services'),
(1518, 4892, NULL, NULL, 'Snare: A property of Certificate Services changed'),
(1518, 4893, NULL, NULL, 'Snare: Certificate Services archived a key'),
(1518, 4894, NULL, NULL, 'Snare: Certificate Services imported and archived a key'),
(1518, 4895, NULL, NULL, 'Snare: Certificate Services published the CA certificate to Active Directory Domain Services'),
(1518, 4896, NULL, NULL, 'Snare: One or more rows have been deleted from the certificate database'),
(1518, 4897, NULL, NULL, 'Snare: Role separation enabled'),
(1518, 4898, NULL, NULL, 'Snare: Certificate Services loaded a template'),
(1518, 4899, NULL, NULL, 'Snare: A Certificate Services template was updated'),
(1518, 4900, NULL, NULL, 'Snare: Certificate Services template security was updated'),
(1518, 4902, NULL, NULL, 'Snare: The Per-user audit policy table was created'),
(1518, 4904, NULL, NULL, 'Snare: An attempt was made to register a security event source'),
(1518, 4905, NULL, NULL, 'Snare: An attempt was made to unregister a security event source'),
(1518, 4906, NULL, NULL, 'Snare: The CrashOnAuditFail value has changed'),
(1518, 4907, NULL, NULL, 'Snare: Auditing settings on object were changed'),
(1518, 4908, NULL, NULL, 'Snare: Special Groups Logon table modified'),
(1518, 4909, NULL, NULL, 'Snare: The local policy settings for the TBS were changed'),
(1518, 4910, NULL, NULL, 'Snare: The group policy settings for the TBS were changed'),
(1518, 4912, NULL, NULL, 'Snare: Per User Audit Policy was changed'),
(1518, 4928, NULL, NULL, 'Snare: An Active Directory replica source naming context was established'),
(1518, 4929, NULL, NULL, 'Snare: An Active Directory replica source naming context was removed'),
(1518, 4930, NULL, NULL, 'Snare: An Active Directory replica source naming context was modified'),
(1518, 4931, NULL, NULL, 'Snare: An Active Directory replica destination naming context was modified'),
(1518, 4932, NULL, NULL, 'Snare: Synchronization of a replica of an Active Directory naming context has begun'),
(1518, 4933, NULL, NULL, 'Snare: Synchronization of a replica of an Active Directory naming context has ended'),
(1518, 4934, NULL, NULL, 'Snare: Attributes of an Active Directory object were replicated'),
(1518, 4935, NULL, NULL, 'Snare: Replication failure begins'),
(1518, 4936, NULL, NULL, 'Snare: Replication failure ends'),
(1518, 4937, NULL, NULL, 'Snare: A lingering object was removed from a replica'),
(1518, 4944, NULL, NULL, 'Snare: The following policy was active when the Windows Firewall started'),
(1518, 4945, NULL, NULL, 'Snare: A rule was listed when the Windows Firewall started'),
(1518, 4946, NULL, NULL, 'Snare: A change has been made to Windows Firewall exception list. A rule was added'),
(1518, 4947, NULL, NULL, 'Snare: A change has been made to Windows Firewall exception list. A rule was modified'),
(1518, 4948, NULL, NULL, 'Snare: A change has been made to Windows Firewall exception list. A rule was deleted'),
(1518, 4949, NULL, NULL, 'Snare: Windows Firewall settings were restored to the default values'),
(1518, 4950, NULL, NULL, 'Snare: A Windows Firewall setting has changed'),
(1518, 4951, NULL, NULL, 'Snare: A rule has been ignored because its major version number was not recognized by Windows Firewall'),
(1518, 4952, NULL, NULL, 'Snare: Parts of a rule have been ignored because its minor version number was not recognized by Windows Firewall'),
(1518, 4953, NULL, NULL, 'Snare: A rule has been ignored by Windows Firewall because it could not parse the rule'),
(1518, 4954, NULL, NULL, 'Snare: Windows Firewall Group Policy settings has changed. The new settings have been applied'),
(1518, 4956, NULL, NULL, 'Snare: Windows Firewall has changed the active profile'),
(1518, 4957, NULL, NULL, 'Snare: Windows Firewall did not apply the following rule'),
(1518, 4958, NULL, NULL, 'Snare: Windows Firewall did not apply the following rule because the rule referred to items not configured on this computer'),
(1518, 4960, NULL, NULL, 'Snare: IPsec dropped an inbound packet that failed an integrity check'),
(1518, 4961, NULL, NULL, 'Snare: IPsec dropped an inbound packet that failed a replay check'),
(1518, 4962, NULL, NULL, 'Snare: IPsec dropped an inbound packet that failed a replay check'),
(1518, 4963, NULL, NULL, 'Snare: IPsec dropped an inbound clear text packet that should have been secured'),
(1518, 4964, NULL, NULL, 'Snare: Special groups have been assigned to a new logon'),
(1518, 4965, NULL, NULL, 'Snare: IPsec received a packet from a remote computer with an incorrect Security Parameter Index (SPI).'),
(1518, 4976, NULL, NULL, 'Snare: During Main Mode negotiation, IPsec received an invalid negotiation packet.'),
(1518, 4977, NULL, NULL, 'Snare: During Quick Mode negotiation, IPsec received an invalid negotiation packet.'),
(1518, 4978, NULL, NULL, 'Snare: During Extended Mode negotiation, IPsec received an invalid negotiation packet.'),
(1518, 4979, NULL, NULL, 'Snare: IPsec Main Mode and Extended Mode security associations were established.'),
(1518, 4980, NULL, NULL, 'Snare: IPsec Main Mode and Extended Mode security associations were established'),
(1518, 4981, NULL, NULL, 'Snare: IPsec Main Mode and Extended Mode security associations were established'),
(1518, 4982, NULL, NULL, 'Snare: IPsec Main Mode and Extended Mode security associations were established'),
(1518, 4983, NULL, NULL, 'Snare: An IPsec Extended Mode negotiation failed'),
(1518, 4984, NULL, NULL, 'Snare: An IPsec Extended Mode negotiation failed'),
(1518, 4985, NULL, NULL, 'Snare: The state of a transaction has changed'),
(1518, 5024, NULL, NULL, 'Snare: The Windows Firewall Service has started successfully'),
(1518, 5025, NULL, NULL, 'Snare: The Windows Firewall Service has been stopped'),
(1518, 5027, NULL, NULL, 'Snare: The Windows Firewall Service was unable to retrieve the security policy from the local storage'),
(1518, 5028, NULL, NULL, 'Snare: The Windows Firewall Service was unable to parse the new security policy.'),
(1518, 5029, NULL, NULL, 'Snare: The Windows Firewall Service failed to initialize the driver'),
(1518, 5030, NULL, NULL, 'Snare: The Windows Firewall Service failed to start'),
(1518, 5031, NULL, NULL, 'Snare: The Windows Firewall Service blocked an application from accepting incoming connections on the network.'),
(1518, 5032, NULL, NULL, 'Snare: Windows Firewall was unable to notify the user that it blocked an application from accepting incoming connections on the network'),
(1518, 5033, NULL, NULL, 'Snare: The Windows Firewall Driver has started successfully'),
(1518, 5034, NULL, NULL, 'Snare: The Windows Firewall Driver has been stopped'),
(1518, 5035, NULL, NULL, 'Snare: The Windows Firewall Driver failed to start'),
(1518, 5037, NULL, NULL, 'Snare: The Windows Firewall Driver detected critical runtime error. Terminating'),
(1518, 5038, NULL, NULL, 'Snare: Code integrity determined that the image hash of a file is not valid'),
(1518, 5039, NULL, NULL, 'Snare: A registry key was virtualized.'),
(1518, 5040, NULL, NULL, 'Snare: A change has been made to IPsec settings. An Authentication Set was added.'),
(1518, 5041, NULL, NULL, 'Snare: A change has been made to IPsec settings. An Authentication Set was modified'),
(1518, 5042, NULL, NULL, 'Snare: A change has been made to IPsec settings. An Authentication Set was deleted'),
(1518, 5043, NULL, NULL, 'Snare: A change has been made to IPsec settings. A Connection Security Rule was added'),
(1518, 5044, NULL, NULL, 'Snare: A change has been made to IPsec settings. A Connection Security Rule was modified'),
(1518, 5045, NULL, NULL, 'Snare: A change has been made to IPsec settings. A Connection Security Rule was deleted'),
(1518, 5046, NULL, NULL, 'Snare: A change has been made to IPsec settings. A Crypto Set was added'),
(1518, 5047, NULL, NULL, 'Snare: A change has been made to IPsec settings. A Crypto Set was modified'),
(1518, 5048, NULL, NULL, 'Snare: A change has been made to IPsec settings. A Crypto Set was deleted'),
(1518, 5049, NULL, NULL, 'Snare: An IPsec Security Association was deleted'),
(1518, 5050, NULL, NULL, 'Snare: An attempt to programmatically disable the Windows Firewall using a call to INetFwProfile.FirewallEnabled(FALSE'),
(1518, 5051, NULL, NULL, 'Snare: A file was virtualized'),
(1518, 5056, NULL, NULL, 'Snare: A cryptographic self test was performed'),
(1518, 5057, NULL, NULL, 'Snare: A cryptographic primitive operation failed'),
(1518, 5058, NULL, NULL, 'Snare: Key file operation'),
(1518, 5059, NULL, NULL, 'Snare: Key migration operation'),
(1518, 5060, NULL, NULL, 'Snare: Verification operation failed'),
(1518, 5061, NULL, NULL, 'Snare: Cryptographic operation'),
(1518, 5062, NULL, NULL, 'Snare: A kernel-mode cryptographic self test was performed'),
(1518, 5063, NULL, NULL, 'Snare: A cryptographic provider operation was attempted'),
(1518, 5064, NULL, NULL, 'Snare: A cryptographic context operation was attempted'),
(1518, 5065, NULL, NULL, 'Snare: A cryptographic context modification was attempted'),
(1518, 5066, NULL, NULL, 'Snare: A cryptographic function operation was attempted'),
(1518, 5067, NULL, NULL, 'Snare: A cryptographic function modification was attempted'),
(1518, 5068, NULL, NULL, 'Snare: A cryptographic function provider operation was attempted'),
(1518, 5069, NULL, NULL, 'Snare: A cryptographic function property operation was attempted'),
(1518, 5070, NULL, NULL, 'Snare: A cryptographic function property operation was attempted'),
(1518, 5120, NULL, NULL, 'Snare: OCSP Responder Service Started'),
(1518, 5121, NULL, NULL, 'Snare: OCSP Responder Service Stopped'),
(1518, 5122, NULL, NULL, 'Snare: A Configuration entry changed in the OCSP Responder Service'),
(1518, 5123, NULL, NULL, 'Snare: A configuration entry changed in the OCSP Responder Service'),
(1518, 5124, NULL, NULL, 'Snare: A security setting was updated on OCSP Responder Service'),
(1518, 5125, NULL, NULL, 'Snare: A request was submitted to OCSP Responder Service'),
(1518, 5126, NULL, NULL, 'Snare: Signing Certificate was automatically updated by the OCSP Responder Service'),
(1518, 5127, NULL, NULL, 'Snare: The OCSP Revocation Provider successfully updated the revocation information'),
(1518, 5136, NULL, NULL, 'Snare: A directory service object was modified'),
(1518, 5137, NULL, NULL, 'Snare: A directory service object was created'),
(1518, 5138, NULL, NULL, 'Snare: A directory service object was undeleted'),
(1518, 5139, NULL, NULL, 'Snare: A directory service object was moved'),
(1518, 5140, NULL, NULL, 'Snare: A network share object was accessed'),
(1518, 5141, NULL, NULL, 'Snare: A directory service object was deleted'),
(1518, 5145, NULL, NULL, 'Snare: A network share object was checked to see whether client can be granted desired access'),
(1518, 5152, NULL, NULL, 'Snare: The Windows Filtering Platform blocked a packet'),
(1518, 5153, NULL, NULL, 'Snare: A more restrictive Windows Filtering Platform filter has blocked a packet'),
(1518, 5154, NULL, NULL, 'Snare: The Windows Filtering Platform has permitted an application or service to listen on a port for incoming connections'),
(1518, 5155, NULL, NULL, 'Snare: The Windows Filtering Platform has blocked an application or service from listening on a port for incoming connections'),
(1518, 5156, NULL, NULL, 'Snare: The Windows Filtering Platform has allowed a connection'),
(1518, 5157, NULL, NULL, 'Snare: The Windows Filtering Platform has blocked a connection'),
(1518, 5158, NULL, NULL, 'Snare: The Windows Filtering Platform has permitted a bind to a local port'),
(1518, 5159, NULL, NULL, 'Snare: The Windows Filtering Platform has blocked a bind to a local port'),
(1518, 5376, NULL, NULL, 'Snare: Credential Manager credentials were backed up'),
(1518, 5377, NULL, NULL, 'Snare: Credential Manager credentials were restored from a backup'),
(1518, 5378, NULL, NULL, 'Snare: The requested credentials delegation was disallowed by policy'),
(1518, 5440, NULL, NULL, 'Snare: The following callout was present when the Windows Filtering Platform Base Filtering Engine started'),
(1518, 5441, NULL, NULL, 'Snare: The following filter was present when the Windows Filtering Platform Base Filtering Engine started'),
(1518, 5442, NULL, NULL, 'Snare: The following provider was present when the Windows Filtering Platform Base Filtering Engine started'),
(1518, 5443, NULL, NULL, 'Snare: The following provider context was present when the Windows Filtering Platform Base Filtering Engine started'),
(1518, 5444, NULL, NULL, 'Snare: The following sub-layer was present when the Windows Filtering Platform Base Filtering Engine started'),
(1518, 5446, NULL, NULL, 'Snare: A Windows Filtering Platform callout has been changed'),
(1518, 5447, NULL, NULL, 'Snare: A Windows Filtering Platform filter has been changed'),
(1518, 5448, NULL, NULL, 'Snare: A Windows Filtering Platform provider has been changed'),
(1518, 5449, NULL, NULL, 'Snare: A Windows Filtering Platform provider context has been changed'),
(1518, 5450, NULL, NULL, 'Snare: A Windows Filtering Platform sub-layer has been changed'),
(1518, 5451, NULL, NULL, 'Snare: An IPsec Quick Mode security association was established'),
(1518, 5452, NULL, NULL, 'Snare: An IPsec Quick Mode security association ended'),
(1518, 5453, NULL, NULL, 'Snare: An IPsec negotiation with a remote computer failed because the IKE and AuthIP IPsec Keying Modules (IKEEXT) service is not started'),
(1518, 5456, NULL, NULL, 'Snare: PAStore Engine applied Active Directory storage IPsec policy on the computer'),
(1518, 5457, NULL, NULL, 'Snare: PAStore Engine failed to apply Active Directory storage IPsec policy on the computer'),
(1518, 5458, NULL, NULL, 'Snare: PAStore Engine applied locally cached copy of Active Directory storage IPsec policy on the computer'),
(1518, 5459, NULL, NULL, 'Snare: PAStore Engine failed to apply locally cached copy of Active Directory storage IPsec policy on the computer'),
(1518, 5460, NULL, NULL, 'Snare: PAStore Engine applied local registry storage IPsec policy on the computer'),
(1518, 5461, NULL, NULL, 'Snare: PAStore Engine failed to apply local registry storage IPsec policy on the computer'),
(1518, 5462, NULL, NULL, 'Snare: PAStore Engine failed to apply some rules of the active IPsec policy on the computer'),
(1518, 5463, NULL, NULL, 'Snare: PAStore Engine polled for changes to the active IPsec policy and detected no changes'),
(1518, 5464, NULL, NULL, 'Snare: PAStore Engine polled for changes to the active IPsec policy, detected changes, and applied them to IPsec Services'),
(1518, 5465, NULL, NULL, 'Snare: PAStore Engine received a control for forced reloading of IPsec policy and processed the control successfully'),
(1518, 5466, NULL, NULL, 'Snare: PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory cannot be reached, and will use the cached copy of the Active Directory IPsec policy instead'),
(1518, 5467, NULL, NULL, 'Snare: PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, and found no changes to the policy'),
(1518, 5468, NULL, NULL, 'Snare: PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, found changes to the policy, and applied those changes'),
(1518, 5471, NULL, NULL, 'Snare: PAStore Engine loaded local storage IPsec policy on the computer'),
(1518, 5472, NULL, NULL, 'Snare: PAStore Engine failed to load local storage IPsec policy on the computer'),
(1518, 5473, NULL, NULL, 'Snare: PAStore Engine loaded directory storage IPsec policy on the computer'),
(1518, 5474, NULL, NULL, 'Snare: PAStore Engine failed to load directory storage IPsec policy on the computer'),
(1518, 5477, NULL, NULL, 'Snare: PAStore Engine failed to add quick mode filter'),
(1518, 5478, NULL, NULL, 'Snare: IPsec Services has started successfully'),
(1518, 5479, NULL, NULL, 'Snare: IPsec Services has been shut down successfully'),
(1518, 5480, NULL, NULL, 'Snare: IPsec Services failed to get the complete list of network interfaces on the computer'),
(1518, 5483, NULL, NULL, 'Snare: IPsec Services failed to initialize RPC server. IPsec Services could not be started'),
(1518, 5484, NULL, NULL, 'Snare: IPsec Services has experienced a critical failure and has been shut down'),
(1518, 5485, NULL, NULL, 'Snare: IPsec Services failed to process some IPsec filters on a plug-and-play event for network interfaces'),
(1518, 5632, NULL, NULL, 'Snare: A request was made to authenticate to a wireless network'),
(1518, 5633, NULL, NULL, 'Snare: A request was made to authenticate to a wired network'),
(1518, 5712, NULL, NULL, 'Snare: A Remote Procedure Call (RPC) was attempted'),
(1518, 5888, NULL, NULL, 'Snare: An object in the COM+ Catalog was modified'),
(1518, 5889, NULL, NULL, 'Snare: An object was deleted from the COM+ Catalog'),
(1518, 5890, NULL, NULL, 'Snare: An object was added to the COM+ Catalog'),
(1518, 6144, NULL, NULL, 'Snare: Security policy in the group policy objects has been applied successfully'),
(1518, 6145, NULL, NULL, 'Snare: One or more errors occured while processing security policy in the group policy objects'),
(1518, 6272, NULL, NULL, 'Snare: Network Policy Server granted access to a user'),
(1518, 6273, NULL, NULL, 'Snare: Network Policy Server denied access to a user'),
(1518, 6274, NULL, NULL, 'Snare: Network Policy Server discarded the request for a user'),
(1518, 6275, NULL, NULL, 'Snare: Network Policy Server discarded the accounting request for a user'),
(1518, 6276, NULL, NULL, 'Snare: Network Policy Server quarantined a user'),
(1518, 6277, NULL, NULL, 'Snare: Network Policy Server granted access to a user but put it on probation because the host did not meet the defined health policy'),
(1518, 6278, NULL, NULL, 'Snare: Network Policy Server granted full access to a user because the host met the defined health policy'),
(1518, 6279, NULL, NULL, 'Snare: Network Policy Server locked the user account due to repeated failed authentication attempts'),
(1518, 6280, NULL, NULL, 'Snare: Network Policy Server unlocked the user account'),
(1518, 7035, NULL, NULL, 'Snare: A service was successfully sent a start/stop control'),
(1518, 7036, NULL, NULL, 'Snare: A service entered the running/stopped state'),
(1518,100,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,1008,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,102,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,105,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,1076,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,1485,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17101,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17103,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17104,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17110,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17111,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17125,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17126,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17136,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17147,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17162,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17164,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17176,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17199,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17403,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,17663,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,19030,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,26018,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,26022,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,26028,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,26048,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,3408,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,3454,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,4133,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,4193,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,7,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,7888,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,958,NULL, NULL, 'Snare: Application event. More info on event details'),
(1518,9688,NULL, NULL, 'Snare: Application event. More info on event details');
