-- Snort preprocessors
-- type: detector
-- plugin_id: 1100-1145

DELETE FROM plugin WHERE id BETWEEN 1100 and 1145;
DELETE FROM plugin_sid WHERE plugin_id BETWEEN 1100 and 1145;

-- INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1001, 1, 'snort_snort', 'Snort General Alert');
-- INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1002, 1, 'snort_tag', 'Snort Tagging');
-- INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1003, 1, 'snort_snort-preprocessors', 'Snort Dynamic Alert');

INSERT IGNORE INTO plugin (id, type, name, description) VALUES
(1100, 1, 'snort_spp_portscan', 'Snort: Portscan preprocessor'),
(1101, 1, 'snort_spp_minfrag', 'Snort: Minfrag preprocessor'),
(1102, 1, 'snort_http_decode', 'Snort: HTTP decoder preprocessor'),
(1103, 1, 'snort_spp_defrag', 'Snort: defragmenter preprocessor'),
(1104, 1, 'snort_spp_anomsensor', 'Snort: SPADE preprocessor'),
(1105, 1, 'snort_spp_bo', 'Snort: Back Orifice preprocessor'),
(1106, 1, 'snort_spp_rpc_decode', 'Snort: RPC preprocessor'),
(1107, 1, 'snort_spp_stream2', 'Snort: stream preprocessor'),
(1108, 1, 'snort_spp_stream3', 'Snort: stream preprocessor'),
(1109, 1, 'snort_spp_telnet', 'Snort: telnet option decoder preprocessor'),
(1110, 1, 'snort_spp_unidecode', 'Snort: Unicode decoder preprocessor'),
(1111, 1, 'snort_spp_stream4', 'Snort: Stream4 preprocessor'),
(1112, 1, 'snort_spp_arpspoof', 'Snort: ARP spoof detector preprocessor'),
(1113, 1, 'snort_spp_frag2', 'Snort: fragment preprocessor'),
(1114, 1, 'snort_spp_fnord', 'Snort: NOP detector preprocessor '),
(1115, 1, 'snort_spp_asn1', 'Snort: ASN.1 validator preprocessor'),
(1116, 1, 'snort_snort_decoder', 'Snort: internal decoder preprocessor'),
(1117, 1, 'snort_spp_portscan2', 'Snort: portscan preprocessor'),
(1118, 1, 'snort_spp_conversation', 'Snort: conversation preprocessor'),
(1119, 1, 'snort_http_inspect', 'Snort: http data check preprocessor'),
(1120, 1, 'snort_http_inspect_anomalous', 'Snort: anomalous http server preprocessor'),
(1121, 1, 'snort_flow-portscan', 'Snort: flow decoder preprocessor'),
(1122, 1, 'snort_portscan', 'Snort: portscan decoder preprocessor'),
(1123, 1, 'snort_frag3', 'Snort: fragmentation decoder preprocessor'),
(1124, 1, 'snort_smtp', 'Snort: SMTP preprocessor'),
(1125, 1, 'snort_ftp_pp', 'Snort: FTP preprocessor'),
(1126, 1, 'snort_telnet_pp', 'Snort: telnet preprocessor'),
(1128, 1, 'snort_ssh', 'Snort: SSH preprocessor'),
(1129, 1, 'snort_stream5', 'Snort: TCP preprocessor'),
(1130, 1, 'snort_dcerp', 'Snort: DCE/RPC server preprocessor'),
(1131, 1, 'snort_dns', 'Snort: DNS preprocessor'),
(1133, 1, 'snort_dcerpc2', 'Snort: DCE/RPC server preprocessor v2'),
(1134, 1, 'snort_ppm', 'Snort: ppm preprocessor'),
(1135, 1, 'snort_internal', 'Snort: internal preprocessor'),
(1137, 1, 'snort_ssp_ssl', 'Snort: SSLPP preprocessor'),
(1138, 1, 'snort_sensitive_data', 'Snort: sensitive data preprocessor'),
(1139, 1, 'snort_sensitive_data2', 'Snort: sensitive data preprocessor'),
(1140, 1, 'snort_sip', 'Snort: SIP preprocessor'),
(1141, 1, 'snort_imap', 'Snort: IMAP preprocessor'),
(1142, 1, 'snort_pop', 'Snort: POP preprocessor'),
(1143, 1, 'snort_gtp', 'Snort: GTP preprocessor'),
(1144, 1, 'snort_modbus', 'Snort: Modbus preprocessor'),
(1145, 1, 'snort_dnp3', 'Snort: DNP3 preprocessor');

--
-- Snort preprocessors plugin sids
--

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES
(1100, 1, NULL, NULL, 'snort_spp_portscan: Portscan Detected'),
(1100, 2, NULL, NULL, 'snort_spp_portscan: Portscan Status'),
(1100, 3, NULL, NULL, 'snort_spp_portscan: Portscan Ended'),
(1101, 1, NULL, NULL, 'snort_spp_minfrag: minfrag alert'),
(1102, 1, NULL, NULL, 'snort_http_decode: Unicode Attack'),
(1102, 2, NULL, NULL, 'snort_http_decode: CGI NULL Byte Attack'),
(1102, 3, NULL, NULL, 'snort_http_decode: large method attempted'),
(1102, 4, NULL, NULL, 'snort_http_decode: missing uri'),
(1102, 5, NULL, NULL, 'snort_http_decode: double encoding detected'),
(1102, 6, NULL, NULL, 'snort_http_decode: illegal hex values detected'),
(1102, 7, NULL, NULL, 'snort_http_decode: overlong character detected'),
(1103, 1, NULL, NULL, 'snort_spp_defrag: Fragmentation Overflow Detected'),
(1103, 2, NULL, NULL, 'snort_spp_defrag: Stale Fragments Discarded'),
(1104, 1, NULL, NULL, 'snort_spp_anomsensor: SPADE Anomaly Threshold Exceeded'),
(1104, 2, NULL, NULL, 'snort_spp_anomsensor: SPADE Anomaly Threshold Adjusted'),
(1105, 1, NULL, NULL, 'snort_spp_bo: Back Orifice Traffic Detected'),
(1105, 2, NULL, NULL, 'snort_spp_bo: Back Orifice Client Traffic Detected'),
(1105, 3, NULL, NULL, 'snort_spp_bo: Back Orifice Server Traffic Detected'),
(1105, 4, NULL, NULL, 'snort_spp_bo: Back Orifice snort_Buffer Attack'),
(1106, 1, NULL, NULL, 'snort_spp_rpc_decode: Fragmented RPC Records'),
(1106, 2, NULL, NULL, 'snort_spp_rpc_decode: Multiple Records in one packet'),
(1106, 3, NULL, NULL, 'snort_spp_rpc_decode: Large RPC Record Fragment'),
(1106, 4, NULL, NULL, 'snort_spp_rpc_decode: Incomplete RPC segment'),
(1106, 5, NULL, NULL, 'snort_spp_rpc_decode: Zero-length RPC Fragment'),
(1110, 1, NULL, NULL, 'snort_spp_unidecode: CGI NULL Attack'),
(1110, 2, NULL, NULL, 'snort_spp_unidecode: Directory Traversal'),
(1110, 3, NULL, NULL, 'snort_spp_unidecode: Unknown Mapping'),
(1110, 4, NULL, NULL, 'snort_spp_unidecode: Invalid Mapping'),
(1111, 1, NULL, NULL, 'snort_spp_stream4: Stealth Activity Detected'),
(1111, 2, NULL, NULL, 'snort_spp_stream4: Evasive Reset Packet'),
(1111, 3, NULL, NULL, 'snort_spp_stream4: Retransmission'),
(1111, 4, NULL, NULL, 'snort_spp_stream4: Window Violation'),
(1111, 5, NULL, NULL, 'snort_spp_stream4: Data on SYN Packet'),
(1111, 6, NULL, NULL, 'snort_spp_stream4: Full XMAS Stealth Scan'),
(1111, 7, NULL, NULL, 'snort_spp_stream4: SAPU Stealth Scan'),
(1111, 8, NULL, NULL, 'snort_spp_stream4: FIN Stealth Scan'),
(1111, 9, NULL, NULL, 'snort_spp_stream4: NULL Stealth Scan'),
(1111, 10, NULL, NULL, 'snort_spp_stream4: NMAP XMAS Stealth Scan'),
(1111, 11, NULL, NULL, 'snort_spp_stream4: VECNA Stealth Scan'),
(1111, 12, NULL, NULL, 'snort_spp_stream4: NMAP Fingerprint Stateful Detection'),
(1111, 13, NULL, NULL, 'snort_spp_stream4: SYN FIN Stealth Scan'),
(1111, 14, NULL, NULL, 'snort_spp_stream4: TCP forward overlap detected'),
(1111, 15, NULL, NULL, 'snort_spp_stream4: TTL Evasion attempt'),
(1111, 16, NULL, NULL, 'snort_spp_stream4: Evasive retransmitted data attempt'),
(1111, 17, NULL, NULL, 'snort_spp_stream4: Evasive retransmitted data with the data split attempt'),
(1111, 18, NULL, NULL, 'snort_spp_stream4: Multiple acked'),
(1111, 19, NULL, NULL, 'snort_spp_stream4: Shifting to Emergency Session Mode'),
(1111, 20, NULL, NULL, 'snort_spp_stream4: Shifting to Suspend Mode'),
(1111, 21, NULL, NULL, 'snort_spp_stream4: TCP Timestamp option has value of zero'),
(1111, 22, NULL, NULL, 'snort_spp_stream4: Too many overlapping TCP packets'),
(1111, 23, NULL, NULL, 'snort_spp_stream4: Packet in established TCP stream missing ACK'),
(1111, 24, NULL, NULL, 'snort_spp_stream4: Evasive FIN Packet'),
(1111, 25, NULL, NULL, 'snort_spp_stream4: SYN on established'),
(1112, 1, NULL, NULL, 'snort_spp_arpspoof: Directed ARP Request'),
(1112, 2, NULL, NULL, 'snort_spp_arpspoof: Etherframe ARP Mismatch SRC'),
(1112, 3, NULL, NULL, 'snort_spp_arpspoof: Etherframe ARP Mismatch DST'),
(1112, 4, NULL, NULL, 'snort_spp_arpspoof: ARP Cache Overwrite Attack'),
(1113, 1, NULL, NULL, 'snort_spp_frag2: Oversized Frag'),
(1113, 2, NULL, NULL, 'snort_spp_frag2: Teardrop/Fragmentation Overlap Attack'),
(1113, 3, NULL, NULL, 'snort_spp_frag2: TTL evasion detected'),
(1113, 4, NULL, NULL, 'snort_spp_frag2: overlap detected'),
(1113, 5, NULL, NULL, 'snort_spp_frag2: Duplicate first fragments'),
(1113, 6, NULL, NULL, 'snort_spp_frag2: memcap exceeded'),
(1113, 7, NULL, NULL, 'snort_spp_frag2: Out of order fragments'),
(1113, 8, NULL, NULL, 'snort_spp_frag2: IP Options on Fragmented Packet'),
(1113, 9, NULL, NULL, 'snort_spp_frag2: Shifting to Emegency Session Mode'),
(1113, 10, NULL, NULL, 'snort_spp_frag2: Shifting to Suspend Mode'),
(1114, 1, NULL, NULL, 'snort_spp_fnord: Possible Mutated GENERIC NOP Sled detected'),
(1114, 2, NULL, NULL, 'snort_spp_fnord: Possible Mutated IA32 NOP Sled detected'),
(1114, 3, NULL, NULL, 'snort_spp_fnord: Possible Mutated HPPA NOP Sled detected'),
(1114, 4, NULL, NULL, 'snort_spp_fnord: Possible Mutated SPARC NOP Sled detected'),
(1115, 1, NULL, NULL, 'snort_spp_asn1: Indefinite ASN.1 length encoding'),
(1115, 2, NULL, NULL, 'snort_spp_asn1: Invalid ASN.1 length encoding'),
(1115, 3, NULL, NULL, 'snort_spp_asn1: ASN.1 oversized item, possible overflow'),
(1115, 4, NULL, NULL, 'snort_spp_asn1: ASN.1 spec violation, possible overflow'),
(1115, 5, NULL, NULL, 'snort_spp_asn1: ASN.1 Attack: Datum length > packet length'),
(1116, 1, NULL, NULL, 'snort_snort_decoder: WARNING: Not IPv4 datagram'),
(1116, 2, NULL, NULL, 'snort_snort_decoder: WARNING: hlen < IP_HEADER_LEN'),
(1116, 3, NULL, NULL, 'snort_snort_decoder: WARNING: IP dgm len < IP Hdr len'),
(1116, 4, NULL, NULL, 'snort_snort_decoder: WARNING: Bad IPv4 Options'),
(1116, 5, NULL, NULL, 'snort_snort_decoder: WARNING: Truncated IPv4 Options'),
(1116, 6, NULL, NULL, 'snort_snort_decoder: WARNING: IP dgm len > captured len'),
(1116, 45, NULL, NULL, 'snort_snort_decoder: WARNING: TCP packet len is smaller than 20 bytes'),
(1116, 46, NULL, NULL, 'snort_snort_decoder: WARNING: TCP Data Offset is less than 5'),
(1116, 47, NULL, NULL, 'snort_snort_decoder: WARNING: TCP Data Offset is longer than payload'),
(1116, 54, NULL, NULL, 'snort_snort_decoder: WARNING: Tcp Options found with bad lengths'),
(1116, 55, NULL, NULL, 'snort_snort_decoder: WARNING: Truncated Tcp Options'),
(1116, 56, NULL, NULL, 'snort_snort_decoder: WARNING: T/TCP Detected'),
(1116, 57, NULL, NULL, 'snort_snort_decoder: WARNING: Obsolete TCP options'),
(1116, 58, NULL, NULL, 'snort_snort_decoder: WARNING: Experimental TCP options'),
(1116, 59, NULL, NULL, 'snort_snort_decoder: WARNING: TCP Window Scale Option Scale Invalid (> 14)'),
(1116, 95, NULL, NULL, 'snort_snort_decoder: WARNING: Truncated UDP Header'),
(1116, 96, NULL, NULL, 'snort_snort_decoder: WARNING: Invalid UDP header, length field < 8'),
(1116, 97, NULL, NULL, 'snort_snort_decoder: WARNING: Short UDP packet, length field > payload length'),
(1116, 98, NULL, NULL, 'snort_snort_decoder: WARNING: Long UDP packet, length field < payload length'),
(1116, 105, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Header Truncated'),
(1116, 106, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Timestamp Header Truncated'),
(1116, 107, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Address Header Truncated'),
(1116, 108, NULL, NULL, 'snort_snort_decoder: WARNING: Unknown Datagram decoding problem'),
(1116, 109, NULL, NULL, 'snort_snort_decoder: WARNING: Truncated ARP Packet'),
(1116, 110, NULL, NULL, 'snort_snort_decoder: WARNING: Truncated EAP Header'),
(1116, 111, NULL, NULL, 'snort_snort_decoder: WARNING: EAP Key Truncated'),
(1116, 112, NULL, NULL, 'snort_snort_decoder: WARNING: EAP Header Truncated'),
(1116, 120, NULL, NULL, 'snort_snort_decoder: WARNING: Bad PPPOE frame detected'),
(1116, 130, NULL, NULL, 'snort_snort_decoder: WARNING: Bad VLAN Frame'),
(1116, 131, NULL, NULL, 'snort_snort_decoder: WARNING: Bad LLC header'),
(1116, 132, NULL, NULL, 'snort_snort_decoder: WARNING: Bad Extra LLC Info'),
(1116, 133, NULL, NULL, 'snort_snort_decoder: WARNING: Bad 802.11 LLC header'),
(1116, 134, NULL, NULL, 'snort_snort_decoder: WARNING: Bad 802.11 Extra LLC Info'),
(1116, 140, NULL, NULL, 'snort_snort_decoder: WARNING: Bad Token Ring Header'),
(1116, 141, NULL, NULL, 'snort_snort_decoder: WARNING: Bad Token Ring ETHLLC Header'),
(1116, 142, NULL, NULL, 'snort_snort_decoder: WARNING: Bad Token Ring MRLEN Header'),
(1116, 143, NULL, NULL, 'snort_snort_decoder: WARNING: Bad Token Ring MR Header'),
(1116, 150, NULL, NULL, 'snort_snort_decoder: WARNING: Bad Traffic Loopback IP'),
(1116, 151, NULL, NULL, 'snort_snort_decoder: WARNING: Bad Traffic Same Src/Dst IP'),
(1116, 160, NULL, NULL, 'snort_snort_decoder: WARNING: GRE header length > payload length'),
(1116, 161, NULL, NULL, 'snort_snort_decoder: WARNING: Multiple encapsulations in packet'),
(1116, 162, NULL, NULL, 'snort_snort_decoder: WARNING: Invalid GRE version'),
(1116, 163, NULL, NULL, 'snort_snort_decoder: WARNING: Invalid GRE v.0 header'),
(1116, 164, NULL, NULL, 'snort_snort_decoder: WARNING: Invalid GRE v.1 PPTP header'),
(1116, 165, NULL, NULL, 'snort_snort_decoder: WARNING: GRE Trans header length > payload length'),
(1116, 170, NULL, NULL, 'snort_snort_decoder: WARNING: Bad MPLS Frame'),
(1116, 171, NULL, NULL, 'snort_snort_decoder: WARNING: MPLS Label 0 Appears in Nonbottom Header'),
(1116, 172, NULL, NULL, 'snort_snort_decoder: WARNING: MPLS Label 1 Appears in Bottom Header'),
(1116, 173, NULL, NULL, 'snort_snort_decoder: WARNING: MPLS Label 2 Appears in Nonbottom Header'),
(1116, 174, NULL, NULL, 'snort_snort_decoder: WARNING: Bad use of label 3'),
(1116, 175, NULL, NULL, 'snort_snort_decoder: WARNING: MPLS Label 4, 5,.. or 15 Appears in Header'),
(1116, 176, NULL, NULL, 'snort_snort_decoder: WARNING: Too Many MPLS headers'),
(1116, 250, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Original IP Header Truncated'),
(1116, 251, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Original IP Header Not IPv4'),
(1116, 252, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Original Datagram Length < Original IP Header Length'),
(1116, 253, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Original IP Payload < 64 bits'),
(1116, 254, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Original IP Payload > 576 bytes'),
(1116, 255, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Original IP Fragmented and Offset Not 0'),
(1116, 270, NULL, NULL, 'snort_snort_decoder: WARNING: IPV6 packet exceeded TTL limit'),
(1116, 271, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 header claims to not be IPv6'),
(1116, 272, NULL, NULL, 'snort_snort_decoder: WARNING: IPV6 truncated extension header'),
(1116, 273, NULL, NULL, 'snort_snort_decoder: WARNING: IPV6 truncated header'),
(1116, 274, NULL, NULL, 'snort_snort_decoder: WARNING: IPV6 dgm len < IPV6 Hdr len'),
(1116, 275, NULL, NULL, 'snort_snort_decoder: WARNING: IPV6 dgm len > captured len'),
(1116, 276, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 packet with destination address ::0'),
(1116, 277, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 packet with multicast source address'),
(1116, 278, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 packet with reserved multicast destination address'),
(1116, 279, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 header includes an undefined option type'),
(1116, 280, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 address includes an unassigned multicast scope value'),
(1116, 281, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 header includes an invalid value for the "next header" field'),
(1116, 282, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 header includes a routing extension header followed by a hop-by-hop header'),
(1116, 283, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 header includes two routing extension headers'),
(1116, 285, NULL, NULL, 'snort_snort_decoder: WARNING: ICMPv6 packet of type 2 (message too big) with MTU field < 1280'),
(1116, 286, NULL, NULL, 'snort_snort_decoder: WARNING: ICMPv6 packet of type 1 (destination unreachable) with invalid code field'),
(1116, 287, NULL, NULL, 'snort_snort_decoder: WARNING: ICMPv6 router solicitation packet with a code not equal to 0'),
(1116, 288, NULL, NULL, 'snort_snort_decoder: WARNING: ICMPv6 router advertisement packet with a code not equal to 0'),
(1116, 289, NULL, NULL, 'snort_snort_decoder: WARNING: ICMPv6 router solicitation packet with the reserved field not equal to 0'),
(1116, 290, NULL, NULL, 'snort_snort_decoder: WARNING: ICMPv6 router advertisement packet with the reachable time field set > 1 hour'),
(1116, 291, NULL, NULL, 'snort_snort_decoder: WARNING: IPV6 tunneled over IPv4, IPv6 header truncated, possible Linux Kernel attack'),
(1116, 292, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 header has destination options followed by a routing header'),
(1116, 293, NULL, NULL, 'snort_snort_decoder: WARNING: Two or more IP (v4 and/or v6) encapsulation layers present'),
(1116, 294, NULL, NULL, 'snort_snort_decoder: WARNING: truncated Encapsulated Security Payload (ESP) header'),
(1116, 295, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 header includes an option which is too big for the containing header.'),
(1116, 296, NULL, NULL, 'snort_snort_decoder: WARNING: IPv6 packet includes out-of-order extension headers'),
(1116, 297, NULL, NULL, 'snort_snort_decoder: WARNING: Two or more GTP encapsulation layers are present'),
(1116, 298, NULL, NULL, 'snort_snort_decoder: WARNING: GTP header length is invalid'),
(1116, 400, NULL, NULL, 'snort_snort_decoder: WARNING: XMAS Attack Detected'),
(1116, 401, NULL, NULL, 'snort_snort_decoder: WARNING: Nmap XMAS Attack Detected'),
(1116, 402, NULL, NULL, 'snort_snort_decoder: WARNING: DOS NAPTHA Vulnerability Detected'),
(1116, 403, NULL, NULL, 'snort_snort_decoder: WARNING: Bad Traffic SYN to multicast address'),
(1116, 404, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet with zero TTL'),
(1116, 405, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet with bad frag bits (Both MF and DF set)'),
(1116, 406, NULL, NULL, 'snort_snort_decoder: WARNING: Invalid IPv6 UDP packet, checksum zero'),
(1116, 407, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet frag offset + length exceed maximum'),
(1116, 408, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet from \'current net\' source address'),
(1116, 409, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet to \'current net\' dest address'),
(1116, 410, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet from multicast source address'),
(1116, 411, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet from reserved source address'),
(1116, 412, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet to reserved dest address'),
(1116, 413, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet from broadcast source address'),
(1116, 414, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet to broadcast dest address'),
(1116, 415, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP4 packet to multicast dest address'),
(1116, 416, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP4 packet to broadcast dest address'),
(1116, 417, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP4 source quence'),
(1116, 418, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP4 type other'),
(1116, 419, NULL, NULL, 'snort_snort_decoder: WARNING: TCP urgent pointer exceeds payload length or no payload'),
(1116, 420, NULL, NULL, 'snort_snort_decoder: WARNING: TCP SYN with FIN'),
(1116, 421, NULL, NULL, 'snort_snort_decoder: WARNING: TCP SYN with RST'),
(1116, 422, NULL, NULL, 'snort_snort_decoder: WARNING: TCP PDU missing ack for established session'),
(1116, 423, NULL, NULL, 'snort_snort_decoder: WARNING: TCP has no SYN, ACK, or RST'),
(1116, 424, NULL, NULL, 'snort_snort_decoder: WARNING: truncated eth header'),
(1116, 425, NULL, NULL, 'snort_snort_decoder: WARNING: truncated IP4 header'),
(1116, 426, NULL, NULL, 'snort_snort_decoder: WARNING: truncated ICMP4 header'),
(1116, 427, NULL, NULL, 'snort_snort_decoder: WARNING: truncated ICMP6 header'),
(1116, 428, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet below TTL limit'),
(1116, 429, NULL, NULL, 'snort_snort_decoder: WARNING: IPV6 packet has zero hop limit'),
(1116, 430, NULL, NULL, 'snort_snort_decoder: WARNING: IPV4 packet both DF and offset set'),
(1116, 431, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP6 type not decoded'),
(1116, 432, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP6 packet to multicast address'),
(1116, 433, NULL, NULL, 'snort_snort_decoder: WARNING: DDOS shaft synflood'),
(1116, 434, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP PING NMAP'),
(1116, 435, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP icmpenum v1.1.1'),
(1116, 436, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP redirect host'),
(1116, 437, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP redirect net'),
(1116, 438, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP traceroute ipopts'),
(1116, 439, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Source Quench'),
(1116, 440, NULL, NULL, 'snort_snort_decoder: WARNING: Broadscan Smurf Scanner'),
(1116, 441, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Destination Unreachable Communication Administratively Prohibited'),
(1116, 442, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Destination Unreachable Communication with Destination Host is Administratively Prohibited'),
(1116, 443, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP Destination Unreachable Communication with Destination Network is Administratively Prohibited'),
(1116, 444, NULL, NULL, 'snort_snort_decoder: WARNING: MISC IP option set'),
(1116, 445, NULL, NULL, 'snort_snort_decoder: WARNING: MISC Large UDP Packet'),
(1116, 446, NULL, NULL, 'snort_snort_decoder: WARNING: BAD-TRAFFIC TCP port 0 traffic'),
(1116, 447, NULL, NULL, 'snort_snort_decoder: WARNING: BAD-TRAFFIC UDP port 0 traffic'),
(1116, 448, NULL, NULL, 'snort_snort_decoder: WARNING: BAD-TRAFFIC IP reserved bit set'),
(1116, 449, NULL, NULL, 'snort_snort_decoder: WARNING: BAD-TRAFFIC Unassigned/Reserved IP protocol'),
(1116, 450, NULL, NULL, 'snort_snort_decoder: WARNING: BAD-TRAFFIC Bad IP protocol'),
(1116, 451, NULL, NULL, 'snort_snort_decoder: WARNING: ICMP PATH MTU denial of service attempt'),
(1116, 452, NULL, NULL, 'snort_snort_decoder: WARNING: BAD-TRAFFIC linux ICMP header dos attempt'),
(1116, 453, NULL, NULL, 'snort_snort_decoder: WARNING: IPV6 ISATAP spoof'),
(1116, 454, NULL, NULL, 'snort_snort_decoder: WARNING: PGM NAK overflow'),
(1116, 455, NULL, NULL, 'snort_snort_decoder: WARNING: IGMP options dos'),
(1116, 456, NULL, NULL, 'snort_snort_decoder: WARNING: too many IPV6 extension headers'),
(1117, 1, NULL, NULL, 'snort_spp_portscan2: Portscan detected'),
(1118, 1, NULL, NULL, 'snort_spp_conversation: Bad IP protocol'),
(1119, 1, NULL, NULL, 'snort_http_inspect: ASCII ENCODING'),
(1119, 2, NULL, NULL, 'snort_http_inspect: DOUBLE DECODING ATTACK'),
(1119, 3, NULL, NULL, 'snort_http_inspect: U ENCODING'),
(1119, 4, NULL, NULL, 'snort_http_inspect: BARE BYTE UNICODE ENCODING'),
(1119, 5, NULL, NULL, 'snort_http_inspect: BASE36 ENCODING'),
(1119, 6, NULL, NULL, 'snort_http_inspect: UTF-8 ENCODING'),
(1119, 7, NULL, NULL, 'snort_http_inspect: IIS UNICODE CODEPOINT ENCODING'),
(1119, 8, NULL, NULL, 'snort_http_inspect: MULTI_SLASH ENCODING'),
(1119, 9, NULL, NULL, 'snort_http_inspect: IIS BACKSLASH EVASION'),
(1119, 10, NULL, NULL, 'snort_http_inspect: SELF DIRECTORY TRAVERSAL'),
(1119, 11, NULL, NULL, 'snort_http_inspect: DIRECTORY TRAVERSAL'),
(1119, 12, NULL, NULL, 'snort_http_inspect: APACHE WHITESPACE (TAB)'),
(1119, 13, NULL, NULL, 'snort_http_inspect: NON-RFC HTTP DELIMITER'),
(1119, 14, NULL, NULL, 'snort_http_inspect: NON-RFC DEFINED CHAR'),
(1119, 15, NULL, NULL, 'snort_http_inspect: OVERSIZE REQUEST-URI DIRECTORY'),
(1119, 16, NULL, NULL, 'snort_http_inspect: OVERSIZE CHUNK ENCODING'),
(1119, 17, NULL, NULL, 'snort_http_inspect: UNAUTHORIZED PROXY USE DETECTED'),
(1119, 18, NULL, NULL, 'snort_http_inspect: WEBROOT DIRECTORY TRAVERSAL'),
(1119, 19, NULL, NULL, 'snort_http_inspect: LONG HEADER'),
(1119, 20, NULL, NULL, 'snort_http_inspect: MAX HEADERS'),
(1119, 21, NULL, NULL, 'snort_http_inspect: MULTIPLE CONTENT LENGTH HEADER FIELDS'),
(1119, 22, NULL, NULL, 'snort_http_inspect: CHUNK SIZE MISMATCH DETECTED'),
(1119, 23, NULL, NULL, 'snort_http_inspect: INVALID IP IN TRUE-CLIENT-IP/XFF HEADER'),
(1119, 24, NULL, NULL, 'snort_http_inspect: MULTIPLE HOST HEADERS DETECTED '),
(1119, 25, NULL, NULL, 'snort_http_inspect: HOSTNAME EXCEEDS 255 CHARACTERS'),
(1119, 26, NULL, NULL, 'snort_http_inspect: HEADER PARSING SPACE SATURATION'),
(1119, 27, NULL, NULL, 'snort_http_inspect: CHUNKED ENCODING - EXCESSIVE CONSECUTIVE SMALL CHUNKS'),
(1119, 28, NULL, NULL, 'snort_http_inspect: POST W/O CONTENT-LENGTH OR CHUNKS'),
(1119, 29, NULL, NULL, 'snort_http_inspect: MULTIPLE TRUE IPS IN A SESSION'),
(1119, 30, NULL, NULL, 'snort_http_inspect: BOTH TRUE_CLIENT_IP AND XFF HDRS PRESENT'),
(1119, 31, NULL, NULL, 'snort_http_inspect: UNKNOWN METHOD'),
(1119, 32, NULL, NULL, 'snort_http_inspect: SIMPLE REQUEST'),
(1120, 1, NULL, NULL, 'snort_http_inspect: ANOMALOUS HTTP SERVER ON UNDEFINED HTTP PORT'),
(1120, 2, NULL, NULL, 'snort_http_inspect: INVALID STATUS CODE IN HTTP RESPONSE'),
(1120, 3, NULL, NULL, 'snort_http_inspect: NO CONTENT-LENGTH OR TRANSFER-ENCODING IN HTTP RESPONSE'),
(1120, 4, NULL, NULL, 'snort_http_inspect: HTTP RESPONSE HAS UTF CHARSET WHICH FAILED TO NORMALIZE'),
(1120, 5, NULL, NULL, 'snort_http_inspect: HTTP RESPONSE HAS UTF-7 CHARSET'),
(1120, 6, NULL, NULL, 'snort_http_inspect: HTTP RESPONSE GZIP DECOMPRESSION FAILED'),
(1120, 7, NULL, NULL, 'snort_http_inspect: CHUNKED ENCODING - EXCESSIVE CONSECUTIVE SMALL CHUNKS'),
(1120, 8, NULL, NULL, 'snort_http_inspect: MESSAGE WITH INVALID CONTENT-LENGTH OR CHUNK SIZE'),
(1120, 9, NULL, NULL, 'snort_http_inspect: JAVASCRIPT OBFUSCATION LEVELS EXCEEDS 1'),
(1120, 10, NULL, NULL, 'snort_http_inspect: JAVASCRIPT WHITESPACES EXCEEDS MAX ALLOWED'),
(1120, 11, NULL, NULL, 'snort_http_inspect: MULTIPLE ENCODINGS WITHIN JAVASCRIPT OBFUSCATED DATA'),
(1121, 1, NULL, NULL, 'snort_flow-portscan: Fixed Scale Scanner Limit Exceeded'),
(1121, 2, NULL, NULL, 'snort_flow-portscan: Sliding Scale Scanner Limit Exceeded'),
(1121, 3, NULL, NULL, 'snort_flow-portscan: Fixed Scale Talker Limit Exceeded'),
(1121, 4, NULL, NULL, 'snort_flow-portscan: Sliding Scale Talker Limit Exceeded'),
(1122, 1, NULL, NULL, 'snort_portscan: TCP Portscan'),
(1122, 2, NULL, NULL, 'snort_portscan: TCP Decoy Portscan'),
(1122, 3, NULL, NULL, 'snort_portscan: TCP Portsweep'),
(1122, 4, NULL, NULL, 'snort_portscan: TCP Distributed Portscan'),
(1122, 5, NULL, NULL, 'snort_portscan: TCP Filtered Portscan'),
(1122, 6, NULL, NULL, 'snort_portscan: TCP Filtered Decoy Portscan'),
(1122, 7, NULL, NULL, 'snort_portscan: TCP Filtered Portsweep'),
(1122, 8, NULL, NULL, 'snort_portscan: TCP Filtered Distributed Portscan'),
(1122, 9, NULL, NULL, 'snort_portscan: IP Protocol Scan'),
(1122, 10, NULL, NULL, 'snort_portscan: IP Decoy Protocol Scan'),
(1122, 11, NULL, NULL, 'snort_portscan: IP Protocol Sweep'),
(1122, 12, NULL, NULL, 'snort_portscan: IP Distributed Protocol Scan'),
(1122, 13, NULL, NULL, 'snort_portscan: IP Filtered Protocol Scan'),
(1122, 14, NULL, NULL, 'snort_portscan: IP Filtered Decoy Protocol Scan'),
(1122, 15, NULL, NULL, 'snort_portscan: IP Filtered Protocol Sweep'),
(1122, 16, NULL, NULL, 'snort_portscan: IP Filtered Distributed Protocol Scan'),
(1122, 17, NULL, NULL, 'snort_portscan: UDP Portscan'),
(1122, 18, NULL, NULL, 'snort_portscan: UDP Decoy Portscan'),
(1122, 19, NULL, NULL, 'snort_portscan: UDP Portsweep'),
(1122, 20, NULL, NULL, 'snort_portscan: UDP Distributed Portscan'),
(1122, 21, NULL, NULL, 'snort_portscan: UDP Filtered Portscan'),
(1122, 22, NULL, NULL, 'snort_portscan: UDP Filtered Decoy Portscan'),
(1122, 23, NULL, NULL, 'snort_portscan: UDP Filtered Portsweep'),
(1122, 24, NULL, NULL, 'snort_portscan: UDP Filtered Distributed Portscan'),
(1122, 25, NULL, NULL, 'snort_portscan: ICMP Sweep'),
(1122, 26, NULL, NULL, 'snort_portscan: ICMP Filtered Sweep'),
(1122, 27, NULL, NULL, 'snort_portscan: Open Port'),
(1123, 1, NULL, NULL, 'snort_frag3: IP Options on fragmented packet'),
(1123, 2, NULL, NULL, 'snort_frag3: Teardrop attack'),
(1123, 3, NULL, NULL, 'snort_frag3: Short fragment, possible DoS attempt'),
(1123, 4, NULL, NULL, 'snort_frag3: Fragment packet ends after defragmented packet'),
(1123, 5, NULL, NULL, 'snort_frag3: Zero-byte fragment'),
(1123, 6, NULL, NULL, 'snort_frag3: Bad fragment size, packet size is negative'),
(1123, 7, NULL, NULL, 'snort_frag3: Bad fragment size, packet size is greater than 65536'),
(1123, 8, NULL, NULL, 'snort_frag3: Fragmentation overlap'),
(1123, 9, NULL, NULL, 'snort_frag3: IPv6 BSD mbufs remote kernel buffer overflow'),
(1123, 10, NULL, NULL, 'snort_frag3: Bogus fragmentation packet. Possible BSD attack'),
(1123, 11, NULL, NULL, 'snort_frag3: TTL value less than configured minimum, not using for reassembly'),
(1123, 12, NULL, NULL, 'snort_frag3: Number of overlapping fragments exceed configured limit'),
(1123, 13, NULL, NULL, 'snort_frag3: Fragments smaller than configured min_fragment_length'),
(1124, 1, NULL, NULL, 'snort_smtp: Attempted command buffer overflow'),
(1124, 2, NULL, NULL, 'snort_smtp: Attempted data header buffer overflow'),
(1124, 3, NULL, NULL, 'snort_smtp: Attempted response buffer overflow'),
(1124, 4, NULL, NULL, 'snort_smtp: Attempted specific command buffer overflow'),
(1124, 5, NULL, NULL, 'snort_smtp: Unknown command'),
(1124, 6, NULL, NULL, 'snort_smtp: Illegal command'),
(1124, 7, NULL, NULL, 'snort_smtp: Attempted header name buffer overflow'),
(1124, 8, NULL, NULL, 'snort_smtp: Attempted X-Link2State command buffer overflow'),
(1124, 9, NULL, NULL, 'snort_smtp: No memory available for decoding. Max Mime Mem exceeded.'),
(1124, 10, NULL, NULL, 'snort_smtp: Base64 Decoding failed'),
(1124, 11, NULL, NULL, 'snort_smtp: Quoted-Printable Decoding failed'),
(1124, 12, NULL, NULL, 'snort_smtp: 7bit/8bit/binary/text Extraction failed'),
(1124, 13, NULL, NULL, 'snort_smtp: Unix-to-Unix Decoding failed'),
(1125, 1, NULL, NULL, 'snort_ftp_pp: Telnet command on FTP command channel'),
(1125, 2, NULL, NULL, 'snort_ftp_pp: Invalid FTP command'),
(1125, 3, NULL, NULL, 'snort_ftp_pp: FTP parameter length overflow'),
(1125, 4, NULL, NULL, 'snort_ftp_pp: FTP malformed parameter'),
(1125, 5, NULL, NULL, 'snort_ftp_pp: Possible string format attempt in FTP command/parameter'),
(1125, 6, NULL, NULL, 'snort_ftp_pp: FTP response length overflow'),
(1125, 7, NULL, NULL, 'snort_ftp_pp: FTP command channel encrypted'),
(1125, 8, NULL, NULL, 'snort_ftp_pp: FTP bounce attack'),
(1125, 9, NULL, NULL, 'snort_ftp_pp: Evasive Telnet command on FTP command channel'),
(1126, 1, NULL, NULL, 'snort_telnet_pp: Telnet consecutive AYT overflow'),
(1126, 2, NULL, NULL, 'snort_telnet_pp: Telnet data encrypted'),
(1126, 3, NULL, NULL, 'snort_telnet_pp: Subnegotiation Begin without matching Subnegotiation End'),
(1128, 1, NULL, NULL, 'snort_ssh: Gobbles exploit'),
(1128, 2, NULL, NULL, 'snort_ssh: SSH1 CRC32 exploit'),
(1128, 3, NULL, NULL, 'snort_ssh: Server version string overflow'),
(1128, 4, NULL, NULL, 'snort_ssh: Protocol mismatch'),
(1128, 5, NULL, NULL, 'snort_ssh: Bad message direction'),
(1128, 6, NULL, NULL, 'snort_ssh: Payload size incorrect for the given payload'),
(1128, 7, NULL, NULL, 'snort_ssh: Failed to detect SSH version string'),
(1129, 1, NULL, NULL, 'snort_stream5: SYN on established session'),
(1129, 2, NULL, NULL, 'snort_stream5: Data on SYN packet'),
(1129, 3, NULL, NULL, 'snort_stream5: Data sent on stream not accepting data'),
(1129, 4, NULL, NULL, 'snort_stream5: TCP Timestamp is outside of PAWS window'),
(1129, 5, NULL, NULL, 'snort_stream5: Bad segment, overlap adjusted size less than/equal 0'),
(1129, 6, NULL, NULL, 'snort_stream5: Window size (after scaling) larger than policy allows'),
(1129, 7, NULL, NULL, 'snort_stream5: Limit on number of overlapping TCP packets reached'),
(1129, 8, NULL, NULL, 'snort_stream5: Data sent on stream after TCP Reset'),
(1129, 9, NULL, NULL, 'snort_stream5: TCP Client possibly hijacked, different Ethernet Address'),
(1129, 10, NULL, NULL, 'snort_stream5: TCP Server possibly hijacked, different Ethernet Address'),
(1129, 11, NULL, NULL, 'snort_stream5: TCP Data with no TCP Flags set'),
(1129, 12, NULL, NULL, 'snort_stream5: TCP Small Segment Threshold Exceeded'),
(1129, 13, NULL, NULL, 'snort_stream5: TCP 4-way handshake detected'),
(1129, 14, NULL, NULL, 'snort_stream5: TCP Timestamp is missing'),
(1129, 15, NULL, NULL, 'snort_stream5: Reset outside window'),
(1129, 16, NULL, NULL, 'snort_stream5: FIN number is greater than prior FIN'),
(1129, 17, NULL, NULL, 'snort_stream5: ACK number is greater than prior FIN'),
(1129, 18, NULL, NULL, 'snort_stream5: Data sent on stream after TCP Reset received'),
(1129, 19, NULL, NULL, 'snort_stream5: TCP window closed before receiving data'),
(1130, 1, NULL, NULL, 'snort_dcerpc: Maximum memory usage reached'),
(1131, 1, NULL, NULL, 'snort_dns: Obsolete DNS RData Type'),
(1131, 2, NULL, NULL, 'snort_dns: Experimental DNS RData Type'),
(1131, 3, NULL, NULL, 'snort_dns: Client RData TXT Overflow'),
(1133, 1, NULL, NULL, 'snort_dcerpc2: Memory cap exceeded'),
(1133, 2, NULL, NULL, 'snort_dcerpc2: SMB - Bad NetBIOS Session Service session type'),
(1133, 3, NULL, NULL, 'snort_dcerpc2: SMB - Bad SMB message type'),
(1133, 4, NULL, NULL, 'snort_dcerpc2: SMB - Bad SMB Id (not "\xffSMB" for SMB1 or not "\xfeSMB" for SMB2)'),
(1133, 5, NULL, NULL, 'snort_dcerpc2: SMB - Bad word count or structure size for command'),
(1133, 6, NULL, NULL, 'snort_dcerpc2: SMB - Bad byte count for command'),
(1133, 7, NULL, NULL, 'snort_dcerpc2: SMB - Bad format type for command'),
(1133, 8, NULL, NULL, 'snort_dcerpc2: SMB - Bad AndX or data offset in command'),
(1133, 9, NULL, NULL, 'snort_dcerpc2: SMB - Zero total data count in command'),
(1133, 10, NULL, NULL, 'snort_dcerpc2: SMB - NetBIOS data length less than SMB header length'),
(1133, 11, NULL, NULL, 'snort_dcerpc2: SMB - Remaining NetBIOS data length less than command length'),
(1133, 12, NULL, NULL, 'snort_dcerpc2: SMB - Remaining NetBIOS data length less than command byte count'),
(1133, 13, NULL, NULL, 'snort_dcerpc2: SMB - Remaining NetBIOS data length less than command data size'),
(1133, 14, NULL, NULL, 'snort_dcerpc2: SMB - Remaining total data count less than this command data size'),
(1133, 15, NULL, NULL, 'snort_dcerpc2: SMB - Total data sent greater than command total data expected'),
(1133, 16, NULL, NULL, 'snort_dcerpc2: SMB - Byte count less than command data size'),
(1133, 17, NULL, NULL, 'snort_dcerpc2: SMB - Invalid command data size for byte count'),
(1133, 18, NULL, NULL, 'snort_dcerpc2: SMB - Excessive Tree Connect requests with pending Tree Connect responses'),
(1133, 19, NULL, NULL, 'snort_dcerpc2: SMB - Excessive Read requests with pending Read responses'),
(1133, 20, NULL, NULL, 'snort_dcerpc2: SMB - Excessive command chaining'),
(1133, 21, NULL, NULL, 'snort_dcerpc2: SMB - Multiple chained login requests'),
(1133, 22, NULL, NULL, 'snort_dcerpc2: SMB - Multiple chained tree connect requests'),
(1133, 23, NULL, NULL, 'snort_dcerpc2: SMB - Chained/Compounded login followed by logoff'),
(1133, 24, NULL, NULL, 'snort_dcerpc2: SMB - Chained/Compounded tree connect followed by tree disconnect'),
(1133, 25, NULL, NULL, 'snort_dcerpc2: SMB - Chained/Compounded open pipe followed by close pipe'),
(1133, 26, NULL, NULL, 'snort_dcerpc2: SMB - Invalid share access'),
(1133, 27, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Invalid major version'),
(1133, 28, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Invalid minor version'),
(1133, 29, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Invalid pdu type'),
(1133, 30, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Fragment length less than header size'),
(1133, 31, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Remaining fragment length less than size needed'),
(1133, 32, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - No context items specified'),
(1133, 33, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - No transfer syntaxes specified'),
(1133, 34, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Fragment length on non-last fragment less than maximum negotiated fragment transmit size for client'),
(1133, 35, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Fragment length greater than maximum negotiated fragment transmit size'),
(1133, 36, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Alter Context byte order different from Bind'),
(1133, 37, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Call id of non first/last fragment different from call id established for fragmented request'),
(1133, 38, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Opnum of non first/last fragment different from opnum established for fragmented request'),
(1133, 39, NULL, NULL, 'snort_dcerpc2: Connection-oriented DCE/RPC - Context id of non first/last fragment different from context id established for fragmented request'),
(1133, 40, NULL, NULL, 'snort_dcerpc2: Connectionless DCE/RPC - Invalid major version'),
(1133, 41, NULL, NULL, 'snort_dcerpc2: Connectionless DCE/RPC - Invalid pdu type'),
(1133, 42, NULL, NULL, 'snort_dcerpc2: Connectionless DCE/RPC - Data length less than header size'),
(1133, 43, NULL, NULL, 'snort_dcerpc2: Connectionless DCE/RPC - Bad sequence number'),
(1133, 44, NULL, NULL, 'snort_dcerpc2: SMB - Invalid SMB version 1 seen'),
(1133, 45, NULL, NULL, 'snort_dcerpc2: SMB - Invalid SMB version 2 seen'),
(1133, 46, NULL, NULL, 'snort_dcerpc2: SMB - Invalid user, tree connect, file binding'),
(1133, 47, NULL, NULL, 'snort_dcerpc2: SMB - Excessive command compounding'),
(1134, 1, NULL, NULL, 'snort_ppm: rule tree disabled'),
(1134, 2, NULL, NULL, 'snort_ppm: rule tree enabled'),
(1135, 1, NULL, NULL, 'snort_internal: syn received'),
(1135, 2, NULL, NULL, 'snort_internal: session established'),
(1135, 3, NULL, NULL, 'snort_internal: session cleared'),
(1136, 1, NULL, NULL, 'snort_reputation: Packet is blacklisted'),
(1136, 2, NULL, NULL, 'snort_reputation: Packet is whitelisted'),
(1137, 1, NULL, NULL, 'snort_ssp_ssl: Invalid Client HELLO after Server HELLO Detected'),
(1137, 2, NULL, NULL, 'snort_ssp_ssl: Invalid Server HELLO without Client HELLO Detected'),
(1138, 2, NULL, NULL, 'snort_sensitive_data: sensitive data - Credit card numbers'),
(1138, 3, NULL, NULL, 'snort_sensitive_data: sensitive data - U.S. social security numbers with dashes'),
(1138, 4, NULL, NULL, 'snort_sensitive_data: sensitive data - U.S. social security numbers without dashes'),
(1138, 5, NULL, NULL, 'snort_sensitive_data: sensitive data - eMail addresses'),
(1138, 6, NULL, NULL, 'snort_sensitive_data: sensitive data - U.S. phone numbers'),
(1139, 1, NULL, NULL, 'snort_sensitive_data: sensitive data global threshold exceeded'),
(1140, 1, NULL, NULL, 'snort_sip: Maximum sessions reached '),
(1140, 2, NULL, NULL, 'snort_sip: Empty request URI '),
(1140, 3, NULL, NULL, 'snort_sip: URI is too long'),
(1140, 4, NULL, NULL, 'snort_sip: Empty call-Id'),
(1140, 5, NULL, NULL, 'snort_sip: Call-Id is too long'),
(1140, 6, NULL, NULL, 'snort_sip: CSeq number is too large or negative'),
(1140, 7, NULL, NULL, 'snort_sip: Request name in CSeq is too long '),
(1140, 8, NULL, NULL, 'snort_sip: Empty From header'),
(1140, 9, NULL, NULL, 'snort_sip: From header is too long'),
(1140, 10, NULL, NULL, 'snort_sip: Empty To header'),
(1140, 11, NULL, NULL, 'snort_sip: To header is too long'),
(1140, 12, NULL, NULL, 'snort_sip: Empty Via header '),
(1140, 13, NULL, NULL, 'snort_sip: Via header is too long'),
(1140, 14, NULL, NULL, 'snort_sip: Empty Contact'),
(1140, 15, NULL, NULL, 'snort_sip: Contact is too long'),
(1140, 16, NULL, NULL, 'snort_sip: Content length is too large or negative'),
(1140, 17, NULL, NULL, 'snort_sip: Multiple SIP messages in a packet'),
(1140, 18, NULL, NULL, 'snort_sip: Content length mismatch'),
(1140, 19, NULL, NULL, 'snort_sip: Request name is invalid'),
(1140, 20, NULL, NULL, 'snort_sip: Invite replay attack'),
(1140, 21, NULL, NULL, 'snort_sip: Illegal session information modification'),
(1140, 22, NULL, NULL, 'snort_sip: Response status code is not a 3 digit number'),
(1140, 23, NULL, NULL, 'snort_sip: Empty Content type'),
(1140, 24, NULL, NULL, 'snort_sip: SIP version other than 2.0, 1.0, and 1.1 are invalid'),
(1140, 25, NULL, NULL, 'snort_sip: Mismatch in Method of request and the CSEQ header'),
(1140, 26, NULL, NULL, 'snort_sip: The method is unknown'),
(1140, 27, NULL, NULL, 'snort_sip: Maximum dialogs in a session reached '),
(1141, 1, NULL, NULL, 'snort_imap: Unknown IMAP4 command'),
(1141, 2, NULL, NULL, 'snort_imap: Unknown IMAP4 response'),
(1141, 3, NULL, NULL, 'snort_imap: No memory available for decoding. Memcap exceeded.'),
(1141, 4, NULL, NULL, 'snort_imap: Base64 Decoding failed'),
(1141, 5, NULL, NULL, 'snort_imap: Quoted-Printable Decoding failed'),
(1141, 6, NULL, NULL, 'snort_imap: 7bit/8bit/binary/text Extraction failed'),
(1141, 7, NULL, NULL, 'snort_imap: Unix-to-Unix Decoding failed'),
(1142, 1, NULL, NULL, 'snort_pop: Unknown POP3 command'),
(1142, 2, NULL, NULL, 'snort_pop: Unknown POP3 response'),
(1142, 3, NULL, NULL, 'snort_pop: No memory available for decoding. Memcap exceeded.'),
(1142, 4, NULL, NULL, 'snort_pop: Base64 Decoding failed'),
(1142, 5, NULL, NULL, 'snort_pop: Quoted-Printable Decoding failed'),
(1142, 6, NULL, NULL, 'snort_pop: 7bit/8bit/binary/text Extraction failed'),
(1142, 7, NULL, NULL, 'snort_pop: Unix-to-Unix Decoding failed'),
(1143, 1, NULL, NULL, 'snort_gtp: Message length is invalid'),
(1143, 2, NULL, NULL, 'snort_gtp: Information element length is invalid'),
(1143, 3, NULL, NULL, 'snort_gtp: Information elements are out of order'),
(1144, 1, NULL, NULL, 'snort_modbus: Length in Modbus MBAP header does not match the length needed for the given Modbus function.'),
(1144, 2, NULL, NULL, 'snort_modbus: Modbus protocol ID is non-zero.'),
(1144, 3, NULL, NULL, 'snort_modbus: Reserved Modbus function code in use.'),
(1145, 1, NULL, NULL, 'snort_dnp3: DNP3 Link-Layer Frame contains bad CRC.'),
(1145, 2, NULL, NULL, 'snort_dnp3: DNP3 Link-Layer Frame was dropped.'),
(1145, 3, NULL, NULL, 'snort_dnp3: DNP3 Transport-Layer Segment was dropped during reassembly.'),
(1145, 4, NULL, NULL, 'snort_dnp3: DNP3 Reassembly Buffer was cleared without reassembling a complete message.'),
(1145, 5, NULL, NULL, 'snort_dnp3: DNP3 Link-Layer Frame uses a reserved address.'),
(1145, 6, NULL, NULL, 'snort_dnp3: DNP3 Application-Layer Fragment uses a reserved function code.');

