-- SymantecEPM
-- plugin_id: 1619

DELETE FROM plugin WHERE id = "1619";
DELETE FROM plugin_sid where plugin_id = "1619";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1619, 1, 'SymantecEPM', 'SymantecEPM: Symantec AV Server');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 1, NULL, NULL, 'SymantecEPM: Received a new policy from Symantec Endpoint Protection Manager', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 2, NULL, NULL, 'SymantecEPM: Applied new policy', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 3, NULL, NULL, 'SymantecEPM: Location has been changed to Default', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 4, NULL, NULL, 'SymantecEPM: Failed to contact server for more than 10 times', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 5, NULL, NULL, 'SymantecEPM: Block running programs from removable media', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 6, NULL, NULL, 'SymantecEPM: Log writing to USB drives', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 7, NULL, NULL, 'SymantecEPM:TruScan Error - Heuristic Scan or Load Failure', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 8, NULL, NULL, 'SymantecEPM: Client services Registry Write', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 9, NULL, NULL, 'SymantecEPM: Symantec Endpoint Protection services shutdown was successful', 3, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 10, NULL, NULL, 'SymantecEPM: Symantec Endpoint Protection services startup was successful', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 11, NULL, NULL, 'SymantecEPM: Virus Found', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 12, NULL, NULL, 'SymantecEPM: Administrator log on failed', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 13, NULL, NULL, 'SymantecEPM: Administrator log on succeeded', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 14, NULL, NULL, 'SymantecEPM: Policy Edited', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 15, NULL, NULL, 'SymantecEPM: Computer has been moved', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 16, NULL, NULL, 'SymantecEPM: Failed to connect to the server', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 17, NULL, NULL, 'SymantecEPM: Symantec Endpoint Protection Manager Content Catalog Update Information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 18, NULL, NULL, 'SymantecEPM: Decomposer Win32 and Win64 up-to-date information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 19, NULL, NULL, 'SymantecEPM: TruScan proactive threat scan commercial application list up-to-date information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 20, NULL, NULL, 'SymantecEPM: TruScan proactive threat scan whitelist up-to-date information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 21, NULL, NULL, 'SymantecEPM: TruScan proactive threat scan data up-to-date information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 22, NULL, NULL, 'SymantecEPM: Submission Control signatures up-to-date information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 23, NULL, NULL, 'SymantecEPM: TruScan proactive threat scan engine up-to-date information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 24, NULL, NULL, 'SymantecEPM: Intrusion Prevention signatures up-to-date information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 25, NULL, NULL, 'SymantecEPM: TruScan proactive threat scan whitelist up-to-date information', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 26, NULL, NULL, 'SymantecEPM: LiveUpdate encountered one or more errors', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 27, NULL, NULL, 'SymantecEPM: LUALL.EXE finished running', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 28, NULL, NULL, 'SymantecEPM: LiveUpdate retry failed. Will try again.', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 29, NULL, NULL, 'SymantecEPM: Retry timestamp is over the maximum retry window, switching to regular schedule run.', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 30, NULL, NULL, 'SymantecEPM: LDAP Error', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 31, NULL, NULL, 'SymantecEPM: Administrator log out', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 32, NULL, NULL, 'SymantecEPM: Computer has been deleted', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 33, NULL, NULL, 'SymantecEPM: Number of old risk events compressed', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 34, NULL, NULL, 'SymantecEPM: Number of virus definition records swept', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 35, NULL, NULL, 'SymantecEPM: Number of acknowledged notifications swept', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 36, NULL, NULL, 'SymantecEPM: Number of compressed risk events swept', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 37, NULL, NULL, 'SymantecEPM: Number of scan events swept', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 38, NULL, NULL, 'SymantecEPM: LiveUpdate started', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 39, NULL, NULL, 'SymantecEPM: LUALL.EXE has been launched', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 40, NULL, NULL, 'SymantecEPM: Antivirus and antispyware is up-to-date', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 41, NULL, NULL, 'SymantecEPM: TruScan proactive threat scan commercial application engine', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 42, NULL, NULL, 'SymantecEPM: Generic Up to date', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 43, NULL, NULL, 'SymantecEPM: System client-server activity logs have been swept', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 44, NULL, NULL, 'SymantecEPM: Decomposer Up to date', 1, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 45, NULL, NULL, 'SymantecEPM: Security risk found', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 46, NULL, NULL, 'SymantecEPM: Scan Performed', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 47, NULL, NULL, 'SymantecEPM: Scan Cancelled', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 48, NULL, NULL, 'SymantecEPM: Scan Started', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 49, NULL, NULL, 'SymantecEPM: Comercial application detected', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 50, NULL, NULL, 'SymantecEPM: The client has reconnected with the management server', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 51, NULL, NULL, 'SymantecEPM: The client has downloaded the content package successfully', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 52, NULL, NULL, 'SymantecEPM: The management server received the client log successfully', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 53, NULL, NULL, 'SymantecEPM: The client has downloaded sylink.xml successfully', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 54, NULL, NULL, 'SymantecEPM: The client has downloaded the Intrusion Prevention policy successfully', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 55, NULL, NULL, 'SymantecEPM: The client has downloaded the auto-upgrade configuration file successfully', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 60, NULL, NULL, 'SymantecEPM: Traffic from IP address is disengaged', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 61, NULL, NULL, 'SymantecEPM: Traffic from IP address is blocked', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 62, NULL, NULL, 'SymantecEPM: [SID: 23179] OS Attack: MS Windows Server Service RPC Handling CVE-2008-4250 detected. Traffic has been blocked from this application', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 63, NULL, NULL, 'SymantecEPM: [SID: 21596] Jabber IM Client Connection detected.  Traffic has been allowed from this application', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 64, NULL, NULL, 'SymantecEPM: [SID: 24141] Web Attack: Exploit Kit Variant Activity 2 detected.  Traffic has been blocked from this application', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 75, NULL, NULL, 'SymantecEPM: Device Manager Message The device was enabled successfully', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 76, NULL, NULL, 'SymantecEPM: Device Manager Message The device was disabled successfully', 1, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1619, 77, NULL, NULL, 'SymantecEPM: Auto-Block Event', 1, 1);
INSERT IGNORE INTO plugin_sid(plugin_id,sid,name) VALUES(1619,99,'SymantecEPM: Generic EPM message');
