INSERT IGNORE INTO plugin (id, type, name, description) VALUES (90007, 1, 'VCenter', 'VmWare Virtual Center');


INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,1,null,null,'VCenter: Add License Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,2,null,null,'VCenter: Assign License Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,3,null,null,'VCenter: License Expiry Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,4,null,null,'VCenter: CIM Group Health State Changed',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,5,null,null,'VCenter: HA Cluster Failover Action Completed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,6,null,null,'VCenter: HA Cluster Failover Action Initiated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,7,null,null,'VCenter: HA Das Agent Running Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,8,null,null,'VCenter: HA Das Host Failed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,9,null,null,'VCenter: HA Das Total Cluster Failure Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,10,null,null,'VCenter: HA Host Das Agent Healthy Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,11,null,null,'VCenter: HA Host Das Error Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,12,null,null,'VCenter: Health State Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,13,null,null,'VCenter: Net Connectivity Restored',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,14,null,null,'VCenter: Net Redundancy Restored',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,15,null,null,'VCenter: Net Link State Up',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,16,null,null,'VCenter: Dtorage Connectivity Restored',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,17,null,null,'VCenter: Dtorage Redundancy Restored',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,18,null,null,'VCenter: Net Connectivity Lost',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,19,null,null,'VCenter: Net Redundancy Degraded',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,20,null,null,'VCenter: Net Redundancy Lost',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,21,null,null,'VCenter: Storage Connectivity Lost',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,22,null,null,'VCenter: Storage Redundancy Degraded',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,23,null,null,'VCenter: Storage Redundancy Lost',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,24,null,null,'VCenter: Heartbeat Recovered',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,25,null,null,'VCenter: Heartbeat Timedout',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,26,null,null,'VCenter: Alarm Action Triggered Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,27,null,null,'VCenter: Alarm Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,28,null,null,'VCenter: Alarm Reconfigured Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,29,null,null,'VCenter: Alarm Snmp Completed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,30,null,null,'VCenter: Alarm Status Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,31,null,null,'VCenter: Bad Username Session Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,32,null,null,'VCenter: Cluster Compliance Checked Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,33,null,null,'VCenter: Cluster Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,34,null,null,'VCenter: Cluster Reconfigured Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,35,null,null,'VCenter: Custom Field Def Added Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,36,null,null,'VCenter: Custom Field Value Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,37,null,null,'VCenter: Das Admission Control Disabled Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,38,null,null,'VCenter: Das Agent Found Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,39,null,null,'VCenter: Das Agent Unavailable Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,40,null,null,'VCenter: Das Host Isolated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,41,null,null,'VCenter: Datacenter Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,42,null,null,'VCenter: Datacenter Renamed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,43,null,null,'VCenter: Datastore Destroyed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,44,null,null,'VCenter: Datastore Discovered Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,45,null,null,'VCenter: Datastore File Moved Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,46,null,null,'VCenter: Datastore Removed On Host Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,47,null,null,'VCenter: Datastore Renamed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,48,null,null,'VCenter: Drs Vm Migrated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,49,null,null,'VCenter: Drs Vm Powered On Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,50,null,null,'VCenter: Entered Maintenance Mode Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,51,null,null,'VCenter: Entering Maintenance Mode Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,52,null,null,'VCenter: Exit Maintenance Mode Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,53,null,null,'VCenter: Failover Level Restored',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,54,null,null,'VCenter: General Host Error Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,55,null,null,'VCenter: General User Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,56,null,null,'VCenter: Global Message Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,57,null,null,'VCenter: Health Status Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,58,null,null,'VCenter: Host Added Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,59,null,null,'VCenter: Host Compliance Checked Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,60,null,null,'VCenter: Host Compliant Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,61,null,null,'VCenter: Host Config Applied Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,62,null,null,'VCenter: Host Connected Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,63,null,null,'VCenter: Host Connection Lost Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,64,null,null,'VCenter: Host Das Disabled Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,65,null,null,'VCenter: Host Das Disabling Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,66,null,null,'VCenter: Host Das Enabling Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,67,null,null,'VCenter: Host Das Ok Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,68,null,null,'VCenter: Host Disconnected Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,69,null,null,'VCenter: Host Ip Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,70,null,null,'VCenter: Host Isolation Ip Ping Failed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,71,null,null,'VCenter: Host Non Compliant Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,72,null,null,'VCenter: Host Removed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,73,null,null,'VCenter: Host Wwn Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,74,null,null,'VCenter: Insufficient Failover Resources Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,75,null,null,'VCenter: Migration Resource Warning Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,76,null,null,'VCenter: No Access User Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,77,null,null,'VCenter: Permission Added Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,78,null,null,'VCenter: Permission Removed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,79,null,null,'VCenter: Permission Updated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,80,null,null,'VCenter: Profile Associated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,81,null,null,'VCenter: Profile Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,82,null,null,'VCenter: Profile Dissociated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,83,null,null,'VCenter: Profile Reference Host Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,84,null,null,'VCenter: Profile Removed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,85,null,null,'VCenter: Resource Pool Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,86,null,null,'VCenter: Resource Pool Reconfigured Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,87,null,null,'VCenter: Role Added Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,88,null,null,'VCenter: Role Updated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,89,null,null,'VCenter: Scheduled Task Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,90,null,null,'VCenter: Scheduled Task Removed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,91,null,null,'VCenter: Server Started Session Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,92,null,null,'VCenter: Task Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,93,null,null,'VCenter: User Login Session Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,94,null,null,'VCenter: User Logout Session Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,95,null,null,'VCenter: Vc Agent Upgraded Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,96,null,null,'VCenter: Vim Account Password Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,97,null,null,'VCenter: Vm Acquired Ticket Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,98,null,null,'VCenter: Vm Being Cloned Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,99,null,null,'VCenter: Vm Being Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,100,null,null,'VCenter: Vm Being Deployed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,101,null,null,'VCenter: Vm Being Hot Migrated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,102,null,null,'VCenter: Vm Being Relocated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,103,null,null,'VCenter: Vm Cloned Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,104,null,null,'VCenter: Vm Connected Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,105,null,null,'VCenter: Vm Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,106,null,null,'VCenter: Vm Das Being Reset Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,107,null,null,'VCenter: Vm Deployed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,108,null,null,'VCenter: Vm Disconnected Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,109,null,null,'VCenter: Vm Discovered Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,110,null,null,'VCenter: Vm Emigrating Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,111,null,null,'VCenter: Vm Failed Migrate Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,112,null,null,'VCenter: Vm Failover Failed',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,113,null,null,'VCenter: VMFS Datastore Created Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,114,null,null,'VCenter: Vm Guest Reboot Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,115,null,null,'VCenter: Vm Guest Shutdown Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,116,null,null,'VCenter: Vm Health Monitoring State Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,117,null,null,'VCenter: Vm Instance Uuid Assigned Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,118,null,null,'VCenter: Vm Instance Uuid Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,119,null,null,'VCenter: Vm Mac Assigned Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,120,null,null,'VCenter: Vm Mac Changed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,121,null,null,'VCenter: Vm Mac Conflict Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,122,null,null,'VCenter: Vm Max Restart Count Reached',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,123,null,null,'VCenter: Vm Message Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,124,null,null,'VCenter: Vm Message Warning Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,125,null,null,'VCenter: Vm Migrated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,126,null,null,'VCenter: Vm Powered Off Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,127,null,null,'VCenter: Vm Powered On Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,128,null,null,'VCenter: Vm Power Off On Isolation Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,129,null,null,'VCenter: Vm Reconfigured Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,130,null,null,'VCenter: Vm Registered Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,131,null,null,'VCenter: Vm Relocated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,132,null,null,'VCenter: Vm Remote Console Connected Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,133,null,null,'VCenter: Vm Remote Console Disconnected Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,134,null,null,'VCenter: Vm Removed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,135,null,null,'VCenter: Vm Renamed Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,136,null,null,'VCenter: Vm Resetting Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,137,null,null,'VCenter: Vm Resource Pool Moved Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,138,null,null,'VCenter: Vm Resource Reallocated Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,139,null,null,'VCenter: Vm Restarted On Alternate Host Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,140,null,null,'VCenter: Vm Starting Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,141,null,null,'VCenter: Vm Stopping Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,142,null,null,'VCenter: Vm Upgrade Complete Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,143,null,null,'VCenter: Vm Upgrading Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,144,null,null,'VCenter: Vm Uuid Assigned Event',2,2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (90007,145,null,null,'VCenter: Vm Uuid Changed Event',2,2);
