Document: alienvault-center
Title: Debian alienvault-center Manual
Author: <insert document author here>
Abstract: This manual describes what alienvault-center is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alienvault-center/alienvault-center.sgml.gz

Format: postscript
Files: /usr/share/doc/alienvault-center/alienvault-center.ps.gz

Format: text
Files: /usr/share/doc/alienvault-center/alienvault-center.text.gz

Format: HTML
Index: /usr/share/doc/alienvault-center/html/index.html
Files: /usr/share/doc/alienvault-center/html/*.html
