#!/bin/sh
### BEGIN INIT INFO
# Provides:          alienvault-depmod
# Required-Start:    $local_fs
# Required-Stop:    $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Updating module list
### END INIT INFO

case $1 in
    start)
        depmod -a
        ;;
    stop|restart|status|reload)
        ;;
    *)
        # For invalid arguments, print the usage message.
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 2
        ;;
esac
