rules/1.3.1/emerging.rules/LICENSE usr/share/suricata-rules-default/d_clean/etc/suricata/rules/1.3.1
rules/1.3.1/emerging.rules/gpl-2.0.txt usr/share/suricata-rules-default/d_clean/etc/suricata/rules/1.3.1
rules/1.3.1/emerging.rules/BSD-License.txt usr/share/suricata-rules-default/d_clean/etc/suricata/rules/1.3.1
rules/1.3.1/emerging.rules/*.rules usr/share/suricata-rules-default/d_clean/etc/suricata/rules/1.3.1
rules/1.3.1/suricata.rules/*.rules usr/share/suricata-rules-default/d_clean/etc/suricata/rules/1.3.1
rules/1.3.1/alienvault.rules/*.rules usr/share/suricata-rules-default/d_clean/etc/suricata/rules/1.3.1
