SET UNIQUE_CHECKS=0;
INSERT IGNORE INTO product_type (id, name) VALUES (1, 'Alarm');
INSERT IGNORE INTO product_type (id, name) VALUES (2, 'Anomaly Detection');
INSERT IGNORE INTO product_type (id, name) VALUES (3, 'Antivirus');
INSERT IGNORE INTO product_type (id, name) VALUES (4, 'Application');
INSERT IGNORE INTO product_type (id, name) VALUES (5, 'Application Firewall');
INSERT IGNORE INTO product_type (id, name) VALUES (6, 'Authentication and DHCP');
INSERT IGNORE INTO product_type (id, name) VALUES (7, 'Data Protection');
INSERT IGNORE INTO product_type (id, name) VALUES (8, 'Database');
INSERT IGNORE INTO product_type (id, name) VALUES (9, 'Endpoint Security');
INSERT IGNORE INTO product_type (id, name) VALUES (10, 'Firewall');
INSERT IGNORE INTO product_type (id, name) VALUES (11, 'Honeypot');
INSERT IGNORE INTO product_type (id, name) VALUES (12, 'Infrastructure Monitoring');
INSERT IGNORE INTO product_type (id, name) VALUES (13, 'Intrusion Detection');
INSERT IGNORE INTO product_type (id, name) VALUES (14, 'Intrusion Prevention');
INSERT IGNORE INTO product_type (id, name) VALUES (15, 'Mail Security');
INSERT IGNORE INTO product_type (id, name) VALUES (16, 'Mail Server');
INSERT IGNORE INTO product_type (id, name) VALUES (17, 'Management Platform');
INSERT IGNORE INTO product_type (id, name) VALUES (18, 'Network Access Control');
INSERT IGNORE INTO product_type (id, name) VALUES (19, 'Network Discovery');
INSERT IGNORE INTO product_type (id, name) VALUES (20, 'Operating System');
INSERT IGNORE INTO product_type (id, name) VALUES (21, 'Other Devices');
INSERT IGNORE INTO product_type (id, name) VALUES (22, 'Proxy');
INSERT IGNORE INTO product_type (id, name) VALUES (23, 'Remote Application Access');
INSERT IGNORE INTO product_type (id, name) VALUES (24, 'Router/Switch');
INSERT IGNORE INTO product_type (id, name) VALUES (25, 'Server');
INSERT IGNORE INTO product_type (id, name) VALUES (26, 'Unified threat management');
INSERT IGNORE INTO product_type (id, name) VALUES (27, 'VPN');
INSERT IGNORE INTO product_type (id, name) VALUES (28, 'Vulnerability Scanner');
INSERT IGNORE INTO product_type (id, name) VALUES (29, 'Web Server');
INSERT IGNORE INTO product_type (id, name) VALUES (30, 'Wireless Security/Management');
INSERT IGNORE INTO product_type (id, name) VALUES (31, 'Load Balancer');
INSERT IGNORE INTO product_type (id, name) VALUES (32, 'AlienVault Devices');
