sources = {}
sources['Alarm'] = 1
sources['Anomaly Detection'] = 1
sources['Antivirus'] = 1
sources['Application'] = 1
sources['Application Firewall'] = 1
sources['Applications'] = 1
sources['Authentication and DHCP'] = 1
sources['Database'] = 1
sources['Data Protection'] = 1
sources['Firewall'] = 1
sources['Honeypot'] = 1
sources['Infrastructure Monitoring'] = 1
sources['Intrusion Detection'] = 1
sources['Intrusion Prevention'] = 1
sources['Mail Security'] = 1
sources['Mail Server'] = 1
sources['Management Platform'] = 1
sources['Network Discovery'] = 1
sources['Operating System'] = 1
sources['Other Devices'] = 1
sources['Proxy'] = 1
sources['Remote Application Access'] = 1
sources['Router/Switch'] = 1
sources['Server'] = 1
sources['Unified threat management'] = 1
sources['VPN'] = 1
sources['Vulnerability Scanner'] = 1
sources['Web Server'] = 1
sources['Wireless Security/Management'] = 1
