Document: alienvault-api-sdk
Title: Debian alienvault-api-sdk Manual
Author: <insert document author here>
Abstract: This manual describes what alienvault-api-sdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alienvault-api-sdk/alienvault-api-sdk.sgml.gz

Format: postscript
Files: /usr/share/doc/alienvault-api-sdk/alienvault-api-sdk.ps.gz

Format: text
Files: /usr/share/doc/alienvault-api-sdk/alienvault-api-sdk.text.gz

Format: HTML
Index: /usr/share/doc/alienvault-api-sdk/html/index.html
Files: /usr/share/doc/alienvault-api-sdk/html/*.html
