Document: alienvault-dummy-common
Title: Debian alienvault-dummy-common Manual
Author: <insert document author here>
Abstract: This manual describes what alienvault-dummy-common is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alienvault-dummy-common/alienvault-dummy-common.sgml.gz

Format: postscript
Files: /usr/share/doc/alienvault-dummy-common/alienvault-dummy-common.ps.gz

Format: text
Files: /usr/share/doc/alienvault-dummy-common/alienvault-dummy-common.text.gz

Format: HTML
Index: /usr/share/doc/alienvault-dummy-common/html/index.html
Files: /usr/share/doc/alienvault-dummy-common/html/*.html
