-- MySQL Script generated by MySQL Workbench
-- Mon Jun 23 13:01:00 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alienvault_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `current_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `current_status` (
  `message_id` SMALLINT UNSIGNED NOT NULL,
  `component_id` BINARY(16) NOT NULL,
  `component_type` ENUM('net','host','user','sensor','server','system') NOT NULL,
  `creation_time` TIMESTAMP NOT NULL COMMENT '(CURRENT_TIMESTAMP | on create CURRENT_TIMESTAMP )',
  `viewed` ENUM('true','false') NOT NULL,
  `supressed` TINYINT NULL DEFAULT 0 COMMENT 'True or False. Indicates that this kind of message over this component id is disabled.',
  `supressed_time` TIMESTAMP NULL,
  `additional_info` TEXT NULL,
  PRIMARY KEY (`message_id`, `component_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logged_actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logged_actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logged_user` VARCHAR(45) NULL,
  `datetime` TIMESTAMP NULL,
  `action_description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monitor_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitor_data` (
  `component_id` BINARY(16) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `monitor_id` INT NOT NULL,
  `data` TEXT NULL,
  `component_type` VARCHAR(55) NULL COMMENT 'Component type. (net, host, …)',
  PRIMARY KEY (`component_id`, `timestamp`, `monitor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `celery_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `celery_job` (
  `id` BINARY(16) NOT NULL,
  `info` BLOB NULL,
  `last_modified` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `status_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status_message` (
  `id` SMALLINT NOT NULL,
  `level` ENUM('info','error','warning','notification') NOT NULL,
  `content` TEXT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `status_message_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status_message_action` (
  `message_id` INT NOT NULL,
  `action_id` INT NOT NULL,
  PRIMARY KEY (`message_id`, `action_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `status_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status_action` (
  `action_id` INT NOT NULL,
  `message_id` INT NULL,
  `is_admin` TINYINT(1) NULL,
  `content` TEXT NULL,
  `link` TEXT NULL,
  PRIMARY KEY (`action_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
