# Build and Deploy DEB Packages for OSSIM

name: Build and Deploy DEB Packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. Build the DEB packages on Debian Stretch (Debian 9).
      # This step runs a container based on debian:stretch.
      # It replaces the default sources list with legacy archive entries,
      # disables the Check-Valid-Until option (for archived repos),
      # downloads and installs libgnet-dev manually (since libgnet2-dev is not available in Debian 9),
      # installs a broad set of build dependencies, and then builds each package found.
      - name: Build DEB Packages on Stretch
        run: |
          echo "Running build in custom container..."
          docker run --rm -v "$PWD":/workspace debian:stretch bash -c "\
            # Replace sources list with legacy archive entries
            echo 'deb http://archive.debian.org/debian stretch main contrib non-free' > /etc/apt/sources.list && \
            echo 'deb http://archive.debian.org/debian-security stretch/updates main' >> /etc/apt/sources.list && \
            # Disable the Check-Valid-Until option for archived repositories
            echo 'Acquire::Check-Valid-Until \"false\";' > /etc/apt/apt.conf.d/99no-check-valid-until && \
            apt-get update && \
            \
            # Download and install libgnet-dev from the Debian archive
            echo 'Downloading libgnet-dev package...' && \
            wget https://cloudfront.debian.net/debian-archive/debian/pool/main/g/gnet/libgnet-dev_2.0.8-2.2_amd64.deb && \
            echo 'Installing libgnet-dev package...' && \
            dpkg -i libgnet-dev_2.0.8-2.2_amd64.deb || apt-get -f install -y && \
            echo rm libgnet-dev_2.0.8-2.2_amd64.deb && \
            \
            # Install the rest of the build dependencies
            apt-get install -y \
              build-essential \
              devscripts \
              debhelper \
              dpkg-dev \
              apt-utils \
              python-dev \
              python-sphinx \
              python2.7-dev \
              python-setuptools \
              dh-virtualenv \
              libglib2.0-dev \
              librrd-dev \
              libmariadbclient-dev \
              libssl-dev \
              libffi-dev \
              libxml2-dev \
              libcairo2-dev \
              libpango1.0-dev \
              python-mysqldb \
              python-all-dev \
              libjson-glib-dev \
              docbook-to-man \
              pkg-config \
              libhiredis-dev \
              libbson-dev \
              libmaxminddb-dev \
              dpatch \
              uuid-dev \
              libsoup2.4-dev \
              php-dev \
              php-mbstring \
              config-package-dev && \
            \
            # For each package directory (determined by the existence of a 'debian' folder),
            # run dpkg-buildpackage (forcing it to ignore unmet build dependencies with -d)
            for pkg in \$(find . -type d -name debian -printf '%h\n' | sort -u); do \
              echo '-----------------------------'; \
              echo \"Building package in: \$pkg\"; \
              cd \$pkg; \
              if [ -f debian/control ]; then \
                dpkg-buildpackage -uc -us -d || echo \"⚠️  Build failed in \$pkg\"; \
              else \
                echo \"No debian/control file found in \$pkg, skipping...\"; \
              fi; \
              cd - > /dev/null; \
            done"
        id: build

      # 3. Upload all generated .deb files as an artifact for use in the next jobs.
      - name: Upload DEB Files Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: "*.deb"

  build-installer:
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      # 1. Download the DEB package artifact generated in the build-deb job.
      - name: Download DEB Packages Artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: deb_files

      # 2. Install dependencies required for ISO creation (including genisoimage and ISOLINUX).
      - name: Install ISO Creation Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y genisoimage isolinux syslinux-common

      # 3. Prepare the ISO structure directory.
      - name: Prepare ISO Structure
        run: |
          mkdir -p iso_structure/debs
          cp deb_files/*.deb iso_structure/debs/
          # IMPORTANT: This installer ISO is based on Debian 9 (Stretch) and is designed to be bootable and installable.
          #
          # To customize your installation, add bootloader configuration files and kernel/initrd files as needed.
          #
          # For a bootable ISO using ISOLINUX, create and populate the isolinux directory.
          mkdir -p iso_structure/isolinux
          # Copy the necessary ISOLINUX bootloader files from your repository or another source:
          # - isolinux.bin : The ISOLINUX bootloader binary.
          # - isolinux.cfg : The ISOLINUX configuration file.
          # - Optionally, boot.cat will be auto-generated by genisoimage.
          #
          # For example, if your repository contains these files in a folder named "boot":
          cp -r boot/isolinux/* iso_structure/isolinux/ || echo "Warning: ISOLINUX files not found. Please add them to enable a bootable ISO."
          #
          # You can customize isolinux.cfg to include different installation options.
          # For example, a simple isolinux.cfg might contain:
          #
          #   DEFAULT menu.c32
          #   PROMPT 0
          #   TIMEOUT 50
          #   MENU TITLE OSSIM Installer
          #
          #   LABEL install
          #     MENU LABEL ^Install OSSIM
          #     KERNEL /boot/vmlinuz
          #     APPEND initrd=/boot/initrd.img --- quiet
          #
          # To include a custom OSSIM logo in the boot menu, add the following line in isolinux.cfg:
          #   MENU BACKGROUND /isolinux/ossim-logo.png
          #
          # And copy your logo file:
          # cp path/to/ossim-logo.png iso_structure/isolinux/

      # 4. Create a Bootable Installer ISO using genisoimage.
      - name: Create Bootable Installer ISO
        run: |
          # This command creates a bootable and installable OSSIM Installer ISO based on Debian 9 (Stretch).
          # The ISO uses ISOLINUX as the bootloader.
          genisoimage \
            -o OSSIM-Installer.iso \
            -V "OSSIM_Installer" \
            -A "OSSIM" \
            -R -J \
            -b isolinux/isolinux.bin \
            -c isolinux/boot.cat \
            -no-emul-boot \
            -boot-load-size 4 \
            -boot-info-table \
            iso_structure

      # 5. Upload the Installer ISO as an artifact.
      - name: Upload Installer ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer-iso
          path: OSSIM-Installer.iso

      # 6. Create a GitHub Release and upload the Installer ISO to it.
      - name: Create GitHub Release and Upload Installer ISO
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "ossim-installer-${{ github.run_number }}"
          name: "OSSIM Installer ISO"
          body: "Bootable and installable OSSIM Installer"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ISO to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_release.outputs.tag_name }}
          asset_path: OSSIM-Installer.iso
          asset_name: OSSIM-Installer.iso
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      # 1. Download the DEB package artifact generated in the build-deb job.
      - name: Download DEB Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: output

      # 2. Generate the APT repository index file (Packages.gz) in the output directory.
      - name: Create APT Repository Index
        run: |
          cd output
          echo "Generating Packages.gz index..."
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -la
          cd ..

      # 3. Deploy the output folder to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
