name: Build and Deploy DEB Packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Build the DEB packages using a Debian Stretch container.
      # This container uses archived repositories for Debian Stretch. Since the
      # default repositories no longer contain the libgnet2-dev package, we manually
      # download and install libgnet-dev.
      - name: Build DEB Packages on Stretch
        run: |
          echo "Running build in custom container..."
          docker run --rm -v "$PWD":/workspace debian:stretch bash -c "\
            # Replace the sources.list with archived repositories for Debian Stretch \
            echo 'deb http://archive.debian.org/debian stretch main contrib non-free' > /etc/apt/sources.list && \
            echo 'deb http://archive.debian.org/debian-security stretch/updates main' >> /etc/apt/sources.list && \
            # Disable the Check-Valid-Until option for archived repositories \
            echo 'Acquire::Check-Valid-Until \"false\";' > /etc/apt/apt.conf.d/99no-check-valid-until && \
            apt-get update && \
            # Install required build dependencies (excluding libgnet2-dev, which is not available) \
            apt-get install -y \
              build-essential \
              devscripts \
              debhelper \
              dpkg-dev \
              apt-utils \
              python-dev \
              python-sphinx \
              python2.7-dev \
              python-setuptools \
              dh-virtualenv \
              libglib2.0-dev \
              librrd-dev \
              libmariadbclient-dev \
              libssl-dev \
              libffi-dev \
              libxml2-dev \
              libcairo2-dev \
              libpango1.0-dev \
              python-mysqldb \
              python-all-dev \
              libjson-glib-dev \
              docbook-to-man \
              pkg-config \
              libhiredis-dev \
              libbson-dev \
              libmaxminddb-dev \
              dpatch \
              uuid-dev \
              libsoup2.4-dev \
              php-dev \
              php-mbstring \
              config-package-dev && \
            # Download the libgnet-dev package manually from the Debian archive \
            wget -O /tmp/libgnet-dev.deb https://cloudfront.debian.net/debian-archive/debian/pool/main/g/gnet/libgnet-dev_2.0.8-2.2_amd64.deb && \
            # Attempt to install the downloaded package; if installation fails due to missing \
            # dependencies, automatically fix them using apt-get -f install \
            dpkg -i /tmp/libgnet-dev.deb || apt-get -y install -f && \
            # Loop through directories that contain a 'debian' folder and build packages \
            for pkg in \$(find . -type d -name debian -printf '%h\n' | sort -u); do \
              echo '-----------------------------'; \
              echo \"Building package in: \$pkg\"; \
              cd \$pkg; \
              if [ -f debian/control ]; then \
                dpkg-buildpackage -uc -us -d || echo \"⚠️  Build failed in \$pkg\"; \
              else \
                echo \"No debian/control file found in \$pkg, skipping...\"; \
              fi; \
              cd - > /dev/null; \
            done"
        id: build

      # Step 3: Upload all generated .deb files as an artifact for the deploy job.
      - name: Upload DEB Files Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: "*.deb"

  deploy:
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      # Step 4: Download the artifact generated by the build job.
      - name: Download DEB Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: output

      # Step 5: Generate the APT repository index file (Packages.gz) in the output directory.
      - name: Create APT Repository Index
        run: |
          cd output
          echo "Generating Packages.gz index..."
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -la
          cd ..

      # Step 6: Deploy the output folder to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
