name: Build and Deploy DEB Packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. Build the DEB packages on Debian Stretch.
      - name: Build DEB Packages on Stretch
        run: |
          echo "Running build in custom container..."
          docker run --rm -v "$PWD":/workspace debian:stretch bash -c "\
            # Replace sources list with legacy archive entries
            echo 'deb http://archive.debian.org/debian stretch main contrib non-free' > /etc/apt/sources.list && \
            echo 'deb http://archive.debian.org/debian-security stretch/updates main' >> /etc/apt/sources.list && \
            echo 'Acquire::Check-Valid-Until \"false\";' > /etc/apt/apt.conf.d/99no-check-valid-until && \
            apt-get update && \
            # Install a broad list of build dependencies
            apt-get install -y \
              build-essential \
              devscripts \
              debhelper \
              dpkg-dev \
              apt-utils \
              python-dev \
              python-sphinx \
              python2.7-dev \
              python-setuptools \
              dh-virtualenv \
              libglib2.0-dev \
              librrd-dev \
              libmariadbclient-dev \
              libssl-dev \
              libffi-dev \
              libxml2-dev \
              libcairo2-dev \
              libpango1.0-dev \
              python-mysqldb \
              python-all-dev \
              libjson-glib-dev \
              docbook-to-man \
              pkg-config \
              python-support \
              libhiredis-dev \
              libbson-dev \
              libgda-5.0-dev \
              libgnet-dev \
              libmaxminddb-dev \
              dpatch \
              uuid-dev \
              libsoup2.4-dev \
              php-dev \
              php-mbstring \
              config-package-dev && \
            for pkg in \$(find . -type d -name debian -printf '%h\n' | sort -u); do \
              echo '-----------------------------'; \
              echo \"Building package in: \$pkg\"; \
              cd \$pkg; \
              if [ -f debian/control ]; then \
                # Uncomment the -d flag if you want to force the build (ignoring missing dependencies)  
                dpkg-buildpackage -uc -us || echo \"⚠️  Build failed in \$pkg\"; \
              else \
                echo \"No debian/control file found in \$pkg, skipping...\"; \
              fi; \
              cd - > /dev/null; \
            done"
        id: build

      # 3. Upload all generated .deb files as an artifact.
      - name: Upload DEB Files Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: "*.deb"

  deploy:
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      # 4. Download the artifact.
      - name: Download DEB Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: output

      # 5. Generate the APT repository index.
      - name: Create APT Repository Index
        run: |
          cd output
          echo "Generating Packages.gz index..."
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -la
          cd ..

      # 6. Deploy to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output

