name: Build and Deploy DEB Packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. Build the DEB packages on Debian Stretch.
      # This action will run inside a Debian Stretch container, ensuring that your build environment matches your requirements.
      - name: Build DEB Packages on Stretch
        uses: singingwolfboy/build-dpkg-stretch@v1
        id: build
        with:
          args: --unsigned-source --unsigned-changes

      # 3. Upload the resulting DEB package as an artifact.
      - name: Upload DEB Package Artifact
        uses: actions/upload-artifact@v1
        with:
          name: deb-package
          path: ${{ steps.build.outputs.filename }}

  deploy:
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      # 4. Download the artifact generated in the build job.
      - name: Download DEB Package Artifact
        uses: actions/download-artifact@v1
        with:
          name: deb-package
          path: output

      # 5. Generate the APT Packages index file (Packages.gz) for the repository.
      - name: Create APT Repository Index
        run: |
          cd output
          echo "Generating Packages.gz index..."
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -la
          cd ..

      # 6. Deploy the output folder to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output

